### ISSUE TITLE
scalac assertion failed:   Java member module without member class: package foo

### ISSUE THREAD

**Issue by scabug** [scala/bug#10012]
Scalac 2.12 got an assertion failure compiling the following code snippet.

scalac version 2.11.8 can comple this code.

The case is generated from an exsiting test program in the scala repository.

```scala
$ scalac -version
Scala compiler version 2.12.0-20161028-204919-0666377 -- Copyright 2002-2016, LAMP/EPFL and Lightbend, Inc.



$ scalac abc.scala
java.lang.AssertionError: assertion failed: 
  Java member module without member class: package foo - List(package foo)
     while compiling: abc.scala
        during phase: jvm
     library version: version 2.12.0-20161028-204919-0666377
    compiler version: version 2.12.0-20161028-204919-0666377
  reconstructed args: 

  last tree to typer: TypeTree(class Int)
       tree position: line 12 of abc.scala
            tree tpe: Int
              symbol: (final abstract) class Int in package scala
   symbol definition: final abstract class Int extends  (a ClassSymbol)
      symbol package: scala
       symbol owners: class Int
           call site: trait Test9$identifier in package <empty>

== Source file context for tree position ==

     9 package identifier { package identifier.bar {} }
    10 package foo { package identifier.foo {} }
    11 object Test13 { def identifier = 2 }
	at scala.tools.nsc.Global.assert(Global.scala:229)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.$anonfun$setClassInfo$14(BTypesFromSymbols.scala:435)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.$anonfun$setClassInfo$14$adapted(BTypesFromSymbols.scala:430)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.setClassInfo(BTypesFromSymbols.scala:430)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.$anonfun$classBTypeFromSymbol$5(BTypesFromSymbols.scala:126)
	at scala.collection.MapLike.getOrElse(MapLike.scala:128)
	at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
	at scala.collection.concurrent.TrieMap.getOrElse(TrieMap.scala:631)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.classBTypeFromSymbol(BTypesFromSymbols.scala:118)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:94)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker1.visit(GenBCode.scala:190)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker1.$anonfun$run$1(GenBCode.scala:139)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnitNoLog(Global.scala:395)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase$Worker1.run(GenBCode.scala:139)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.buildAndSendToDisk(GenBCode.scala:381)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:350)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1404)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1389)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1384)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1478)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
	at scala.tools.nsc.Driver.process(Driver.scala:55)
	at scala.tools.nsc.Driver.main(Driver.scala:68)
	at scala.tools.nsc.Main.main(Main.scala)
error: Error while emitting abc.scala
assertion failed:
  Java member module without member class: package foo - List(package foo)
     while compiling: abc.scala
        during phase: jvm
     library version: version 2.12.0-20161028-204919-0666377
    compiler version: version 2.12.0-20161028-204919-0666377
  reconstructed args:

  last tree to typer: TypeTree(class Int)
       tree position: line 12 of abc.scala
            tree tpe: Int
              symbol: (final abstract) class Int in package scala
   symbol definition: final abstract class Int extends  (a ClassSymbol)
      symbol package: scala
       symbol owners: class Int
           call site: trait Test9$identifier in package <empty>

== Source file context for tree position ==

     9 package identifier { package identifier.bar {} }
    10 package foo { package identifier.foo {} }
    11 object Test13 { def identifier = 2 }
one error found


$ cat abc.scala
object Test1 { val identifier = ??? }
object Test2 { var identifier = ??? }
object Test3 { type identifier = Int }
package test4 { class identifier }
object Test5 { class identifier }
package test6 { object identifier }
object Test7 { object identifier }
package foo { trait identifier }
object Test9 { trait identifier }
package identifier { package identifier.bar {} }
package foo { package identifier.foo {} }
object Test13 { def identifier = 2 }
```

**Comment by som-snytt** [comment]
Minimized at https://github.com/scala/bug/issues/10052
