### ISSUE TITLE
Compiler crash: StackOverflowError in defineBaseTypeSeqOfCompoundType

### ISSUE THREAD

**Issue by TomasMikula** [scala/bug#10259]
To reproduce, try to compile the following file with scalac 2.12.1:

```scala
import scala.language.implicitConversions

trait Foo {
  type A
}

object Foo {
  type Foo1[F0[_]] = Foo { type F[A] = F0[A] }
  type Foo2[F0[_], A0] = Foo1[F0] { type A = A0 }
}

import Foo._

trait Bar[F[_], A] {
  implicit def foo: Foo2[F, A]
}

object Bar {
  implicit def toFoo[F[_], A](implicit bar: Bar[F, A]): Foo2[F, A] =
    bar.foo
}

final case class Ops[F[_], A](f: F[Unit])(implicit P: Foo2[F, A]) {
  def op(): Unit = ()
}

object ToOps {
  implicit def toOps[F[_]](f: F[Unit])(implicit foo: Foo1[F]): Ops[F, foo.A] = ???
}

object Main {
  import Bar._
  import ToOps._

  def main[F[_], A](f: F[Unit])(implicit bar: Bar[F, A]): Unit =
    f.op()
}
```

The compiler crashes with `StackOverflowError`, looping in

```
	at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1377)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType(Types.scala:1498)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType$(Types.scala:1469)
	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:16)
	at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1377)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType(Types.scala:1498)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType$(Types.scala:1469)
	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:16)
	at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1377)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType(Types.scala:1498)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType$(Types.scala:1469)
	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:16)
```

Full stack trace is in [out.txt](https://github.com/scala/bug/files/912113/out.txt).

**Comment by TomasMikula** [comment]
Note that the crash is a regression. With 2.11.8, it doesn't crash. (It doesn't compile, either, though probably because of #10257.)
