### ISSUE TITLE
regression Scala 2.12.2. backward binary compatibility broken?

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#10268]
```scala
package com

package object example {
  object A {

  }

  type A = B
}

case class B()

package example {

  object C {
    def x: java.io.Serializable = A
    def y: scala.Serializable = A
  }
}
```

compile success with Scala 2.12.1, 2.11.11, 2.11.8, 2.10.6

compiie fail with Scala 2.12.2

```
A.scala:16: error: type mismatch;
 found   : com.example.A.type
 required: java.io.Serializable
    def x: java.io.Serializable = A
                                  ^
A.scala:17: error: type mismatch;
 found   : com.example.A.type
 required: Serializable
    def y: scala.Serializable = A
                                ^
two errors found

```

**Comment by xuwei-k** [comment]
backward binary compatibility broken?

- https://travis-ci.org/xuwei-k/scalaz/jobs/222507767#L6597
- https://github.com/xuwei-k/scalaz/commit/971753330a9b728c6eddbfb4760eaf932c8e0ef2

```
[error]  * the type hierarchy of object scalaz.typelevel.package#HCons is different in current version. Missing types {scala.Serializable,java.io.Serializable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scalaz.typelevel.package$HCons$")
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.12;1.0.5 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.12;1.0.6 ...
[info] scalaz-iteratee: found 0 potential binary incompatibilities while checking against org.scalaz:scalaz-iteratee_2.12:7.1.12 
[info] Resolving org.scalaz#scalaz-concurrent_2.12;7.1.12 ...
[info] Resolving org.scalaz#scalaz-effect_2.12;7.1.12 ...
[info] Resolving org.scalaz#scalaz-typelevel_2.12;7.1.12 ...
[info] Resolving org.scalaz#scalaz-xml_2.12;7.1.12 ...
[info] Resolving org.scalaz#scalaz-iteratee_2.12;7.1.12 ...
2K[info] Resolving org.scalacheck#scalacheck_2.12;1.11.6 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] downloading https://repo1.maven.org/maven2/org/scalaz/scalaz-scalacheck-binding_2.12/7.1.12/scalaz-scalacheck-binding_2.12-7.1.12.jar ...
[info] 	[SUCCESSFUL ] org.scalaz#scalaz-scalacheck-binding_2.12;7.1.12!scalaz-scalacheck-binding_2.12.jar(bundle) (54ms)
[info] scalaz-scalacheck-binding: found 0 potential binary incompatibilities while checking against org.scalaz:scalaz-scalacheck-binding_2.12:7.1.12 
[info] scalaz-core: found 6 potential binary incompatibilities while checking against org.scalaz:scalaz-core_2.12:7.1.12 
[error]  * the type hierarchy of object scalaz.package#Reader is different in current version. Missing types {scala.Serializable,java.io.Serializable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scalaz.package$Reader$")
[error]  * the type hierarchy of object scalaz.package#Store is different in current version. Missing types {scala.Serializable,java.io.Serializable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scalaz.package$Store$")
[error]  * the type hierarchy of object scalaz.package#Writer is different in current version. Missing types {scala.Serializable,java.io.Serializable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scalaz.package$Writer$")
[error]  * the type hierarchy of object scalaz.package#StoreT is different in current version. Missing types {scala.Serializable,java.io.Serializable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scalaz.package$StoreT$")
[error]  * the type hierarchy of object scalaz.package#IndexedStore is different in current version. Missing types {scala.Serializable,java.io.Serializable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scalaz.package$IndexedStore$")
[error]  * the type hierarchy of object scalaz.package#Unwriter is different in current version. Missing types {scala.Serializable,java.io.Serializable}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scalaz.package$Unwriter$")
java.lang.RuntimeException: scalaz-typelevel: Binary compatibility check failed!
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.tools.mima.plugin.SbtMima$.reportModuleErrors(SbtMima.scala:110)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6$$anonfun$apply$4.apply(MimaPlugin.scala:57)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6$$anonfun$apply$4.apply(MimaPlugin.scala:48)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6.apply(MimaPlugin.scala:48)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6.apply(MimaPlugin.scala:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: scalaz-core: Binary compatibility check failed!
	at scala.sys.package$.error(package.scala:27)
	at com.typesafe.tools.mima.plugin.SbtMima$.reportModuleErrors(SbtMima.scala:110)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6$$anonfun$apply$4.apply(MimaPlugin.scala:57)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6$$anonfun$apply$4.apply(MimaPlugin.scala:48)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:109)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6.apply(MimaPlugin.scala:48)
	at com.typesafe.tools.mima.plugin.MimaPlugin$$anonfun$mimaReportSettings$6.apply(MimaPlugin.scala:42)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (typelevel/*:mimaReportBinaryIssues) scalaz-typelevel: Binary compatibility check failed!
[error] (core/*:mimaReportBinaryIssues) scalaz-core: Binary compatibility check failed!
```

**Comment by sjrd** [comment]
The "regression" is actually fixing a bug. That snippet should not compile. `A` definitely does not extend `Serializable`.

The binary compatibility issue you observe is in your library, not the distributed binaries of Scala itself, so that is not a beach of the policy.

You can fix both issues in your library by adding `extends scala.Serializable` to `object A`.

In short, Scala 2.12.2 is not entirely *source* compatible with 2.12.1, because the previous versions had a bug that allowed invalid code to compile. That's a valid reason to break source compatibility.

**Comment by lrytz** [comment]
For reference, the change was implemented in https://github.com/scala/scala/pull/5602
