### ISSUE TITLE
Scaladoc crashes when running at /tmp

### ISSUE THREAD

**Issue by Atry** [scala/bug#10324]
```
$ scaladoc -version
Scaladoc version 2.12.2 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
```

```
$ cd /tmp; echo > Foo.scala;  scaladoc Foo.scala
Exception in thread "main" java.lang.NullPointerException
	at java.util.Arrays.sort(Arrays.java:1438)
	at scala.tools.nsc.classpath.JFileDirectoryLookup.listChildren(DirectoryClassPath.scala:112)
	at scala.tools.nsc.classpath.JFileDirectoryLookup.listChildren$(DirectoryClassPath.scala:96)
	at scala.tools.nsc.classpath.DirectoryClassPath.listChildren(DirectoryClassPath.scala:199)
	at scala.tools.nsc.classpath.DirectoryClassPath.listChildren(DirectoryClassPath.scala:199)
	at scala.tools.nsc.classpath.DirectoryLookup.list(DirectoryClassPath.scala:72)
	at scala.tools.nsc.classpath.DirectoryLookup.list$(DirectoryClassPath.scala:68)
	at scala.tools.nsc.classpath.DirectoryClassPath.list(DirectoryClassPath.scala:199)
	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$list$1(AggregateClassPath.scala:78)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at scala.tools.nsc.classpath.AggregateClassPath.list(AggregateClassPath.scala:76)
	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:269)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:218)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1521)
	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2291)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.<init>(FindMembers.scala:17)
	at scala.reflect.internal.tpe.FindMembers$FindMembers.<init>(FindMembers.scala:194)
	at scala.reflect.internal.Types$Type.findMembersInternal$1(Types.scala:1016)
	at scala.reflect.internal.Types$Type.findMembers(Types.scala:1017)
	at scala.reflect.internal.Types$Type.membersBasedOnFlags(Types.scala:645)
	at scala.reflect.internal.Types$Type.members(Types.scala:591)
	at scala.tools.nsc.doc.model.ModelFactory.isEmptyJavaObject(ModelFactory.scala:1011)
	at scala.tools.nsc.doc.model.ModelFactory.templateShouldDocument(ModelFactory.scala:990)
	at scala.tools.nsc.doc.DocFactory$$anon$1.templateShouldDocument(DocFactory.scala:77)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.$anonfun$memberSymsLazy$1(ModelFactory.scala:352)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.$anonfun$memberSymsLazy$1$adapted(ModelFactory.scala:352)
	at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.collection.TraversableLike.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike.filterImpl$(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.filterImpl(Traversable.scala:104)
	at scala.collection.TraversableLike.filter(TraversableLike.scala:259)
	at scala.collection.TraversableLike.filter$(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.<init>(ModelFactory.scala:352)
	at scala.tools.nsc.doc.model.ModelFactory$PackageImpl.<init>(ModelFactory.scala:465)
	at scala.tools.nsc.doc.model.ModelFactory$RootPackageImpl.<init>(ModelFactory.scala:473)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$$anon$1.<init>(ModelFactory.scala:657)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:657)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createRootPackage(ModelFactory.scala:605)
	at scala.tools.nsc.doc.model.ModelFactory$$anon$21.<init>(ModelFactory.scala:50)
	at scala.tools.nsc.doc.model.ModelFactory.makeModel(ModelFactory.scala:47)
	at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:81)
	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:124)
	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:131)
	at scala.tools.nsc.ScalaDoc.process(ScalaDoc.scala:41)
	at scala.tools.nsc.ScalaDoc$.main(ScalaDoc.scala:92)
	at scala.tools.nsc.ScalaDoc.main(ScalaDoc.scala)
```

**Comment by SethTisue** [comment]
I've labeled this as "good first issue" because at least figuring out what's going on here ought to be not-too-hard. how "easy" an actual fix might be depends on the results of that investigation.

**Comment by izeigerman** [comment]
This issue occurs due to the behavior of `java.io.File` which returns null in the `listFiles()` method instead of throwing exception when the directory is prohibited for reading. Here is a minimal directory structure which reproduces this issue on Mac OS 10.13.3:
```
$ ls -lh
total 8
-rw-r--r--  1 izeigerman  2075806812     1B Mar 10 09:28 Foo.scala
drwx------  2 root        wheel         64B Mar 10 09:28 test/

$ ls ./test
ls: test: Permission denied
```
The null value is returned here: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala#L98-L101 .

The trivial solution will be adding `packageDir.canRead` condition here: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala#L94 . I've tested this fix and it works as expected. Other option will be to check the output of the `listFiles()` method before using it. I personally think the first approach is better. If this sounds ok I'll be glad to create a PR with fix.
