### ISSUE TITLE
Invalid range positions with XML in expression position of a lambda

### ISSUE THREAD

**Issue by retronym** [scala/bug#10321]
```scala
class RangePosFail {
  def fail = {
    (name: String) =>
      val s = ""
      <iframe/> // Positions$ValidateException: Enclosing tree [53] does not include tree [52]
  }

  def ok1 = {
    (name: String) =>
      val s = ""
      (<iframe/>)
  }

  def ok2 = {
    (name: String) => {
      val s = ""
      <iframe/>
    }
  }
}

```

**Comment by som-snytt** [comment]
I remember some hokey interactions between xml mode and brackets, because of brace syntax in xml.

But I can't seem to repro this under `-Yrangepos`. What am I missing?

**Comment by retronym** [comment]
Seen again in the wild, with reports that the failure was intermittent.

Possibly related #8101.

**Comment by retronym** [comment]
Turns out this only reproduces with CRLF line endings. Thanks to @mkeskells for minimizing!

```
$ cat -e /Users/jz/Downloads/XmlTest-crlf.scala; echo ""; cat -e cat -e /Users/jz/Downloads/XmlTest-lf.scala
^M$
object Test {^M$
  Nil.map { _ =>^M$
    <X />^M$
    <Y />^M$
  }^M$
}
cat: cat: No such file or directory
cat: -e: No such file or directory
$
object Test {$
  Nil.map { _ =>$
    <X />$
    <Y />$
  }$
}
```

```
$ /usr/local/bin/scalac -Yvalidate-pos:typer -Xprint:parser -Xprint-pos -Yrangepos /Users/jz/Downloads/XmlTest-crlf.scala
[[syntax trees at end of                    parser]] // XmlTest-crlf.scala
[2:63]package [2:2]<empty> {
  [2:63]object Test extends [14:63][63]scala.AnyRef {
    [14]def <init>() = [14]{
      [NoPosition][NoPosition][NoPosition]super.<init>();
      [14]()
    };
    [19:60][19:26]Nil.map([29:55](([29:30]x$1) => [40:56]{
      [40]val $buf = [40][40][40]new [40]_root_.scala.xml.NodeBuffer();
      [40:45][40]$buf.$amp$plus(<40:45>{
        <40:45>{
          <40:45><40:45><40:45>new <40:45>_root_.scala.xml.Elem(<40:45>null, <40:45>"X", <40:45>_root_.scala.xml.Null, <40:45>$scope, <40:45>true)
        }
      });
      [51:56][40]$buf.$amp$plus(<51:56>{
        <51:56>{
          <51:56><51:56><51:56>new <51:56>_root_.scala.xml.Elem(<51:56>null, <51:56>"Y", <51:56>_root_.scala.xml.Null, <51:56>$scope, <51:56>true)
        }
      });
      [40]$buf
    }))
  }
}

======= Position error
Enclosing tree [376] does not include tree [375]
== Enclosing tree [376] of type Function at [29:55]XmlTest-crlf.scala

[L   3        ] #376    [29:55]         Function   // =>

== Enclosed tree [375] of type Block at [40:56]XmlTest-crlf.scala

[L   4        ] #375    [40:56]         Block      // X />


While validating #796
[L   2        ] #796    [2:63]          PackageDef // object Test {

Children:
  [L   2 P#  796] #95     [2:2]           Ident      // o
  [L   2 P#  796] #795    [2:63]          ModuleDef  // Test {
=======
error: scala.reflect.internal.Positions$ValidateException: Enclosing tree [376] does not include tree [375]
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:128)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions.validatePositions(Positions.scala:252)
	at scala.reflect.internal.Positions.validatePositions$(Positions.scala:140)
	at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:18)
	at scala.tools.nsc.Global$Run.$anonfun$compileUnitsInternal$2(Global.scala:1495)
	at scala.tools.nsc.Global$Run.$anonfun$compileUnitsInternal$2$adapted(Global.scala:1495)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1495)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1451)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1444)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1567)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
	at scala.tools.nsc.Driver.process(Driver.scala:55)
	at scala.tools.nsc.Driver.main(Driver.scala:68)
	at scala.tools.nsc.Main.main(Main.scala)
Exception in thread "main" scala.reflect.internal.Positions$ValidateException: Enclosing tree [376] does not include tree [375]
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:128)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions$worker$2$.loop(Positions.scala:243)
	at scala.reflect.internal.Positions.validatePositions(Positions.scala:252)
	at scala.reflect.internal.Positions.validatePositions$(Positions.scala:140)
	at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:18)
	at scala.tools.nsc.Global$Run.$anonfun$compileUnitsInternal$2(Global.scala:1495)
	at scala.tools.nsc.Global$Run.$anonfun$compileUnitsInternal$2$adapted(Global.scala:1495)
	at scala.collection.Iterator.foreach(Iterator.scala:937)
	at scala.collection.Iterator.foreach$(Iterator.scala:937)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1495)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1451)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1444)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1567)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
	at scala.tools.nsc.Driver.process(Driver.scala:55)
	at scala.tools.nsc.Driver.main(Driver.scala:68)
	at scala.tools.nsc.Main.main(Main.scala)
/code/guardian-frontend on master*
$ /usr/local/bin/scalac -Yvalidate-pos:typer -Xprint:parser -Xprint-pos -Yrangepos /Users/jz/Downloads/XmlTest-lf.scala
[[syntax trees at end of                    parser]] // XmlTest-lf.scala
[1:57]package [1:1]<empty> {
  [1:57]object Test extends [13:57][57]scala.AnyRef {
    [13]def <init>() = [13]{
      [NoPosition][NoPosition][NoPosition]super.<init>();
      [13]()
    };
    [17:55][17:24]Nil.map([27:51](([27:28]x$1) => [37:51]{
      [37]val $buf = [37][37][37]new [37]_root_.scala.xml.NodeBuffer();
      [37:41][37]$buf.$amp$plus(<37:41>{
        <37:41>{
          <37:41><37:41><37:41>new <37:41>_root_.scala.xml.Elem(<37:41>null, <37:41>"X", <37:41>_root_.scala.xml.Null, <37:41>$scope, <37:41>true)
        }
      });
      [47:51][37]$buf.$amp$plus(<47:51>{
        <47:51>{
          <47:51><47:51><47:51>new <47:51>_root_.scala.xml.Elem(<47:51>null, <47:51>"Y", <47:51>_root_.scala.xml.Null, <47:51>$scope, <47:51>true)
        }
      });
      [37]$buf
    }))
  }
}

```

**Comment by som-snytt** [comment]
@som-snytt You're missing that in the original example, the line comment is not part of the original example.

**Comment by mkeskells** [comment]
I cant take **all** the credit for the minimalization of the repro.
It was a team effort. 4 of us poking around in the debugger on one machine on 2 different workspaces where one workspace worked and one failed. After about an hour I spotted the CRLF check in the code, and thought "I wonder what the git line ending setting was in the other workspace"
The rest was more predictable.
😃
