### ISSUE TITLE
Undeclared and unprovided dependencies in scala-compiler

### ISSUE THREAD

**Issue by paulp** [scala/bug#10335]
Bundling the ant jar would only affect this particular demonstration. The scala-compiler maven artifact has the same issue. Shipping classes which blows up if loaded affects things even if nobody has any interest in or need for those classes, such as when analyzing the contents of a jar.

```scala
% scala-2.12
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions for evaluation. Or try :help.

scala> new scala.tools.ant.sabbus.Make
error: missing or invalid dependency detected while loading class file Make.class.
Could not access type Task in package org.apache.tools.ant,
because it (or its dependencies) are missing. Check your build definition for
missing or conflicting dependencies. (Re-run with -Ylog-classpath to see the problematic classpath.)
A full rebuild may help if Make.class was compiled against an incompatible version of org.apache.tools.ant.

scala> new scala.tools.ant.sabbus.Make
java.lang.IllegalArgumentException: requirement failed: package ant
	at scala.reflect.internal.Types$ModuleTypeRef.<init>(Types.scala:1879)
	at scala.reflect.internal.Types$PackageTypeRef.<init>(Types.scala:1897)
	at scala.reflect.internal.Types$TypeRef$.apply(Types.scala:2401)
	at scala.reflect.internal.Types.typeRef(Types.scala:3553)
	at scala.reflect.internal.Types.typeRef$(Types.scala:3536)
```

**Comment by SethTisue** [comment]
PR: https://github.com/scala/scala/pull/6255

**Comment by SethTisue** [comment]
the issue is still present in 2.12.4, so I assume @paulp closed the ticket just out of generalized weltschmerz

**Comment by paulp** [comment]
@SethTisue There is a github page for all the tickets one has opened which remain open across all repositories, which somewhat unfortunately incentivizes one to close old tickets to make that page useful. No weltschmerz in this case, just minimalism and misaligned incentives.

**Comment by SethTisue** [comment]
I just wanted to say "weltschmerz", it's been a while since the last time.

**Comment by paulp** [comment]
Follow me around and opportunities will be abundant.
