### ISSUE TITLE
compiler fails on my code ("unexpected type: class scala.reflect.internal.Symbols$TypeSkolem")

### ISSUE THREAD

**Issue by vpatryshev** [scala/bug#10380]
Compiler fails with this error:
```
[error] unexpected type: class scala.reflect.internal.Symbols$TypeSkolem type vs
scala.reflect.internal.FatalError: unexpected type: class scala.reflect.internal.Symbols$TypeSkolem type vs
	at scala.reflect.internal.Reporting.abort(Reporting.scala:61)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:57)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
	at scala.reflect.internal.Symbols$TypeSymbol.existentialBound(Symbols.scala:3022)
	at scala.reflect.internal.Symbols$TypeSkolem.existentialBound(Symbols.scala:3152)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$packedType$6(Typers.scala:3976)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$packedType$6$adapted(Typers.scala:3976)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.tools.nsc.typechecker.Typers$Typer.addLocals$1(Typers.scala:3976)
	at scala.tools.nsc.typechecker.Typers$Typer.packedType(Typers.scala:3980)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5725)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1069)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1615)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1784)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1749)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:837)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1946)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1944)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1939)
```

Scala version:
Scala compiler version 2.12.2

Java version:
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

How to reproduce: 

- Pull [(https://github.com/vpatryshev/ScalaKittens/commit/1b82c1ef71e1f27ce68191a775df771d86a8ea9b)]
- in ```ScalaKittens/scala212/core```, run sbt clean test

(let me know if more information is needed)

**Comment by lrytz** [comment]
@vpatryshev If you have time to distill this into a self-contained source file that triggers the error, that would help us a lot.

**Comment by vpatryshev** [comment]
Ok, sorry, will try to create a concise test case.

**Comment by frosforever** [comment]
Hey there, I hit this recently and came up with a fairly small example. This is running with scala `2.11.12`.
```scala
sealed abstract class Id(val id: Int)
object Id {
  case object One extends Id(1)
}
case class TypedToExplode[T <: Id](id: Int)

object Foo {
  def blowUp(id: Id, ids: Int*): TypedToExplode[id.type] = null
  val ids = Seq(1, 2)

  val happy = blowUp(Id.One, ids: _*)
  val stillHappy = blowUp(Id.One, 1)
  val explodes = blowUp(Id.One, 1, 2)
}
```

`explodes` explodes with:
```
[error] unexpected type: class scala.reflect.internal.Symbols$TypeSkolem type id
[error] ## Exception when compiling 5 sources to XXXX/target/scala-2.11/classes
[error] unexpected type: class scala.reflect.internal.Symbols$TypeSkolem type id
[error] scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
[error] scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
[error] scala.reflect.internal.Symbols$TypeSymbol.existentialBound(Symbols.scala:3068)
[error] scala.reflect.internal.Symbols$TypeSkolem.existentialBound(Symbols.scala:3198)
[error] scala.tools.nsc.typechecker.Typers$Typer$$anonfun$scala$tools$nsc$typechecker$Typers$Typer$$addLocals$1$2.apply(Typers.scala:3863)
[error] scala.tools.nsc.typechecker.Typers$Typer$$anonfun$scala$tools$nsc$typechecker$Typers$Typer$$addLocals$1$2.apply(Typers.scala:3863)
[error] scala.collection.immutable.List.foreach(List.scala:392)
[error] scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
[error] scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$addLocals$1(Typers.scala:3863)
[error] scala.tools.nsc.typechecker.Typers$Typer.packedType(Typers.scala:3867)
[error] scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5585)
[error] scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:967)
[error] scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1490)
[error] scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1641)
[error] scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1650)
[error] scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:869)
[error] scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:868)
[error] scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:868)
[error] scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1677)
[error] scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:868)
[error] scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:860)
[error] scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1799)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1807)
[error] scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1797)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
[error] scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1680)
[error] scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$class.addDerivedTrees(MethodSynthesis.scala:182)
[error] scala.tools.nsc.typechecker.Namers$Namer.addDerivedTrees(Namers.scala:54)
[error] scala.tools.nsc.typechecker.Typers$Typer$$anonfun$25.apply(Typers.scala:1903)
[error] scala.tools.nsc.typechecker.Typers$Typer$$anonfun$25.apply(Typers.scala:1903)
[error] scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1840)
[error] scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1837)
[error] scala.collection.immutable.List.flatMap(List.scala:338)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1903)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1803)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5337)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5386)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
[error] scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5481)
[error] scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3042)
[error] scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
[error] scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3150)
[error] scala.collection.immutable.List.loop$1(List.scala:176)
[error] scala.collection.immutable.List.mapConserve(List.scala:200)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3150)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5042)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5339)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5386)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5423)
[error] scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5450)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5401)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5477)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
[error] scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:467)
[error] scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:458)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:467)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:94)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:93)
[error] scala.collection.Iterator$class.foreach(Iterator.scala:891)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1528)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1513)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1508)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1609)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1443)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1417)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] sbt.std.Transform$$anon$4.work(System.scala:66)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:272)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
```

**Comment by SethTisue** [comment]
yeah, let's just keep #7924
