### ISSUE TITLE
Positions$ValidateException: Overlapping trees for typed infix operator

### ISSUE THREAD

**Issue by olafurpg** [scala/bug#10416]
```scala
$ cat fo.scala
object fo {
  2 ::[Int] List(2)
}
$ scalac -version
Scala code runner version 2.12.2 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
$ scalac -Yrangepos fo.scala
======= Position error
Overlapping trees (30,34)
== Ancestor tree [35] of type Block at [14:31]fo.scala

[L   2        ] #35     [14:31]         Block      // ::[Int] List(2)

== First overlapping tree [30] of type ValDef at [14:15]fo.scala

[L   2        ] #30     [14:15]         ValDef     // ::

== Second overlapping tree [34] of type Apply at [14:15]fo.scala

[L   2        ] #34     [14:15]         Apply      // ::


While validating #49
[L   1        ] #49     [0:33]          PackageDef // object fo {

Children:
  [L   1 P#   49] #48     [0:0]           Ident      // o
  [L   1 P#   49] #47     [0:33]          ModuleDef  // fo {
=======
error: scala.reflect.internal.Positions$ValidateException: Overlapping trees (30,34)
	at scala.reflect.internal.Positions.validate$1(Positions.scala:102)
	at scala.reflect.internal.Positions.$anonfun$validatePositions$12(Positions.scala:142)
	at scala.reflect.internal.Positions.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions.$anonfun$validatePositions$12(Positions.scala:142)
	at scala.reflect.internal.Positions.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions.$anonfun$validatePositions$12(Positions.scala:142)
	at scala.reflect.internal.Positions.validate$1(Positions.scala:142)
	at scala.reflect.internal.Positions.validatePositions(Positions.scala:147)
	at scala.reflect.internal.Positions.validatePositions$(Positions.scala:83)
	at scala.reflect.internal.SymbolTable.validatePositions(SymbolTable.scala:16)
```

I expected the code to compile without an exception. I'm unable to reproduce if I leave out `[Int]`.

Related https://github.com/scala/scala-dev/issues/390 

It does not seem to be related to `::` being right-associative, this also reproduces the issue
```scala
object fo {
  List(2) ++[Int] List(2)
}
```

**Comment by hrhino** [comment]
Possibly https://github.com/scala/bug/issues/10240? Which (lucky you?) is fixed by https://github.com/scala/scala/pull/5787..

**Comment by olafurpg** [comment]
I searched for related issues but that one did not pop up. Seems to be the same ticket indeed, thanks!

**Comment by SethTisue** [comment]
Duplicate of #10240

**Comment by SethTisue** [comment]
check out the new GitHub duplicate-ticket feature! https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates

**Comment by hrhino** [comment]
We truly live in the future.

**Comment by som-snytt** [comment]
The future is re-closing as not planned.
