### ISSUE TITLE
reflective typecheck has failed: object random is not a member of package math

### ISSUE THREAD

**Issue by Atry** [scala/bug#10433]
``` scala
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> import scala.reflect.runtime.universe._ 
import scala.reflect.runtime.universe._

scala> import scala.tools.reflect.ToolBox 
import scala.tools.reflect.ToolBox

scala> val toolBox = scala.reflect.runtime.currentMirror.mkToolBox() 
toolBox: scala.tools.reflect.ToolBox[reflect.runtime.universe.type] = scala.tools.reflect.ToolBoxFactory$ToolBoxImpl@28f33810

scala> q"math.random" 
res0: reflect.runtime.universe.Select = math.random

scala> toolBox.typecheck(res0) 
scala.tools.reflect.ToolBoxError: reflective typecheck has failed: object random is not a member of package math
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.$anonfun$typecheck$1(ToolBoxFactory.scala:182)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.$anonfun$transformDuringTyper$4(ToolBoxFactory.scala:150)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.$anonfun$transformDuringTyper$3(ToolBoxFactory.scala:150)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.$anonfun$transformDuringTyper$1(ToolBoxFactory.scala:149)
  at scala.reflect.internal.Trees.wrappingIntoTerm(Trees.scala:1710)
  at scala.reflect.internal.Trees.wrappingIntoTerm$(Trees.scala:1707)
  at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:16)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.transformDuringTyper(ToolBoxFactory.scala:119)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.typecheck(ToolBoxFactory.scala:174)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.$anonfun$typecheck$6(ToolBoxFactory.scala:379)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:359)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typecheck(ToolBoxFactory.scala:371)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typecheck(ToolBoxFactory.scala:26)
  ... 29 elided

```

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/6393
