### ISSUE TITLE
Thread unsafety in Scala reflection

### ISSUE THREAD

**Issue by jameshales** [scala/bug#10431]
Given the following snippet in Scala 2.12.2, 2.11.11, or 2.11.0:

```scala
import scala.reflect.runtime.universe.{ ClassSymbol, typeOf }

object Foo {
  val fooType = typeOf[Foo.type]

  def getFooClass: ClassSymbol =
    fooType.typeSymbol.asClass

  def itFails: Unit =
    (1 to 10).par.foreach { _ =>
      getFooClass
    }

  def itWorks: Unit = {
    getFooClass
    itFails
  }
}
```

Running `Foo.itFails` in a Scala REPL throws an exception the first time it is run:

```
scala> Foo.itFails
scala.ScalaReflectionException: <none> is not a class
  at scala.reflect.api.Symbols$SymbolApi.asClass(Symbols.scala:272)
  at scala.reflect.api.Symbols$SymbolApi.asClass$(Symbols.scala:272)
  at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:88)
  at Foo$.getFooClass(Foo.scala:7)
  at Foo$.$anonfun$itFails$1(Foo.scala:11)
  at Foo$.$anonfun$itFails$1$adapted(Foo.scala:10)
  at scala.Function1.apply$mcVI$sp(Function1.scala:36)
  at scala.collection.parallel.immutable.ParRange$ParRangeIterator.foreach(ParRange.scala:90)
  at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
  at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
  at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
  at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
  at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
  at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
  at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
  at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
  at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
  Suppressed: scala.ScalaReflectionException: <none> is not a class
    ... 26 more
    Suppressed: scala.ScalaReflectionException: <none> is not a class
      at scala.reflect.api.Symbols$SymbolApi.asClass(Symbols.scala:272)
      at scala.reflect.api.Symbols$SymbolApi.asClass$(Symbols.scala:272)
      at scala.reflect.internal.Symbols$SymbolContextApiImpl.asClass(Symbols.scala:88)
      at Foo$.getFooClass(Foo.scala:7)
      at Foo$.$anonfun$itFails$1(Foo.scala:11)
      at Foo$.$anonfun$itFails$1$adapted(Foo.scala:10)
      at scala.Function1.apply$mcVI$sp(Function1.scala:36)
      at scala.collection.parallel.immutable.ParRange$ParRangeIterator.foreach(ParRange.scala:90)
      at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:970)
      at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:49)
      at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
      at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:63)
      at scala.collection.parallel.Task.tryLeaf(Tasks.scala:52)
      at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:46)
      at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:967)
      at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:156)
      at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:153)
      at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
      at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:146)
      at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:145)
      at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
      at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
      at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
      at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
      at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
      at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

But running `Foo.itFails` a second time in the same Scala REPL does not throw:

```
scala> Foo.itFails
scala>
```

And running `Foo.itWorks` in a *new* Scala REPL does not throw:

```
scala> Foo.itWorks
scala>
```

I suspect this is related to a race condition in the initialization of Scala reflection. The initial failure of `itFails` occurs because of the race condition, but subsequent calls to `itFails` succeed because the initialization has completed. Similarly, `itWorks` works because the initial single-threaded call to `getFooClass` causes some initialization to occur, so that the race condition doesn't occur in the multi-threaded calls.

The initialization appears to be specific to the type used in `fooType`. For example, defining a similar class with `s/foo/bar/`, e.g.:

```scala
object Bar {
  val barType = typeOf[Bar.type]

  def getBarClass: ClassSymbol =
    barType.typeSymbol.asClass

  def itFails: Unit =
    (1 to 10).par.foreach { _ =>
      getBarClass
    }

  def itWorks: Unit = {
    getBarClass
    itFails
  }
}
```

We get the following in a new Scala REPL:

```
scala> Foo.itFails
scala.ScalaReflectionException: <none> is not a class
[...]

scala> Foo.itFails

scala> Bar.itFails
scala.ScalaReflectionException: <none> is not a class
[...]

scala> Bar.itFails

scala>
```

An [old article](http://docs.scala-lang.org/overviews/reflection/thread-safety.html) in the Scala documentation mentions that Scala reflection is thread-unsafe in Scala 2.10, due to races in the initialization of reflection, but claims that it's been fixed as of 2.11. I suspect this is a similar problem.

**Comment by SethTisue** [comment]
see my remarks at https://github.com/scala/bug/issues/6240#issuecomment-643633001
