### ISSUE TITLE
javax.script.ScriptEngine not working JSR-223

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10444]
The compiler is in the classpath:

```
libraryDependencies += "org.scala-lang" % "scala-compiler" % "2.12.3"
```

```
import javax.script._
val engines = new ScriptEngineManager().getEngineFactories
engines.size // 1
engines.get(0).getEngineName // "Scala REPL"
```

Bug 1

```
engines.get(0).getScriptEngine
```

```
Caused by: scala.reflect.internal.FatalError: class StringContext does not have a member f
	at scala.reflect.internal.Definitions$DefinitionsClass.fatalMissingSymbol(Definitions.scala:1238)
	at scala.reflect.internal.Definitions$DefinitionsClass.$anonfun$getMember$1(Definitions.scala:1261)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1256)
	at scala.reflect.internal.Definitions$DefinitionsClass.getMemberMethod(Definitions.scala:1290)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.StringContext_f$lzycompute(Definitions.scala:1479)
	at scala.reflect.internal.Definitions$DefinitionsClass$RunDefinitions.StringContext_f(Definitions.scala:1479)
	at scala.tools.reflect.FastTrack.$anonfun$fastTrackCache$1(FastTrack.scala:53)
	at scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:401)
	at scala.tools.reflect.FastTrack.get(FastTrack.scala:22)
	at scala.tools.nsc.typechecker.Macros.standardIsBlackbox(Macros.scala:290)
	at scala.tools.nsc.typechecker.Macros.standardIsBlackbox$(Macros.scala:289)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.standardIsBlackbox(ReplGlobal.scala:26)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$9.default(AnalyzerPlugins.scala:392)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$9.default(AnalyzerPlugins.scala:389)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:369)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsIsBlackbox(AnalyzerPlugins.scala:389)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsIsBlackbox$(AnalyzerPlugins.scala:389)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.pluginsIsBlackbox(ReplGlobal.scala:26)
	at scala.tools.nsc.typechecker.Macros.isBlackbox(Macros.scala:284)
	at scala.tools.nsc.typechecker.Macros.isBlackbox$(Macros.scala:284)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.isBlackbox(ReplGlobal.scala:26)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:649)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:628)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:496)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:947)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:975)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1032)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1392)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:81)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.inferImplicit(ReplGlobal.scala:26)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitByType(Implicits.scala:47)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitByType$(Implicits.scala:46)
	at scala.tools.nsc.interpreter.ReplGlobal$$anon$1.inferImplicitByType(ReplGlobal.scala:26)
	at scala.tools.nsc.typechecker.Typers$Typer.hasImport$1(Typers.scala:743)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$checkFeature$3(Typers.scala:745)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$apply$1$adapted(Analyzer.scala:104)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1431)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1416)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1412)
	at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:431)
	at scala.tools.nsc.interpreter.IMain.compileSources(IMain.scala:439)
	at scala.tools.nsc.interpreter.IMain.compileString(IMain.scala:445)
	at scala.tools.nsc.interpreter.Scripted.<init>(Scripted.scala:109)
	at scala.tools.nsc.interpreter.Scripted$.apply(Scripted.scala:309)
	at scala.tools.nsc.interpreter.Scripted$Factory.getScriptEngine(Scripted.scala:302)
	at Playground.<init>(main.scala:6)
```

Bug 2

```
new javax.script.ScriptEngineManager().getEngineByName("Scala REPL") // null
```

**Comment by SethTisue** [comment]
is this a regression?

**Comment by som-snytt** [comment]
The API is `getEngineByName(String shortName)`. The "full name" is "Scala REPL", the "short name" is "scala".

The error running under sbt is https://github.com/scala/bug/issues/10058.

Part of the REPL refactor is intended to include better sbt integration, Adriaan has mentioned.
