### ISSUE TITLE
compiler crash as type variable leaks into a signature

### ISSUE THREAD

**Issue by retronym** [scala/bug#10463]
```
import java.util.Map
import java.util.function.Function
import java.util.stream.Collector
import java.util.stream.Collectors

object Test {
  val c = Collectors.groupingBy(Function.identity[String](), Collectors.counting[String]()) 
  
// scala.reflect.internal.FatalError: bad type: =?String(class scala.reflect.internal.Types$TypeVar$$anon$4)
//   at scala.tools.nsc.symtab.classfile.Pickler$Pickle.scala$tools$nsc$symtab$classfile$Pickler$Pickle$$putType(Pickler.scala:257)
//   at scala.tools.nsc.symtab.classfile.Pickler$Pickle.scala$tools$nsc$symtab$classfile$Pickler$Pickle$$putType(Pickler.scala:236)
//   at scala.tools.nsc.symtab.classfile.Pickler$Pickle.putSymbol(Pickler.scala:181)
}
```

For extra credit, the originally posed problem:

> deontologic @deontologic 14:19
> Hello. I can't seem to compile the following with scalac:

```scala
import java.util.Map
import java.util.function.Function
import java.util.stream.Collector
import java.util.stream.Collectors
val c: Collector[String, _, Map[String, Long]] = Collectors.groupingBy(Function.identity(), Collectors.counting())
```

which compiles fine in Java:

```java
Collector<String, ?, Map<String, Long>> c = Collectors.groupingBy(Function.identity(), Collectors.counting());
```

The compile error :
```
<console>:19: error: type mismatch; found : java.util.stream.Collector[Nothing,?0(in value c),Long] where type ?0(in value c) required: java.util.stream.Collector[_ >: T, ?0(in value c), Long] where type ?0(in value c) Note: Nothing <: Any, but Java-defined trait Collector is invariant in type T. You may wish to investigate a wildcard type such as `_ <: Any`. (SLS 3.2.10) val c: Collector[String, _, util.Map[String, Long]] = Collectors.groupingBy(Function.identity(), Collectors.counting())
```
> I've tried added in type parameters to Function.identity and Collectors.counting, without success. Is this compiler issue?

**Comment by retronym** [comment]
A fairly unpalatable workaround:

```
scala> def cast[A, B, C](c: Collector[_, _, _]): Collector[A, B, C] = c.asInstanceOf[Collector[A, B, C]]
cast: [A, B, C](c: java.util.stream.Collector[_, _, _])java.util.stream.Collector[A,B,C]

scala> Collectors.groupingBy[String, String, String, java.lang.Long](Function.identity(), cast(Collectors.counting()))
res31: java.util.stream.Collector[String, _, java.util.Map[String,Long]] = java.util.stream.Collectors$CollectorImpl@5a524a19
```

**Comment by deontologic** [comment]
Was playing around with `universe.reify`, and got the below stack trace. Not sure where to investigate from here.

```scala
scala> scala.reflect.runtime.universe.reify { Collectors.groupingBy(Function.identity[String](), Collectors.counting[String]()) }.tree
<console>:17: error: exception during macro expansion:
java.lang.Error: internal error: =?String (TypeVar) is not supported
	at scala.reflect.reify.codegen.GenTypes.reifyToughType(GenTypes.scala:192)
	at scala.reflect.reify.codegen.GenTypes.reifyType(GenTypes.scala:66)
	at scala.reflect.reify.codegen.GenTypes.reifyType$(GenTypes.scala:16)
	at scala.reflect.reify.Reifier.reifyType(Reifier.scala:15)
	at scala.reflect.reify.phases.Reify.$anonfun$reify$1(Reify.scala:44)
	at scala.reflect.reify.phases.Reify.reify(Reify.scala:24)
	at scala.reflect.reify.phases.Reify.reify$(Reify.scala:39)
	at scala.reflect.reify.Reifier.reify(Reifier.scala:15)
	at scala.reflect.reify.codegen.GenUtils.$anonfun$reifyBuildCall$1(GenUtils.scala:46)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at scala.reflect.reify.codegen.GenUtils.reifyBuildCall(GenUtils.scala:46)
	at scala.reflect.reify.codegen.GenUtils.reifyBuildCall$(GenUtils.scala:45)
	at scala.reflect.reify.Reifier.reifyBuildCall(Reifier.scala:15)
	at scala.reflect.reify.codegen.GenTypes.reifyType(GenTypes.scala:60)
	at scala.reflect.reify.codegen.GenTypes.reifyType$(GenTypes.scala:16)
	at scala.reflect.reify.Reifier.reifyType(Reifier.scala:15)
	at scala.reflect.reify.phases.Reify.$anonfun$reify$1(Reify.scala:44)
	at scala.reflect.reify.phases.Reify.reify(Reify.scala:24)
	at scala.reflect.reify.phases.Reify.reify$(Reify.scala:39)
	at scala.reflect.reify.Reifier.reify(Reifier.scala:15)
	at scala.reflect.reify.utils.SymbolTables$SymbolTable$.fillInSymbol$1(SymbolTables.scala:165)
	at scala.reflect.reify.utils.SymbolTables$SymbolTable$.encode(SymbolTables.scala:180)
	at scala.reflect.reify.utils.SymbolTables$SymbolTable.$anonfun$encode$1(SymbolTables.scala:110)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:82)
	at scala.reflect.reify.utils.SymbolTables$SymbolTable.encode(SymbolTables.scala:110)
	at scala.reflect.reify.utils.Extractors.scala$reflect$reify$utils$Extractors$$mkCreator(Extractors.scala:71)
	at scala.reflect.reify.utils.Extractors$ReifiedType$.apply(Extractors.scala:134)
	at scala.reflect.reify.Reifier.liftedTree1$1(Reifier.scala:82)
	at scala.reflect.reify.Reifier.reification$lzycompute(Reifier.scala:56)
	at scala.reflect.reify.Reifier.reification(Reifier.scala:55)
	at scala.reflect.reify.package$.reifyType(package.scala:47)
	at scala.reflect.reify.Reifier.liftedTree1$1(Reifier.scala:72)
	at scala.reflect.reify.Reifier.reification$lzycompute(Reifier.scala:56)
	at scala.reflect.reify.Reifier.reification(Reifier.scala:55)
	at scala.reflect.reify.package$.reifyTree(package.scala:44)
	at scala.reflect.macros.contexts.Reifiers.reifyTree(Reifiers.scala:18)
	at scala.reflect.macros.contexts.Reifiers.reifyTree$(Reifiers.scala:16)
	at scala.reflect.macros.contexts.Context.reifyTree(Context.scala:6)
	at scala.reflect.reify.Taggers.$anonfun$materializeExpr$1(Taggers.scala:73)
	at scala.reflect.reify.Taggers.materializeExpr(Taggers.scala:79)

       scala.reflect.runtime.universe.reify { Collectors.groupingBy(Function.identity[String](), Collectors.counting[String]()) }.tree
                                            ^
```
