### ISSUE TITLE
Repl -verbose crash

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#10476]
Since 2.12.2:
```
$ ./scala-2.12.2/bin/scala -verbose
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> /home/apm/jdk8/jdk1.8.0_111/jre/lib/resources.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/rt.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/jsse.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/jce.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/charsets.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/jfr.jar is not yet in the classpath cache
/home/apm/scala-2.12.2/lib/jline-2.14.3.jar is not yet in the classpath cache
/home/apm/scala-2.12.2/lib/scala-compiler.jar is not yet in the classpath cache
/home/apm/scala-2.12.2/lib/scala-library.jar is not yet in the classpath cache
/home/apm/scala-2.12.2/lib/scalap-2.12.2.jar is not yet in the classpath cache
/home/apm/scala-2.12.2/lib/scala-parser-combinators_2.12-1.0.5.jar is not yet in the classpath cache
/home/apm/scala-2.12.2/lib/scala-reflect.jar is not yet in the classpath cache
/home/apm/scala-2.12.2/lib/scala-swing_2.12-2.0.0.jar is not yet in the classpath cache
/home/apm/scala-2.12.2/lib/scala-xml_2.12-1.0.6.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/cldrdata.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/jaccess.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/nashorn.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/sunec.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/sunjce_provider.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/zipfs.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/localedata.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/sunpkcs11.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/jfxrt.jar is not yet in the classpath cache
/home/apm/jdk8/jdk1.8.0_111/jre/lib/ext/dnsns.jar is not yet in the classpath cache
Exception in thread "main" java.lang.NullPointerException
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1078)
	at scala.tools.nsc.interpreter.IMain._initialize(IMain.scala:127)
	at scala.tools.nsc.interpreter.IMain.global$lzycompute(IMain.scala:156)
	at scala.tools.nsc.interpreter.IMain.global(IMain.scala:155)
	at scala.tools.nsc.interpreter.IMain$naming$.<init>(IMain.scala:184)
	at scala.tools.nsc.interpreter.IMain.naming$lzycompute$1(IMain.scala:183)
	at scala.tools.nsc.interpreter.IMain.naming(IMain.scala:183)
	at scala.tools.nsc.interpreter.IMain$ReplStrippingWriter.stripImpl(IMain.scala:1258)
	at scala.tools.nsc.interpreter.IMain$StrippingWriter.strip(IMain.scala:1232)
	at scala.tools.nsc.interpreter.IMain$StrippingWriter.strip$(IMain.scala:1232)
	at scala.tools.nsc.interpreter.IMain$StrippingTruncatingWriter.strip(IMain.scala:1243)
	at scala.tools.nsc.interpreter.IMain$StrippingTruncatingWriter.clean(IMain.scala:1249)
	at scala.tools.nsc.interpreter.IMain$StrippingTruncatingWriter.write(IMain.scala:1250)
	at java.io.PrintWriter.print(PrintWriter.java:603)
	at java.io.PrintWriter.println(PrintWriter.java:739)
	at scala.tools.nsc.reporters.ConsoleReporter.echo(ConsoleReporter.scala:48)
	at scala.tools.nsc.Global.<init>(Global.scala:354)
	at scala.tools.nsc.interpreter.IMain$$anon$1.<init>(IMain.scala:242)
	at scala.tools.nsc.interpreter.IMain.newCompiler(IMain.scala:242)
	at scala.tools.nsc.interpreter.IMain.<init>(IMain.scala:89)
	at scala.tools.nsc.interpreter.ILoop$ILoopInterpreter.<init>(ILoop.scala:110)
	at scala.tools.nsc.interpreter.ILoop.createInterpreter(ILoop.scala:122)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$12(ILoop.scala:990)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.tools.nsc.interpreter.ILoop.savingReader(ILoop.scala:98)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$11(ILoop.scala:990)
	at scala.tools.nsc.interpreter.ILoop.startup$1(ILoop.scala:964)
	at scala.tools.nsc.interpreter.ILoop.$anonfun$process$1(ILoop.scala:1009)
	at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:75)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:88)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:99)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:104)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

```

**Comment by hrhino** [comment]
Its head seems duly hung...

```scala
  private def _initialize() = {
    try {
      // if this crashes, REPL will hang its head in shame
      val run = new _compiler.Run()
```

**Comment by som-snytt** [comment]
https://github.com/scala/scala/pull/6045

Previously, it would wait for a line of input. This isn't obvious with reams of verbose output since the prompt.

```
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
42
Exception in thread "Thread-1" java.lang.InterruptedException
	at java.util.concurrent.SynchronousQueue.put(SynchronousQueue.java:879)
	at scala.tools.nsc.interpreter.SplashLoop.run(InteractiveReader.scala:81)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by som-snytt** [comment]
I didn't track down what behavior changed: lazy vals? outer pointers? or the semantics of the unmangling code. The Great REPL refactor makes it moot.

**Comment by lrytz** [comment]
2.13.0-M2 seems to be immune to this bug

**Comment by som-snytt** [comment]
Somewhere it ought to say no-merge.
