### ISSUE TITLE
NoSuchFileException: C:\Users\Name\.scala_history

### ISSUE THREAD

**Issue by Nicofisi** [scala/bug#10494]
When I downloaded, extracted and run Scala (REPL) 2.13.0-M2 for the first time (it was the first time I run REPL on my laptop), and before evaluating anything I typed `:help`, I got this error:
```
Exception in thread "Thread-1" java.nio.file.NoSuchFileException: C:\Users\Nicofisi\.scala_history
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.write(Files.java:3351)
        at scala.tools.nsc.interpreter.jline.FileBackedHistory.append(FileBackedHistory.scala:76)
        at scala.tools.nsc.interpreter.jline.FileBackedHistory.append$(FileBackedHistory.scala:75)
        at scala.tools.nsc.interpreter.jline.JLineHistory$JLineFileHistory.append(JLineHistory.scala:49)
        at scala.tools.nsc.interpreter.jline.FileBackedHistory.addLineToFile(FileBackedHistory.scala:67)
        at scala.tools.nsc.interpreter.jline.FileBackedHistory.addLineToFile$(FileBackedHistory.scala:65)
        at scala.tools.nsc.interpreter.jline.JLineHistory$JLineFileHistory.addLineToFile(JLineHistory.scala:49)
        at scala.tools.nsc.interpreter.jline.JLineHistory$JLineFileHistory.add(JLineHistory.scala:53)
        at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:728)
        at jline.console.ConsoleReader.accept(ConsoleReader.java:2020)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2693)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2373)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2361)
        at scala.tools.nsc.interpreter.jline.JlineReader.readOneLine(JLineReader.scala:67)
        at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine(InteractiveReader.scala:34)
        at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine$(InteractiveReader.scala:31)
        at scala.tools.nsc.interpreter.jline.JlineReader.readLine(JLineReader.scala:32)
        at scala.tools.nsc.interpreter.shell.SplashLoop.run(InteractiveReader.scala:70)
        at java.lang.Thread.run(Thread.java:748)
```
Then I tried typing `:help` the second time and it worked. But, `:history` crashed the REPL

I guess it's not a big issue but anyways I'm reporting it ;)

**Comment by Nicofisi** [comment]
Actually I get this when I try to evaluate anything:
```
Nicofisi@DESKTOP-D6NAKOH MINGW64 ~/Desktop
$ scala
Welcome to Scala 2.13.0-M2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> 1 + 5
Exception in thread "Thread-1" java.nio.file.NoSuchFileException: C:\Users\Nicofisi\.scala_history
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.write(Files.java:3351)
        at scala.tools.nsc.interpreter.jline.FileBackedHistory.append(FileBackedHistory.scala:76)
        at scala.tools.nsc.interpreter.jline.FileBackedHistory.append$(FileBackedHistory.scala:75)
        at scala.tools.nsc.interpreter.jline.JLineHistory$JLineFileHistory.append(JLineHistory.scala:49)
        at scala.tools.nsc.interpreter.jline.FileBackedHistory.addLineToFile(FileBackedHistory.scala:67)
        at scala.tools.nsc.interpreter.jline.FileBackedHistory.addLineToFile$(FileBackedHistory.scala:65)
        at scala.tools.nsc.interpreter.jline.JLineHistory$JLineFileHistory.addLineToFile(JLineHistory.scala:49)
        at scala.tools.nsc.interpreter.jline.JLineHistory$JLineFileHistory.add(JLineHistory.scala:53)
        at jline.console.ConsoleReader.finishBuffer(ConsoleReader.java:728)
        at jline.console.ConsoleReader.accept(ConsoleReader.java:2020)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2693)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2373)
        at jline.console.ConsoleReader.readLine(ConsoleReader.java:2361)
        at scala.tools.nsc.interpreter.jline.JlineReader.readOneLine(JLineReader.scala:67)
        at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine(InteractiveReader.scala:34)
        at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine$(InteractiveReader.scala:31)
        at scala.tools.nsc.interpreter.jline.JlineReader.readLine(JLineReader.scala:32)
        at scala.tools.nsc.interpreter.shell.SplashLoop.run(InteractiveReader.scala:70)
        at java.lang.Thread.run(Thread.java:748)

scala> 1 + 5
```
I guess I'm going to create it manually now

**Comment by Nicofisi** [comment]
Okay now I'm actually a bit surprised, I had no idea this folder required any special permissions?
```
Nicofisi@DESKTOP-D6NAKOH MINGW64 ~/Desktop
$ scala
Welcome to Scala 2.13.0-M2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> 1 + 1
Exception in thread "Thread-1" java.nio.file.AccessDeniedException: C:\Users\Nicofisi\.scala_history
```
(This happened after I created it manually)

**Comment by som-snytt** [comment]
I've had user management issues under cygwin, I wound up with a windows domain user plus my cygwin user, and then they changed how etc/passwd is done, I keep meaning to figure that out, but I don't spend enough time in cygwin. One consequence was fighting permissions.

You can specify the history file or effectively turn it off, `scala -Dscala.shell.histfile=/dev/null`.

**Comment by cmxia** [comment]
you can make a new file manually named " .scala_history" at the path C:\Users\Nicofisi\

**Comment by Nicofisi** [comment]
@cmxia read my comment to the end :wink:

**Comment by sasanjoy** [comment]
I deleted the file .scala_history and create a new one. It works for me.

**Comment by som-snytt** [comment]
Worth adding it was renamed `.scala_history_jline3` for jline3 support. Switching versions can be confusing on that score.

**Comment by SethTisue** [comment]
closing unless/until someone experiences it in 2.13.3 or a newer version
