### ISSUE TITLE
Class or methods named with anonymous encoding can crash the compiler

### ISSUE THREAD

**Issue by nicolasstucki** [scala/bug#10492]
The code
```scala
class Foo {
  class $anon$1
  new Object { }
}
```

Will crash the compiler while lambda lifting after naming the class for `new Object { }` with `$anon$1`
```
error: java.lang.AssertionError: assertion failed: (<$anon: Object> in class Foo,<$anon: Object> in class Foo)
	at scala.reflect.internal.Scopes$Scope.enterUnique(Scopes.scala:131)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.liftDef(LambdaLift.scala:463)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.postTransform(LambdaLift.scala:473)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:544)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:56)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2589)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2587)
...
```

Similarly for methods
```scala
class Foo {
  def foo = {
    def f() = ()
    f()
  }
  def f$1() = ()
}
```

```scala
error: java.lang.AssertionError: assertion failed: (method f$1 in class Foo,method f$1 in class Foo)
	at scala.reflect.internal.Scopes$Scope.enterUnique(Scopes.scala:131)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.liftDef(LambdaLift.scala:463)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.postTransform(LambdaLift.scala:476)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:544)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:56)
```

**Comment by jvican** [comment]
I think this is on purpose. Per the spec, users are not supposed to name any term or type with '$', but I may be wrong.

**Comment by nicolasstucki** [comment]
Then it should be an error message, not a compiler crash ;)

@jvican Could you link the part of the spec that says mentioned it.

**Comment by jvican** [comment]
From http://scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html:
  
> The ‘$’ character is reserved for compiler-synthesized identifiers. User programs should not define identifiers which contain ‘$’ characters.

**Comment by som-snytt** [comment]
This is an interesting question. A crash is clearly a sort of message. Exiting w/o emitting anything would unacceptable.

The reporter interface should include a mechanism for intercepting throwables.
