### ISSUE TITLE
ToolBox cannot typecheck secondary constructors

### ISSUE THREAD

**Issue by joroKr21** [scala/bug#10507]
Example:
```scala
object Main extends App {
  import scala.reflect.runtime.universe._
  import scala.reflect.runtime.currentMirror
  import scala.tools.reflect.ToolBox

  class A(i: Int) { def this() { this(0) } } // ok
  val tb = currentMirror.mkToolBox()
  val a = tb.typecheck(q"class A(i: Int) { def this() { this(0) } }")
  println(a)
}
```
The error we get is:
```scala
Exception in thread "main" scala.tools.reflect.ToolBoxError: reflective typecheck has failed: called constructor's definition must precede calling constructor's definition
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.$anonfun$typecheck$1(ToolBoxFactory.scala:182)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.$anonfun$transformDuringTyper$4(ToolBoxFactory.scala:150)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.$anonfun$transformDuringTyper$3(ToolBoxFactory.scala:150)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.$anonfun$transformDuringTyper$1(ToolBoxFactory.scala:149)
	at scala.reflect.internal.Trees.wrappingIntoTerm(Trees.scala:1717)
	at scala.reflect.internal.Trees.wrappingIntoTerm$(Trees.scala:1714)
	at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:16)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.transformDuringTyper(ToolBoxFactory.scala:119)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.typecheck(ToolBoxFactory.scala:174)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.$anonfun$typecheck$6(ToolBoxFactory.scala:379)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:359)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typecheck(ToolBoxFactory.scala:371)
	at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typecheck(ToolBoxFactory.scala:26)
	at Main$.delayedEndpoint$Main$1(Main.scala:8)
	at Main$delayedInit$body.apply(Main.scala:1)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at Main$.main(Main.scala:1)
	at Main.main(Main.scala)
```
Scala version: 2.12.3
Java version: Oracle 1.8.0_144

**Comment by joroKr21** [comment]
Same issue with macros. The problem is that the trees don't have a position and the logic that checks for preceding constructor definition relies on positions.
