### ISSUE TITLE
Type inference of type variable crash with existential and super type relationship

### ISSUE THREAD

**Issue by gabriel-bezerra** [scala/bug#10519]
I'm trying to compile the following code snippet

```scala
object X {
  case class D[A]()

  val xs = Seq(D[Int](), D[Boolean]())

  def g[Y](is: Seq[D[_ >: Y]]) = ???
  g(xs)
}
```

It compiles in dotty but crashes on scala 2.11, 2.12 and 2.13 (commit 711c8aaf0ef4ae9dd8d83276ca6a5b03a6ffcecc) with the message:
```
scala.reflect.internal.FatalError: 
  trying to do lub/glb of typevar ?Y
        during phase: typer
```

I traced the problem to `isSubType` in `TypeComparers.scala` and put some `println`s to understand what was going on.

This is the output I have so far:
```
isWeakSubType tp1 = Seq[X.D[_ >: Boolean with Int <: AnyVal]] - tp2 = Seq[X.D[_ >: ?Y]]
isSubType tp1 = Seq[X.D[_ >: Boolean with Int <: AnyVal]] - tp2 = Seq[X.D[_ >: ?Y]] - depth = Depth(-3)
isSubType tp1 = Seq[X.D[_ >: Boolean with Int <: AnyVal]] - tp2 = Seq[X.D[_ >: ?Y]] - depth = Depth(-3)
isSubType tp1 = X.D[_ >: Boolean with Int <: AnyVal] - tp2 = X.D[_ >: ?Y] - depth = Depth(-3)
isSubType tp1 = X.D[_1] - tp2 = X.D[_ >: ?Y] - depth = Depth(-3)
[    create] ?_$2                     ( In X#g[Y]#is )
isSubType tp1 = X.D[_1] - tp2 = X.D[?_$2] - depth = Depth(-3)
isSubType tp1 = X.type - tp2 = X.type - depth = Depth(-3)
isSubType tp1 = ?_$2 - tp2 = _1 - depth = Depth(-3)
isSubType tp1 = _1 - tp2 = ?_$2 - depth = Depth(-3)
lub of List(?Y, _1) at depth Depth(1)
isSubType tp1 = _1 - tp2 = ?Y - depth = Depth(0)
isSubType tp1 = ?Y - tp2 = _1 - depth = Depth(0)
Here type Y -- crash!
scala.reflect.internal.FatalError: 
  trying to do lub/glb of typevar ?Y
```

I suspect the problem is around the lines:
```
isSubType tp1 = X.D[_1] - tp2 = X.D[?_$2] - depth = Depth(-3)
isSubType tp1 = X.type - tp2 = X.type - depth = Depth(-3)
isSubType tp1 = ?_$2 - tp2 = _1 - depth = Depth(-3)
```
because I don't get how it comes to invert the order of the types in this search.

May you help debug this problem?

Stack trace:
```
	at scala.reflect.internal.Reporting.abort(Reporting.scala:61)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:57)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
	at scala.reflect.internal.Types.stripType$1(Types.scala:4508)
	at scala.reflect.internal.Types.$anonfun$stripExistentialsAndTypeVars$4(Types.scala:4512)
	at scala.reflect.internal.Types.$anonfun$stripExistentialsAndTypeVars$4$adapted(Types.scala:4512)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.reflect.internal.Types.stripExistentialsAndTypeVars(Types.scala:4512)
	at scala.reflect.internal.Types.stripExistentialsAndTypeVars$(Types.scala:4484)
	at scala.reflect.internal.SymbolTable.stripExistentialsAndTypeVars(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.GlbLubs.lub1$1(GlbLubs.scala:310)
	at scala.reflect.internal.tpe.GlbLubs.lub0$1(GlbLubs.scala:304)
	at scala.reflect.internal.tpe.GlbLubs.lub(GlbLubs.scala:401)
	at scala.reflect.internal.tpe.GlbLubs.lub$(GlbLubs.scala:281)
	at scala.reflect.internal.SymbolTable.lub(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.GlbLubs.lub(GlbLubs.scala:260)
	at scala.reflect.internal.tpe.GlbLubs.lub$(GlbLubs.scala:253)
	at scala.reflect.internal.SymbolTable.lub(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeConstraints.solveOne$1(TypeConstraints.scala:248)
	at scala.reflect.internal.tpe.TypeConstraints.$anonfun$solve$9(TypeConstraints.scala:260)
	at scala.reflect.internal.tpe.TypeConstraints.$anonfun$solve$9$adapted(TypeConstraints.scala:260)
	at scala.reflect.internal.util.Collections.foreach3(Collections.scala:244)
	at scala.reflect.internal.util.Collections.foreach3$(Collections.scala:239)
	at scala.reflect.internal.SymbolTable.foreach3(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeConstraints.solve(TypeConstraints.scala:260)
	at scala.reflect.internal.tpe.TypeConstraints.solve$(TypeConstraints.scala:192)
	at scala.reflect.internal.SymbolTable.solve(SymbolTable.scala:16)
	at scala.reflect.internal.Types$ExistentialType.withTypeVars(Types.scala:2818)
	at scala.reflect.internal.tpe.TypeComparers.thirdTry$1(TypeComparers.scala:509)
	at scala.reflect.internal.tpe.TypeComparers.secondTry$1(TypeComparers.scala:475)
	at scala.reflect.internal.tpe.TypeComparers.firstTry$1(TypeComparers.scala:450)
	at scala.reflect.internal.tpe.TypeComparers.isSubType2(TypeComparers.scala:572)
	at scala.reflect.internal.tpe.TypeComparers.isSubType1(TypeComparers.scala:331)
	at scala.reflect.internal.tpe.TypeComparers.isSubType(TypeComparers.scala:289)
	at scala.reflect.internal.tpe.TypeComparers.isSubType$(TypeComparers.scala:250)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeComparers.secondTry$1(TypeComparers.scala:470)
	at scala.reflect.internal.tpe.TypeComparers.firstTry$1(TypeComparers.scala:450)
	at scala.reflect.internal.tpe.TypeComparers.isSubType2(TypeComparers.scala:572)
	at scala.reflect.internal.tpe.TypeComparers.isSubType1(TypeComparers.scala:331)
	at scala.reflect.internal.tpe.TypeComparers.isSubType(TypeComparers.scala:289)
	at scala.reflect.internal.tpe.TypeComparers.isSubType$(TypeComparers.scala:250)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:16)
	at scala.reflect.internal.Types.isSubArg$1(Types.scala:4237)
	at scala.reflect.internal.Types.$anonfun$isSubArgs$2(Types.scala:4240)
	at scala.reflect.internal.Types.$anonfun$isSubArgs$2$adapted(Types.scala:4240)
	at scala.reflect.internal.util.Collections.corresponds3(Collections.scala:24)
	at scala.reflect.internal.util.Collections.corresponds3$(Collections.scala:21)
	at scala.reflect.internal.SymbolTable.corresponds3(SymbolTable.scala:16)
	at scala.reflect.internal.Types.isSubArgs(Types.scala:4240)
	at scala.reflect.internal.Types.isSubArgs$(Types.scala:4234)
	at scala.reflect.internal.SymbolTable.isSubArgs(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeComparers.firstTry$1(TypeComparers.scala:422)
	at scala.reflect.internal.tpe.TypeComparers.isSubType2(TypeComparers.scala:572)
	at scala.reflect.internal.tpe.TypeComparers.isSubType1(TypeComparers.scala:331)
	at scala.reflect.internal.tpe.TypeComparers.isSubType(TypeComparers.scala:289)
	at scala.reflect.internal.tpe.TypeComparers.isSubType$(TypeComparers.scala:250)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeComparers.retry$4(TypeComparers.scala:480)
	at scala.reflect.internal.tpe.TypeComparers.thirdTryRef$1(TypeComparers.scala:491)
	at scala.reflect.internal.tpe.TypeComparers.firstTry$1(TypeComparers.scala:431)
	at scala.reflect.internal.tpe.TypeComparers.isSubType2(TypeComparers.scala:572)
	at scala.reflect.internal.tpe.TypeComparers.isSubType1(TypeComparers.scala:331)
	at scala.reflect.internal.tpe.TypeComparers.isSubType(TypeComparers.scala:289)
	at scala.reflect.internal.tpe.TypeComparers.isSubType$(TypeComparers.scala:250)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeComparers.isWeakSubType(TypeComparers.scala:597)
	at scala.reflect.internal.tpe.TypeComparers.isWeakSubType$(TypeComparers.scala:576)
	at scala.reflect.internal.SymbolTable.isWeakSubType(SymbolTable.scala:16)
	at scala.reflect.internal.Types$Type.weak_$less$colon$less(Types.scala:855)
	at scala.tools.nsc.typechecker.Infer$Inferencer.isCompatible(Infer.scala:308)
	at scala.tools.nsc.typechecker.Infer$Inferencer.$anonfun$methTypeArgs$3(Infer.scala:555)
	at scala.tools.nsc.typechecker.Infer$Inferencer.$anonfun$methTypeArgs$3$adapted(Infer.scala:547)
	at scala.reflect.internal.util.Collections.map2(Collections.scala:92)
	at scala.reflect.internal.util.Collections.map2$(Collections.scala:87)
	at scala.reflect.internal.SymbolTable.map2(SymbolTable.scala:16)
	at scala.tools.nsc.typechecker.Infer$Inferencer.methTypeArgs(Infer.scala:547)
	at scala.tools.nsc.typechecker.Infer$Inferencer.inferMethodInstance(Infer.scala:994)
	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3656)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3661)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4734)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4762)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5552)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5569)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5605)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5635)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5579)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5583)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5666)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3080)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3225)
	at scala.collection.immutable.List.loop$1(List.scala:176)
	at scala.collection.immutable.List.mapConserve(List.scala:200)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3225)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1988)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1859)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5519)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5568)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5605)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5635)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5579)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5583)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5666)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3080)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3225)
	at scala.collection.immutable.List.loop$1(List.scala:176)
	at scala.collection.immutable.List.mapConserve(List.scala:200)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3225)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5218)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5521)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5568)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5605)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5635)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5579)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5583)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5662)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:427)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnitNoLog(Global.scala:420)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:411)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:427)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1434)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1418)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1413)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1518)
	at scala.tools.partest.nest.DirectCompiler.execCompile$1(DirectCompiler.scala:114)
	at scala.tools.partest.nest.DirectCompiler.compile(DirectCompiler.scala:123)
	at scala.tools.partest.nest.Runner.attemptCompile(Runner.scala:439)
	at scala.tools.partest.nest.Runner$ScalaAndJava.result$lzycompute(Runner.scala:498)
	at scala.tools.partest.nest.Runner$ScalaAndJava.result(Runner.scala:498)
	at scala.tools.partest.nest.Runner$CompileRound.isOk(Runner.scala:484)
	at scala.tools.partest.nest.Runner.$anonfun$runTestCommon$3(Runner.scala:529)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
	at scala.tools.partest.nest.Runner.nextTestAction(Runner.scala:143)
	at scala.tools.partest.nest.Runner.nextTestActionExpectTrue(Runner.scala:148)
	at scala.tools.partest.nest.Runner.$anonfun$runTestCommon$2(Runner.scala:529)
	at scala.tools.partest.nest.Runner.$anonfun$runTestCommon$2$adapted(Runner.scala:529)
	at scala.collection.LinearSeqOptimized.forall(LinearSeqOptimized.scala:81)
	at scala.collection.LinearSeqOptimized.forall$(LinearSeqOptimized.scala:78)
	at scala.collection.immutable.List.forall(List.scala:86)
	at scala.tools.partest.nest.Runner.$anonfun$runTestCommon$1(Runner.scala:529)
	at scala.tools.partest.nest.Runner.runInContext(Runner.scala:415)
	at scala.tools.partest.nest.Runner.runTestCommon(Runner.scala:529)
	at scala.tools.partest.nest.Runner.run(Runner.scala:650)
	at scala.tools.partest.nest.SuiteRunner.$anonfun$runTest$1(Runner.scala:774)
	at scala.tools.partest.package$.timed(package.scala:129)
	at scala.tools.partest.nest.SuiteRunner.liftedTree1$1(Runner.scala:774)
	at scala.tools.partest.nest.SuiteRunner.runTest(Runner.scala:774)
	at scala.tools.partest.nest.SuiteRunner.$anonfun$runTestsForFiles$2(Runner.scala:789)
	at scala.tools.partest.package$$anon$2.call(package.scala:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gabriel-bezerra** [comment]
I traced it further, and it comes to:

```
isSubType tp1 = X.D[_ >: X.H with X.G <: X.F] - tp2 = X.D[_ >: ?Y] - depth = Depth(-3)
firstTry
secondTry
tp1 existential X.D[_ >: X.H with X.G <: X.F]
isSubType tp1 = X.D[_1] - tp2 = X.D[_ >: ?Y] - depth = Depth(-3)
firstTry
secondTry
thirdTry
tp2 existential 3rd X.D[_ >: ?Y] - underlying = X.D[_$1]
[    create] ?_$1                     ( In X#g[Y]#is )
isSubType tp1 = X.D[_1] - tp2 = X.D[?_$1] - depth = Depth(-3)
firstTry
t1 and t2 are TypeRef: sym1 = class D - sym2 = class D - pre1 = X.type - pre2 = X.type
check ref prefix
isSubType tp1 = X.type - tp2 = X.type - depth = Depth(-3)
done = true
isSubArgs(tr1.args = List(_1), tr2.args = List(?_$1), sym1.typeParams = List(type A), depth = Depth(-3))
isSubArg(t1: Type = _1, t2: Type = ?_$1, variance: Variance = invariant)
t1.bounds =  >: X.H with X.G <: X.F - t2.bounds =  >: ?_$1 <: ?_$1
t1 is type ref
t2 is type var
isSubType tp1 = ?_$1 - tp2 = _1 - depth = Depth(-3)
firstTry
secondTry
regBound: (?_$1,?NoPrefix$?._1.,false)
isSubType tp1 = _1 - tp2 = ?_$1 - depth = Depth(-3)
firstTry
tv2 type var ?_$1
tp1 is not annotated or bounded _1
regBound: (?_$1,?NoPrefix$?._1.,true)
isSubArgs result = true
lub of List(?Y, _1) at depth Depth(1)
isSubType tp1 = _1 - tp2 = ?Y - depth = Depth(0)
firstTry
tv2 type var ?Y
tp1 is not annotated or bounded _1
regBound: (?Y,?NoPrefix$?._1.,true)
isSubType tp1 = ?Y - tp2 = _1 - depth = Depth(0)
firstTry
secondTry
regBound: (?Y,?NoPrefix$?._1.,false)
Here type Y
scala.reflect.internal.FatalError: 
  trying to do lub/glb of typevar ?Y
```

**Comment by gabriel-bezerra** [comment]
I noticed also that, in dotty:

```
isSubArgs(args1 = List(X.D[_ >: Int & Boolean <: Int | Boolean]), args2 = List(X.D[_ >: Y]), tp1 = scala.collection.Seq[X.D[_ >: Int & Boolean <: Int | Boolean]], tparams = List(type A))
isSubArg(arg1 = X.D[_ >: Int & Boolean <: Int | Boolean], arg2 = X.D[_ >: Y])
isSubType(tp1 = X.D[_ >: Int & Boolean <: Int | Boolean], tp2 = X.D[_ >: Y])
firstTry
secondTry
thirdTry
appliedtype case
isSubType(tp1 = X.type(X), tp2 = X.type(X))
isSubArgs(args1 = List( >: Int & Boolean <: Int | Boolean), args2 = List( >: Y), tp1 = X.D[_ >: Int & Boolean <: Int | Boolean], tparams = List(type A))
```

Instead of making type skolems, it removes the existential types from both sides and compare just the type bounds.

**Comment by Blaisorblade** [comment]
> because I don't get how it comes to invert the order of the types in this search.

That confused me for a while, also because there's more information not being printed. But `D` is invariant, so `D[A] <: D[B]` if and only if `A` and `B` are equivalent, which means you have both `A <: B` and `B <: A`. That might explain lines:

> isSubType tp1 = ?_$2 - tp2 = _1 - depth = Depth(-3)
> isSubType tp1 = _1 - tp2 = ?_$2 - depth = Depth(-3)

because this happens while checking that:

> isSubType tp1 = X.D[_1] - tp2 = X.D[?_$2] - depth = Depth(-3)

Printing the recursion depth as part of the log might help.

**Comment by gabriel-bezerra** [comment]
I noticed that it actually finds a `true` for that `isSubType`, then moves to the constraint solver. There it crashes because it includes the `?Y` type variable in the list that is sent to be `lub`bed.
```
solving List(?_$1)/List(type _$1)/List( >: ?Y)
solveOne0(tv, tp, v, b)=(TVar<_$1=null>,type _$1,invariant,?Y)
TVar<_$1=null> addLoBound ?Y.instantiateTypeParams(List(type _$1), List(TVar<_$1=null>))
addLoBound: (TVar<_$1=null>,?Y)
solving ?_$1 false List(?Y, _1)List(?Y, _1)
lub of List(?Y, _1) at depth Depth(1)
isSubType tp1 = _1 - tp2 = ?Y - depth = Depth(0)
firstTry
tv2 type var ?Y
tp1 is not annotated or bounded _1
regBound: (?Y,?NoPrefix$?._1.,true)
isSubType tp1 = ?Y - tp2 = _1 - depth = Depth(0)
firstTry
secondTry
tp1 type var ?Y
regBound: (?Y,?NoPrefix$?._1.,false)
Here type Y 
scala.reflect.internal.FatalError: 
  trying to do lub/glb of typevar ?Y
```

**Comment by gabriel-bezerra** [comment]
> Printing the recursion depth as part of the log might help.

I'd love to do that, but I don't know how. Is there an easy way, with some build option for instance?

**Comment by Blaisorblade** [comment]
Among the -X and -Y options there are a few for logging; but the code you pointed at, strangely, seems to have no logging (at least in 2.13, haven't checked other versions). Code for implicits prints IIUC the recursion depth, but that's tracked by hand with a counter parameter...

Beware I'm not an expert of the Scalac internals (I understand the typing rules); I chipped in because nobody had yet...

Also relevant: have you tried running Scalac under a debugger? I used to set it up with Scala IDE, nowadays it might work with IDEA (@retronym uses IDEA IIUC), and using a real debugger is much more helpful. It might take a while to set up, but this bug might be tricky enough for it to be worthy.

**Comment by Blaisorblade** [comment]
Wait, is solve being called to replace the type variables/skolems with themselves? That's indeed non-obvious, you'd want usually unification to deduce Y and give it a value that does not mention Y. And maybe that's why the latter code does not expect Y to be there and complains.
But this is just an hypothesis and might be a red herring. I'm not even sure about all the different sorts of type variables in Scalac, between skolems, existentials and what not.

**Comment by gabriel-bezerra** [comment]
> Wait, is solve being called to replace the type variables/skolems with themselves? That's indeed non-obvious, you'd want usually unification to deduce Y and give it a value that does not mention Y.

Yes, that's what I've found. The inner resolution creates a new `TypeVar` when it finds `X.D[_ >: ?Y]`. IIUC it is seen as `Existential` which leads to `et2.withTypeVars(isSubType(tp1, _, depth), depth)`:
```
tp2 existential 3rd X.D[_ >: ?Y] - underlying = X.D[_$1]
[    create] ?_$1                     ( In X#g[Y]#is )
```
```scala
    def withTypeVars(op: Type => Boolean): Boolean = withTypeVars(op, AnyDepth)

    def withTypeVars(op: Type => Boolean, depth: Depth): Boolean = {
      val quantifiedFresh = cloneSymbols(quantified)
      val tvars = quantifiedFresh map (tparam => TypeVar(tparam))
      val underlying1 = underlying.instantiateTypeParams(quantified, tvars) // fuse subst quantified -> quantifiedFresh -> tvars
      op(underlying1) && {
        println(s"going to solve for ${this.safeToString}")
        solve(tvars, quantifiedFresh, quantifiedFresh map (_ => Invariant), upper = false, depth) &&
        isWithinBounds(NoPrefix, NoSymbol, quantifiedFresh, tvars map (_.inst))
      }
    }
  }
```

During the `solve` of the `?_$1`, that was created in this very inner body, it picks `?Y` (from `underlying`?) and crash. But the point is exactly resolving `?Y`.

The code I'm using to investigate it: https://github.com/gabriel-bezerra/scala/pull/1

**Comment by gabriel-bezerra** [comment]
I'm not running it on a debugger. This is how I understand the stack is. I put at the same level the `println`s that I have as soon as the method is called and those that are in its body.
```
infer method inst X.this.g[Y], tparams = List(type Y), args = List(Seq[X.D[_ >: X.H with X.G <: X.F]]), pt = ?, lobounds = List(Nothing), parambounds = List()
  methTypeArgs(X.this.g[Y], List(type Y), List(Seq[X.D[_ >: Y]]), Nothing, List(Seq[X.D[_ >: X.H with X.G <: X.F]]), ?)
  tvars: List(?Y)
  [    create] ?Y                       ( In X#g[Y] )
  restpeInst: Nothing
    isCompatible tp1 = Nothing
    isWeakSubType tp1 = Nothing - tp2 = ?
    isSubType tp1 = Nothing - tp2 = ? - depth = Depth(-3)
  done with weak_<:< = true
  passed conservatively compatibile test
  came up to here!
  came up to here!! tp1 = Seq[X.D[_ >: X.H with X.G <: X.F]]
  came up to here!!! pt1 = Seq[X.D[_ >: ?Y]]
    isCompatible tp1 = Seq[X.D[_ >: X.H with X.G <: X.F]]
      isWeakSubType tp1 = Seq[X.D[_ >: X.H with X.G <: X.F]] - tp2 = Seq[X.D[_ >: ?Y]]
        isSubType tp1 = Seq[X.D[_ >: X.H with X.G <: X.F]] - tp2 = Seq[X.D[_ >: ?Y]] - depth = Depth(-3)
        firstTry
        t1 and t2 are TypeRef: sym1 = trait Seq - sym2 = type Seq - pre1 = scala.collection.type - pre2 = scala.type
        thirdTryRef
          isSubType tp1 = Seq[X.D[_ >: X.H with X.G <: X.F]] - tp2 = Seq[X.D[_ >: ?Y]] - depth = Depth(-3)
          firstTry
          t1 and t2 are TypeRef: sym1 = trait Seq - sym2 = trait Seq - pre1 = scala.collection.type - pre2 = scala.collection.type
          [    create] ?_$1                     ( In X#g[Y]#is )

            isSubArgs(tr1.args = List(X.D[_ >: X.H with X.G <: X.F]), tr2.args = List(X.D[_ >: ?Y]), sym1.typeParams = List(type A), depth = Depth(-3))
              isSubArg(t1: Type = X.D[_ >: X.H with X.G <: X.F], t2: Type = X.D[_ >: ?Y], variance: Variance = covariant)
              t1.bounds =  >: X.D[_ >: X.H with X.G <: X.F] <: X.D[_ >: X.H with X.G <: X.F] - t2.bounds =  >: X.D[_ >: ?Y] <: X.D[_ >: ?Y]
              t1 is existential type
              t2 is existential type
                isSubType tp1 = X.D[_ >: X.H with X.G <: X.F] - tp2 = X.D[_ >: ?Y] - depth = Depth(-3)
                firstTry
                secondTry
                tp1 existential X.D[_ >: X.H with X.G <: X.F]
                  isSubType tp1 = X.D[_1] - tp2 = X.D[_ >: ?Y] - depth = Depth(-3)
                  firstTry
                  secondTry
                  thirdTry
                  tp2 existential 3rd X.D[_ >: ?Y] - underlying = X.D[_$1]
                    withTypeVars(op: Type => Boolean, depth = Depth(-3)) {
                    quantifiedFresh = List(type _$1)
                    tvars = List(?_$1)
                    underlying1 = X.D[?_$1]
                      isSubType tp1 = X.D[_1] - tp2 = X.D[?_$1] - depth = Depth(-3)
                      firstTry
                      t1 and t2 are TypeRef: sym1 = class D - sym2 = class D - pre1 = X.type - pre2 = X.type
                        check ref prefix
                        isSubType tp1 = X.type - tp2 = X.type - depth = Depth(-3)
                        done = true
                      isSubArgs(tr1.args = List(_1), tr2.args = List(?_$1), sym1.typeParams = List(type A), depth = Depth(-3))
                        isSubArg(t1: Type = _1, t2: Type = ?_$1, variance: Variance = invariant)
                        t1.bounds =  >: X.H with X.G <: X.F - t2.bounds =  >: ?_$1 <: ?_$1
                        t1 is type ref
                        t2 is type var
                          isSubType tp1 = ?_$1 - tp2 = _1 - depth = Depth(-3)
                            firstTry
                            secondTry
                            tp1 type var ?_$1
                              regBound: (?_$1,?NoPrefix$?._1.,false)
                                trying to unify ?_$1 simple case
                                addHiBound: (?_$1,?NoPrefix$?._1.)
                          isSubType tp1 = _1 - tp2 = ?_$1 - depth = Depth(-3)
                            firstTry
                            tv2 type var ?_$1
                            tp1 is not annotated or bounded _1
                              regBound: (?_$1,?NoPrefix$?._1.,true)
                                trying to unify ?_$1 simple case
                                addLoBound: (?_$1,?NoPrefix$?._1.)
                      isSubArgs result = true
                      going to solve for X.D[_ >: ?Y]
                        trying to solve(tvars = List(?_$1), tparams = List(type _$1), variances = List(invariant), upper = false, depth = Depth(-3))
                        solving List(?_$1)/List(type _$1)/List( >: ?Y)
                          solveOne0(tv, tp, v, b)=(TVar<_$1=null>,type _$1,invariant,?Y)
                          TVar<_$1=null> addLoBound ?Y.instantiateTypeParams(List(type _$1), List(TVar<_$1=null>))
                            addLoBound: (TVar<_$1=null>,?Y)
                            solving ?_$1 false List(?Y, _1)List(?Y, _1)
                            (tvar.constr.loBounds = List(?Y, _1) .map(_.bounds) -> List( >: ?Y <: ?Y,  >: X.H with X.G <: X.F))
                              lub of List(?Y, _1) at depth Depth(1)
                                isSubType tp1 = _1 - tp2 = ?Y - depth = Depth(0)
                                firstTry
                                tv2 type var ?Y
                                tp1 is not annotated or bounded _1
                                  regBound: (?Y,?NoPrefix$?._1.,true)
                                isSubType tp1 = ?Y - tp2 = _1 - depth = Depth(0)
                                  firstTry
                                  secondTry
                                  tp1 type var ?Y
                                    regBound: (?Y,?NoPrefix$?._1.,false)
                                      lub running on List(?Y, _1) -- lubresults = Map()
                                        Here type Y
                                        scala.reflect.internal.FatalError:

```

**Comment by joroKr21** [comment]
It can't `glb/lub` because `?Y isRelatable _1` returns false (`_1` has skolemization level of 1 and `?Y` has a skolemization level of 0). I have no understanding of skolemization level and why it is needed, but maybe someone else can explain?

**Comment by joroKr21** [comment]
Ah I think I understand. Without skolemization level `Y` would be inferred as the skolem `_1` of the existential `Seq[D[_ >: Boolean with Int <: AnyVal]]` (type of `xs`) which is useless because it's not visible outside of said existential.
