### ISSUE TITLE
Classloader created by MainGenericRunner only sees java.base on JDK9

### ISSUE THREAD

**Issue by retronym** [scala/bug#10520]
```
 (java_use 9; qscalac $(f 'package p1; object Test extends App { println(Class.forName("javax.tools.ToolProvider")) }') && SCALA_RUNNER_DEBUG=true scala p1.Test)
saved stty:
gfmt1:cflag=4b00:iflag=6b02:lflag=200005cf:oflag=3:discard=f:dsusp=19:eof=4:eol=ff:eol2=ff:erase=7f:intr=3:kill=15:lnext=16:min=1:quit=1c:reprint=12:start=11:status=14:stop=13:susp=1a:time=0:werase=17:ispeed=38400:ospeed=38400

/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java
-Xmx256M
-Xms32M
-Xbootclasspath/a:/usr/local/Cellar/scala/2.12.3/libexec/lib/jline-2.14.4.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-compiler.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-library.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-parser-combinators_2.12-1.0.6.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-reflect.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-swing_2.12-2.0.0.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-xml_2.12-1.0.6.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scalap-2.12.3.jar
-classpath
""
-Dscala.boot.class.path=/usr/local/Cellar/scala/2.12.3/libexec/lib/jline-2.14.4.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-compiler.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-library.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-parser-combinators_2.12-1.0.6.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-reflect.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-swing_2.12-2.0.0.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-xml_2.12-1.0.6.jar:/usr/local/Cellar/scala/2.12.3/libexec/lib/scalap-2.12.3.jar
-Dscala.home=/usr/local/Cellar/scala/2.12.3/libexec
-Dscala.usejavacp=true
-Denv.emacs=
scala.tools.nsc.MainGenericRunner
p1.Test

java.lang.ClassNotFoundException: javax.tools.ToolProvider
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:292)
	at p1.Test$.delayedEndpoint$p1$Test$1(a.scala:1)
	at p1.Test$delayedInit$body.apply(a.scala:1)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at p1.Test$.main(a.scala:1)
	at p1.Test.main(a.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:98)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:32)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:30)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:129)
	at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:98)
	at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:90)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:129)
	at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:22)
	at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:21)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:28)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:66)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:85)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
restoring stty:
gfmt1:cflag=4b00:iflag=6b02:lflag=200005cf:oflag=3:discard=f:dsusp=19:eof=4:eol=ff:eol2=ff:erase=7f:intr=3:kill=15:lnext=16:min=1:quit=1c:reprint=12:start=11:status=14:stop=13:susp=1a:time=0:werase=17:ispeed=38400:ospeed=38400
```

```
% java -cp .:/usr/local/Cellar/scala/2.12.3/libexec/lib/scala-library.jar p1.Test
class javax.tools.ToolProvider
```

Which is an instance of this problem:

> From sstark at redhat.com  Mon Jul 11 04:36:43 2016
> From: sstark at redhat.com (Scott Stark)
> Date: Mon, 11 Jul 2016 04:36:43 -0400 (EDT)
> Subject: [wildfly-dev] common cdi-tck problem on wildfly with java 9
> In-Reply-To: <1633402839.4936392.1468221332903.JavaMail.zimbra@redhat.com>
> References: <1633402839.4936392.1468221332903.JavaMail.zimbra@redhat.com>
> Message-ID: <1543655717.4951760.1468226203603.JavaMail.zimbra@redhat.com>
> 
> So the problem is a change in behavior of a URLClassLoader that has a null parent class loader. This seems like it is a big compatibility problem as classes defined by such a class loader only have visibility into the java.base module rather than the entire platform. 
> 
> The simple fix is to pass in the new ClassLoader.getPlatformClassLoader() as the URLClassLoader parent rather than null. However, this seems like what the ClassLoader should be doing itself as I would expect a lot of code will break. I'll create a bug report for the simple test case I have that shows the problem.

**Comment by retronym** [comment]
A work around is to use `java $SCALA_HOME'/lib/*.jar':. my.App`.
