### ISSUE TITLE
ResizableArray max size should account for the specifics of the JVM implementation

### ISSUE THREAD

**Issue by buryat** [scala/bug#10567]
You cannot create a `ArrayBuffer` of the size `Int.MaxValue/2`, even though the backing array should be able to hold that many values.

```scala
scala> ArrayBuffer[Byte](Array.fill(Int.MaxValue/2 - 2)(0.toByte): _*)
java.lang.OutOfMemoryError: Java heap space
  at scala.collection.mutable.ResizableArray$class.ensureSize(ResizableArray.scala:103)
```

The reason for that is that in [ResizableArray.scala](https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/mutable/ResizableArray.scala#L101-L103) `newSize` gets limited at `Int.MaxValue`, however, the actual max size of an array depends on the JVM specifics.

For example, in OpenJDK arrays can hold up to `Int.MaxValue - 2`, but in other JVM implementations the max size can be a bit smaller.
`ArrayList` from OpenJDK itself defines the safe limit at `Int.MaxValue - 8` http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/ArrayList.java#l229

**Comment by buryat** [comment]
Both OpenJDK and HotSpot have `Int.MaxValue - 1` as the max size

```
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-b16)
OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)
```

```
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
```

```scala
scala> Array.fill(Int.MaxValue - 2)(0.toByte)
res1: Array[Byte] = Array( ...
scala> Array.fill(Int.MaxValue - 1)(0.toByte)
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
  at scala.collection.mutable.ArrayBuilder$ofByte.mkArray(ArrayBuilder.scala:131)
  at scala.collection.mutable.ArrayBuilder$ofByte.resize(ArrayBuilder.scala:137)
  at scala.collection.mutable.ArrayBuilder$ofByte.sizeHint(ArrayBuilder.scala:142)
  at scala.Array$.fill(Array.scala:264)
  ... 28 elided
```

**Comment by som-snytt** [comment]
There have been a couple of discussions about max allotment, but you still have to allot it.
```
➜  snips scala -J-Xmx8g
Welcome to Scala 2.13.15 (OpenJDK 64-Bit Server VM, Java 23.0.1).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.mutable._
import scala.collection.mutable._

scala> ArrayBuffer[Byte](Array.fill(Int.MaxValue/2 - 2)(0.toByte): _*)
                                                       ^
       warning: Passing an explicit array value to a Scala varargs method is deprecated (since 2.13.0) and will result in a defensive copy; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
val res0: scala.collection.mutable.ArrayBuffer[Byte] = ArrayBuffer(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...

```
especially when defensively copying.
