### ISSUE TITLE
Compiler crashes when a private early initializer is referenced in an inner class

### ISSUE THREAD

**Issue by mpang** [scala/bug#10561]
Reproducer:

```
class Parent {
    private val field: Int = 3
}

class Child(n: Int) extends {
    private val field = n
} with Parent {
    class Inner {
        def f = field
    }
}
```

Here's the stack trace:

```
error: java.lang.AssertionError: assertion failed:
  expected exactly one field by name field in List(private[this] val field: Int = _) of class Child's early initializers
     while compiling: Test.scala
        during phase: constructors
     library version: version 2.12.3
    compiler version: version 2.12.3
  reconstructed args: -Ystop-before:jvm

  last tree to typer: This(class Inner)
       tree position: line 11 of Test.scala
            tree tpe: Child#Inner
              symbol: class Inner in class Child
   symbol definition: class Inner extends Object (a ClassSymbol)
      symbol package: <empty>
       symbol owners: class Inner -> class Child
           call site: class Child in package <empty>

== Source file context for tree position ==

     8     private val field = n
     9 } with Parent {
    10     class Inner {
    11         def f = field
    12     }
    13 }
    14
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.$anonfun$triage$1(Constructors.scala:613)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.triage(Constructors.scala:607)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.<init>(Constructors.scala:591)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer.transformed(Constructors.scala:694)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.$anonfun$transform$1(Constructors.scala:85)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:85)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:29)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
        at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1437)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1437)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:89)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:29)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1431)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1416)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1412)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1515)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
        at scala.tools.nsc.Driver.process(Driver.scala:55)
        at scala.tools.nsc.Driver.main(Driver.scala:68)
        at scala.tools.nsc.Main.main(Main.scala)
Exception in thread "main" java.lang.AssertionError: assertion failed:
  expected exactly one field by name field in List(private[this] val field: Int = _) of class Child's early initializers
     while compiling: Test.scala
        during phase: constructors
     library version: version 2.12.3
    compiler version: version 2.12.3
  reconstructed args: -Ystop-before:jvm

  last tree to typer: This(class Inner)
       tree position: line 11 of Test.scala
            tree tpe: Child#Inner
              symbol: class Inner in class Child
   symbol definition: class Inner extends Object (a ClassSymbol)
      symbol package: <empty>
       symbol owners: class Inner -> class Child
           call site: class Child in package <empty>

== Source file context for tree position ==

     8     private val field = n
     9 } with Parent {
    10     class Inner {
    11         def f = field
    12     }
    13 }
    14
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.$anonfun$triage$1(Constructors.scala:613)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.triage(Constructors.scala:607)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer$Triage.<init>(Constructors.scala:591)
        at scala.tools.nsc.transform.Constructors$TemplateTransformer.transformed(Constructors.scala:694)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.$anonfun$transform$1(Constructors.scala:85)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:85)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:29)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
        at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1437)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
        at scala.reflect.internal.Trees.itransform(Trees.scala:1437)
        at scala.reflect.internal.Trees.itransform$(Trees.scala:1347)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:89)
        at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:29)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:390)
        at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:390)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:390)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1431)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1416)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1412)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1515)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
        at scala.tools.nsc.Driver.process(Driver.scala:55)
        at scala.tools.nsc.Driver.main(Driver.scala:68)
        at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by SethTisue** [comment]
crashes 2.12.20 and 2.13.16

the syntax in question does not exist in Scala 3
