### ISSUE TITLE
NPE from the compiler: class Predef is broken

### ISSUE THREAD

**Issue by ghik** [scala/bug#10637]
Reproducible in: https://github.com/AVSystem/scex
Example failed build: https://travis-ci.org/AVSystem/scex/jobs/309559927

```
java.lang.NullPointerException
	at scala.tools.nsc.Global.isPast(Global.scala:986)
	at scala.tools.nsc.Global.isPastTyper(Global.scala:982)
	at scala.reflect.internal.Symbols$ClassSymbol.addChild(Symbols.scala:3369)
	at scala.reflect.internal.pickling.UnPickler$Scan.readChildren(UnPickler.scala:450)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$run$3(UnPickler.scala:103)
	at scala.reflect.internal.pickling.UnPickler$Scan.run(UnPickler.scala:83)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:40)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:887)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$17(ClassfileParser.scala:1092)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:1092)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:517)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:154)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:125)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:318)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1678)
	at scala.tools.nsc.symtab.SymbolLoaders$moduleClassLoader$.doComplete(SymbolLoaders.scala:343)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
	at scala.reflect.internal.pickling.UnPickler$Scan.fromName$1(UnPickler.scala:221)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readSymbol$3(UnPickler.scala:246)
	at scala.reflect.internal.pickling.UnPickler$Scan.readExtSymbol$1(UnPickler.scala:246)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbol(UnPickler.scala:273)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolRef(UnPickler.scala:637)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:405)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readTypeRef$1(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypeRef(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readType$1(UnPickler.scala:367)
	at scala.reflect.internal.pickling.PickleBuffer.until(PickleBuffer.scala:154)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypes$1(UnPickler.scala:365)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:405)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readTypeRef$1(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypeRef(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readType$1(UnPickler.scala:367)
	at scala.reflect.internal.pickling.PickleBuffer.until(PickleBuffer.scala:154)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypes$1(UnPickler.scala:365)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:407)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.$anonfun$completeInternal$1(UnPickler.scala:714)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.completeInternal(UnPickler.scala:714)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:741)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
	at scala.reflect.internal.pickling.UnPickler$Scan.fromName$1(UnPickler.scala:221)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readSymbol$3(UnPickler.scala:246)
	at scala.reflect.internal.pickling.UnPickler$Scan.readExtSymbol$1(UnPickler.scala:246)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbol(UnPickler.scala:273)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolRef(UnPickler.scala:637)
	at scala.reflect.internal.pickling.UnPickler$Scan.readNonEmptyTree(UnPickler.scala:596)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTree(UnPickler.scala:609)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readTreeRef$1(UnPickler.scala:650)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTreeRef(UnPickler.scala:650)
	at scala.reflect.internal.pickling.UnPickler$Scan.ref$1(UnPickler.scala:529)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTree$1(UnPickler.scala:553)
	at scala.reflect.internal.pickling.UnPickler$Scan.readNonEmptyTree(UnPickler.scala:597)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTree(UnPickler.scala:609)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readAnnotArg$1(UnPickler.scala:457)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan.readAnnotArg(UnPickler.scala:457)
	at scala.reflect.internal.pickling.UnPickler$Scan.readAnnotationInfo(UnPickler.scala:491)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolAnnotation(UnPickler.scala:503)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$run$2(UnPickler.scala:101)
	at scala.reflect.internal.pickling.UnPickler$Scan.run(UnPickler.scala:83)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:40)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:887)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$17(ClassfileParser.scala:1092)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:1092)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:517)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:154)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:125)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:318)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:302)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:357)
	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:286)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
	at scala.reflect.internal.pickling.UnPickler$Scan.fromName$1(UnPickler.scala:221)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readSymbol$3(UnPickler.scala:246)
	at scala.reflect.internal.pickling.UnPickler$Scan.readExtSymbol$1(UnPickler.scala:246)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbol(UnPickler.scala:273)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolRef(UnPickler.scala:637)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:402)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readTypeRef$1(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypeRef(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:405)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readTypeRef$1(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypeRef(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readType$1(UnPickler.scala:367)
	at scala.reflect.internal.pickling.PickleBuffer.until(PickleBuffer.scala:154)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypes$1(UnPickler.scala:365)
	at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:405)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readTypeRef$1(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:183)
	at scala.reflect.internal.pickling.UnPickler$Scan.readTypeRef(UnPickler.scala:646)
	at scala.reflect.internal.pickling.UnPickler$Scan.readAnnotationInfo(UnPickler.scala:480)
	at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolAnnotation(UnPickler.scala:503)
	at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$run$2(UnPickler.scala:101)
	at scala.reflect.internal.pickling.UnPickler$Scan.run(UnPickler.scala:83)
	at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:40)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:887)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$17(ClassfileParser.scala:1092)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:1092)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:517)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:154)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:125)
	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:318)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:302)
	at scala.reflect.internal.SymbolTable.$anonfun$openPackageModule$4(SymbolTable.scala:319)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:317)
	at scala.reflect.internal.SymbolTable.$anonfun$openPackageModule$4(SymbolTable.scala:319)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:317)
	at scala.reflect.internal.SymbolTable.openPackageModule(SymbolTable.scala:357)
	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:286)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2304)
	at scala.reflect.internal.tpe.FindMembers$FindMemberBase.<init>(FindMembers.scala:17)
	at scala.reflect.internal.tpe.FindMembers$FindMember.<init>(FindMembers.scala:219)
	at scala.reflect.internal.Types$Type.findMemberInternal$1(Types.scala:1033)
	at scala.reflect.internal.Types$Type.findMember(Types.scala:1035)
	at scala.reflect.internal.Types$Type.memberBasedOnName(Types.scala:661)
	at scala.reflect.internal.Types$Type.member(Types.scala:625)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	at scala.reflect.internal.Mirrors$RootsBase.staticModuleOrClass(Mirrors.scala:77)
	at scala.reflect.internal.Mirrors$RootsBase.staticClass(Mirrors.scala:121)
	at com.avsystem.commons.analyzer.AnalyzerRule.classType(AnalyzerRule.scala:16)
	at com.avsystem.commons.analyzer.VarargsAtLeast.<init>(VarargsAtLeast.scala:10)
	at com.avsystem.commons.analyzer.AnalyzerPlugin.<init>(AnalyzerPlugin.scala:11)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at scala.tools.nsc.plugins.Plugin$.instantiate(Plugin.scala:190)
	at scala.tools.nsc.plugins.Plugins.$anonfun$loadRoughPluginsList$9(Plugins.scala:47)
	at scala.tools.nsc.plugins.Plugins.loadRoughPluginsList(Plugins.scala:47)
	at scala.tools.nsc.plugins.Plugins.loadRoughPluginsList$(Plugins.scala:27)
	at scala.tools.nsc.Global.loadRoughPluginsList(Global.scala:36)
	at scala.tools.nsc.plugins.Plugins.roughPluginsList(Plugins.scala:50)
	at scala.tools.nsc.plugins.Plugins.roughPluginsList$(Plugins.scala:50)
	at scala.tools.nsc.Global.roughPluginsList$lzycompute(Global.scala:36)
	at scala.tools.nsc.Global.roughPluginsList(Global.scala:36)
	at scala.tools.nsc.plugins.Plugins.loadPlugins(Plugins.scala:86)
	at scala.tools.nsc.plugins.Plugins.loadPlugins$(Plugins.scala:56)
	at scala.tools.nsc.Global.loadPlugins(Global.scala:36)
	at scala.tools.nsc.plugins.Plugins.plugins(Plugins.scala:102)
	at scala.tools.nsc.plugins.Plugins.plugins$(Plugins.scala:102)
	at scala.tools.nsc.Global.plugins$lzycompute(Global.scala:36)
	at scala.tools.nsc.Global.plugins(Global.scala:36)
	at scala.tools.nsc.plugins.Plugins.computePluginPhases(Plugins.scala:113)
	at scala.tools.nsc.plugins.Plugins.computePluginPhases$(Plugins.scala:112)
	at scala.tools.nsc.Global.computePluginPhases(Global.scala:36)
	at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:690)
	at xsbt.ZincCompiler.phaseDescriptors$lzycompute(CallbackGlobal.scala:125)
	at xsbt.ZincCompiler.phaseDescriptors(CallbackGlobal.scala:119)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1186)
	at xsbt.ZincCompiler$ZincRun.<init>(CallbackGlobal.scala:63)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:129)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:117)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1406)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1388)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:266)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] error while loading Predef, class file '/home/travis/.sbt/boot/scala-2.12.4/lib/scala-library.jar(scala/Predef.class)' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of Predef.class: null)
[error] one error found
```

**Comment by ghik** [comment]
Ugh, I'm sorry - this was related to the compiler plugin we're using. It's just that something very random triggered the crash while everything was working fine before...
