### ISSUE TITLE
BUG/FeatureRequest: Type Inference doesn't always use expected Return Type

### ISSUE THREAD

**Issue by schlichtanders** [scala/bug#10633]
Dear all,

I run into an issue with type inference using the expected output type of a type-parameterized function and asked for this on scala gitter where after a rather long discussion I was recommended to open an issue here.

Two simple examples where in fact inference with expected return type works are the following versions of ``map``
```scala
def lift1[A, B](func: A => B): Seq[A] => Seq[B] = {
  s => s.map(func)
}
val func1: Seq[Double] => Seq[Int] = lift1(_.toInt)
func1(Seq(2.0, 1.0))

def lift2[A1:ClassTag,A2:ClassTag,B:ClassTag](func: (A1, A2) => B): (Seq[A1], Seq[A2]) => Seq[B] = {
  (s1, s2) => (s1, s2).zipped.map(func)
}
val func2: (Seq[Double], Seq[Double]) => Seq[Double] = lift2(_ + _)
func2(Seq(1,2,3), Seq(3,4,5))
```
They compile well and give correct results.

However I stumbled upon one case where this type inference using expected return type doesn't work. But it looks pretty similar to me. The case is with ``json4s`` package. Adapted from http://json4s.org/ here is a minimal example:
```scala
import org.json4s._
import org.json4s.jackson.Serialization
implicit val formats = Serialization.formats(NoTypeHints)

case class Test(a:Double, b:String)
val test = Test(2.0, "foo")

val string = Serialization.write(test)
val test_parsed: Test = Serialization.read(string)
```
The very last line will give an error 
```
org.json4s.package$MappingException: Parsed JSON values do not match with class constructor
args=
arg types=
constructor=public scala.runtime.Nothing$()
at org.json4s.Extraction$ClassInstanceBuilder.org$json4s$Extraction$ClassInstanceBuilder$$instantiate(Extraction.scala:495)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:515)
at org.json4s.Extraction$ClassInstanceBuilder$$anonfun$result$6.apply(Extraction.scala:512)
at org.json4s.Extraction$.org$json4s$Extraction$$customOrElse(Extraction.scala:524)
at org.json4s.Extraction$ClassInstanceBuilder.result(Extraction.scala:512)
at org.json4s.Extraction$.extract(Extraction.scala:351)
at org.json4s.Extraction$.extract(Extraction.scala:42)
at org.json4s.ExtractableJsonAstNode.extract(ExtractableJsonAstNode.scala:21)
at org.json4s.jackson.Serialization$.read(Serialization.scala:50)
... 40 elided
```
while using ``val test_parsed2 = Serialization.read[Test](string)`` does work indeed,
returning ``test_parsed2: Test = Test(2.0,foo)``.

So the bottomline is: If the compiler is able to use the return type information like it seems to be, why is this not enabled in general?

**Comment by schlichtanders** [comment]
especially, it was mentioned in the gitter dialog that this example is probably not related to #8347 
because it seems not related to eta-expansion

**Comment by milessabin** [comment]
Possibly related to https://github.com/scala/scala/pull/6127 or https://github.com/scala/scala/pull/6140.

**Comment by Jasper-M** [comment]
In essence, this looks the same to me as part of [this report](https://github.com/scala/bug/issues/9680). There it is said that it's normal expected behavior that a type argument is inferred as `Nothing` in a situation such as this:
```
scala> def foo[A: TypeTag]: A = {println(typeOf[A]); ???}
foo: [A](implicit evidence$1: reflect.runtime.universe.TypeTag[A])A

scala> val a: String = foo
Nothing
scala.NotImplementedError: an implementation is missing
```
Because `Nothing` is a subtype of `String`.
