### ISSUE TITLE
Generic mixin crashes compiler

### ISSUE THREAD

**Issue by joroKr21** [scala/bug#10661]
This should issue a descriptive error message:
```scala
object GenericMixin {
  trait Tag
  class C
  def tagged[T] = new C with T
  tagged[Tag]
}
```
Instead, the compiler crashes:
```sbt
[error] addChild inapplicable for type T
[error] scala.reflect.internal.Symbols$Symbol.addChild(Symbols.scala:1834)
[error] scala.tools.nsc.typechecker.Namers$Namer.$anonfun$templateSig$1(Namers.scala:1128)
[error] scala.tools.nsc.typechecker.Namers$Namer.templateSig(Namers.scala:1116)
[error] scala.tools.nsc.typechecker.Namers$Namer.classSig(Namers.scala:1187)
[error] scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1798)
[error] scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1761)
[error] scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:840)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1958)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1956)
[error] scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1951)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2427)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$96(Typers.scala:5505)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typerWithLocalContext$1(Typers.scala:486)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:486)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5540)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5658)
[error] scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5746)
[error] scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1077)
[error] scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1412)
[error] scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1795)
[error] scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1761)
[error] scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:840)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1958)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1956)
[error] scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1951)
[error] scala.tools.nsc.typechecker.Namers$PolyTypeCompleter.completeImpl(Namers.scala:1991)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1958)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1956)
[error] scala.tools.nsc.typechecker.Namers$PolyTypeCompleter.complete(Namers.scala:1970)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[error] scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1678)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5200)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5647)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3086)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3231)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3231)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1987)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1858)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5497)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5647)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3086)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3231)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3231)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5207)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5499)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
[error] scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
[error] scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5643)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
[error] scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
[error] scala.collection.Iterator.foreach(Iterator.scala:929)
[error] scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1452)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1436)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1429)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1545)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:131)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:32)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:117)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1406)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1388)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] sbt.std.Transform$$anon$4.work(System.scala:64)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:266)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] java.lang.UnsupportedOperationException: addChild inapplicable for type T
[error] 	at scala.reflect.internal.Symbols$Symbol.addChild(Symbols.scala:1834)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$templateSig$1(Namers.scala:1128)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.templateSig(Namers.scala:1116)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.classSig(Namers.scala:1187)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1798)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1761)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:840)
[error] 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1958)
[error] 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1956)
[error] 	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1951)
[error] 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2427)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$96(Typers.scala:5505)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typerWithLocalContext$1(Typers.scala:486)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:486)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5540)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5658)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5746)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1077)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1412)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1795)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1761)
[error] 	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:840)
[error] 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1958)
[error] 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1956)
[error] 	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1951)
[error] 	at scala.tools.nsc.typechecker.Namers$PolyTypeCompleter.completeImpl(Namers.scala:1991)
[error] 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1958)
[error] 	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1956)
[error] 	at scala.tools.nsc.typechecker.Namers$PolyTypeCompleter.complete(Namers.scala:1970)
[error] 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[error] 	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1678)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5200)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5647)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3086)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3231)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3231)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1987)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1858)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5497)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5647)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3086)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3231)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3231)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5207)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5499)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
[error] 	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5643)
[error] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
[error] 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
[error] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
[error] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1452)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1436)
[error] 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1429)
[error] 	at scala.tools.nsc.Global$Run.compile(Global.scala:1545)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:131)
[error] 	at xsbt.CachedCompiler0.run(CompilerInterface.scala:106)
[error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:32)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:117)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:64)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:70)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1406)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1388)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Atry** [comment]
Note that you can use [Constructor](https://javadoc.io/page/com.thoughtworks.feature/constructor_2.11/latest/com/thoughtworks/feature/Constructor.html) in [feature.scala](https://github.com/ThoughtWorksInc/feature.scala) for dynamically creating mixins.

**Comment by wsargent** [comment]
Just ran into this :-/
