### ISSUE TITLE
null when compiling (Uncurry.scala / var)

### ISSUE THREAD

**Issue by mbcx4jrh** [scala/bug#10712]
I get a Null Pointer Exception when trying to compile [mbcx4jrh/bling](https://github.com/mbcx4jrh/bling) under sbt 1.1.0/1.0.4/0.13.17 & scala 2.12.7
sbt has suggested this is a compiler error (https://github.com/sbt/sbt/issues/3919)
```
sbt:Bling> compile 
[info] Updating ...
[info] Done updating.
[info] Compiling 12 Scala sources to /home/joe/src/bling/target/scala-2.12/classes ...
[error] ## Exception when compiling 12 sources to /home/joe/src/bling/target/scala-2.12/classes
[error] null
[error] scala.reflect.internal.transform.UnCurry.scala$reflect$internal$transform$UnCurry$$expandAlias(UnCurry.scala:29)
[error] scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:33) 
... [full stacktrace below]
```

## steps
```
git clone git@github.com:mbcx4jrh/bling.git
git checkout bug/npe-in-sbt
sbt compile
```
## problem
NullPointerException occurs and exits sbt
The issue appears to around the file: Layer.scala - commenting out as below removes the problem:
```
package bling
import breeze.linalg.{DenseMatrix, DenseVector}

abstract class Layer(val size: Int, val previousLayer: Int) extends FeedForward with BackPropagate {
  override var lastInputBiassed: DenseVector[Double] = DenseVector.zeros(size)
  override var weights: DenseMatrix[Double] = DenseMatrix.rand(size, previousLayer)
}


trait StoredInput {
  var lastInputBiassed: Double

  def stored(input: DenseVector[Double]): DenseVector[Double] = {
//    lastInputBiassed = input //havent biassed this!! TBC
    input
  }
}
```

## expectation
Successful compilation or compilation failure due to my code

## notes
sbt version: 1.1.0 & 1.0.4 & 0.13.17
Scala version: 2.12.7

## full stacktrace
```
joe@beast ~/src/bling (bug/npe-in-sbt) $ sbt
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /home/joe/.sbt/1.0/plugins
[info] Updating ProjectRef(uri("file:/home/joe/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading project definition from /home/joe/src/bling/project
[info] Updating ProjectRef(uri("file:/home/joe/src/bling/project/"), "bling-build")...
[info] Done updating.
[info] Compiling 1 Scala source to /home/joe/src/bling/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] Loading settings from build.sbt ...
[info] Set current project to Bling (in build file:/home/joe/src/bling/)
[info] sbt server started at local:///home/joe/.sbt/1.0/server/7bfcf832542256b9c5b7/sock
sbt:Bling> compile
[info] Updating ...
[info] Done updating.
[info] Compiling 12 Scala sources to /home/joe/src/bling/target/scala-2.12/classes ...
[error] ## Exception when compiling 12 sources to /home/joe/src/bling/target/scala-2.12/classes
[error] null
[error] scala.reflect.internal.transform.UnCurry.scala$reflect$internal$transform$UnCurry$$expandAlias(UnCurry.scala:29)
[error] scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:33)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:525)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error] scala.reflect.internal.Trees.itransform(Trees.scala:1357)
[error] scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:514)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.$anonfun$mainTransform$12(UnCurry.scala:476)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:394)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error] scala.reflect.internal.Trees.$anonfun$itransform$2(Trees.scala:1375)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
[error] scala.reflect.internal.Trees.itransform(Trees.scala:1373)
[error] scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.super$transform(UnCurry.scala:462)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.$anonfun$mainTransform$5(UnCurry.scala:462)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:394)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error] scala.reflect.internal.Trees.itransform(Trees.scala:1416)
[error] scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:40)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.super$transform(UnCurry.scala:462)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.$anonfun$mainTransform$16(UnCurry.scala:511)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:413)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error] scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
[error] scala.reflect.internal.Trees.$anonfun$itransform$4(Trees.scala:1420)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
[error] scala.reflect.internal.Trees.itransform(Trees.scala:1419)
[error] scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:514)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error] scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
[error] scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error] scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1438)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
[error] scala.reflect.internal.Trees.itransform(Trees.scala:1438)
[error] scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error] scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error] scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:514)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error] scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error] scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
[error] scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[error] scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
[error] scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:400)
[error] scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:400)
[error] scala.collection.Iterator.foreach(Iterator.scala:929)
[error] scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] scala.tools.nsc.Global$GlobalPhase.run(Global.scala:400)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1452)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1436)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1429)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1545)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.lang.reflect.Method.invoke(Method.java:498)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1427)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1401)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] sbt.std.Transform$$anon$4.work(System.scala:66)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] sbt.Execute.work(Execute.scala:271)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] java.lang.Thread.run(Thread.java:748)
[error]            
[error] java.lang.NullPointerException
[error]         at scala.reflect.internal.transform.UnCurry.scala$reflect$internal$transform$UnCurry$$expandAlias(UnCurry.scala:29)
[error]         at scala.reflect.internal.transform.UnCurry$$anon$1.apply(UnCurry.scala:33)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:525)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error]         at scala.reflect.internal.Trees.itransform(Trees.scala:1357)
[error]         at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:514)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.$anonfun$mainTransform$12(UnCurry.scala:476)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:394)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error]         at scala.reflect.internal.Trees.$anonfun$itransform$2(Trees.scala:1375)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
[error]         at scala.reflect.internal.Trees.itransform(Trees.scala:1373)
[error]         at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.super$transform(UnCurry.scala:462)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.$anonfun$mainTransform$5(UnCurry.scala:462)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:394)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error]         at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
[error]         at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error]         at scala.reflect.internal.Trees.itransform(Trees.scala:1416)
[error]         at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:40)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.super$transform(UnCurry.scala:462)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.$anonfun$mainTransform$16(UnCurry.scala:511)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:413)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error]         at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2563)
[error]         at scala.reflect.internal.Trees.$anonfun$itransform$4(Trees.scala:1420)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
[error]         at scala.reflect.internal.Trees.itransform(Trees.scala:1419)
[error]         at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:514)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error]         at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2589)
[error]         at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2587)
[error]         at scala.reflect.internal.Trees.$anonfun$itransform$7(Trees.scala:1438)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
[error]         at scala.reflect.internal.Trees.itransform(Trees.scala:1438)
[error]         at scala.reflect.internal.Trees.itransform$(Trees.scala:1348)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
[error]         at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.super$transform(TypingTransformers.scala:40)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:42)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
[error]         at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:25)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:514)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:111)
[error]         at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:71)
[error]         at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:140)
[error]         at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:400)
[error]         at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:400)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:929)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error]         at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:400)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1452)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1436)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1429)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1545)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:83)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:134)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:74)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:117)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:305)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:101)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:82)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:110)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:57)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:84)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:129)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:75)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:61)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:309)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:267)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:158)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:237)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:68)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1427)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1401)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:271)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) java.lang.NullPointerException
[error] Total time: 3 s, completed 04-Feb-2018 16:11:10
```

**Comment by som-snytt** [comment]
Catching the exception up at `Uncurry.transform`, NPE says a tree here is untyped. To borrow from the comment there, `// I don't have a clue why I'm catching NullPointerException`.

```
src/main/scala/bling/CostFunction.scala:14: error: java.lang.NullPointerException
    output * (1.0 - output).t *:* (target - output)
           ^
```
It already didn't like `1.0.<$minus: error>(output).<t: error>`.

**Comment by SethTisue** [comment]
repo no longer exists
