### ISSUE TITLE
`Array` used as an annotation class

### ISSUE THREAD

**Issue by alexknvl** [scala/bug#10729]
Either one of these
```scala
val a: List[_@Array(10)] = Nil
//
class A @Array(10)
//
class A@Array(_)
```
slains 2.13 and 2.12.4 REPLs

P.S. ~~I think that last line is the shortest compiler slayer so far.~~ Nevermind, @hrhino found an event shorter *derivative* `1: @Array(_)` :P

**Comment by SethTisue** [comment]
Dotty, too

```
assertion failure for  <:< T, frozen = false
assertion failure for  @Array <:< T, frozen = false
assertion failure for  @Array <:< T, frozen = false
assertion failure for List[ @Array] <:< List[T], frozen = false
assertion failure for List[ @Array] <:< List[T], frozen = false
assertion failure for dotty.Show[List[T]] <:< dotty.Show[List[ @Array]], frozen = false
Exception in thread "main" java.lang.AssertionError: assertion failed: TypeBounds(TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Nothing),TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Any))
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:36)
	at dotty.tools.dotc.core.Types$TypeBounds.<init>(Types.scala:3468)
```

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/7546

**Comment by SethTisue** [comment]
@psilospore I'll assign you this bug if you accept the invitation to the contributors team and comment here saying you've done so

**Comment by psilospore** [comment]
@sethtissue I missed that comment but I did  accept the invite

**Comment by hrhino** [comment]
welcome!
