### ISSUE TITLE
Cannot emit primitive conversion from Lscala/runtime/Null$; to I

### ISSUE THREAD

**Issue by alexknvl** [scala/bug#10742]
```scala
scala> def foo(b: Null with Nothing): Int = b
java.lang.AssertionError: assertion failed: 
  Cannot emit primitive conversion from Lscala/runtime/Null$; to I - <console>
     while compiling: <console>
        during phase: jvm
     library version: version 2.13.0-M3
    compiler version: version 2.13.0-M3
  reconstructed args: -deprecation -classpath /home/alex/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.13.0-M3.jar:/home/alex/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.13.0-M3.jar:/home/alex/.ivy2/cache/org.scala-lang.modules/scala-xml_2.13.0-M3/bundles/scala-xml_2.13.0-M3-1.0.6.jar:/home/alex/.ivy2/cache/jline/jline/jars/jline-2.14.5.jar -Yrepl-sync -bootclasspath /usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes:/home/alex/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.13.0-M3.jar

  last tree to typer: Ident(b)
       tree position: line 1 of <console>
            tree tpe: Null
              symbol: value b
   symbol definition: b: Null (a TermSymbol)
      symbol package: $line85
       symbol owners: value b -> method foo -> object iw
           call site: constructor $read$$iw$$iw in package $line85

<Cannot read source file>
	at scala.tools.nsc.backend.jvm.BCodeIdiomatic$JCodeMethodN.emitT2T(BCodeIdiomatic.scala:225)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.adapt(BCodeBodyBuilder.scala:829)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:389)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:604)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:636)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:510)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.$anonfun$gen$7(BCodeSkelBuilder.scala:512)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:512)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:112)
	at scala.tools.nsc.backend.jvm.CodeGen.genClass(CodeGen.scala:52)
	at scala.tools.nsc.backend.jvm.CodeGen.genClassDef$1(CodeGen.scala:24)
	at scala.tools.nsc.backend.jvm.CodeGen.genClassDefs$1(CodeGen.scala:40)
	at scala.tools.nsc.backend.jvm.CodeGen.$anonfun$genUnit$2(CodeGen.scala:39)
	at scala.tools.nsc.backend.jvm.CodeGen.genClassDefs$1(CodeGen.scala:39)
	at scala.tools.nsc.backend.jvm.CodeGen.genUnit(CodeGen.scala:43)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$apply$1(GenBCode.scala:43)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.apply(GenBCode.scala:43)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:400)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:400)
	at scala.collection.Iterator.foreach(Iterator.scala:938)
	at scala.collection.Iterator.foreach$(Iterator.scala:938)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1426)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:400)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.super$run(GenBCode.scala:53)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$run$1(GenBCode.scala:53)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:51)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1453)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1437)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:711)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:900)
	at scala.tools.nsc.interpreter.IMain.$anonfun$compile$2(IMain.scala:504)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:504)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:498)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:481)
	at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:892)
	at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:750)
	at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:455)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:478)
	at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$run$1(ILoop.scala:985)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:950)
	at scala.tools.nsc.InterpreterLoop.main(Interpreter.scala:71)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:76)
	at sbt.Console.sbt$Console$$console0$1(Console.scala:22)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply(Console.scala:23)
	at sbt.Logger$$anon$4.apply(Logger.scala:85)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by alexknvl** [comment]
Also found the following inconsistency:

```scala
scala> def foo(b: Null with Int): Int = b
java.lang.AssertionError: assertion failed: 
  Cannot emit primitive conversion from Lscala/runtime/Null$; to I - <console>
....

scala> def foo(b: Null with Long): Int = b
foo: (b: Null with Long)Int
```

**Comment by hepin1989** [comment]
in Scala 2.12.4 too

**Comment by OndrejSpanel** [comment]
What does this error mean? I am hitting it now in a large project with lots of implicit conversion (a DSL, not a normal Scala code) and the error is not very helpful - it seems to be triggered on a place where there is apparently no Null or null.

**Comment by SethTisue** [comment]
@OndrejSpanel I'm not sure we can offer further insight unless you have a reproducer that's interestingly different from the ones we already have in this ticket

**Comment by SethTisue** [comment]
in 2.13.3, you instead get:

```scala
scala 2.13.3> def foo(b: Null with Nothing): Int = b
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    foo(Lscala/runtime/Null$;)I @3: ireturn
  Reason:
    Type null (current frame, stack[0]) is not assignable to integer
  Current Frame:
    bci: @3
    flags: { }
    locals: { '$iw', 'scala/runtime/Null$' }
    stack: { null }
  Bytecode:
    0x0000000: 2b57 01ac

  ... 31 elided
```

🤷

**Comment by dwijnand** [comment]
Need to send a JEP to add 🤷 before `java.lang.VerifyError`
