### ISSUE TITLE
Compiler slayer referencing a package that doesn't exist.

### ISSUE THREAD

**Issue by jmcardon** [scala/bug#10748]
Assuming the package `doesntExist` does not exist, the following crashes the compiler:

```scala
type B[A] <: Array[Byte]

def uhOh[A]: C[A] = new C[A]

private[doesntExist] final class C[A](val dummy: Boolean = true) extends AnyVal {
  def apply[F[_]](value: F[Array[Byte]]): F[B[A]] = value.asInstanceOf[F[B[A]]]
}

<pastie>:15: error: doesntExist is not an enclosing class
private[doesntExist] final class C[A](val dummy: Boolean = true) extends AnyVal {
                                 ^
java.lang.AssertionError: assertion failed: C
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1511)
        at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1678)
        at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$addDefaultGetters$9(Namers.scala:1508)
        at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$addDefaultGetters$7(Namers.scala:1506)
        at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$addDefaultGetters$5(Namers.scala:1475)
        at scala.tools.nsc.typechecker.Namers$Namer.addDefaultGetters(Namers.scala:1471)
...
```

However, this throws an error properly (Credits to @hrhino for telling me to try this):

```scala
type B[A] <: Array[Byte]

def uhOh[A]: C[A] = new C[A]

object C

private[doesntExist] final class C[A](val dummy: Boolean = true) extends AnyVal {
  def apply[F[_]](value: F[Array[Byte]]): F[B[A]] = value.asInstanceOf[F[B[A]]]
}

<pastie>:17: error: doesntExist is not an enclosing class
private[doesntExist] final class C[A](val dummy: Boolean = true) extends AnyVal {
```

**Comment by hrhino** [comment]
~Golfed~ minimized:

```
scala> new C;private[a]class C(z:1=1)
                             ^
       error: a is not an enclosing class
java.lang.AssertionError: assertion failed: C
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1513)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1680)
	at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$addDefaultGetters$9(Namers.scala:1521)
	at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$addDefaultGetters$7(Namers.scala:1519)
	at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$addDefaultGetters$5(Namers.scala:1488)
	at scala.tools.nsc.typechecker.Namers$Namer.addDefaultGetters(Namers.scala:1484)
	at scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1405)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1808)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1774)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:842)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1971)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1969)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1964)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1532)
	at scala.reflect.internal.Symbols.argsDependOnPrefix(Symbols.scala:3739)
	at scala.reflect.internal.Symbols.argsDependOnPrefix$(Symbols.scala:3727)
	at scala.reflect.internal.SymbolTable.argsDependOnPrefix(SymbolTable.scala:16)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:5022)```

**Comment by som-snytt** [comment]
There are a few paths to destruction, as shown in the PR tests. Probably it needs more tests.
