### ISSUE TITLE
Strange compiler crash on a `for/yield` with `Either`

### ISSUE THREAD

**Issue by winitzki** [scala/bug#10785]
See https://github.com/winitzki/scala-bug-1/blob/master/src/main/scala/example/Bug1.scala for a minimal runnable example of code that crashes the compiler. I am using Scala 2.12.4 with all default compiler options. The file `build.sbt` contains nothing but the Scala version.

This is the code that causes a compiler crash:

```scala
implicit def safeInt(x: Int): Either[String, Int] = Right(x)

for {
    x <- Left("error")
    y <- 1 + x
  } yield x

```

```
Error:scalac: Error while emitting Bug1.scala
<error> (of class scala.reflect.internal.Types$ErrorType$)
Error:scalac: Error while emitting Bug1.scala
assertion failed: ClassBType.info not yet assigned: Lexample/Bug1$;
Warning:scalac: an unexpected type representation reached the compiler backend while compiling Bug1.scala: <error>. If possible, please file a bug on https://github.com/scala/bug/issues.
Warning:scalac: scala.MatchError: <error> (of class scala.reflect.internal.Types$ErrorType$)
Warning:scalac:
Warning:scalac: 	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.typeToBType(BTypesFromSymbols.scala:195)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.methodBTypeFromMethodType(BTypesFromSymbols.scala:129)
Warning:scalac: 	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.methodBTypeFromSymbol(BTypesFromSymbols.scala:120)
...
```

Small changes to this code will make it compile:

```scala
val c: Either[String, Int] = Left("error")

// works
  for {
    x <- c
    y <- 1 + x
  } yield x

// works
 for {
    x <- Left("error")
    y <- Right(1 + x)
  } yield x
```

I am reporting this bug because the compiler error message suggests that I do so.

**Comment by som-snytt** [comment]
Type inference failure lets erroneous trees leak. A fix similar to [this one](https://github.com/scala/scala/pull/4250) produces:

```
t10785.scala:7: error: type mismatch;
 found   : String
 required: scala.util.Either[?,?]
  Left("error").flatMap(x => 1.+(x).map(y => x))
                                       ^
```
or
```
  for (x <- Left("") ; y <- 1 + x) yield x
                         ^
```
where cleverly
```
[log typer] error tree = scala.Predef.augmentString(scala.Predef.any2stringadd[scala.this.Int](1).$plus(x)).map[scala.this.Nothing, String](((y: scala.this.Char) => x))(scala.Predef.StringCanBuildFrom)
```

Using `Left[String, Int]("")` is another workaround.

**Comment by xuwei-k** [comment]
not crash with Scala 2.13.0-M4 🤔 


| ○ | × |
|-------------------|-----------------------------------------|
| 2.13.0-M4, 2.11.x | 2.12.x, 2.13.0-M1, 2.13.0-M2, 2.13.0-M3 | 

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> implicit def safeInt(x: Int): Either[String, Int] = Right(x)
safeInt: (x: Int)Either[String,Int]

scala> for {
     |   x <- Left("error")
     |   y <- 1 + x
     | } yield y
         y <- 1 + x
           ^
On line 3: error: type mismatch;
        found   : String
        required: scala.util.Either[?,?]
```

**Comment by som-snytt** [comment]
It looks like it progressed on 2.13 the same week I was looking at it on 2.12.

Crashes on 2.13.0-20180321-093501-0170e73, errors on scala-2.13.0-pre-457dfd0-SNAPSHOT if that's meaningful.
