### ISSUE TITLE
AdaptTypeError - foundType is Erroneous

### ISSUE THREAD

**Issue by alexknvl** [scala/bug#10803]
Tested on 2.12.4.

```scala
trait DistributiveCategory[F[_, _]] { self =>
  val sum: CocartesianMonoidalCategory[F] {
    type Unit          = self.Zero
  }
}

trait SymmetricDistributiveCategory[F[_, _]]

object instances {
  type Void
  type Dummy

  implicit val function1: SymmetricDistributiveCategory[Function1] {
    type Obj[A]
  } = new SymmetricDistributiveCategory[Function1] with CCC[Function1] { self =>
      type Zero
      val sum = new CocartesianMonoidalCategory[F] {
      }
    }
}
```

```scala
java.lang.AssertionError: assertion failed: 
  AdaptTypeError - foundType is Erroneous: Playground.this.SymmetricDistributiveCategory[Function1] with <error>{type Zero}
     while compiling: /tmp/scastie5052530215433746801/src/main/scala/main.scala
        during phase: typer
     library version: version 2.12.4
    compiler version: version 2.12.4
...
last tree to typer: Select(New, <init>)
       tree position: line 17 of /tmp/scastie5052530215433746801/src/main/scala/main.scala
            tree tpe: ()Playground.this.SymmetricDistributiveCategory[Function1] with <error>{type Zero}
              symbol: constructor $anon
   symbol definition: def <init>(): $anon (a MethodSymbol)
      symbol package: <empty>
       symbol owners: constructor $anon -> <$anon: Playground.this.SymmetricDistributiveCategory[Function1] with <error>> -> value function1 -> object instances -> class Playground
           call site: object instances in class Playground in package <empty>

== Source file context for tree position ==

    14 
    15   implicit val function1: SymmetricDistributiveCategory[Function1] {
    16     type Obj[A]
    17   } = new SymmetricDistributiveCategory[Function1] with CCC[Function1] { self =>
    18       type Zero
    19       val sum = new CocartesianMonoidalCategory[F] {
    20       }

	at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AdaptTypeError(ContextErrors.scala:216)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptMismatchedSkolems$1(Typers.scala:1058)
	at scala.tools.nsc.typechecker.Typers$Typer.lastTry$1(Typers.scala:1069)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptExprNotFunMode$1(Typers.scala:1124)
	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1170)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1214)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5598)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2457)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$96(Typers.scala:5505)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typerWithLocalContext$1(Typers.scala:486)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:486)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5540)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5798)
	at scala.tools.nsc.typechecker.Typers$Typer.typedValDefImpl(Typers.scala:2068)
	at scala.tools.nsc.typechecker.Typers$Typer.typedValDef(Typers.scala:2024)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5494)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5647)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3086)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3231)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3231)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1987)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1858)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5497)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5647)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3086)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3231)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3231)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1987)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1811)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5496)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5647)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3086)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3231)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3231)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5207)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5499)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5546)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5616)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5557)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5562)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5643)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:436)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:429)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1452)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1436)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1429)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1545)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:107)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:53)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:74)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:49)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:64)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:32)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:72)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:71)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:99)
	at sbt.inc.Incremental$.compile(Incremental.scala:71)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:155)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:912)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:904)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:902)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hrhino** [comment]
This shouldn't compile, should it? There's no `self.Zero` in `DistributiveCategory`. I do like the assertion tripping inside of an error method.
