### ISSUE TITLE
Some scala apps don't work on WinXP on JRE >= 8u162 with scala 2.12.4

### ISSUE THREAD

**Issue by KOLANICH** [scala/bug#10816]
The problem appeared when scala toolchain was upgraded from 2.11.11 to 2.12.4.

<details>
<summary>The error message</summary>

```
Exception in thread "main" java.lang.VerifyError: Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab6 0060 04a0 001e b200 b8b2 00bd 04bd
    0x0000010: 0002 5903 2a53 c000 bfb6 00c3 b600 c7c0
    0x0000020: 00c9 b02a b600 36b8 0040 3c1b 04a4 015e
    0x0000030: 1b05 6c3d 2a1b 056c 2ab6 0036 b700 cb3e
    0x0000040: 2ab6 0036 021d 787e 3604 2ab6 0036 0210
    0x0000050: 201d 647c 7e36 05bb 0019 59b2 00bd 2ab6
    0x0000060: 0038 c000 bfb6 00cf b700 d21c b600 d63a
    0x0000070: 0619 06c6 001a 1906 b600 dac0 0086 3a07
    0x0000080: 1906 b600 ddc0 0086 3a08 a700 0dbb 00df
    0x0000090: 5919 06b7 00e2 bf19 073a 0919 083a 0abb
    0x00000a0: 0002 5915 0419 09bb 0019 59b2 00bd 1909
    0x00000b0: c000 bfb6 00cf b700 d203 b800 e83a 0e3a
    0x00000c0: 0d03 190d b900 ec01 0019 0e3a 1136 1036
    0x00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d
    0x00000e0: 150f b900 ef02 00c0 0005 3a17 1911 1917
    0x00000f0: b800 f33a 1136 1036 0fa7 ffd8 1911 b800
    0x0000100: f7b7 0065 3a0b bb00 0259 1505 190a bb00
    0x0000110: 1959 b200 bd19 0ac0 00bf b600 cfb7 00d2
    0x0000120: 03b8 00e8 3a13 3a12 0319 12b9 00ec 0100
    0x0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715
    0x0000140: 1404 6015 1519 1215 14b9 00ef 0200 c000
    0x0000150: 053a 1819 1619 18b8 00fa 3a16 3615 3614
    0x0000160: a7ff d819 16b8 00f7 b700 653a 0cb2 00ff
    0x0000170: b200 bd05 bd00 0259 0319 0b53 5904 190c
    0x0000180: 53c0 00bf b600 c3b6 0102 b02a b600 3803
    0x0000190: 32b6 0104 b0
  Stackmap Table:
    same_frame(@35)
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114]},{})
    append_frame(@151,Object[#134],Object[#134])
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114],Object[#134],Object[#134],Object[#134],Object[#134],Top,Top,Object[#25],Object[#60],Integer,Integer,Object[#112]},{Uninitialized[#159],Uninitialized[#159], Integer,Object[#134]})
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114],Object[#134],Object[#134],Object[#134],Object[#134],Top,Top,Object[#25],Object[#60],Integer,Integer,Object[#112]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#134]})
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114],Object[#134],Object[#134],Object[#134],Object[#134],Object[#2],Top,Object[#25],Object[#60],Integer,Integer,Object[#112],Objct[#25],Object[#60],Integer,Integer,Object[#112]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#134]})
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#114],Object[#134],Object[#134],Object[#134],Object[#134],Object[#2],Top,Object[#25],Object[#60],Integer,Integer,Object[#112],Objct[#25],Object[#60],Integer,Integer,Object[#112]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#134]})
    full_frame(@395,{Object[#2],Integer},{})

        at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:182)
        at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:217)
        at scala.collection.immutable.HashMap.updated(HashMap.scala:59)
        at scala.collection.immutable.Map$Map4.updated(Map.scala:201)
        at scala.collection.immutable.Map$Map4.$plus(Map.scala:202)
        at scala.collection.immutable.Map$Map4.$plus(Map.scala:180)
        at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:29)
        at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:25)
        at scala.collection.generic.Growable.$anonfun$$plus$plus$eq$1(Growable.scala:59)
        at scala.collection.generic.Growable$$Lambda$7/2113185.apply(Unknown Source)
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
        at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:59)
        at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:50)
        at scala.collection.mutable.MapBuilder.$plus$plus$eq(MapBuilder.scala:25)
        at scala.collection.generic.GenMapFactory.apply(GenMapFactory.scala:48)
        at io.kaitai.struct.languages.components.LanguageCompilerStatic$.<init>(LanguageCompilerStatic.scala:23)
        at io.kaitai.struct.languages.components.LanguageCompilerStatic$.<clinit>(LanguageCompilerStatic.scala)
        at io.kaitai.struct.JavaMain$.<init>(JavaMain.scala:27)
        at io.kaitai.struct.JavaMain$.<clinit>(JavaMain.scala)
        at io.kaitai.struct.JavaMain.main(JavaMain.scala)
```

</details>

Googling showed that such errors are widespread with scala and usually solved by upgrading JRE but this is the latest version in Java 8.

https://stackoverflow.com/questions/40628310/scala-build-crashed
https://stackoverflow.com/questions/42324602/scala-error-using-intellij-remote-serverexception
https://github.com/FasterXML/jackson-module-scala/issues/245
https://github.com/scala-js/scalajs-tutorial/issues/12
https://github.com/vert-x3/vertx-mysql-postgresql-client/issues/80

The version I use is
```
java version "1.8.0_20-ea" Java(TM) SE Runtime Environment (build 1.8.0_20-ea-b21) Java HotSpot(TM) Client VM (build 25.20-b20, mixed mode) 
```

The same version on Windows 7 machine works fine.

**Comment by lrytz** [comment]
You need JDK 8u25 or newer (https://stackoverflow.com/review/suggested-edits/17438561)

**Comment by KOLANICH** [comment]
1 JRE 8u162 is the latest version of JRE by the moment http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

2 8u162 > 8u25

**Comment by martin-g** [comment]
You need to use JDK, not JRE.

**Comment by lrytz** [comment]
> 2 8u162 > 8u25

Ah, I didn't see the title, I looked at the version message you posted which says `1.8.0_20-ea-b21`.

**Comment by KOLANICH** [comment]
>You need to use JDK, not JRE.

1 I tried on both JDK and JRE.
2 Do you really mean that every user of apps written in scala must have JDK (not JRE) on their machines?

**Comment by KOLANICH** [comment]
Are you going to fix this?
