### ISSUE TITLE
Macro: switch v 2.12.4 -> v 2.12.6 breaks c.info

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [scala/bug#10869]
the following snippet works on v 2.12.4  and fails on v 2.12.6

https://github.com/random-maven/scalor-maven-plugin/blob/master/demo/src/macro/scala/meta/MacroContext.scala

```scala
trait MacroContext {

  val c : Context
  import c.universe._

  def prefix( message : String ) = s"Macro demo: $message"
  def info( message : String ) = c.info( c.enclosingPosition, prefix( message ), true )
  def warn( message : String ) = c.warning( c.enclosingPosition, prefix( message ) )
  def fail( message : String ) = c.abort( c.enclosingPosition, prefix( message ) )

  @tailrec
  final def extractName( tree : c.Tree ) : c.Name = tree match {
    case Ident( name )        => name
    case Select( _, name )    => name
    case Function( _, body )  => extractName( body )
    case Block( _, expr )     => extractName( expr )
    case Apply( func, _ )     => extractName( func )
    case TypeApply( func, _ ) => extractName( func )
    case _                    => fail( s"Unsupported expression: $tree" )
  }

}
```
with trace

https://travis-ci.org/random-maven/scalor-maven-plugin/jobs/376348956#L4285

```java
java.lang.UnsupportedOperationException: Macro demo: kp:genAsciiNames=null (source-/home/travis/build/random-maven/scalor-maven-plugin/demo/src/main/scala/kind/SystemProperty.scala,line-11,offset=155)
	at scala.reflect.internal.ForwardingReporter.info0(Reporting.scala:130)
	at scala.reflect.internal.ForwardingReporter.info0$(Reporting.scala:129)
	at scala.tools.nsc.reporters.LimitingReporter.info0(LimitingReporter.scala:9)
	at scala.tools.nsc.reporters.LimitingReporter.info0(LimitingReporter.scala:9)
	at scala.tools.nsc.reporters.Reporter.info(Reporter.scala:20)
	at scala.reflect.macros.contexts.FrontEnds.info(FrontEnds.scala:11)
	at scala.reflect.macros.contexts.FrontEnds.info$(FrontEnds.scala:11)
	at scala.reflect.macros.contexts.Context.info(Context.scala:6)
```

**Comment by olafurpg** [comment]
From the logs

```
	-Xplugin
	/home/travis/.m2/repository/org/scala-js/scalajs-compiler_2.12.6/0.6.22/scalajs-compiler_2.12.6-0.6.22.jar
	-Xplugin
	/home/travis/.m2/repository/org/scala-js/scalajs-junit-test-plugin_2.12.6/0.6.22/scalajs-junit-test-plugin_2.12.6-0.6.22.jar
	-Xplugin
	/home/travis/.m2/repository/org/scalamacros/paradise_2.12.6/2.1.1/paradise_2.12.6-2.1.1.jar
	-Xplugin
	/home/travis/.m2/repository/org/spire-math/kind-projector_2.12/0.9.6/kind-projector_2.12-0.9.6.jar

[INFO] 	-Xplugin
[INFO] 	/home/travis/.m2/repository/com/artima/supersafe/supersafe_2.12.6/1.1.5/supersafe_2.12.6-1.1.5.jar
[INFO] 	-Xplugin
[INFO] 	/home/travis/.m2/repository/org/scalamacros/paradise_2.12.6/2.1.1/paradise_2.12.6-2.1.1.jar
```
Could any of those plugins be the cause?

**Comment by hrhino** [comment]
I suspect it's related to scala/scala#6240.

**Comment by SethTisue** [comment]
cc @som-snytt

**Comment by Andrei-Pozolotin** [comment]
I made a clean case, with no plugins:
https://github.com/random-maven/scalor-maven-plugin/tree/develop/src/it/test-macro

it produces the same trace:
```java
[INFO] [compile-main] [DBUG] [zinc] The Scala compiler is invoked with:
	-Xmaxerrs
	10
	-deprecation
	-feature
	-unchecked
	-bootclasspath
	/nix/store/x0byn24w5db3c3b6iba90krhjg9ah4ax-oraclejdk-8u171/jre/lib/resources.jar:/nix/store/x0byn24w5db3c3b6iba90krhjg9ah4ax-oraclejdk-8u171/jre/lib/rt.jar:/nix/store/x0byn24w5db3c3b6iba90krhjg9ah4ax-oraclejdk-8u171/jre/lib/sunrsasign.jar:/nix/store/x0byn24w5db3c3b6iba90krhjg9ah4ax-oraclejdk-8u171/jre/lib/jsse.jar:/nix/store/x0byn24w5db3c3b6iba90krhjg9ah4ax-oraclejdk-8u171/jre/lib/jce.jar:/nix/store/x0byn24w5db3c3b6iba90krhjg9ah4ax-oraclejdk-8u171/jre/lib/charsets.jar:/nix/store/x0byn24w5db3c3b6iba90krhjg9ah4ax-oraclejdk-8u171/jre/lib/jfr.jar:/nix/store/x0byn24w5db3c3b6iba90krhjg9ah4ax-oraclejdk-8u171/jre/classes:/home/work/repository/maven/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.jar
	-classpath
	/home/work/source/git/scalor-maven-plugin/src/it/test-macro/target/classes:/home/work/repository/maven/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.jar:/home/work/repository/maven/org/scala-lang/scala-compiler/2.12.6/scala-compiler-2.12.6.jar:/home/work/repository/maven/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar:/home/work/repository/maven/org/scala-lang/scala-reflect/2.12.6/scala-reflect-2.12.6.jar
[ERROR] [compile-main] [FAIL] [Error] /home/work/source/git/scalor-maven-plugin/src/it/test-macro/src/main/scala/kind/SystemProperty.scala:11: exception during macro expansion: 
java.lang.UnsupportedOperationException: Macro demo: kp:genAsciiNames=null (source-/home/work/source/git/scalor-maven-plugin/src/it/test-macro/src/main/scala/kind/SystemProperty.scala,line-11,offset=155)
	at scala.reflect.internal.ForwardingReporter.info0(Reporting.scala:130)
	at scala.reflect.internal.ForwardingReporter.info0$(Reporting.scala:129)
	at scala.tools.nsc.reporters.LimitingReporter.info0(LimitingReporter.scala:9)
	at scala.tools.nsc.reporters.LimitingReporter.info0(LimitingReporter.scala:9)
	at scala.tools.nsc.reporters.Reporter.info(Reporter.scala:20)
	at scala.reflect.macros.contexts.FrontEnds.info(FrontEnds.scala:11)
	at scala.reflect.macros.contexts.FrontEnds.info$(FrontEnds.scala:11)
	at scala.reflect.macros.contexts.Context.info(Context.scala:6)
	at scala.reflect.macros.contexts.Context.info(Context.scala:6)
	at meta.MacroContext.info(MacroContext.scala:16)
	at meta.MacroContext.info$(MacroContext.scala:16)
	at meta.MacroBundle.info(MacroBundle.scala:7)
	at meta.MacroBundle.systemProperty(MacroBundle.scala:22)
```

**Comment by som-snytt** [comment]
The workaround is to avoid `-Xmaxerrs` on 2.12.5 and 2.12.6.

**Comment by som-snytt** [comment]
@adriaanm I see that `info` is missing from `reflect.internal.Reporter`, though it is still present in `nsc.reporters.Reporter`, where it is final. Hence it is not forwarded by `ForwardingReporter`. Is it intended to simply remove `info` in favor of `echo`? Or to maintain the distinction between a "forced" info message and mere chatter?

**Comment by som-snytt** [comment]
The other workaround is to set `-Xmaxerrs 100` or more, the default; that's the backdoor.

The PR fixes `nsc.reporters.LimitingReporter`; the other possible item is to give macro's reporter a pass in `Global.reporter_=`. That may be the anon class in `JavaUniverse.reporter`?

**Comment by adriaanm** [comment]
> Is it intended to simply remove info in favor of echo? Or to maintain the distinction between a "forced" info message and mere chatter?

So, the levels would be: error / warning / info / echo. Indeed -- not sure we need the lowest one, though I'm sure someone could come up with a use for it if we leave it in...

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6609
