### ISSUE TITLE
Scala 2.10 with JDK9 compilation error

### ISSUE THREAD

**Issue by vveider** [scala/bug#10871]
Hi, Scala dev team!

I'm trying to compile [Apache Ignite #master](https://github.com/apache/ignite) under JDK9 and one of it's modules (**ignite-scalar_2.10**) is categorically refuses to do so.

I run
```mvn install -U -Pall-java,all-scala,licenses,lgpl,examples -DskipTests -Dmaven.javadoc.skip=true -pl :ignite-scalar_2.10 -am```
and have the following problems:
```[ERROR] error: java.lang.NoClassDefFoundError: javax/tools/ToolProvider
[INFO] 	at scala.reflect.io.JavaToolsPlatformArchive.iterator(ZipArchive.scala:242)
[INFO] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[INFO] 	at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:92)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:308)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.x$16$lzycompute(ClassPath.scala:317)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.x$16(ClassPath.scala:317)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:317)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:317)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:297)
[INFO] 	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
[INFO] 	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
[INFO] 	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[INFO] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[INFO] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[INFO] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[INFO] 	at scala.tools.nsc.util.MergedClassPath.packages$lzycompute(ClassPath.scala:375)
[INFO] 	at scala.tools.nsc.util.MergedClassPath.packages(ClassPath.scala:370)
[INFO] 	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:243)
[INFO] 	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:194)
[INFO] 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:240)
[INFO] 	at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:59)
[INFO] 	at scala.tools.nsc.Global.rootMirror(Global.scala:57)
[INFO] 	at scala.tools.nsc.Global.rootMirror(Global.scala:37)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.<init>(Definitions.scala:166)
[INFO] 	at scala.reflect.internal.Definitions$definitions$.<init>(Definitions.scala:20)
[INFO] 	at scala.reflect.internal.SymbolTable.definitions$lzycompute(SymbolTable.scala:13)
[INFO] 	at scala.reflect.internal.SymbolTable.definitions(SymbolTable.scala:13)
[INFO] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
[INFO] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
[INFO] 	at scala.tools.nsc.Main$.doCompile(Main.scala:79)
[INFO] 	at scala.tools.nsc.Driver.process(Driver.scala:54)
[INFO] 	at scala.tools.nsc.Driver.main(Driver.scala:67)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[INFO]
[INFO] java.lang.reflect.InvocationTargetException
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[INFO] 	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
[INFO] 	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
[ERROR] Caused by: java.lang.NoClassDefFoundError: javax/tools/ToolProvider
[INFO] 	at scala.reflect.io.JavaToolsPlatformArchive.iterator(ZipArchive.scala:242)
[INFO] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[INFO] 	at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:92)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:308)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.x$16$lzycompute(ClassPath.scala:317)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.x$16(ClassPath.scala:317)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:317)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:317)
[INFO] 	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:297)
[INFO] 	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
[INFO] 	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
[INFO] 	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
[INFO] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
[INFO] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[INFO] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[INFO] 	at scala.tools.nsc.util.MergedClassPath.packages$lzycompute(ClassPath.scala:375)
[INFO] 	at scala.tools.nsc.util.MergedClassPath.packages(ClassPath.scala:370)
[INFO] 	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:243)
[INFO] 	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:194)
[INFO] 	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
[INFO] 	at scala.reflect.internal.Mirrors$RootsBase.init(Mirrors.scala:240)
[INFO] 	at scala.tools.nsc.Global.rootMirror$lzycompute(Global.scala:59)
[INFO] 	at scala.tools.nsc.Global.rootMirror(Global.scala:57)
[INFO] 	at scala.tools.nsc.Global.rootMirror(Global.scala:37)
[INFO] 	at scala.reflect.internal.Definitions$DefinitionsClass.<init>(Definitions.scala:166)
[INFO] 	at scala.reflect.internal.Definitions$definitions$.<init>(Definitions.scala:20)
[INFO] 	at scala.reflect.internal.SymbolTable.definitions$lzycompute(SymbolTable.scala:13)
[INFO] 	at scala.reflect.internal.SymbolTable.definitions(SymbolTable.scala:13)
[INFO] 	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
[INFO] 	at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
[INFO] 	at scala.tools.nsc.Main$.doCompile(Main.scala:79)
[INFO] 	at scala.tools.nsc.Driver.process(Driver.scala:54)
[INFO] 	at scala.tools.nsc.Driver.main(Driver.scala:67)
[INFO] 	at scala.tools.nsc.Main.main(Main.scala)
[INFO] 	... 6 more```

Scala version is 2.10.7

Can you please advise some workaround or alike?


Thanks!

**Comment by vveider** [comment]
@SethTisue, if it is duplicate, then can you advise how should I set scala compiler options from maven?

**Comment by martin-g** [comment]
@vveider Does [this](https://github.com/wicketstuff/core/blob/4fd43efb2356f46ac23b9a0af337f19e263e183a/scala-extensions-parent/pom.xml#L118-L133) example help you ?

**Comment by vveider** [comment]
@martin-g, thanks, that worked!
@SethTisue, FYI, {{-nc}} is unrecognized option, also only {{-nobootcp}} is required for successful compilation.
