### ISSUE TITLE
Upgrading to Scala 2.12.6 from 2.12.4 breaks Scaldi injection.  

### ISSUE THREAD

**Issue by dsarosi** [scala/bug#10880]
When upgrading our Play projects to Scala 2.12.6 from 2.12.4, scaldi-play produces serious errors.  Could this be a regression in Scala macros?  

```
java.lang.ArrayIndexOutOfBoundsException: 1
    at java.lang.reflect.Executable.getAllGenericParameterTypes(Executable.java:318)
    at java.lang.reflect.Parameter.getParameterizedType(Parameter.java:201)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$jparamsAsScala$1(JavaMirrors.scala:1209)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.jparamsAsScala(JavaMirrors.scala:1203)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.jconstrAsScala1(JavaMirrors.scala:1190)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$jconstrAsScala$1(JavaMirrors.scala:1182)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:98)
    at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:38)
    at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:96)
    at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$jconstrAsScala(JavaMirrors.scala:1182)
    at scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.$anonfun$completeRest$7(JavaMirrors.scala:789)
    at scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.$anonfun$completeRest$4(JavaMirrors.scala:789)
    at scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.$anonfun$completeRest$1(JavaMirrors.scala:797)
    at scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.completeRest(JavaMirrors.scala:755)
    at scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$LazyPolyType.complete(JavaMirrors.scala:804)
    at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$7.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:173)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:129)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:125)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:129)
    at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$7.info(SynchronizedSymbols.scala:173)
    at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2304)
    at scaldi.jsr330.AnnotationBinding.<init>(AnnotationBinding.scala:47)
    at scaldi.play.ScaldiBuilder$.$anonfun$toScaldiBindings$2(ScaldiBuilder.scala:210)
    at scala.collection.immutable.List.map(List.scala:283)
    at scaldi.play.ScaldiBuilder$.$anonfun$toScaldiBindings$1(ScaldiBuilder.scala:190)
    at scaldi.SimpleContainerInjector.preparedBindings$lzycompute(Module.scala:376)
    at scaldi.SimpleContainerInjector.preparedBindings(Module.scala:376)
    at scaldi.SimpleContainerInjector.init(Module.scala:392)
    at scaldi.Initializeable.partialInit(Injector.scala:299)
    at scaldi.Initializeable.partialInit$(Injector.scala:297)
    at scaldi.SimpleContainerInjector.partialInit(Module.scala:375)
    at scaldi.MutableInjectorAggregation.$anonfun$init$1(Injector.scala:219)
    at scala.collection.immutable.List.flatMap(List.scala:335)
    at scaldi.MutableInjectorAggregation.init(Injector.scala:218)
    at scaldi.Initializeable.partialInit(Injector.scala:299)
    at scaldi.Initializeable.partialInit$(Injector.scala:297)
    at scaldi.MutableInjectorAggregation.partialInit(Injector.scala:177)
    at scaldi.Initializeable.initNonLazy(Injector.scala:284)
    at scaldi.Initializeable.initNonLazy$(Injector.scala:284)
    at scaldi.MutableInjectorAggregation.initNonLazy(Injector.scala:177)
    at scaldi.play.ScaldiBuilder$.createScaldiInjector(ScaldiBuilder.scala:151)
    at scaldi.play.ScaldiBuilder.createInjector(ScaldiBuilder.scala:96)
    at scaldi.play.ScaldiApplicationBuilder.realInjector(ScaldiApplicationBuilder.scala:72)
    at scaldi.play.ScaldiApplicationBuilder.build(ScaldiApplicationBuilder.scala:80)
    at muneris.console.ui.ApplicationLoader.load(ApplicationLoader.scala:35)
    at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
    at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
    at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:171)
```

**Comment by martin-g** [comment]
@dsarosi Did you also update your Java version ? There was a change in Java that led to similar problems for pure Java libraries too.

**Comment by dsarosi** [comment]
@marting-g I used Java 8 version 171 on Mac OS.

**Comment by martin-g** [comment]
@dsarosi https://github.com/scala/bug/issues/10835 - this is the issue I am aware of. It also affected some Java libraries (https://twitter.com/rafaelcodes/status/989772636979838981). That's why I've asked whether you also updated (maybe automatically) your Java together with Scala.

**Comment by dsarosi** [comment]
@martin-g, it also happened with Java 8 version 144 on Mac OS.  I upgraded to version 171 in hope that it would fix the bug.

**Comment by dsarosi** [comment]
@hrhino 

Having a code sample is kinda tough as it's part of a huge stack.  Other people have reported the same problem under the [scaldi-play issue](https://github.com/scaldi/scaldi-play/issues/36) that I opened and I have also posted it on [stackoverflow](https://stackoverflow.com/questions/50285563/play-2-6-13-having-trouble-running-with-scaldi). 

What I could do is upgrade the [play-scaldi-example](https://github.com/scaldi/scaldi-play-example) to play 2.6.13 which is a barebones application and see whether I can reproduce it.  In that scenario you can just run it and debug.  Would that work for you?

**Comment by dsarosi** [comment]
@hrhino I've created a code sample for you to try it.  Just execute `sbt run` then run in your browser.  The same sample works fine with Scala 2.12.4.

https://github.com/dsarosi/scaldi-play-example/tree/play-2.6.x-scala-2.12.6

Please make sure to checkout the branch play-2.6.x-scala-2.12.6.

**Comment by hrhino** [comment]
Thanks for setting that up, @dsarosi! That reliably crashes for me.

This isn't a 2.12.6 regression in the sense that it's doing anything wrong; 2.12.6 simply adds that call to `Parameter.getParameterizedType`, which is choking on a bad classfile in Play:

```
  public play.api.inject.BindingKey$$anon$1(play.api.inject.BindingKey<T>);
    descriptor: (Lplay/api/inject/BindingKey;Lscala/Function0;)V
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=3, args_size=3
         0: aload_0
         1: aload_2
         2: putfield      #19                 // Field instance$1:Lscala/Function0;
         5: aload_0
         6: invokespecial #32                 // Method java/lang/Object."<init>":()V
         9: return
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0      10     0  this   Lplay/api/inject/BindingKey$$anon$1;
            0      10     1 $outer   Lplay/api/inject/BindingKey;
            0      10     2 instance$1   Lscala/Function0;
      LineNumberTable:
        line 193: 0
        line 194: 5
    Signature: #39                          // (Lplay/api/inject/BindingKey<TT;>;)V
    MethodParameters:
      Name                           Flags
      $outer                         final
      instance$1                     final
```

The constructor of this class has two parameters, according to its descriptor, but only one shows up in its signature. 

Java does something subtly different: when compiling

```java
public abstract class O {
  public class I<T> {
    public I(T s) { }
  }
}
```

one gets

```
  public O$I(T);
    descriptor: (LO;Ljava/lang/Object;)V
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=3, args_size=3
         0: aload_0
         1: aload_1
         2: putfield      #1                  // Field this$0:LO;
         5: aload_0
         6: invokespecial #2                  // Method java/lang/Object."<init>":()V
         9: return
      LineNumberTable:
        line 3: 0
    MethodParameters:
      Name                           Flags
      this$0                         final mandated
      s
    Signature: #14                          // (TT;)V
```

Note that the outer pointer parameter has the `ACC_MANDATED` flag set; this tells Java runtime reflection to ignore it when computing the parameter types. Scala does _not_ emit that (or `ACC_SYNTHETIC`), causing a mismatch between the number of args in the descriptor and the number of args in the signature.

**Comment by hrhino** [comment]
I'll take a poke at this this week. It should be relatively easy to fix, however, it will probably need to wait until Play re-publishes with 2.12.7. Going to assign it to that milestone to make sure that it gets fixed.

**Comment by lrytz** [comment]
@hrhino maybe related to https://github.com/scala/bug/issues/10889
