### ISSUE TITLE
Iterator#toString shouldn't side-effect

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#10892]
Here's an example where the re-ordering the evaluation of `toString` affects the behaviour of iterators:

```scala
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> val it = Iterator("a", "number", "of", "words"); val x = it dropWhile (_.length < 2); it.next()
it: Iterator[String] = non-empty iterator
x: Iterator[String] = non-empty iterator
res0: String = a

scala> val it = Iterator("a", "number", "of", "words"); val x = it dropWhile (_.length < 2)
it: Iterator[String] = non-empty iterator
x: Iterator[String] = non-empty iterator

scala> it.next()
res1: String = of
```

It was brought up on Gitter: https://gitter.im/scala/contributors?at=5b02b656e0b50c2d05dca187

**Comment by SethTisue** [comment]
even without considering the REPL context specifically, I think it's a bad thing, essentially a bug, that our `Iterator#toString` calls `hasNext` at all, which might need to consume arbitrary amount of data in order to return an answer.

so 👍 to just printing `<iterator>` or some such

there are no Java Joneses to keep up with here:

```
scala> (new java.util.Iterator[String] { def hasNext = ??? ; def next = ??? }).toString
res5: String = $anon$1@ea7a4c3
```

**Comment by som-snytt** [comment]
How about something like:
```
scala> val (lo, hi) = (1 to 10).iterator.span(_ < 5)
lo: Iterator[Int] = <iterator>
hi: Iterator[Int] = <iterator>

scala> lo.hasNext
res0: Boolean = true

scala> lo
res1: Iterator[Int] = non-empty iterator

scala> hi
res2: Iterator[Int] = <iterator>

scala> lo.next
res3: Int = 1

scala> lo
res4: Iterator[Int] = <iterator>

scala> hi.hasNext
res5: Boolean = true

scala> lo
res6: Iterator[Int] = non-empty iterator

scala> lo.next
res7: Int = 2

scala> lo.next;lo.next;lo.next
java.util.NoSuchElementException: next on empty iterator
  at scala.collection.Iterator$$anon$2.next(Iterator.scala:42)
  at scala.collection.Iterator$$anon$2.next(Iterator.scala:40)
  at scala.collection.Iterator$Leading$1.next(Iterator.scala:742)
  ... 28 elided

scala> lo
res9: Iterator[Int] = empty iterator

scala> hi
res10: Iterator[Int] = non-empty iterator

scala> hi.next
res11: Int = 5

scala> hi
res12: Iterator[Int] = <iterator>

```

**Comment by SethTisue** [comment]
@som-snytt I'd rather `Iterator` were kept simple... if someone wants to know if the iterator is empty or not, let them call `hasNext` themselves

**Comment by som-snytt** [comment]
@SethTisue That's OK, [this PR](https://github.com/scala/scala/pull/6668) is only 2.12.  Strawman got its side-effecting `toString` restored in February.
