### ISSUE TITLE
StackOverflow on type self application

### ISSUE THREAD

**Issue by nau** [scala/bug#10896]
It's probably a known issue but I couldn't find it. 
Scala 2.12.4, Scala 2.12.6.

    object Bug {
      type S[A[_]] = A[A[Int]]
      type F[A] = S[S] // StackOverflow
      // type F = S[S] // this complains: cyclic aliasing or subtyping involving type S
    }

causes 

    java.lang.StackOverflowError
	at scala.reflect.internal.Types$SimpleTypeProxy.baseType(Types.scala:160)
	at scala.reflect.internal.Types$SimpleTypeProxy.baseType$(Types.scala:160)
	at scala.reflect.internal.Types$SingletonType.baseType(Types.scala:1095)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.loop$4(TypeMaps.scala:680)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.thisTypeAsSeen(TypeMaps.scala:686)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:481)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:102)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:484)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:454)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:111)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:484)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:454)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:111)
	at scala.reflect.internal.tpe.TypeMaps$AsSeenFromMap.apply(TypeMaps.scala:484)
	at scala.reflect.internal.Types$Type.asSeenFrom(Types.scala:693)
	at scala.reflect.internal.Types$TypeRef.seenFromOwnerInstantiated$1(Types.scala:2210)
	at scala.reflect.internal.Types$TypeRef.relativize(Types.scala:2214)
	at scala.reflect.internal.Types$AliasTypeRef.betaReduce(Types.scala:2037)
	at scala.reflect.internal.Types$AliasTypeRef.betaReduce$(Types.scala:2037)
	at scala.reflect.internal.Types$AliasArgsTypeRef.betaReduce(Types.scala:2430)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl(Types.scala:2017)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl$(Types.scala:2016)
	at scala.reflect.internal.Types$AliasArgsTypeRef.normalizeImpl(Types.scala:2430)
	at scala.reflect.internal.Types$TypeRef.normalize(Types.scala:2254)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl(Types.scala:2017)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl$(Types.scala:2016)
	at scala.reflect.internal.Types$AliasArgsTypeRef.normalizeImpl(Types.scala:2430)
	at scala.reflect.internal.Types$TypeRef.normalize(Types.scala:2254)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl(Types.scala:2017)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl$(Types.scala:2016)
    ...

Haskell manages to handle this correctly:

```
    GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
   Prelude> type T a = a (a Int)
   Prelude> type F c = T T

<interactive>:2:14: error:
    • Expected kind ‘* -> *’, but ‘T’ has kind ‘(* -> *) -> *’
    • In the first argument of ‘T’, namely ‘T’
      In the type ‘T T’
      In the type declaration for ‘F’
```

**Comment by hrhino** [comment]
The bottom of the stack trace:

```
	at scala.reflect.internal.Types$TypeRef.normalize(Types.scala:2254)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl(Types.scala:2017)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl$(Types.scala:2016)
	at scala.reflect.internal.Types$AliasArgsTypeRef.normalizeImpl(Types.scala:2430)
	at scala.reflect.internal.Types$TypeRef.normalize(Types.scala:2254)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl(Types.scala:2017)
	at scala.reflect.internal.Types$AliasTypeRef.normalizeImpl$(Types.scala:2016)
	at scala.reflect.internal.Types$AliasArgsTypeRef.normalizeImpl(Types.scala:2430)
	at scala.reflect.internal.Types$TypeRef.normalize(Types.scala:2254)
	at scala.reflect.internal.Types$AliasTypeRef.typeSymbol(Types.scala:1995)
	at scala.reflect.internal.Types$AliasTypeRef.typeSymbol$(Types.scala:1995)
	at scala.reflect.internal.Types$AliasArgsTypeRef.typeSymbol(Types.scala:2430)
	at scala.reflect.internal.Types$PolyType.typeSymbol(Types.scala:2611)
	at scala.tools.nsc.typechecker.Namers$Namer.validate(Namers.scala:1891)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:862)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1960)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1958)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1953)
	at scala.tools.nsc.typechecker.Namers$PolyTypeCompleter.completeImpl(Namers.scala:1993)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1960)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1958)
	at scala.tools.nsc.typechecker.Namers$PolyTypeCompleter.complete(Namers.scala:1972)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1535)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1683)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5255)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2006)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1876)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5553)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5703)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:3129)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3274)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5262)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5555)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5602)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5640)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInternal(Typers.scala:5672)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5613)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5618)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5699)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:104)
	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:426)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:419)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1(Analyzer.scala:94)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.$anonfun$run$1$adapted(Analyzer.scala:93)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:93)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1446)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1430)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1423)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1539)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
	at scala.tools.nsc.Driver.process(Driver.scala:55)
	at scala.tools.nsc.Driver.main(Driver.scala:68)
	at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by nau** [comment]
Also reproduces on 2.11.8 and 2.10.7

**Comment by Blaisorblade** [comment]
FWIW Dotty correctly rejects this with an error similar to Haskell:
```scala
scala> object Bug {
           type S[A[_]] = A[A[Int]]
           type F[A] = S[S] // StackOverflow
           // type F = S[S] // this complains: cyclic aliasing or subtyping involving type S
         }
3 |    type F[A] = S[S] // StackOverflow
  |                  ^
  |   Type argument Bug.S has not the same kind as its bound  <: [_$5] => Any
```
