### ISSUE TITLE
ExecutionContext.reportFailure is never called

### ISSUE THREAD

**Issue by darkfrog26** [scala/bug#10921]
In the following test code I intentionally throw an exception, but `reportFailure` is never invoked:

```scala
package test

import scala.concurrent.duration.Duration
import scala.concurrent.{Await, ExecutionContext, Future}

object TestBug {
  object TestExecutionContext extends ExecutionContext {
    override def execute(runnable: Runnable): Unit = {
      scala.concurrent.ExecutionContext.global.execute(runnable)
    }

    override def reportFailure(cause: Throwable): Unit = {
      println(s"REPORT FAILURE! ${cause.getMessage}")
      scala.concurrent.ExecutionContext.global.reportFailure(cause)
    }
  }

  def main(args: Array[String]): Unit = {
    Await.result(Future(throw new RuntimeException("Test!"))(TestExecutionContext), Duration.Inf)
  }
}
```

This is on Scala 2.12.6

**Comment by plokhotnyuk** [comment]
1) `ExecutionContext.global` has already defined reporter that prints stack traces to the `System.err`.
2) You should not call `reportFailure()`, your context will be called automatically if it executes the runnable, but not just forward it to another async context with a different reporter.

**Comment by darkfrog26** [comment]
1.) I'm attempting to access the stack trace from my custom `ExecutionContext` and assumed that was the purpose of `reportFailure()`?

2.) I'm not calling it...looking at the source, my expectation was that it would automatically be called.  Look at the source above, I'm not calling `reportFailure` and when the runnable errors it doesn't call it either.

**Comment by darkfrog26** [comment]
To clarify, I'm expecting the above code to result in `REPORT FAILURE! Test!` to be printed out, but it doesn't.  This seems like a bug to me.

**Comment by plokhotnyuk** [comment]
Yes, you are right here the bug definitely somewhere here: in the code or in docs:
```
  /** Reports that an asynchronous computation failed.
   *
   *  @param cause  the cause of the failure
   */
  def reportFailure(@deprecatedName('t) cause: Throwable): Unit
```

**Comment by martin-g** [comment]
I think your reporter is ignored because the runnable is actually executed
with `scala.concurrent.ExecutionContext.global.execute(runnable)`

**Comment by darkfrog26** [comment]
@martin-g, sorry, that is misleading...even if I just call `runnable.run()` the same situation occurs in that code.

**Comment by som-snytt** [comment]
Throw from your `execute` to witness true failure:
```
    override def execute(runnable: Runnable): Unit = {
      //scala.concurrent.ExecutionContext.global.execute(runnable)
      ???
    }
```

**Comment by darkfrog26** [comment]
@som-snytt the problem is that I'm trying to access the `Throwable` when it occurs from my `ExecutionContext`, which, as I understand it, is the point of `reportFailure`.

**Comment by viktorklang** [comment]
`reportFailure` is only invoked for those async failures where there are no other means of propagating the failure.

**Comment by darkfrog26** [comment]
@viktorklang is there no way for the custom `ExecutionContext` to access that `Throwable` that occurs within a `Future`?

**Comment by viktorklang** [comment]
@darkfrog26 No, ExecutionContext has no knowledge about Future. You can see examples of cases where the Future machinery has no option but to call `reportFailure` here: https://github.com/scala/scala/blob/2.13.x/src/library/scala/concurrent/impl/Promise.scala#L68

**Comment by darkfrog26** [comment]
@viktorklang That's a shame.  My use-case is that I'm trying to inject trace information for asynchronous calls to populate missing trace data broken by `Future`.  This all works with a simple custom `ExecutionContext` if I could only get access to the underlying `Throwable` when it occurs.

**Comment by darkfrog26** [comment]
Still seems like a bug that `reportFailure` isn't consistently called when a `Throwable` is fired.

**Comment by viktorklang** [comment]
@darkfrog26 It would only be a bug if that was the contract for `reportFailure`. Could could of course instrument so that whenever a Promise is completed with a Failure, you hook in there. (remember that the exception doesn't need to be thrown in the first place)

**Comment by darkfrog26** [comment]
@viktorklang the problem is contextualization though.  The `ExecutionContext` has access to the stack data, and that is lost by the time the failure propagates up.

**Comment by viktorklang** [comment]
@darkfrog26 Ah, so you wanted to hook in there to do stack walking? It would be too late anyway since it would have been called lower in the stack. I guess you'd have to trap the throw instruction.

**Comment by viktorklang** [comment]
@darkfrog26 But since not all failures are thrown (merely completed with .failure(…) or any of the other complete-methods) that wouldn't cover everything.

**Comment by darkfrog26** [comment]
@viktorklang not exactly...at compile-time it builds a stack trace with `ExecutionContext`s (see https://github.com/outr/scribe/blob/master/core/shared/src/main/scala/scribe/Macros.scala#L73).  This all works and I can log the stack, but I want to add a feature, where possible, to update `Throwable`'s stacktrace when it's fired.  I can do this with creating a custom `Future`, but that's far more invasive than I'd like.

**Comment by darkfrog26** [comment]
This was my attempt at solving: https://www.schibsted.pl/blog/tracing-back-scala-future-chains/ a little more cleanly

**Comment by viktorklang** [comment]
@darkfrog26 Ah, ok, then I perhaps misunderstood.

**Comment by darkfrog26** [comment]
Is it safe to assume there's no good solution to this problem?

**Comment by viktorklang** [comment]
@darkfrog26 IMO the best (imaginary) solution would be JVM support for async stack traces. Perhaps we'll get them with Project Loom?

**Comment by darkfrog26** [comment]
@viktorklang while I absolutely agree, I'm on the cusp of a pretty useful solution if I could just get past this one issue.  I was just hoping you guys might know of a clever workaround that would let me do it.

**Comment by darkfrog26** [comment]
I have this fully functional with a horrible extra step.  My original code looks like:

```scala
throw new RuntimeException("Failure!")
```

and it outputs the stack trace:
```
java.lang.RuntimeException: Failure!
        at spec.FutureTesting$Test3$.$anonfun$doSomething$3(FutureTesting.scala:27)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scribe.LoggingExecutionContext$$anon$1.$anonfun$run$1(LoggingExecutionContext.scala:16)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scribe.MDC$.contextualize(MDC.scala:16)
        at scribe.LoggingExecutionContext$$anon$1.run(LoggingExecutionContext.scala:15)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
But if I change it to:
```scala
throw Position.fix(new RuntimeException("Failure!"))
```
The trace becomes:
```
java.lang.RuntimeException: Failure!
        at spec.FutureTesting$Test3$.$anonfun$doSomething$3(FutureTesting.scala:29)
        at spec.FutureTesting.Test3.doSomething(FutureTesting.scala:28)
        at spec.FutureTesting.Test2.doSomething(FutureTesting.scala:22)
        at spec.FutureTesting.Test1.doSomething(FutureTesting.scala:16)
        at spec.FutureTesting.position(FutureTesting.scala:11)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scribe.LoggingExecutionContext$$anon$1.$anonfun$run$1(LoggingExecutionContext.scala:17)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scribe.MDC$.contextualize(MDC.scala:16)
        at scribe.LoggingExecutionContext$$anon$1.run(LoggingExecutionContext.scala:16)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

See how close to perfect this is?   If I could just get access to the `Throwable` from the `ExecutionContext` I wouldn't need the fix call.

**Comment by darkfrog26** [comment]
The relevant code is:

```scala
object FutureTesting {
  def position(): Future[List[Position]] = Future {
    Test1.doSomething()
  }.flatten

  object Test1 {
    def doSomething(): Future[List[Position]] = Future {
      Test2.doSomething()
    }.flatten
  }

  object Test2 {
    def doSomething(): Future[List[Position]] = Future {
      Test3.doSomething()
    }.flatten
  }

  object Test3 {
    def doSomething(): Future[List[Position]] = Future {
      throw new RuntimeException("Failure!")
    }
  }
}
```

**Comment by viktorklang** [comment]
@darkfrog26 Sounds like this would need runtime weaving.

**Comment by darkfrog26** [comment]
@viktorklang, I've tried using Reflection to access the `CallbackRunnable`'s `value: Try[T]`, but even when an exception is thrown, it's still a `Success`.

**Comment by viktorklang** [comment]
@darkfrog26 I don't know the circumstances. You sure you are looking at the right thing?

**Comment by darkfrog26** [comment]
The `Runnable` that the `ExecutionContext` receives is a `CallbackRunnable`. Beyond that, I really have no clue. :-p

**Comment by SethTisue** [comment]
it doesn't sound like there's anything clearly actionable here? reopen if I'm wrong.

**Comment by som-snytt** [comment]
@SethTisue you mean wrong about this, right?

**Comment by SethTisue** [comment]
![e2c](https://user-images.githubusercontent.com/161079/41265246-537673b0-6dbf-11e8-8a21-48b3eca0a7e3.jpg)

**Comment by darkfrog26** [comment]
Yeah, looks like a limitation that won't be easily circumvented.  I've got a less-than-perfect workaround, but that's life in the programming world.
