### ISSUE TITLE
showCode outputs incorrect code for implicit lambda parameters

### ISSUE THREAD

**Issue by ggevay** [scala/bug#10936]
```
import scala.tools.reflect.ToolBox
import scala.reflect.runtime.universe._
val code = showCode(reify {
  val f = {implicit x: Int => x+1}
}.tree) 
val tb = runtimeMirror(getClass.getClassLoader).mkToolBox()
tb.eval(tb.parse(code))
```
which gives
```
scala.tools.reflect.ToolBoxError: reflective compilation has failed:

'=>' expected but '(' found.
illegal start of simple expression
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:316)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.parse(ToolBoxFactory.scala:291)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$parse$1.apply(ToolBoxFactory.scala:417)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$parse$1.apply(ToolBoxFactory.scala:414)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:355)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:355)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.parse(ToolBoxFactory.scala:414)
  ... 33 elided
```
Here `showCode` prints the following, which can't be parsed:
```
{
  val f = (implicit x: Int => x.+(1));
  ()
}
```
Note that it can be parsed if I edit it to this:
```
{
  val f = {implicit x: Int => x.+(1)};
  ()
}
```
(I tried this on Scala 2.12.6)

**Comment by SethTisue** [comment]
this also parses: `(implicit (x: Int) => ...)`
