### ISSUE TITLE
scala.collection.ArrayOps#slice throw OutOfMemoryError in latest Scala 2.13. (Int overflow?)

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#10930]
- https://github.com/scala/scala/blob/2b49d718fd2ce034a5f450b2041013e2889591d0/src/library/scala/collection/ArrayOps.scala#L239-L241
- https://github.com/scala/scala/blob/v2.12.6/src/library/scala/collection/mutable/ArrayOps.scala#L46-L48

build.sbt

```scala
resolvers += "scala-pr" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"

scalaVersion := "2.13.0-pre-2b49d71" // latest 2018-06-05
```

### latest Scala 2.13

```
Welcome to Scala 2.13.0-pre-2b49d71 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Array(1).slice(1052471512, -1496048404)
java.lang.OutOfMemoryError: Java heap space
  at java.util.Arrays.copyOfRange(Arrays.java:3592)
  at scala.collection.ArrayOps$.slice$extension(ArrayOps.scala:245)
  ... 30 elided
```

###  Scala 2.13.0-M4

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Array(1).slice(1052471512, -1496048404)
java.lang.OutOfMemoryError: Java heap space
  at java.util.Arrays.copyOfRange(Arrays.java:3592)
  at scala.collection.ArrayOps$.slice$extension(ArrayOps.scala:244)
  ... 30 elided
```

### Scala 2.12.6

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Array(1).slice(1052471512, -1496048404)
res0: Array[Int] = Array()
```

**Comment by xuwei-k** [comment]
`scala.collection.immutable.ArraySeq#slice` as well

```
Welcome to Scala 2.13.0-pre-2b49d71 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> scala.collection.immutable.ArraySeq(1).slice(1052471512, -1496048404)
java.lang.OutOfMemoryError: Java heap space
  at java.util.Arrays.copyOfRange(Arrays.java:3592)
  at scala.collection.ArrayOps$.slice$extension(ArrayOps.scala:245)
  at scala.collection.immutable.ArraySeq.slice(ArraySeq.scala:108)
  ... 29 elided
```

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> scala.collection.immutable.ArraySeq(1).slice(1052471512, -1496048404)
java.lang.OutOfMemoryError: Java heap space
  at java.util.Arrays.copyOfRange(Arrays.java:3592)
  at scala.collection.ArrayOps$.slice$extension(ArrayOps.scala:244)
  at scala.collection.immutable.ArraySeq.slice(ArraySeq.scala:105)
  ... 29 elided
```
