### ISSUE TITLE
"a".mkString(",") throw OutOfMemoryError in latest Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#10951]
```
resolvers += "scala-pr" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"

scalaVersion := "2.13.0-pre-8bb6f9d" // latest 2018-06-20
```

```
Welcome to Scala 2.13.0-pre-8bb6f9d (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> "a".mkString(",")
java.lang.OutOfMemoryError: Java heap space
  at java.util.Arrays.copyOf(Arrays.java:3332)
  at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
  at java.lang.StringBuilder.append(StringBuilder.java:202)
  at scala.collection.mutable.StringBuilder.append(Builder.scala:205)
  at scala.collection.StringOps$.addString$extension2(StringOps.scala:523)
  at scala.collection.StringOps$.mkString$extension0(StringOps.scala:495)
  at scala.collection.StringOps$.mkString$extension1(StringOps.scala:503)
  ... 24 elided
```

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> "a".mkString(",")
java.lang.OutOfMemoryError: Java heap space
  at java.util.Arrays.copyOf(Arrays.java:3332)
  at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
  at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:649)
  at java.lang.StringBuilder.append(StringBuilder.java:202)
  at scala.collection.mutable.StringBuilder.append(Builder.scala:209)
  at scala.collection.StringOps$.addString$extension2(StringOps.scala:524)
  at scala.collection.StringOps$.mkString$extension0(StringOps.scala:496)
  at scala.collection.StringOps$.mkString$extension1(StringOps.scala:504)
  ... 24 elided
```

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> "a".mkString(",")
res0: String = a
```

**Comment by SethTisue** [comment]
LOL

**Comment by som-snytt** [comment]
This makes me rethink my experiment to distinguish "lowercase" numerals, where one would be indistinguishable from the Turkish dotless eye, and to my eye, indistinguishable from eye `i`.

Anyway, `i` is way overused. `n` should suffice.

`"Seth never indexes into anything."`
