### ISSUE TITLE
Strange behavior in ValDef

### ISSUE THREAD

**Issue by nokok** [scala/bug#10952]
I was found strange behavior in `val 1 = 1`.
Is this by design?

### REPL:
```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> val 1 = 1

scala> val 1 = 2
scala.MatchError: 2 (of class java.lang.Integer)
  ... 28 elided

scala> :type val 1 = 1 

scala> // !?
```

### scalac:

```scala
// Main.scala
object Main extends App {
  val 30 = 2
}
```

```
> scalac -Xprint:typer Main.scala -Xdev
warning: !!! NoSymbol.owner
scala.reflect.internal.SymbolTable.$anonfun$devWarningDumpStack$1(SymbolTable.scala:86)
  at scala.tools.nsc.Global.devWarning(Global.scala:302)
  at scala.reflect.internal.Symbols$NoSymbol.owner(Symbols.scala:3561)
  at scala.reflect.internal.Symbols$Symbol.canMatchInheritedSymbols(Symbols.scala:2362)
  at scala.reflect.internal.Symbols$Symbol.isOverridingSymbol$lzycompute(Symbols.scala:2389)
  at scala.reflect.internal.Symbols$Symbol.isOverridingSymbol(Symbols.scala:2390)
  at scala.reflect.internal.Symbols$Symbol.nextOverriddenSymbol(Symbols.scala:2401)
  at scala.tools.nsc.typechecker.Namers$Namer.safeNextOverriddenSymbol(Namers.scala:1651)
  at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1612)
  at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1796)
  at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1761)
  at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:840)
  at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1958)
  at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1956)
  at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1951)
[[syntax trees at end of                     typer]] // Main.scala
package <empty> {
  object Main extends AnyRef with App {
    def <init>(): Main.type = {
      Main.super.<init>();
      ()
    };
    <synthetic> <artifact> private[this] val x$1: Unit = (2: Int(2) @unchecked) match {
      case 30 => ()
    }
  }
}

one warning found
> scala Main
scala.MatchError: 2 (of class java.lang.Integer)
        at Main$.delayedEndpoint$Main$1(Main.scala:2)
        at Main$delayedInit$body.apply(Main.scala:1)
        at scala.Function0.apply$mcV$sp(Function0.scala:34)
        at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App.$anonfun$main$1$adapted(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:389)
        at scala.App.main(App.scala:76)
        at scala.App.main$(App.scala:74)
        at Main$.main(Main.scala:1)
        at Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:99)
        at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:34)
        at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:30)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:125)
        at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:99)
        at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:91)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:125)
        at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:22)
        at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:21)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
        at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:29)
        at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:28)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:66)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:85)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by SethTisue** [comment]
yes, by design, this is legal Scala. `val` takes a pattern, `1` is a pattern.

this was discussed thoroughly at https://www.scala-lang.org/old/node/10730
