### ISSUE TITLE
java.lang.IllegalAccessError while instantiating specialized class in certain circumstances

### ISSUE THREAD

**Issue by nuransan** [scala/bug#10967]
```
class A[@specialized(Int) T]

class B[@specialized(Int) T] {
  val a = new A[T]
  val b = new Object // requires a second field for the bug to occur
}

object BugDemo extends App {
  new B[Int]
}
```

```
Exception in thread "main" java.lang.IllegalAccessError
	at B$mcI$sp.<init>(bug.scala:5)
	at BugDemo$.<init>(bug.scala:9)
	at BugDemo$.<clinit>(bug.scala)
	at BugDemo.main(bug.scala)
```

Scala version: 2.12.6 (also: 2.11.12 and seems all the earlier)
Java version: 1.8.0_171

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/4511

I added the test sample there.
