### ISSUE TITLE
Compiler crash while compiling with JDK 10

### ISSUE THREAD

**Issue by denisrosset** [scala/bug#11022]
This is with OpenJDK 10 on Ubuntu (where, weirdly, the package is name `openjdk-11-jdk`), on Scala 2.12.6.

The project is here: https://github.com/denisrosset/symdpoly

It's a medium-sized code base, using notably macros, path-dependent and singleton types.

The macros come mostly from `machinist` (for typeclass operators), `shapeless` (`Witness` is used a lot), `metal` and `scalin`.

The last two libraries are available here: https://github.com/denisrosset/metal
and here: https://github.com/denisrosset/scalin

Those last wo libraries compile and test without issues though on JDK 10.

Everything mentioned above runs just fine on JDK 8.

Excerpt of the console output:
```
[error] Error while emitting Solution.scala
[error] assertion failed: ClassBType.info not yet assigned: Ljava/lang/String;
java.lang.AssertionError: assertion failed: ClassBType.info not yet assigned: Ljava/lang/Object;
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.info(BTypes.scala:629)
	at scala.tools.nsc.backend.jvm.BTypes$ClassBType.isInterface(BTypes.scala:661)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genCallMethod(BCodeBodyBuilder.scala:1082)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:579)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:296)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:80)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.$anonfun$genBlock$1(BCodeBodyBuilder.scala:812)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:812)
	at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:366)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:602)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:634)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:508)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.$anonfun$gen$7(BCodeSkelBuilder.scala:510)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:510)
	at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:110)
```

**Comment by xuwei-k** [comment]
https://github.com/scala/bug/issues/10717 ? 

https://github.com/denisrosset/symdpoly/blob/1a43e3fca334d027257284c3863732efbe357a50/build.sbt#L109

**Comment by denisrosset** [comment]
Yep indeed, disabling optimizations help -- the tests run perfectly then.

You can close this as duplicate if you feel like it! Thanks for your input.
