### ISSUE TITLE
ArrayOps#startsWith throw ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11023]
### latest Scala 2.13.x [0c15792](https://github.com/scala/scala/tree/0c157929fe01a0e47723ca3a9bb5c31ab0183836)

```
Welcome to Scala 2.13.0-pre-0c15792 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Array(1).startsWith(Array[Int](1), Int.MinValue + 2)
java.lang.ArrayIndexOutOfBoundsException: -2147483646
  at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:55)
  at scala.collection.ArrayOps$.startsWith$extension1(ArrayOps.scala:1302)
  ... 38 elided
```

### 2.13.0-M4

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Array(1).startsWith(Array[Int](1), Int.MinValue + 2)
java.lang.ArrayIndexOutOfBoundsException: -2147483646
  at scala.runtime.ScalaRunTime$.array_apply(ScalaRunTime.scala:55)
  at scala.collection.ArrayOps$.startsWith$extension1(ArrayOps.scala:1305)
  ... 30 elided
```

### 2.12.6

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Array(1).startsWith(Array[Int](1), Int.MinValue + 2)
java.lang.ArrayIndexOutOfBoundsException: -2147483646
  at scala.collection.mutable.ArrayOps$ofInt$.apply$extension(ArrayOps.scala:249)
  at scala.collection.mutable.ArrayOps$ofInt.apply(ArrayOps.scala:242)
  at scala.collection.IndexedSeqOptimized.startsWith(IndexedSeqOptimized.scala:243)
  at scala.collection.IndexedSeqOptimized.startsWith$(IndexedSeqOptimized.scala:237)
  at scala.collection.mutable.ArrayOps$ofInt.startsWith(ArrayOps.scala:242)
  ... 28 elided
```

### 2.11.12

```
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Array(1).startsWith(Array[Int](1), Int.MinValue + 2)
java.lang.ArrayIndexOutOfBoundsException: -2147483646
  at scala.collection.mutable.ArrayOps$ofInt$.apply$extension(ArrayOps.scala:241)
  at scala.collection.mutable.ArrayOps$ofInt.apply(ArrayOps.scala:234)
  at scala.collection.IndexedSeqOptimized$class.startsWith(IndexedSeqOptimized.scala:244)
  at scala.collection.mutable.ArrayOps$ofInt.startsWith(ArrayOps.scala:234)
  ... 32 elided
```

**Comment by Jasper-M** [comment]
What's wrong with `-1`?
