### ISSUE TITLE
scalac java.lang.StackOverflowError on moderately large file

### ISSUE THREAD

**Issue by rnd4222** [scala/bug#11107]
Scala version 2.12.6
OpenJDK 1.8.0_181
Ubuntu 16.04

Compiling [this](https://pastebin.com/jmmUKyGP) piece of code results in [StackOverflowError](https://pastebin.com/raw/ARDpJSbU).

**Comment by SethTisue** [comment]
in general, we consider it normal that some kinds of heavily nested code will require giving the compiler more stack (e.g. with `-Xss`)

does the problem go away with `-Xss`? if so, this is almost certainly a "won't fix"

**Comment by rnd4222** [comment]
@SethTisue I'm already tried increasing -Xss and -Xmx and problem still remains:
`> show scalacOptions
[info] * -J-Xss256m
[info] * -J-Xmx8G`
And increasing it further doesn't solves the problem.

**Comment by SethTisue** [comment]
is the problem reproducible without external dependencies? I tried compiling the code myself, but couldn't without dependency declarations.

**Comment by rnd4222** [comment]
Sorry, forgot to mention external dependencies:

> "com.github.finagle" %% "finch-core" % "0.22.0"
"com.github.finagle" %% "finch-circe" % "0.22.0"
"io.circe" %% "circe-generic" % "0.9.0"

I don't tried to reproduce a bug without it - all the code do is combine dependencies in various ways.

**Comment by rnd4222** [comment]
OK, [https://pastebin.com/iAnZ83QH](here) is minimized example without external dependencies at all.

**Comment by SethTisue** [comment]
the repeated section of the stack trace is

```
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:73)
	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:57)
	at scala.reflect.internal.Trees.itransform(Trees.scala:1387)
	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:73)
	at scala.tools.nsc.transform.patmat.PatternMatching$MatchTransformer.transform(PatternMatching.scala:57)
```

**Comment by SethTisue** [comment]
the no-external-dependencies version gives SOE with default stack size, but compiles fine with `scalac -J-Xss2m S.scala`

**Comment by SethTisue** [comment]
```
show scalacOptions
[info] * -J-Xss256m
[info] * -J-Xmx8G
```

I think the issue here is the method you are using to increase the stack size. once the JVM has already started, it's too late. you need to set it at JVM startup time
