### ISSUE TITLE
Iteration over exhausted sub-iterator leads to NPE

### ISSUE THREAD

**Issue by tIGO** [scala/bug#11153]
```
val a = Iterator.empty ++ Iterator.empty
a.hasNext
val b = Iterator.empty ++ a
while (b.hasNext) b.next()

Exception in thread "main" java.lang.NullPointerException
	at scala.collection.Iterator$ConcatIterator.advance(Iterator.scala:195)
	at scala.collection.Iterator$ConcatIterator.hasNext(Iterator.scala:222)
	at Test$.delayedEndpoint$Test$1(Test.scala:19)
	at Test$delayedInit$body.apply(Test.scala:13)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at Test$.main(Test.scala:13)
	at Test.main(Test.scala)
```
The reason is that internals of ConcatIterator [null'ed](https://github.com/scala/scala/blame/2.13.x/src/library/scala/collection/Iterator.scala#L1044) on `hasNext` method invocation, but `advance` invokes [current.hasNext](https://github.com/scala/scala/blame/2.13.x/src/library/scala/collection/Iterator.scala#L1053) without checking it for null. 

Works in 2.11.8. Doesn't work in 2.12.6/2.13-M5.

**Comment by SethTisue** [comment]
2.12.x backport https://github.com/scala/scala/pull/7227
