### ISSUE TITLE
VectorMap throws MatchError when key is null

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11217]
```
Welcome to Scala 2.13.0-pre-a84ce5b (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_192).
Type in expressions for evaluation. Or try :help.

scala> Map((null, 1), ("a", 2))
res0: scala.collection.immutable.Map[String,Int] = Map(null -> 1, a -> 2)

scala> import scala.collection.immutable.VectorMap
import scala.collection.immutable.VectorMap

scala> VectorMap((null, 1), ("a", 2))
scala.MatchError: null
  at scala.collection.immutable.VectorMap.scala$collection$immutable$VectorMap$$field(VectorMap.scala:78)
  at scala.collection.immutable.VectorMap$$anon$1.advance(VectorMap.scala:99)
  at scala.collection.immutable.VectorMap$$anon$1.<init>(VectorMap.scala:110)
  at scala.collection.immutable.VectorMap.iterator(VectorMap.scala:88)
  at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:234)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:243)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:251)
  at .$print$lzycompute(<synthetic>:8)
  ... 35 elided
```

**Comment by SethTisue** [comment]
@odd I'll assign you this and the other tickets if you accept the invite to https://github.com/orgs/scala/teams/contributors
