### ISSUE TITLE
VectorMap#remove throw IllegalStateException

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11220]
```
Welcome to Scala 2.13.0-pre-a84ce5b (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_192).
Type in expressions for evaluation. Or try :help.

scala> scala.collection.immutable.VectorMap(1 -> "a") - 1 + (2 -> "b") - 2
java.lang.IllegalStateException: kinless tombstone found in prefix: 2
  at scala.collection.immutable.VectorMap.remove(VectorMap.scala:144)
  at scala.collection.immutable.VectorMap.remove(VectorMap.scala:34)
  at scala.collection.immutable.MapOps.$minus(Map.scala:78)
  at scala.collection.immutable.MapOps.$minus$(Map.scala:78)
  at scala.collection.immutable.AbstractMap.$minus(Map.scala:417)
  ... 38 elided
```

**Comment by szeiger** [comment]
PR: https://github.com/scala/scala/pull/7357
