### ISSUE TITLE
compactification is not appropriate for Java classes

### ISSUE THREAD

**Issue by hrhino** [scala/bug#11277]
We have `-Xmax-classfile-name` to avoid going over filename character limits that exist on certain platforms (see #3623), but `javac` has no such mechanism. However, we blithely subject Java inner class names to the same post-flattening transformation as we do to our own, which leads to linkage errors at runtime.

```java
// Long_1.java
package p;

public class Long_1 {
    public static class ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ_1 {
    }
}
```

```scala
// Test_2.scala
import p._

object Test extends App {
  println {
    new Long_1.ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ_1()
      .getClass
      .getName
  }
}
```

```
hhoughton:java-long-names hhoughton$ javac -d . Long_1.java
hhoughton:java-long-names hhoughton$ scala-launch 2.12.7 -Xmax-classfile-name 72
Welcome to Scala 2.12.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_161).
Type in expressions for evaluation. Or try :help.

scala> :load Test_2.scala
Loading Test_2.scala...
import p._
defined object Test

scala> Test.main(null)
java.lang.NoClassDefFoundError: p/Long_1$ABCDE$$$$445a495554f1946eae40205dfa159580$$$$QRSTUVWXYZ_1
  at Test$.delayedEndpoint$$line4$$read$Test$1(Test_2.scala:17)
  at Test$delayedInit$body.apply(Test_2.scala:14)
  at scala.Function0.apply$mcV$sp(Function0.scala:34)
```

Reported by @edmondo1984 on [gitter](https://gitter.im/scala/scala?at=5bfd79fbcfa682348d92c663)

**Comment by edmondo1984** [comment]
Is there any available work around at the moment?

**Comment by lrytz** [comment]
We should probably remove that compiler flag in its current form. https://groups.google.com/d/msg/scala-internals/hNWuwWBJCOg/CrvPhnqJVaMJ

**Comment by SethTisue** [comment]
> We should probably remove that compiler flag in its current form 

https://github.com/scala/scala/pull/7497
