### ISSUE TITLE
AbstractMethodError with lambdas

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11355]
``` scala
trait A[T] { def apply(x: T): T }
trait B extends A[Int] { def apply(x: Int): Int }

object Test {
  def f: B = (x: Int) => x + 1
  def g: A[Int] = f

  def main(args: Array[String]): Unit = {
    println(f(10))
    println(g(10))
  }
}
```

```
$ qsc Test.scala
$ qs Test
11
java.lang.AbstractMethodError: Test$$$Lambda$115/1705929636.apply(Ljava/lang/Object;)Ljava/lang/Object;
```

**Comment by lrytz** [comment]
On current 2.13.18

```
Exception in thread "main" java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:187)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:310)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:250)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:240)
	at Test$.f(t11355.scala:5)
	at Test$.main(t11355.scala:9)
	at Test.main(t11355.scala)
Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for dynamic parameter 0: int is not a subtype of class java.lang.Object
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.checkDescriptor(AbstractValidatingLambdaMetafactory.java:324)
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:312)
	at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:545)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:143)
	... 6 more
```

It doesn't crash in Scala 3.
