### ISSUE TITLE
Unpickle error reading try catch statement in annotation.

### ISSUE THREAD

**Issue by Prithvirajbilla** [scala/bug#11371]
scala version: 2.12.8
Java version: 1.8.0_112

The following code reproduces the issue. Unpickler is not able to read try catch statement and returns a runtime exception.

```
scala> class Superhero(power:String) extends scala.annotation.StaticAnnotation
defined class Superhero

scala> @Superhero(power = { try { "Awesome"} catch { case default => "NotAwesome" }})
     | class Spiderman {}
       @Superhero(power = { try { "Awesome"} catch { case default => "NotAwesome" }})
                                                          ^
java.lang.RuntimeException: malformed Scala signature of $read at 320; expected a case def (<empty>)
	at scala.reflect.internal.pickling.UnPickler$Scan.errorBadSignature(UnPickler.scala:699)
	at scala.reflect.internal.pickling.UnPickler$Scan.readCaseDefRef(UnPickler.scala:671)
	at scala.reflect.internal.pickling.UnPickler$Scan.caseRef$1(UnPickler.scala:537)
......
```

**Comment by SethTisue** [comment]
does the language spec restrict what kind of code can appear in this position?

**Comment by som-snytt** [comment]
This happens during REPL reflection; compilation succeeds.
```
scala 2.13.0-M5> @deprecated(try "", "") class C
                             ^
                 warning: A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.
java.lang.ClassCastException: scala.reflect.internal.Types$UniqueThisType cannot be cast to scala.reflect.internal.Trees$Tree
```

```
scala 2.12.6> @deprecated(try "", "") class C
<console>:11: warning: A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.
              @deprecated(try "", "") class C
                          ^
java.lang.ClassCastException: scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8 cannot be cast to scala.reflect.internal.Trees$Tree
```
