### ISSUE TITLE
Compiling with JDK 12 causes runtime crash under JDK 11

### ISSUE THREAD

**Issue by max-kammerer** [scala/bug#11398]
Next code fails at runtime if compiled against JDK 12 and runned with lower version of JDK (but work if compiled with JDK 11 and below)
```
object Foo {
  def main(args: Array[String]): Unit = {
    new Foo(classOf[Foo])
  }
}

class Foo(val clazz: Class[_]) {
  private var result = if (clazz.getEnclosingConstructor == null) clazz
    else "123"
}
```
Error: Unable to initialize main class Foo
Caused by: java.lang.NoClassDefFoundError: java/lang/constant/Constable

'Constable' was added in JDK 12

**Comment by Jasper-M** [comment]
Isn't it expected that code (be it Java, Scala, ...) compiled against JDK X only works on JDK X and higher, not lower?

**Comment by SethTisue** [comment]
I'm curious how `Constable` even enters into this at all, and also curious whether the same error would occur with equivalent Java code.

**Comment by smarter** [comment]
java.lang.Class now extends Constable, but that doesn't explain where it's popping up here. @max-kammerer can you post the output of `javap -p -v Foo` and `javap -p -v 'Foo$'` when compilng with jdk 11 and with jdk 12 ?

**Comment by max-kammerer** [comment]
1. String and boxed primitives also extends Constable in JDK 12. 
Problem in changed field/accessors types:
```
class Foo(val cond: Boolean) {
  //private Ljava/lang/constant/Constable; result
  //private result()Ljava/lang/constant/Constable;
  private var result = if (cond) "123" else Double.box(123)
}
```
similar with function return type
``` 
  //public foo(Z)Ljava/lang/constant/Constable;
  def foo(cond: Boolean) = {
    val result = if (cond) Double.box(123) else "123"
    result
  }
```

2. Next example doesn't cause any error in old JDKs, but Constable is appeared in LocalVariableTable
```
object Foo {

  def main(args: Array[String]): Unit = {
    foo(true)
  }

  def foo(cond: Boolean): Any = {
    val result = if (cond) Double.box(123) else "123"
    result
  //LOCALVARIABLE result Ljava/lang/constant/Constable; L2 L4 2
  }
}
```

Javac generated different types for local variables and frames depending on '-target' option

**Comment by SethTisue** [comment]
aha, now it makes sense, thanks!

does `-release 11` make the problem go away?

**Comment by max-kammerer** [comment]
I can't use -release option on JDK 12 (works with JDK 11) cause:
```
Error:scalac: Error: object java.lang.Object in compiler mirror not found.
scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:24)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:25)
	at scala.reflect.internal.Mirrors$RootsBase.$anonfun$getModuleOrClass$4(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:52)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:52)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:73)
	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:108)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:111)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:294)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:294)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1463)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1194)
	at xsbt.ZincCompiler$ZincRun.<init>(CallbackGlobal.scala:63)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:128)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:40)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:35)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$4(ScalaBuilder.scala:49)
	at scala.util.Either.map(Either.scala:350)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$3(ScalaBuilder.scala:43)
	at scala.util.Either.flatMap(Either.scala:338)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$2(ScalaBuilder.scala:42)
	at scala.util.Either.flatMap(Either.scala:338)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.compile(ScalaBuilder.scala:40)
	at org.jetbrains.jps.incremental.scala.IdeaIncrementalBuilder.build(IdeaIncrementalBuilder.scala:89)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1327)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1007)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1074)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:968)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:797)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:375)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:178)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:302)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:135)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:229)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by SethTisue** [comment]
the failure for `-release` to work is now #11403

**Comment by SethTisue** [comment]
(closed because the compiler is behaving correctly here. it's expected that `-release 11` or `-release 8` would be needed here)
