### ISSUE TITLE
failed to build project on scala-sdk-2.12.8 & jdk 1.8.0_20

### ISSUE THREAD

**Issue by mataeil** [scala/bug#11404]
failed to build project on scala-sdk-2.12.8 & jdk 1.8.0_20
if i change java-vserion to 1.8.0_201, It's well working.

```
Error:scalac: Error: Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab6 0064 04a0 001e b200 c1b2 00c6 04bd
    0x0000010: 0002 5903 2a53 c000 c8b6 00cc b600 d0c0
    0x0000020: 00d2 b02a b600 38b8 0042 3c1b 04a4 0156
    0x0000030: 1b05 6c3d 2a1b 056c 2ab6 0038 b700 d43e
    0x0000040: 2ab6 0038 021d 787e 3604 2ab6 0038 0210
    0x0000050: 201d 647c 7e36 05bb 0019 59b2 00c6 2ab6
    0x0000060: 003a c000 c8b6 00d8 b700 db1c b600 df3a
    0x0000070: 0619 06c6 001a 1906 b600 e3c0 008b 3a07
    0x0000080: 1906 b600 e6c0 008b 3a08 a700 0dbb 00e8
    0x0000090: 5919 06b7 00eb bf19 073a 0919 083a 0abb
    0x00000a0: 0002 5915 0419 09bb 0019 59b2 00c6 1909
    0x00000b0: c000 c8b6 00d8 b700 db03 b800 f13a 0e3a
    0x00000c0: 0d03 190d b900 f501 0019 0e3a 1136 1036
    0x00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d
    0x00000e0: 150f b900 f802 00c0 0005 3a17 1911 1917
    0x00000f0: b800 fc3a 1136 1036 0fa7 ffd8 1911 b801
    0x0000100: 00b7 0069 3a0b bb00 0259 1505 190a bb00
    0x0000110: 1959 b200 c619 0ac0 00c8 b600 d8b7 00db
    0x0000120: 03b8 00f1 3a13 3a12 0319 12b9 00f5 0100
    0x0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715
    0x0000140: 1404 6015 1519 1215 14b9 00f8 0200 c000
    0x0000150: 053a 1819 1619 18b8 0103 3a16 3615 3614
    0x0000160: a7ff d819 16b8 0100 b700 693a 0cbb 0105
    0x0000170: 5919 0bbb 0105 5919 0cb2 010a b701 0db7
    0x0000180: 010d b02a b600 3a03 32b6 010f b0       
  Stackmap Table:
    same_frame(@35)
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118]},{})
    append_frame(@151,Object[#139],Object[#139])
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Top,Top,Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#139]})
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Top,Top,Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#139]})
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Object[#2],Top,Object[#25],Object[#62],Integer,Integer,Object[#116],Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#139]})
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Object[#2],Top,Object[#25],Object[#62],Integer,Integer,Object[#116],Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#139]})
    full_frame(@387,{Object[#2],Integer},{})
java.lang.VerifyError: Uninitialized object exists on backward branch 209
Exception Details:
  Location:
    scala/collection/immutable/HashMap$HashTrieMap.split()Lscala/collection/immutable/Seq; @249: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ab6 0064 04a0 001e b200 c1b2 00c6 04bd
    0x0000010: 0002 5903 2a53 c000 c8b6 00cc b600 d0c0
    0x0000020: 00d2 b02a b600 38b8 0042 3c1b 04a4 0156
    0x0000030: 1b05 6c3d 2a1b 056c 2ab6 0038 b700 d43e
    0x0000040: 2ab6 0038 021d 787e 3604 2ab6 0038 0210
    0x0000050: 201d 647c 7e36 05bb 0019 59b2 00c6 2ab6
    0x0000060: 003a c000 c8b6 00d8 b700 db1c b600 df3a
    0x0000070: 0619 06c6 001a 1906 b600 e3c0 008b 3a07
    0x0000080: 1906 b600 e6c0 008b 3a08 a700 0dbb 00e8
    0x0000090: 5919 06b7 00eb bf19 073a 0919 083a 0abb
    0x00000a0: 0002 5915 0419 09bb 0019 59b2 00c6 1909
    0x00000b0: c000 c8b6 00d8 b700 db03 b800 f13a 0e3a
    0x00000c0: 0d03 190d b900 f501 0019 0e3a 1136 1036
    0x00000d0: 0f15 0f15 109f 0027 150f 0460 1510 190d
    0x00000e0: 150f b900 f802 00c0 0005 3a17 1911 1917
    0x00000f0: b800 fc3a 1136 1036 0fa7 ffd8 1911 b801
    0x0000100: 00b7 0069 3a0b bb00 0259 1505 190a bb00
    0x0000110: 1959 b200 c619 0ac0 00c8 b600 d8b7 00db
    0x0000120: 03b8 00f1 3a13 3a12 0319 12b9 00f5 0100
    0x0000130: 1913 3a16 3615 3614 1514 1515 9f00 2715
    0x0000140: 1404 6015 1519 1215 14b9 00f8 0200 c000
    0x0000150: 053a 1819 1619 18b8 0103 3a16 3615 3614
    0x0000160: a7ff d819 16b8 0100 b700 693a 0cbb 0105
    0x0000170: 5919 0bbb 0105 5919 0cb2 010a b701 0db7
    0x0000180: 010d b02a b600 3a03 32b6 010f b0       
  Stackmap Table:
    same_frame(@35)
    full_frame(@141,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118]},{})
    append_frame(@151,Object[#139],Object[#139])
    full_frame(@209,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Top,Top,Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#139]})
    full_frame(@252,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Top,Top,Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#159],Uninitialized[#159],Integer,Object[#139]})
    full_frame(@312,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Object[#2],Top,Object[#25],Object[#62],Integer,Integer,Object[#116],Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#139]})
    full_frame(@355,{Object[#2],Integer,Integer,Integer,Integer,Integer,Object[#118],Object[#139],Object[#139],Object[#139],Object[#139],Object[#2],Top,Object[#25],Object[#62],Integer,Integer,Object[#116],Object[#25],Object[#62],Integer,Integer,Object[#116]},{Uninitialized[#262],Uninitialized[#262],Integer,Object[#139]})
    full_frame(@387,{Object[#2],Integer},{})
	at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:185)
	at scala.collection.immutable.HashMap$.scala$collection$immutable$HashMap$$makeHashTrieMap(HashMap.scala:189)
	at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:220)
	at scala.collection.immutable.HashMap.updated(HashMap.scala:62)
	at scala.collection.immutable.Map$Map4.updated(Map.scala:227)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:228)
	at scala.collection.immutable.Map$Map4.$plus(Map.scala:200)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:32)
	at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:28)
	at scala.collection.generic.Growable.$anonfun$$plus$plus$eq$1(Growable.scala:62)
	at scala.collection.generic.Growable$$Lambda$233/1266486017.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.MapBuilder.$plus$plus$eq(MapBuilder.scala:28)
	at scala.collection.generic.GenMapFactory.apply(GenMapFactory.scala:51)
	at scala.sys.package$.env(package.scala:64)
	at scala.tools.nsc.settings.ScalaSettings.defaultClasspath(ScalaSettings.scala:39)
	at scala.tools.nsc.settings.ScalaSettings.defaultClasspath$(ScalaSettings.scala:39)
	at scala.tools.nsc.settings.MutableSettings.defaultClasspath(MutableSettings.scala:27)
	at scala.tools.nsc.settings.ScalaSettings.$init$(ScalaSettings.scala:66)
	at scala.tools.nsc.settings.MutableSettings.<init>(MutableSettings.scala:28)
	at scala.tools.nsc.Settings.<init>(Settings.scala:19)
	at xsbt.CachedCompiler0.<init>(CompilerInterface.scala:63)
	at xsbt.CompilerInterface.newCompiler(CompilerInterface.scala:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:134)
	at sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:121)
	at sbt.internal.inc.FreshCompilerCache.apply(CompilerCache.scala:78)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:88)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:40)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:30)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$3(ScalaBuilder.scala:45)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$$$Lambda$174/558288940.apply(Unknown Source)
	at scala.util.Either.map(Either.scala:350)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$2(ScalaBuilder.scala:39)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$$$Lambda$136/32455393.apply(Unknown Source)
	at scala.util.Either.flatMap(Either.scala:338)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$1(ScalaBuilder.scala:38)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$$$Lambda$121/2002434921.apply(Unknown Source)
	at scala.util.Either.flatMap(Either.scala:338)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.compile(ScalaBuilder.scala:37)
	at org.jetbrains.jps.incremental.scala.IdeaIncrementalBuilder.build(IdeaIncrementalBuilder.scala:89)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1317)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:993)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1065)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:956)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:788)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:377)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:184)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:309)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:137)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:235)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$$Lambda$24/1526086616.run(Unknown Source)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$$Lambda$4/1629687658.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by SethTisue** [comment]
seems like Oracle's bug, not ours, if using a newer JVM fixes it.

thanks for the report — knowing the solution should help future searchers

**Comment by mataeil** [comment]
thanks for your confirmation. 👍
