### ISSUE TITLE
PriorityQueue throws NPE when on mapInPlace on empty queue

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11439]
```
Welcome to Scala 2.13.0-20190319-203750-5e547be (OpenJDK 64-Bit Server VM, Java 1.8.0_191).
Type in expressions for evaluation. Or try :help.

scala> collection.mutable.PriorityQueue.empty[String].mapInPlace(_.toUpperCase)
java.lang.NullPointerException
  at .$anonfun$res0$1(<console>:1)
  at scala.collection.mutable.IndexedSeqOps.mapInPlace(IndexedSeq.scala:42)
  at scala.collection.mutable.IndexedSeqOps.mapInPlace$(IndexedSeq.scala:39)
  at scala.collection.mutable.ArrayBuffer.mapInPlace(ArrayBuffer.scala:40)
  at scala.collection.mutable.PriorityQueue.mapInPlace(PriorityQueue.scala:94)
  ... 37 elided
```

**Comment by adriaanm** [comment]
I snuck in a fix in my other PR. This is some weird stuff, so I'm not sure it's correct, but it can't be worse than the status quo.
