### ISSUE TITLE
ListBuffer patchInPlace throws an exception in no-work case

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11438]
```
Welcome to Scala 2.13.0-20190319-203750-5e547be (OpenJDK 64-Bit Server VM, Java 1.8.0_191).
Type in expressions for evaluation. Or try :help.

scala> collection.mutable.ListBuffer.empty[Int].patch(0, Nil, -1)
res0: scala.collection.mutable.ListBuffer[Int] = ListBuffer()

scala> collection.mutable.ListBuffer.empty[Int].patchInPlace(0, Nil, -1)
java.lang.NullPointerException
  at scala.collection.mutable.ListBuffer.insertAfter(ListBuffer.scala:230)
  at scala.collection.mutable.ListBuffer.patchInPlace(ListBuffer.scala:332)
  ... 37 elided
```

All other collections agree with `patch`--this (no-op) operation is totally fine.

**Comment by SethTisue** [comment]
can we have a volunteer to attempt a fix?
