### ISSUE TITLE
BUG in BatchingExecutor.Batch: parentBlockContext is null

### ISSUE THREAD

**Issue by eed3si9n** [scala/bug#11450]
## steps

- clone https://github.com/scala/scala-parallel-collections/tree/fcf50933c0873163647d9ae9951682005595bf3d
- ++2.13.0-pre-bd28253!
- junit/test

## problems

```
sbt:scala-parallel-collections> junit/test
[info] Test run started
[info] Test scala.collection.NewBuilderTest.mapPreservesCollectionType started
[error] Test scala.collection.NewBuilderTest.mapPreservesCollectionType failed: java.lang.IllegalStateException: BUG in BatchingExecutor.Batch: parentBlockContext is null, took 0.548 sec
[error]     at scala.concurrent.BatchingExecutorStatics$MissingParentBlockContext$.blockOn(BatchingExecutor.scala:38)
[error]     at scala.concurrent.BatchingExecutor$AsyncBatch.blockOn(BatchingExecutor.scala:205)
[error]     at scala.concurrent.package$.blocking(package.scala:124)
[error]     at scala.concurrent.Await$.result(package.scala:200)
[error]     at scala.collection.parallel.FutureTasks.$anonfun$execute$2(Tasks.scala:365)
[error]     at scala.collection.parallel.FutureTasks.executeAndWaitResult(Tasks.scala:371)
[error]     at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult(Tasks.scala:407)
[error]     at scala.collection.parallel.ExecutionContextTasks.executeAndWaitResult$(Tasks.scala:407)
[error]     at scala.collection.parallel.ExecutionContextTaskSupport.executeAndWaitResult(TaskSupport.scala:75)
[error]     at scala.collection.parallel.immutable.HashSetCombiner.result(ParHashSet.scala:160)
[error]     at scala.collection.parallel.immutable.HashSetCombiner.result(ParHashSet.scala:137)
[error]     at scala.collection.parallel.Combiner.resultWithTaskSupport(Combiner.scala:90)
[error]     at scala.collection.parallel.Combiner.resultWithTaskSupport$(Combiner.scala:89)
[error]     at scala.collection.parallel.BucketCombiner.resultWithTaskSupport(package.scala:167)
[error]     at scala.collection.parallel.ParIterableLike.$anonfun$map$2(ParIterableLike.scala:490)
[error]     at scala.collection.parallel.ParIterableLike$$anon$1$$anon$2.map(ParIterableLike.scala:304)
[error]     at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:933)
[error]     at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:52)
[error]     at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error]     at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
[error]     at scala.collection.parallel.Task.tryLeaf(Tasks.scala:55)
[error]     at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:49)
[error]     at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:927)
[error]     at scala.collection.parallel.FutureTasks.$anonfun$exec$5(Tasks.scala:351)
[error]     at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:662)
[error]     at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
[error]     at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
[error]     at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
[error]     at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
[error]     at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
[error]     at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
[error]     at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[error]     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error]     at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]     at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[info] Test run finished: 1 failed, 0 ignored, 1 total, 0.555s
```

## expectation

No bugs?

**Comment by retronym** [comment]
This reproduces the bug:

```
scala.collection.parallel.immutable.ParSet(1).map(x => x)
```

**Comment by viktorklang** [comment]
@eed3si9n @retronym Try commenting out this line https://github.com/scala/scala/blob/2.13.x/src/library/scala/concurrent/BatchingExecutor.scala#L192 and see if you can reproduce using `scala.collection.parallel.immutable.ParSet(1).map(x => x)`

**Comment by retronym** [comment]
@viktorklang That's the line I've been staring at. Me debug session suggests that same `AsyncBatch` is exeuctuing things in `blockOn` twice. The first `cloneAndClear` corrupts the `parentBlockContext` for the second turn.

What's the intent of this part of the code?

**Comment by viktorklang** [comment]
```
    override final def blockOn[T](thunk: => T)(implicit permission: CanAwait): T = {
      // If we know there will be blocking, we don't want to keep tasks queued up because it could deadlock.
      if(this.size > 0)
        submitForExecution(cloneAndClear()) // If this throws then we have bigger problems

      parentBlockContext.blockOn(thunk) // Now delegate the blocking to the previous BC
    }
```

**Comment by retronym** [comment]
The simplified version fixes this problem. I wasn't able to extract a minimal test case for it yet, but I've submitted the code change as https://github.com/scala/scala/pull/7940

**Comment by viktorklang** [comment]
Great work, thanks @retronym!

**Comment by SethTisue** [comment]
2.13 community build shows the same error for Monix, too:

```
[monix] monix.execution.atomic.ConcurrentAtomicNumberNumberAnyNoPaddingJava7Suite
[monix] - should perform concurrent compareAndSet
[monix] - should perform concurrent getAndSet
[monix] - should perform concurrent increment *** FAILED ***
[monix]   IllegalStateException: BUG in BatchingExecutor.Batch: parentBlockContext is null
[monix]     scala.concurrent.BatchingExecutorStatics$MissingParentBlockContext$.blockOn(BatchingExecutor.scala:38)
[monix]     scala.concurrent.BatchingExecutor$AsyncBatch.blockOn(BatchingExecutor.scala:205)
[monix]     scala.concurrent.Await$.result(package.scala:124)
[monix]     monix.execution.atomic.ConcurrentAtomicNumberSuite.$anonfun$new$11(ConcurrentAtomicNumberSuite.scala:68)
[monix]     minitest.SimpleTestSuite.$anonfun$test$1(SimpleTestSuite.scala:27)
[monix]     minitest.api.TestSpec$.$anonfun$sync$1(TestSpec.scala:51)
[monix]     minitest.api.TestSpec.apply(TestSpec.scala:27)
[monix]     minitest.api.Properties.$anonfun$iterator$2(Properties.scala:38)
[monix]     minitest.api.TestSpec.apply(TestSpec.scala:27)
[monix]     minitest.runner.Task.loop$1(Task.scala:56)
[monix]     minitest.runner.Task.$anonfun$execute$1(Task.scala:63)
[monix]     scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
[monix]     scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
[monix]     scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
[monix]     scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
[monix]     scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
[monix]     scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
[monix]     java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[monix]     java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[monix]     java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[monix]     java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[monix]     java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
