### ISSUE TITLE
-Ybrowse does not pause thread in scala 2.13.0

### ISSUE THREAD

**Issue by vincentdehaan** [scala/bug#11568]
When displaying the tree browser, the main thread should be paused to make sure that the syntax tree does not change while the user is browsing it.

Expected behavior (comments marked with `#`):
```
./scala-2.12.8/bin/scala -Ybrowse:parser scala/HelloWorld.scala
#tree browser displays parse tree at parser phase
#end user closes the tree browser
Hello world!
```

Actual behavior:
```
./scala-2.13.0/bin/scala -Ybrowse:parser scala/HelloWorld.scala
Hello world!
#tree browser displays parse tree at a later phase
#end user closes the tree browser
Exception in thread "AWT-EventQueue-0" java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:151)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1261)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at scala.tools.nsc.ast.TreeBrowsers$BrowserFrame$$anon$1.windowClosed(TreeBrowsers.scala:185)
	at java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java:359)
	at java.awt.Window.processWindowEvent(Window.java:2057)
	at javax.swing.JFrame.processWindowEvent(JFrame.java:305)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by som-snytt** [comment]
This has been broken, so it's surprising [no one noticed](https://twitter.com/TwoBuffy/status/1139894647973539840).
