### ISSUE TITLE
JAR files whose path contains a space cannot be added to the REPL classpath

### ISSUE THREAD

**Issue by dbdahl** [scala/bug#11565]
JAR files whose path contains a space cannot be added to the REPL classpath:

`$intp.addUrlsToClassPath(new java.io.File("directory with spaces/hello.jar").toURI.toURL)`

> Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 11.0.3).
> Type in expressions for evaluation. Or try :help.
> 
> scala> $intp.addUrlsToClassPath(new java.io.File("directory with space/hello.jar").toURI.toURL)
> java.lang.NullPointerException
>   at scala.tools.nsc.Global.assoc$1(Global.scala:877)
>   at scala.tools.nsc.Global.$anonfun$invalidateClassPathEntries$2(Global.scala:892)
>   at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
>   at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
>   at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:34)
>   at scala.tools.nsc.Global.invalidateClassPathEntries(Global.scala:892)
>   at scala.tools.nsc.Global.extendCompilerClassPath(Global.scala:827)
>   at scala.tools.nsc.interpreter.IMain.addUrlsToClassPath(IMain.scala:241)
>   ... 28 elided
> 

In contrast, the JAR is successfully added if its path contains no spaces:

`$intp.addUrlsToClassPath(new java.io.File("directoryWithoutSpaces/hello.jar").toURI.toURL)`

Note that this issue is also manifest using REPL's ":require" feature.  I have reproduced this bug in both Scala 2.13.0 & 2.12.8 and both Ubuntu 18.04 and Windows 10.

This seems to be related to #9405 but that report deals with directories, whereas this report deals with spaces in paths.

By way of context, this bug is affecting my [rscala](https://github.com/dbdahl/rscala) package, which allows R packages to be written in Scala.  In that context, users of may have little control over whether or not a JAR file embedded within a package has a space in its full path.  My current work-around is to copy the JAR to a location without a space and load it from there.

I'd love to have the bug fixed but don't think I have the skills to attack it myself.  Thanks!

**Comment by som-snytt** [comment]
```
➜  snips scala
Welcome to Scala 2.13.3 (OpenJDK 64-Bit Server VM, Java 1.8.0_232).
Type in expressions for evaluation. Or try :help.

scala> :require mine only
java.lang.NullPointerException
	at scala.tools.nsc.Global.assoc$1(Global.scala:887)
	at scala.tools.nsc.Global.$anonfun$invalidateClassPathEntries$2(Global.scala:902)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
	at scala.collection.immutable.ArraySeq.flatMap(ArraySeq.scala:35)
	at scala.tools.nsc.Global.invalidateClassPathEntries(Global.scala:902)
	at scala.tools.nsc.Global.extendCompilerClassPath(Global.scala:837)
	at scala.tools.nsc.interpreter.IMain.addUrlsToClassPath(IMain.scala:245)
	at scala.tools.nsc.interpreter.shell.ILoop.require(ILoop.scala:716)
	at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$standardCommands$12(ILoop.scala:205)
	at scala.tools.nsc.interpreter.shell.LoopCommands$LineCmd.apply(LoopCommands.scala:160)
	at scala.tools.nsc.interpreter.shell.LoopCommands.colonCommand(LoopCommands.scala:122)
	at scala.tools.nsc.interpreter.shell.LoopCommands.colonCommand$(LoopCommands.scala:120)
	at scala.tools.nsc.interpreter.shell.ILoop.colonCommand(ILoop.scala:45)
	at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:431)
	at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:440)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:458)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:968)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]n
```
but
```
➜  snips scala -classpath 'mine only'
Welcome to Scala 2.13.3 (OpenJDK 64-Bit Server VM, Java 1.8.0_232).
Type in expressions for evaluation. Or try :help.

scala> new myp.MyC
val res0: myp.MyC = myp.MyC@5f80fa43
```
