### ISSUE TITLE
scala 2.13.0 compiler crashes with no-symbol does not have a type constructor

### ISSUE THREAD

**Issue by seraphr** [scala/bug#11579]
## Scala version

```
$ scalac -version
Scala compiler version 2.13.0 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
```

## Java version

```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

and

```
$ java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```

## code

```scala
package foo

object Foo {
  import scala.collection.generic.IsIterable
  import scala.language.implicitConversions

  class Ops[I] {
    def method: Unit = ()
  }

  implicit def ToOps[Repr, L, R](aCol: Repr)(implicit isIterable: IsIterable[Repr]{type A = (L, R)}): Ops[isIterable.type] = new Ops[isIterable.type]

  List(1 -> 2).method
}
```

## error

```
$ scalac Foo.scala 
error:
  no-symbol does not have a type constructor (this may indicate scalac cannot find fundamental classes)
     while compiling: Foo.scala
        during phase: typer
     library version: version 2.13.0
    compiler version: version 2.13.0
  reconstructed args:

  last tree to typer: Ident(<argument>)
       tree position: line 13 of Foo.scala
            tree tpe: List[(Int, Int)]
              symbol: <none>
   symbol definition: <none> (a NoSymbol)
      symbol package: <none>
       symbol owners:
           call site: object Foo in package foo in package foo

== Source file context for tree position ==

    10
    11   implicit def ToOps[Repr, L, R](aCol: Repr)(implicit isIterable: IsIterable[Repr]{type A = (L, R)}): Ops[isIterable.type] = new Ops[isIterable.type]
    12
    13   List(1 -> 2).method
    14 }
    15
error: scala.reflect.internal.FatalError:
  no-symbol does not have a type constructor (this may indicate scalac cannot find fundamental classes)
     while compiling: Foo.scala
        during phase: typer
     library version: version 2.13.0
    compiler version: version 2.13.0
  reconstructed args:

  last tree to typer: Ident(<argument>)
       tree position: line 13 of Foo.scala
            tree tpe: List[(Int, Int)]
              symbol: <none>
   symbol definition: <none> (a NoSymbol)
      symbol package: <none>
       symbol owners:
           call site: object Foo in package foo in package foo

== Source file context for tree position ==

    10
    11   implicit def ToOps[Repr, L, R](aCol: Repr)(implicit isIterable: IsIterable[Repr]{type A = (L, R)}): Ops[isIterable.type] = new Ops[isIterable.type]
    12
    13   List(1 -> 2).method
    14 }
    15
	at scala.reflect.internal.Reporting.abort(Reporting.scala:68)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:64)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.reflect.internal.Symbols$Symbol.typeConstructor(Symbols.scala:1484)
	at scala.reflect.internal.Types$$anon$2.apply(Types.scala:1723)
	at scala.reflect.internal.Types$$anon$2.apply(Types.scala:1720)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2355)
	at scala.reflect.internal.Types$$anon$2.apply(Types.scala:1726)
	at scala.reflect.internal.Types$$anon$2.apply(Types.scala:1720)
	at scala.reflect.internal.Symbols$Symbol.modifyInfo(Symbols.scala:1565)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:141)
	at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:127)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType(Types.scala:1730)
	at scala.reflect.internal.Types.defineBaseTypeSeqOfCompoundType$(Types.scala:1709)
	at scala.reflect.internal.SymbolTable.defineBaseTypeSeqOfCompoundType(SymbolTable.scala:28)
	at scala.reflect.internal.Types$CompoundType.baseTypeSeq(Types.scala:1617)
	at scala.reflect.internal.Types$CompoundType.baseTypeSeqDepth(Types.scala:1625)
	at scala.reflect.internal.Types$NullaryMethodType.baseTypeSeqDepth(Types.scala:2914)
	at scala.reflect.internal.Types.$anonfun$baseTypeSeqDepth$1(Types.scala:4427)
	at scala.reflect.internal.Depth$.maximumBy(Depth.scala:59)
	at scala.reflect.internal.Types.baseTypeSeqDepth(Types.scala:4427)
	at scala.reflect.internal.Types.lubDepth(Types.scala:4411)
	at scala.reflect.internal.Types.lubDepth$(Types.scala:4409)
	at scala.reflect.internal.SymbolTable.lubDepth(SymbolTable.scala:28)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$matchesPtInst(Implicits.scala:694)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1128)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1164)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1221)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1646)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
	at scala.tools.nsc.Global$$anon$5.inferImplicit(Global.scala:482)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
	at scala.tools.nsc.Global$$anon$5.inferImplicitFor(Global.scala:482)
	at scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:271)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:849)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:801)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:621)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1129)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1164)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1221)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1620)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
	at scala.tools.nsc.Global$$anon$5.inferImplicit(Global.scala:482)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitView(Implicits.scala:51)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitView$(Implicits.scala:50)
	at scala.tools.nsc.Global$$anon$5.inferImplicitView(Global.scala:482)
	at scala.tools.nsc.typechecker.Typers$Typer.inferView(Typers.scala:337)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToMember(Typers.scala:1339)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adaptToMemberWithArgs$7(Typers.scala:1389)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:715)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToMemberWithArgs(Typers.scala:1389)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:5115)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5266)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5822)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2050)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1925)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5776)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5931)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3396)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5475)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5778)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5867)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1510)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1494)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1615)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:48)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:30)
	at scala.tools.nsc.Driver.process(Driver.scala:68)
	at scala.tools.nsc.Driver.main(Driver.scala:82)
	at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by joroKr21** [comment]
Looks like regression from this line:
https://github.com/scala/scala/pull/7376/files#diff-ecaa4198a04261cd0e00a708b695eafbR1486

The origin of a `TypeVar` could be a `WildcardType` (constructed by `wildcardToTypeVarMap`).
The symbol of `WildcardType` is `NoSymbol` and calling `NoSymbol.typeConstructor` aborts.

cc @adriaanm
