### ISSUE TITLE
BigDecimal and IterableOnce.sum

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#11592]
There is second problem with `sum`:

```
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import java.math.MathContext

object BigDecimalTest {
  def main(args: Array[String]): Unit = {
    test()
  }

  def test(): Unit = {

     val bds = List(
     scala.math.BigDecimal("1000000000000000000000000.1", MathContext.UNLIMITED),
     scala.math.BigDecimal("9.0000000000000000000000009", MathContext.UNLIMITED))

     assert(bds.sum == scala.math.BigDecimal("1000000000000000000000009.1000000000000000000000009", MathContext.UNLIMITED))

     // Below line works with scala 2.13.0
     //assert(bds.foldLeft(BigDecimal(0, MathContext.UNLIMITED))(_ + _) == scala.math.BigDecimal("1000000000000000000000009.1000000000000000000000009", MathContext.UNLIMITED))
     println("BigDecimal works")
  }
}

// Exiting paste mode, now interpreting.

import java.math.MathContext
defined object BigDecimalTest

scala> BigDecimalTest.test
java.lang.AssertionError: assertion failed
  at scala.Predef$.assert(Predef.scala:267)
  at BigDecimalTest$.test(<console>:14)
  ... 28 elided
```
Which is probably caused by wrong math context with `num.zero` in here: https://github.com/scala/scala/blob/6b4d32c3f518d21a798e8d3cf4a8c35866afa8e2/src/library/scala/collection/IterableOnce.scala#L915

I can't stress enough that this change with 2.13 is highly surprising, even though orinal implementation with 2.11 and 2.12 has been broken.

P.S. Above code works with 2.12.8

_Originally posted by @35VLG84 in https://github.com/scala/bug/issues/11590#issuecomment-505613273_

**Comment by 35VLG84** [comment]
As @Ichoran pointed out in https://github.com/scala/bug/issues/11590#issuecomment-505644631 this applies also for `product`:

`product` is broken on 2.11.12, 2.12.8 and 2.13.0:

``` 
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> :paste
// Entering paste mode (ctrl-D to finish)

import java.math.MathContext

val bds = List(
   scala.math.BigDecimal("1000000000000000000000000.1", MathContext.UNLIMITED),
   scala.math.BigDecimal("9.00000000000000000000000091", MathContext.UNLIMITED))

val prod = bds.foldLeft(BigDecimal(1, MathContext.UNLIMITED))(_ * _)
assert(prod.toString == "9000000000000000000000001.810000000000000000000000091")

// Exiting paste mode, now interpreting.

import java.math.MathContext
bds: List[scala.math.BigDecimal] = List(1000000000000000000000000.1, 9.00000000000000000000000091)
prod: scala.math.BigDecimal = 9000000000000000000000001.810000000000000000000000091

scala> bds.product
res1: scala.math.BigDecimal = 9000000000000000000000001.810000000

scala> assert(prod == bds.product)
java.lang.AssertionError: assertion failed
  at scala.Predef$.assert(Predef.scala:267)
  ... 28 elided
```

**Comment by Ichoran** [comment]
For reference, my suggested fix is to use `reduceOption` rather than `foldLeft` to implement these.  (If someone doesn't like the overhead, then something like

```
val i = xs.iterator
if (!i.hasNext) num.one
else {
  var x = i.next
  while (i.hasNext) x = num.times(x, i.next)
  x
}
```

for IterableOnce, with maybe an override for efficiency in List and IndexedSeq.)
