### ISSUE TITLE
BigDecimal mod (`%`) behavior change in 2.13 vs 2.12 on certain multiples

### ISSUE THREAD

**Issue by changlinli** [scala/bug#11597]
I suspect the entire idea of mod for `BigDecimal`s is fraught with danger (at least in the current implementation) and has been across multiple Scala versions, so I'm not sure if this is a bug per se.

Nonetheless, it's surprising and any discussion of this might help others. So here goes:

Scala 2.12

```scala
Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> val x = BigDecimal(new java.math.BigDecimal("1E+136"))
x: scala.math.BigDecimal = 1E+136

scala> val upperLimit = BigDecimal(11)
upperLimit: scala.math.BigDecimal = 11

scala> x % upperLimit
res0: scala.math.BigDecimal = 1

scala> val upperLimit = BigDecimal(10)
upperLimit: scala.math.BigDecimal = 10

scala> x % upperLimit
res1: scala.math.BigDecimal = 0E+135
```

Scala 2.13
```scala
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> val x = BigDecimal(new java.math.BigDecimal("1E+136"))
x: scala.math.BigDecimal = 1E+136

scala> val upperLimit = BigDecimal(11)
upperLimit: scala.math.BigDecimal = 11

scala> x % upperLimit
java.lang.ArithmeticException: Division impossible
  at java.math.BigDecimal.divideToIntegralValue(BigDecimal.java:1857)
  at java.math.BigDecimal.divideAndRemainder(BigDecimal.java:1989)
  at java.math.BigDecimal.remainder(BigDecimal.java:1923)
  at scala.math.BigDecimal.remainder(BigDecimal.scala:525)
  at scala.math.BigDecimal.$percent(BigDecimal.scala:529)
  ... 36 elided

scala> val upperLimit = BigDecimal(10)
upperLimit: scala.math.BigDecimal = 10

scala> x % upperLimit
res1: scala.math.BigDecimal = 0E+135
```

**Comment by dwijnand** [comment]
See #11590, IIUC this is because of the MathContext, indeed this works like 2.12.8, on 2.13.0:

```
Welcome to Scala 2.13.0 (OpenJDK GraalVM CE 19.0.0, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> val x = BigDecimal("1E+136", java.math.MathContext.UNLIMITED)
x: scala.math.BigDecimal = 1E+136

scala> val upperLimit = BigDecimal(11, java.math.MathContext.UNLIMITED)
upperLimit: scala.math.BigDecimal = 11

scala> x % upperLimit
res0: scala.math.BigDecimal = 1
```

**Comment by SethTisue** [comment]
although I haven't studied this in detail, I'm inclined to assume this is covered by #11590 (see lengthy discussion there) unless someone wants to step forward and make the case otherwise

**Comment by som-snytt** [comment]
probably, but I had to recall a few months ago

https://github.com/scala/scala/pull/10230

where the underlying behavior breaks "naive" implementations of `sum`.

I don't have a similar example for `%`.
