### ISSUE TITLE
ArrayDeque::trimToSize throws OutOfBoundsException

### ISSUE THREAD

**Issue by isaacl** [scala/bug#11624]
My https://github.com/scala/scala/pull/8092 introduced a bug in ArrayDeque.

```scala
scala> ArrayDeque.range(0, 256).trimToSize()
java.lang.IndexOutOfBoundsException: 256 is out of bounds (min 0, max 255)
  at scala.collection.mutable.ArrayDeque.reset(ArrayDeque.scala:566)
  at scala.collection.mutable.ArrayDeque.scala$collection$mutable$ArrayDeque$$resize(ArrayDeque.scala:494)
  at scala.collection.mutable.ArrayDeque.trimToSize(ArrayDeque.scala:474)
  ... 36 elided
```

This is caused by an peculiar choice in trimToSize
```scala
def trimToSize(): Unit = resize(length - 1)
```

Instead we need functions like `shouldShrink` and `canShrink`, and trimToSize needs to call the latter. I'll put out a PR shortly to fix this.

cc @Ichoran

**Comment by NthPortal** [comment]
should it just be `resize(length)`?

**Comment by isaacl** [comment]
Hmm maybe
