### ISSUE TITLE
LinkedHashMap throw NoSuchElementException after adding specific character in key's mutable string field

### ISSUE THREAD

**Issue by Soya-Onishi** [scala/bug#11633]
LinkedHashMap throws an NoSuchElementException after I add "_" in case class's String type mutable field even if using same case class instance as key to get value.

below is example in interpreter
```
scala> import scala.collection.mutable.LinkedHash
scala> import scala.collection.mutable.LinkedHashMap
scala> case class A(var s: String)
scala> val a = A("a")
scala> val m = LinkedHashMap(a -> 1)
scala> a.s = "_a"
scala> m(a)
java.util.NoSuchElementException: key not found: A(_a)
  at scala.collection.MapOps.default(Map.scala:244)
  at scala.collection.MapOps.default$(Map.scala:243)
  at scala.collection.AbstractMap.default(Map.scala:375)
  at scala.collection.MapOps.apply(Map.scala:149)
  at scala.collection.MapOps.apply$(Map.scala:148)
  at scala.collection.AbstractMap.apply(Map.scala:375)
  ... 28 elided
```

I realized that this problem occurs only when I add `_` in the string field, and alphabet like `a` does not cause this. 

```
$ scala -version
Scala code runner version 2.13.0 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.19.04.2-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)
```

**Comment by Jasper-M** [comment]
That's probably expected since the hashcode of `a` changes when you mutate its field.

**Comment by lrytz** [comment]
See https://alvinalexander.com/source-code/scala/scala-be-careful-using-mutable-fields-var-equals-methods for example
