### ISSUE TITLE
Scala signature Parser has wrong version  expected: 5.0  found: 5.2 in Parser.class

### ISSUE THREAD

**Issue by k-bespalov** [scala/bug#11648]
I found similar issues but in another language version. Now it's 2.13 version.

```
 error while loading Client, class file '/Users/k.bespalov/.ivy2/cache/org.uaparser/uap-scala_2.13/jars/uap-scala_2.13-0.8.0.jar(org/uaparser/scala/Client.class)' is broken
[error] (class java.lang.RuntimeException/error reading Scala signature of Client.class: Scala signature Client has wrong version
[error]  expected: 5.0
[error]  found: 5.2 in Client.class)
java.io.IOException: Scala signature Parser has wrong version
 expected: 5.0
 found: 5.2 in Parser.class
        at scala.reflect.internal.pickling.UnPickler$Scan.checkVersion(UnPickler.scala:117)
        at scala.reflect.internal.pickling.UnPickler$Scan.<init>(UnPickler.scala:59)
        at scala.reflect.internal.pickling.UnPickler.unpickle(UnPickler.scala:40)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttribute$1(ClassfileParser.scala:887)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parseAttributes$19(ClassfileParser.scala:1113)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseAttributes(ClassfileParser.scala:1113)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:518)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.$anonfun$parse$1(ClassfileParser.scala:155)
        at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:126)
        at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:318)
        at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:220)
        at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.load(SymbolLoaders.scala:236)
        at scala.tools.nsc.typechecker.Typers$Typer.isStale(Typers.scala:506)
        at scala.tools.nsc.typechecker.Typers$Typer.reallyExists(Typers.scala:497)
        at scala.tools.nsc.typechecker.Typers$Typer.qualifies$1(Typers.scala:5072)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$63(Typers.scala:5098)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$63$adapted(Typers.scala:5098)
        at scala.reflect.internal.Symbols$Symbol.filter(Symbols.scala:1983)
        at scala.tools.nsc.typechecker.Contexts$Context.lookupSymbol(Contexts.scala:1135)
        at scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:5098)
        at scala.tools.nsc.typechecker.Typers$Typer.typedIdentOrWildcard$1(Typers.scala:5140)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5569)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5701)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5572)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5701)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5572)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4746)
        at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:693)
        at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4748)
        at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4776)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5571)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Typers$Typer.typedValDefImpl(Typers.scala:5833)
        at scala.tools.nsc.typechecker.Typers$Typer.typedValDef(Typers.scala:2036)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5535)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
        at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2468)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$98(Typers.scala:5546)
        at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:480)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5581)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:5833)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5536)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1999)
        at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1821)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5537)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5247)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5540)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:106)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:96)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1467)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1451)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1444)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1567)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
        at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
        at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
        at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
        at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
        at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
        at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
        at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
        at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
        at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
        at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
        at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
        at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
        at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
        at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
        at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
        at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
        at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
        at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
        at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
        at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1549)
        at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1523)
        at scala.Function1.$anonfun$compose$1(Function1.scala:44)
        at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:67)
        at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
        at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
        at sbt.Execute.work(Execute.scala:278)
        at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
        at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

Thank you for help in advance!

**Comment by k-bespalov** [comment]
`javap -verbose /Users/k.bespalov/.ivy2/cache/org.uaparser/uap-scala_2.13/jars/org/uaparser/scala/Client\$.class` shows

```
Classfile /Users/k.bespalov/.ivy2/cache/org.uaparser/uap-scala_2.13/jars/org/uaparser/scala/Client$.class
  Last modified Jun 23, 2019; size 2510 bytes
  MD5 checksum 1925c6a06ab6a916dd32dcd2a5de1414
  Compiled from "Client.scala"
public final class org.uaparser.scala.Client$ extends scala.runtime.AbstractFunction3<org.uaparser.scala.UserAgent, org.uaparser.scala.OS, org.uaparser.scala.Device, org.uaparser.scala.Client> implements java.io.Serializable
  minor version: 0
  major version: 52
```

**Comment by SethTisue** [comment]
I don't think that javap output is relevant here. 52 is the JVM bytecode version, not the Scala signature version.

how would I reproduce the problem on my own machine?

offhand, I would guess that you are mixing JARs compiled by different versions of Scala. to use 2.13, you must use only libraries compiled by 2.13.x (and that doesn't include 2.13.0-Mx or 2.13.0-RCx).

**Comment by SethTisue** [comment]
in particular, "expected: 5.0 found: 5.2" looks like you are trying to use the 2.12 compiler with a 2.13 library

**Comment by k-bespalov** [comment]
but
```
macmini-kbespalov:sso-mono k.bespalov$ scalac -version
Scala compiler version 2.13.0 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.
```

**Comment by k-bespalov** [comment]
suppose I have found what problem is. I had library dependency `"org.uaparser" % "uap-scala_2.12" % "0.7.0"` and try to use `"org.uaparser" % "uap-scala_2.13" % "0.9.0"` but it found out to be wrong. it should be `"org.uaparser" % "uap-scala" % "0.9.0"`

sorry for bothering you

**Comment by SethTisue** [comment]
Glad you got it sorted out. It is a deficiency of our compiler that it doesn't usually give a clear error message in these scenarios.

**Comment by Uttam95yadav** [comment]
i got the same error "Error:scalac: error while loading package, Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in package.class" but not sure how to trace the root cause. any Idea ?

**Comment by SethTisue** [comment]
please seek help on https://users.scala-lang.org
