### ISSUE TITLE
2.13 regression: objects may be instantiated twice in reflectModule

### ISSUE THREAD

**Issue by kaishh** [scala/bug#11645]
I'm experiencing test failures when comparing static objects reflected by `Mirror.reflectModule` two different object instances are created:

```
[info] - should resolve config sealed traits *** FAILED *** (64 milliseconds)
[info]   No did not equal No (ConfigTest.scala:155)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:530)

CLASSLOADER: `sun.misc.Launcher$AppClassLoader@6d6f6e28`
CLASSLOADER: `sun.misc.Launcher$AppClassLoader@6d6f6e28`
CLASS: `class com.github.pshirshov.configapp.SealedTrait2$No$(1058091543)`
CLASS: `class com.github.pshirshov.configapp.SealedTrait2$No$(1058091543)`
Identity of this No: `1692507983`
Identity of that No: `920768065`
Identity of static No in test: `920768065`
Identity of reflected No in test: `1692507983`
Identity of static No in this.equals: `920768065`
Identity of reflected No in this.equals: `920768065`
```

The new instance is at first consistent between subsequent calls to `reflectModule`, but then redirects to the static instance.
I'm not sure if this error is a scala-reflect-only bug, since `JavaModuleMirror`/`Runtime.staticSingletonInstance` don't seem to do anything funny – they just call `.MODULE$`.

Note that it's not sbt-classloarder-related, as it reproduces with `fork := true`, and possibly not concurrency related since it reproduces with sequential tests `parallelExecution in ThisBuild := false`

The branch with reproduction is [here](https://github.com/7mind/izumi/tree/bug/scala-2.13-duplicate-object-with-scala-reflect), to reproduce execute:

```
git clone https://github.com/7mind/izumi.git
cd izumi
git checkout bug/scala-2.13-duplicate-object-with-scala-reflect
sbt ++2.13.0 distage-config/test
```

**Comment by pshirshov** [comment]
Please note that the instances are being compared within the **same** classloader and their `.getClass` results are referentially equal

**Comment by javax-swing** [comment]
Interestingly this seems to manifesting because of the changes to instantiation of objects in 2.13

This is the 2.12 generated java class
```
public static class No$ implements SealedTrait2, Product, Serializable {
   public static SealedTrait2.No$ MODULE$;

   static {
      new SealedTrait2.No$();
   }

   public boolean equals(final Object obj) {
      scala.Predef..MODULE$.println((new StringBuilder(15)).append("CLASSLOADER: `").append(this.getClass().getClassLoader()).append("`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(15)).append("CLASSLOADER: `").append(obj.getClass().getClassLoader()).append("`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(11)).append("CLASS: `").append(this.getClass()).append("(").append(System.identityHashCode(this.getClass())).append(")`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(11)).append("CLASS: `").append(obj.getClass()).append("(").append(System.identityHashCode(obj.getClass())).append(")`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(40)).append("Identity of static No in this.equals: `").append(System.identityHashCode(com.github.pshirshov.configapp.external..MODULE$.getNoObj())).append("`").toString());
      scala.Predef. var10000 = scala.Predef..MODULE$;
      StringBuilder var10001 = (new StringBuilder(43)).append("Identity of reflected No in this.equals: `");
      JavaMirror var10002 = scala.reflect.runtime.package..MODULE$.universe().runtimeMirror(this.getClass().getClassLoader());
      TypeTags var10003 = (TypeTags)scala.reflect.runtime.package..MODULE$.universe();
      JavaUniverse $u = scala.reflect.runtime.package..MODULE$.universe();
      JavaMirror $m = scala.reflect.runtime.package..MODULE$.universe().runtimeMirror(this.getClass().getClassLoader());

      final class $typecreator1$1 extends TypeCreator {
         public TypeApi apply(final Mirror $m$untyped) {
            Universe $u = $m$untyped.universe();
            return $u.internal().reificationSupport().ThisType($m$untyped.staticModule("com.github.pshirshov.configapp.SealedTrait2.No").asModule().moduleClass());
         }

         public $typecreator1$1() {
         }
      }

      var10000.println(var10001.append(System.identityHashCode(var10002.reflectModule(var10003.typeOf(((TypeTags)$u).TypeTag().apply((Mirror)$m, new $typecreator1$1())).typeSymbol().asClass().module().asModule()).instance())).append("`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(23)).append("Identity of this No: `").append(System.identityHashCode(this)).append("`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(23)).append("Identity of that No: `").append(System.identityHashCode(obj)).append("`").toString());
      return this == obj;
   }

   public String productPrefix() {
      return "No";
   }

   public int productArity() {
      return 0;
   }

   public Object productElement(final int x$1) {
      throw new IndexOutOfBoundsException(BoxesRunTime.boxToInteger(x$1).toString());
   }

   public Iterator productIterator() {
      return scala.runtime.ScalaRunTime..MODULE$.typedProductIterator(this);
   }

   public boolean canEqual(final Object x$1) {
      return x$1 instanceof SealedTrait2.No$;
   }

   public int hashCode() {
      return 2529;
   }

   public String toString() {
      return "No";
   }

   private Object readResolve() {
      return MODULE$;
   }

   public No$() {
      MODULE$ = this;
      Product.$init$(this);
      scala.Predef..MODULE$.println("Making No");
      Thread.dumpStack();
   }
}
```

this is the 2.13 generated java class
```
public static class No$ implements SealedTrait2, Product, Serializable {
   public static final SealedTrait2.No$ MODULE$ = new SealedTrait2.No$();

   static {
      Product.$init$(MODULE$);
      scala.Predef..MODULE$.println("Making No");
      Thread.dumpStack();
   }

   public String productElementName(final int n) {
      return Product.productElementName$(this, n);
   }

   public Iterator productElementNames() {
      return Product.productElementNames$(this);
   }

   public boolean equals(final Object obj) {
      scala.Predef..MODULE$.println((new StringBuilder(15)).append("CLASSLOADER: `").append(this.getClass().getClassLoader()).append("`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(15)).append("CLASSLOADER: `").append(obj.getClass().getClassLoader()).append("`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(11)).append("CLASS: `").append(this.getClass()).append("(").append(System.identityHashCode(this.getClass())).append(")`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(11)).append("CLASS: `").append(obj.getClass()).append("(").append(System.identityHashCode(obj.getClass())).append(")`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(40)).append("Identity of static No in this.equals: `").append(System.identityHashCode(com.github.pshirshov.configapp.external..MODULE$.getNoObj())).append("`").toString());
      scala.Predef. var10000 = scala.Predef..MODULE$;
      StringBuilder var10001 = (new StringBuilder(43)).append("Identity of reflected No in this.equals: `");
      JavaMirror var10002 = scala.reflect.runtime.package..MODULE$.universe().runtimeMirror(this.getClass().getClassLoader());
      TypeTags var10003 = (TypeTags)scala.reflect.runtime.package..MODULE$.universe();
      JavaUniverse $u = scala.reflect.runtime.package..MODULE$.universe();
      JavaMirror $m = scala.reflect.runtime.package..MODULE$.universe().runtimeMirror(this.getClass().getClassLoader());

      final class $typecreator1$1 extends TypeCreator {
         public TypeApi apply(final Mirror $m$untyped) {
            Universe $u = $m$untyped.universe();
            return $u.internal().reificationSupport().ThisType($m$untyped.staticModule("com.github.pshirshov.configapp.SealedTrait2.No").asModule().moduleClass());
         }

         public $typecreator1$1() {
         }
      }

      var10000.println(var10001.append(System.identityHashCode(var10002.reflectModule(var10003.typeOf(((TypeTags)$u).TypeTag().apply((Mirror)$m, new $typecreator1$1())).typeSymbol().asClass().module().asModule()).instance())).append("`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(23)).append("Identity of this No: `").append(System.identityHashCode(this)).append("`").toString());
      scala.Predef..MODULE$.println((new StringBuilder(23)).append("Identity of that No: `").append(System.identityHashCode(obj)).append("`").toString());
      return this == obj;
   }

   public String productPrefix() {
      return "No";
   }

   public int productArity() {
      return 0;
   }

   public Object productElement(final int x$1) {
      Object var2 = Statics.ioobe(x$1);
      return var2;
   }

   public Iterator productIterator() {
      return scala.runtime.ScalaRunTime..MODULE$.typedProductIterator(this);
   }

   public boolean canEqual(final Object x$1) {
      return x$1 instanceof SealedTrait2.No$;
   }

   public int hashCode() {
      return 2529;
   }

   public String toString() {
      return "No";
   }

   private Object writeReplace() {
      return new ModuleSerializationProxy(SealedTrait2.No$.class);
   }
}
```

**Comment by javax-swing** [comment]
In 2.13 the construction of a Module no longer results in the re-assignment of the MODULE$ variable.
If you add 
```
    println("Making No")
    Thread.dumpStack()
```

To the body of `object No` and run the test in 2.12 you see it twice, but in 2.13 you see it only once.

So i think the issue lies in that somewhere the code is creating a new one of these (most likely via reflection)

```
aking No
java.lang.Exception: Stack trace
	at java.lang.Thread.dumpStack(Thread.java:1336)
	at com.github.pshirshov.configapp.SealedTrait2$No$.<init>(TestConfigReaders.scala:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror0.jinvokeraw(JavaMirrors.scala:379)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaMethodMirror.jinvoke(JavaMirrors.scala:354)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror.apply(JavaMirrors.scala:370)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveCaseClassReader$2(RuntimeConfigReaderDefaultImpl.scala:114)
	at scala.util.Try$.apply(Try.scala:213)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveCaseClassReader$1(RuntimeConfigReaderDefaultImpl.scala:78)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveSealedTraitReader$2(RuntimeConfigReaderDefaultImpl.scala:179)
	at scala.util.Try$.apply(Try.scala:213)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveSealedTraitReader$1(RuntimeConfigReaderDefaultImpl.scala:125)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveCaseClassReader$4(RuntimeConfigReaderDefaultImpl.scala:92)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scalaIdentity of static No in test: `1843418996`
Identity of reflected No in test: `1843418996`
:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveCaseClassReader$2(RuntimeConfigReaderDefaultImpl.scala:88)
	at scala.util.Try$.apply(Try.scala:213)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveCaseClassReader$1(RuntimeConfigReaderDefaultImpl.scala:78)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveSealedTraitReader$2(RuntimeConfigReaderDefaultImpl.scala:179)
	at scala.util.Try$.apply(Try.scala:213)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveSealedTraitReader$1(RuntimeConfigReaderDefaultImpl.scala:125)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveCaseClassReader$4(RuntimeConfigReaderDefaultImpl.scala:92)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:89)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveCaseClassReader$2(RuntimeConfigReaderDefaultImpl.scala:88)
	at scala.util.Try$.apply(Try.scala:213)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.$anonfun$deriveCaseClassReader$1(RuntimeConfigReaderDefaultImpl.scala:78)
	at com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl.readConfigAsCaseClass(RuntimeConfigReaderDefaultImpl.scala:40)
	at com.github.pshirshov.izumi.distage.config.ConfigProvider.toProduct(ConfigProvider.scala:109)
	at com.github.pshirshov.izumi.distage.config.ConfigProvider.translate(ConfigProvider.scala:86)
	at com.github.pshirshov.izumi.distage.config.ConfigProvider.$anonfun$phase20Customization$1(ConfigProvider.scala:33)
```

In the above stackTrace we can see that `com.github.pshirshov.izumi.fundamentals.typesafe.config.RuntimeConfigReaderDefaultImpl#deriveCaseClassReader` is the culprit. as it is constructing a new one every time

**Comment by pshirshov** [comment]
But we **do not** create new instances. We use `reflectModule` to get one.

**Comment by javax-swing** [comment]
This can be fixed by changing the method above with the following code 
```
        case _: ConfigObject if  targetType.tpe.termSymbol.isModule && targetType.tpe.termSymbol.isStatic =>
          // statically available module yay \o/
          println(s"Resolving module type symbol ${targetType.tpe.typeSymbol}")
          mirror.reflectModule(targetType.tpe.termSymbol.asModule).instance

        case _: ConfigObject if targetType.tpe.termSymbol.isModule =>
          // objects within a class for example, these can only be constructed with an instance of the class
          throw new ConfigReadException(
            s"""
               |Can't read config value as a non static module
               | ConfigValue was: $cv""".stripMargin)
```

The change you will see in 2.12 is that `Thread.dumpStack()` is only executed once :)

**Comment by kaishh** [comment]
🤦‍♀  Yep, that's was a bug in our code, the test is checking a config with `No` read from `{ No {} }` which specifically fails `if cv.valueType() == ConfigValueType.STRING` and uses the `newInstance` branch instead of enum branch.

**Comment by kaishh** [comment]
@javax-swing Thank you so much for pointing that out!

**Comment by javax-swing** [comment]
@kaishh no worries 👍
