### ISSUE TITLE
"Failed to construct terminal" in 2.11.12

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11723]
Probably just a jline upgrade interaction but I keep falling back to a previous point release of scala:
```
$ ./scala-2.11.12/bin/scala
Welcome to Scala 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:223)
	at scala.tools.nsc.interpreter.jline.JLineConsoleReader.<init>(JLineReader.scala:64)
	at scala.tools.nsc.interpreter.jline.InteractiveReader.<init>(JLineReader.scala:33)
```

**Comment by som-snytt** [comment]
I had forgotten [the known issue](https://users.scala-lang.org/t/scala-repl-throws-java-lang-numberformatexception/1600/4).

There is an issue at jline2 which I will not annoy anyone by linking to. Also an sbt issue.

Recommendation is to change `TERM` from `xterm-256color` to `xterm-color`:
```
$ TERM=xterm-color ~/scala-2.11.12/bin/scala
```

Or, replace `lib/jline-2.14.3.jar` with `jline-2.14.4.jar`, which just works for a quick REPL session.

Using `-toolcp ~/.ivy2/cache/jline/jline/jars/jline-2.14.4.jar` doesn't work because it appends to the bootclasspath instead of prepending, gah.

**Comment by som-snytt** [comment]
Or wait, is there a 2.11.13 milestone? Maybe it's an aspirational milestone, like 2.14.

**Comment by eed3si9n** [comment]
Maybe there should be a note on https://github.com/scala/docs.scala-lang/blob/master/_overviews/jdk-compatibility/overview.md page if we're not going to fix this issue.
