### ISSUE TITLE
Error:  scalac: Error: assertion failed:

### ISSUE THREAD

**Issue by mggger** [scala/bug#11795]
```
Error:scalac: Error: assertion failed: 
  Context(Main.scala) {
   owner       = value gg
   tree        = ValDef:val gg = ((Message.unapply: (() => <empty>)): _root_.scala.Function1[M
   scope       = 0 decls
   contextMode = AmbiguousErrors MacrosEnabled TypeConstructorAllowed
   outer.owner = method *
}
     while compiling: /Users/home/git/company/migrate-event/src/main/scala/Main.scala
        during phase: globalPhase=typer, enteringPhase=namer
     library version: version 2.12.8
    compiler version: version 2.12.8
  reconstructed args: -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/tools.jar:/Users/home/git/company/migrate-event/target/scala-2.12/classes:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.47/mysql-connector-java-5.1.47.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/slick/slick-hikaricp_2.12/3.3.0/slick-hikaricp_2.12-3.3.0.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/slick/slick_2.12/3.3.0/slick_2.12-3.3.0.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/com/zaxxer/HikariCP/3.2.0/HikariCP-3.2.0.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
  last tree to typer: Ident(_root_)
       tree position: line 37 of /Users/home/git/company/migrate-event/src/main/scala/Main.scala
            tree tpe: <root>
              symbol: final package _root_
   symbol definition: final package _root_ (a RootPackage)
      symbol package: <none>
       symbol owners: package _root_
           call site: method * in class MessageTable in package <empty>
== Source file context for tree position ==
    34 
    35   def content = column[String]("content", O.SqlType("VARCHAR(30)"))
    36 
    37   def * = (sender, content, id).mapTo[Message]
    38 
    39 }
    40 
java.lang.AssertionError: assertion failed: 
  Context(Main.scala) {
   owner       = value gg
   tree        = ValDef:val gg = ((Message.unapply: (() => <empty>)): _root_.scala.Function1[M
   scope       = 0 decls
   contextMode = AmbiguousErrors MacrosEnabled TypeConstructorAllowed
   outer.owner = method *
}
     while compiling: /Users/home/git/company/migrate-event/src/main/scala/Main.scala
        during phase: globalPhase=typer, enteringPhase=namer
     library version: version 2.12.8
    compiler version: version 2.12.8
  reconstructed args: -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home/lib/tools.jar:/Users/home/git/company/migrate-event/target/scala-2.12/classes:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.2/logback-classic-1.1.2.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.47/mysql-connector-java-5.1.47.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.2/logback-core-1.1.2.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/slick/slick-hikaricp_2.12/3.3.0/slick-hikaricp_2.12-3.3.0.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/slick/slick_2.12/3.3.0/slick_2.12-3.3.0.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/com/zaxxer/HikariCP/3.2.0/HikariCP-3.2.0.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar:/Users/home/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar
  last tree to typer: Ident(_root_)
       tree position: line 37 of /Users/home/git/company/migrate-event/src/main/scala/Main.scala
            tree tpe: <root>
              symbol: final package _root_
   symbol definition: final package _root_ (a RootPackage)
      symbol package: <none>
       symbol owners: package _root_
           call site: method * in class MessageTable in package <empty>
== Source file context for tree position ==
    34 
    35   def content = column[String]("content", O.SqlType("VARCHAR(30)"))
    36 
    37   def * = (sender, content, id).mapTo[Message]
    38 
    39 }
    40 
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:183)
	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1189)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1243)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5740)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$60(Typers.scala:5142)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTypeSelectionQualifier$1(Typers.scala:5142)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:5150)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5681)
	at scala.tools.nsc.typechecker.Typers$Typer.typedAppliedTypeTree$1(Typers.scala:5275)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5633)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedHigherKindedType$2(Typers.scala:5788)
	at scala.tools.nsc.typechecker.Typers$Typer.typedHigherKindedType(Typers.scala:5863)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$82(Typers.scala:5490)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTypeApply$1(Typers.scala:5490)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5657)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5690)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5801)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1090)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1708)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1877)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1842)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:853)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2039)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2037)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2032)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1690)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5790)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2503)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$98(Typers.scala:5655)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:500)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5690)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTyped$1(Typers.scala:5453)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5683)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Macros$DefMacroExpander.$anonfun$onSuccess$1(Macros.scala:687)
	at scala.tools.nsc.typechecker.Macros$DefMacroExpander.typecheck$1(Macros.scala:687)
	at scala.tools.nsc.typechecker.Macros$DefMacroExpander.onSuccess(Macros.scala:695)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:638)
	at scala.tools.nsc.Global.withInfoLevel(Global.scala:227)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:625)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:612)
	at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:787)
	at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:785)
	at scala.tools.nsc.Global$$anon$4.standardMacroExpand(Global.scala:477)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:439)
	at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:436)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:408)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:436)
	at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:436)
	at scala.tools.nsc.Global$$anon$4.pluginsMacroExpand(Global.scala:477)
	at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:776)
	at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:769)
	at scala.tools.nsc.Global$$anon$4.macroExpand(Global.scala:477)
	at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1183)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1243)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5740)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$2(Typers.scala:864)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:713)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:861)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:491)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1239)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5740)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5801)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1090)
	at scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1431)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1876)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1842)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:853)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2039)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2037)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2032)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1690)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5790)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2030)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1843)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5646)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5790)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3373)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5356)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5649)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:114)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:448)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:103)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1498)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1482)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1475)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1598)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:40)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:35)
	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:83)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:26)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

***
Hope someone can help me understand what happened

**Comment by som-snytt** [comment]
[They decided not to assert](https://github.com/scala/scala/pull/8515) that anymore.

Probably gitter would be helpful for the underlying error.

**Comment by lrytz** [comment]
In order to diagnose this, we need more information, ideally a source file that triggers the error.

Are there other errors reported, does it seem likely that https://github.com/scala/scala/pull/8515 fixed the issue?

I'm closing this, but feel free to re-open if you can provide more details.

**Comment by polentino** [comment]
@mggger I don't know if you've fixed the problem already; anyhow, I had the same issue as yours, and it turned out my select clause `*` was using a column reference that was **not** optional, so you have an extra `.?` somewhere to remove in it.

**Comment by mggger** [comment]
@polentino   The cause of the error is caused by the inconsistent mapping relationship。 

```scala
def * = (sender, content, id).mapTo[Message]
```
And the database schema is 

|id|content|sender|
|:--:|:--:|:--:|
||||
