### ISSUE TITLE
s.c.LinearSeq and s.c.i.LinearSeq have infinite recursion in their isEmpty/lengthCompare methods

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11811]
```scala
scala> new collection.immutable.LinearSeq[Int]{}.toString

  .....
  at $anon$1.isEmpty(<console>:1)
  at scala.collection.LinearSeqOps.loop$1(LinearSeq.scala:75)
  at scala.collection.LinearSeqOps.lengthCompare(LinearSeq.scala:82)
  at scala.collection.LinearSeqOps.lengthCompare$(LinearSeq.scala:72)
  at $anon$1.lengthCompare(<console>:1)
  at scala.collection.SeqOps.isEmpty(Seq.scala:819)
  at scala.collection.SeqOps.isEmpty$(Seq.scala:819)
  at $anon$1.isEmpty(<console>:1)
  at scala.collection.LinearSeqOps.loop$1(LinearSeq.scala:75)
  at scala.collection.LinearSeqOps.lengthCompare(LinearSeq.scala:82)
  at scala.collection.LinearSeqOps.lengthCompare$(LinearSeq.scala:72)
  at $anon$1.lengthCompare(<console>:1)
  at scala.collection.SeqOps.isEmpty(Seq.scala:819)
  at scala.collection.SeqOps.isEmpty$(Seq.scala:819)
  at $anon$1.isEmpty(<console>:1)
  at scala.collection.LinearSeqOps.loop$1(LinearSeq.scala:75)
  at scala.collection.LinearSeqOps.lengthCompare(LinearSeq.scala:82)
  at scala.collection.LinearSeqOps.lengthCompare$(LinearSeq.scala:72)
  at $anon$1.lengthCompare(<console>:1)
  at scala.collection.SeqOps.isEmpty(Seq.scala:819)
  at scala.collection.SeqOps.isEmpty$(Seq.scala:819)
  at $anon$1.isEmpty(<console>:1)
  at scala.collection.LinearSeqOps.loop$1(LinearSeq.scala:75)
  at scala.collection.LinearSeqOps.lengthCompare(LinearSeq.scala:82)
```

**Comment by joshlemer** [comment]
Whoops, this is duplicate of https://github.com/scala/bug/issues/11697
