### ISSUE TITLE
Compiler crash while reporting ambiguity

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11866]
## I contrived a fairly trivial example to illustrate my point as follows:
```
class X { def f(n: Int) = 42 ; object f { def apply(i: Int) = 42 + i } }

object Test extends App {
  new X().f(1)
}
```
which doesn't seem too pernicious except:
```
error: scala.ScalaReflectionException: object f is not a method
	at scala.reflect.api.Symbols$SymbolApi.asMethod(Symbols.scala:240)
	at scala.reflect.api.Symbols$SymbolApi.asMethod$(Symbols.scala:234)
	at scala.reflect.internal.Symbols$SymbolContextApiImpl.asMethod(Symbols.scala:99)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.AmbiguousMethodAlternativeError(ContextErrors.scala:1164)
	at scala.tools.nsc.typechecker.Infer$Inferencer$InferMethodAlternativeTwice$1.bestForExpectedType(Infer.scala:1475)
	at scala.tools.nsc.typechecker.Infer$Inferencer$InferMethodAlternativeTwice$1.tryOnce(Infer.scala:1485)
	at scala.tools.nsc.typechecker.Contexts$Context$TryTwice.$anonfun$apply$1(Contexts.scala:556)
	at scala.tools.nsc.typechecker.Contexts$Context$TryTwice.apply(Contexts.scala:624)
	at scala.tools.nsc.typechecker.Infer$Inferencer.inferMethodAlternative(Infer.scala:1489)
	at scala.tools.nsc.typechecker.Typers$Typer.handleOverloaded$1(Typers.scala:3547)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3551)
```
Dotty at least manages to say:
```
-- [E051] Reference Error: woops.scala:5:10 ------------------------------------
5 |  new X().f(1)
  |  ^^^^^^^^^
  |Ambiguous overload. The overloaded alternatives of object f in class X with types
  | X#f$
  | (n: Int): Int
  |both match arguments ((1 : Int))
```
This was an inspired by a SO question which they closed prematurely. Now they close all the so-called dumb questions, which are the good ones.

**Comment by Jasper-M** [comment]
Strictly speaking this is a duplicate of #11415 but I forgive you.
