### ISSUE TITLE
enumeration serialization destabilization (depending on initialization)

### ISSUE THREAD

**Issue by hrhino** [scala/bug#11919]
## Fairly trivial contrived example:

```
[nix-shell:/tmp/tmp.HUYBl23Biv]$ ./scala --scala-version 2.12.11
Welcome to Scala 2.12.11 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> :pa -raw
// Entering paste mode (ctrl-D to finish)

object MyEnum extends Enumeration { val MyVal = Value }

// Exiting paste mode, now interpreting.

scala> import java.io._
import java.io._

scala> def write(x: AnyRef, fn: String) { val out = new ObjectOutputStream(new FileOutputStream(fn)); out writeObject x; out.close() }
write: (x: AnyRef, fn: String)Unit

scala> write(MyEnum.MyVal, "good.bin")

scala> MyEnum.ValueSet.empty
res1: MyEnum.ValueSet = MyEnum.ValueSet()

scala> write(MyEnum.MyVal, "bad.bin")

scala> :quit

[nix-shell:/tmp/tmp.HUYBl23Biv]$ ./scala --scala-version 2.12.10
Welcome to Scala 2.12.10 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> :pa -raw
// Entering paste mode (ctrl-D to finish)

object MyEnum extends Enumeration { val MyVal = Value }

// Exiting paste mode, now interpreting.

scala> import java.io._
import java.io._

scala> def read(fn: String): AnyRef = { val in = new ObjectInputStream(new FileInputStream(fn)); try in.readObject() finally in.close() }
read: (fn: String)AnyRef

scala> read("good.bin")
res0: AnyRef = MyVal

scala> read("bad.bin")
java.io.InvalidClassException: scala.Enumeration$ValueSet; local class incompatible: stream classdesc serialVersionUID = -7406336672087551067, local class serialVersionUID = 7317159981283342720
  at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1885)
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1751)
```

```scala
println("hello, world")
```

## problem

It crashes.

## expectation

It should not crash.

Caused, in a way, by scala/scala#8725. 

Ideally we should not serialize `Enumeration$ValueSet$` at all (as Lukas noted in #9642 lo so many years ago) but we've got to live with the current format for now.

**Comment by SethTisue** [comment]
#cajunman

**Comment by SethTisue** [comment]
(Is a separate 2.12 fix forthcoming, or was it decided that having a 2.13 fix was sufficient?)

**Comment by hrhino** [comment]
I'm going to try to do something for 2.12.12, but I don't know how useful it'll be. Sorry I didn't catch this before the release

**Comment by SethTisue** [comment]
I haven't heard anyone complain :-)

**Comment by hrhino** [comment]
Other than me...
