### ISSUE TITLE
scaladoc on JDK 11 with `-release 8` crashes (2.12.11 and 2.13.1)

### ISSUE THREAD

**Issue by jrudolph** [scala/bug#11927]
```
$> java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

$> cat Test.scala
class C

$> ~/Applications/bin/scala-runners/scaladoc --scala-version 2.12.11 -release 8 Test.scala
Exception in thread "main" java.lang.AssertionError: assertion failed:
  type AnyRef in java.lang
     while compiling: Test.scala
        during phase: globalPhase=terminal, enteringPhase=typer
     library version: version 2.12.11
    compiler version: version 2.12.11
  reconstructed args: -release 8

  last tree to typer: Literal(Constant(()))
       tree position: line 1 of Test.scala
            tree tpe: Unit
              symbol: null
           call site: constructor C in class C in package <empty>

== Source file context for tree position ==

     1 class C
     2
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:702)
	at scala.tools.nsc.doc.model.ModelFactory.makeMember0$1(ModelFactory.scala:797)
	at scala.tools.nsc.doc.model.ModelFactory.makeMember(ModelFactory.scala:810)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.$anonfun$ownMembers$1(ModelFactory.scala:370)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.<init>(ModelFactory.scala:370)
	at scala.tools.nsc.doc.model.ModelFactory$PackageImpl.<init>(ModelFactory.scala:479)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$$anon$8.<init>(ModelFactory.scala:689)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:689)
	at scala.tools.nsc.doc.model.ModelFactory.makeMember0$1(ModelFactory.scala:797)
	at scala.tools.nsc.doc.model.ModelFactory.makeMember(ModelFactory.scala:810)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.$anonfun$ownMembers$1(ModelFactory.scala:370)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.<init>(ModelFactory.scala:370)
	at scala.tools.nsc.doc.model.ModelFactory$PackageImpl.<init>(ModelFactory.scala:479)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$$anon$8.<init>(ModelFactory.scala:689)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:689)
	at scala.tools.nsc.doc.model.ModelFactory.makeMember0$1(ModelFactory.scala:797)
	at scala.tools.nsc.doc.model.ModelFactory.makeMember(ModelFactory.scala:810)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.$anonfun$ownMembers$1(ModelFactory.scala:370)
	at scala.tools.nsc.doc.model.ModelFactory$DocTemplateImpl.<init>(ModelFactory.scala:370)
	at scala.tools.nsc.doc.model.ModelFactory$PackageImpl.<init>(ModelFactory.scala:479)
	at scala.tools.nsc.doc.model.ModelFactory$RootPackageImpl.<init>(ModelFactory.scala:487)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$$anon$7.<init>(ModelFactory.scala:671)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createTemplate(ModelFactory.scala:671)
	at scala.tools.nsc.doc.model.ModelFactory$modelCreation$.createRootPackage(ModelFactory.scala:619)
	at scala.tools.nsc.doc.model.ModelFactory$$anon$1.<init>(ModelFactory.scala:55)
	at scala.tools.nsc.doc.model.ModelFactory.makeModel(ModelFactory.scala:52)
	at scala.tools.nsc.doc.DocFactory.makeUniverse(DocFactory.scala:88)
	at scala.tools.nsc.doc.DocFactory.generate$1(DocFactory.scala:131)
	at scala.tools.nsc.doc.DocFactory.document(DocFactory.scala:138)
	at scala.tools.nsc.ScalaDoc.process(ScalaDoc.scala:47)
	at scala.tools.nsc.ScalaDoc$.main(ScalaDoc.scala:98)
	at scala.tools.nsc.ScalaDoc.main(ScalaDoc.scala)
```

**Comment by raboof** [comment]
> [error]         during phase: globalPhase=terminal, enteringPhase=silencer

Hmm, does this have to do with the silencer plugin somehow? Don't see anything at https://github.com/ghik/silencer/ though...

**Comment by raboof** [comment]
I'm also seeing it with other Scala versions it seems - so might be something in the akka build

**Comment by lrytz** [comment]
I'm looking at it. I also saw that it's the same in 2.12.10, so not a recent regression.

**Comment by SethTisue** [comment]
Puzzling that the community build wouldn't have caught this.

**Comment by lrytz** [comment]
@jrudolph @raboof the problem is `-release 8`, I updated the description. As a workaround, maybe you can remove that flag when invoking scaladoc?

**Comment by raboof** [comment]
Ah, good find, thanks!

**Comment by jrudolph** [comment]
Thanks for investigating and fixing. Sorry about the too eager conclusion that it would be related to 2.12.11.

**Comment by SethTisue** [comment]
> Puzzling that the community build wouldn't have caught this.

oh heh perhaps this is why

```
    // idk why, but prevents dbuild-only sun.misc.Unsafe compile errors;
    // see https://github.com/scala/community-builds/issues/757
    "set scalacOptions in Compile in actor --= Seq(\"-release\", \"8\")"
    // prevents: Class jdk.internal.HotSpotIntrinsicCandidate not found - continuing with a stub.
    "set scalacOptions in Compile in stream --= Seq(\"-release\", \"8\")"
```

**Comment by SethTisue** [comment]
heh, I already reported this way back when at https://github.com/scala/bug/issues/11682 :-)
