### ISSUE TITLE
expanded (non-LMFable) function needlessly captures outer

### ISSUE THREAD

**Issue by hrhino** [scala/bug#11930]
## Fairly trivial contrived example:

```scala
[nix-shell:~]$ scala
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> :pa -raw
// Entering paste mode (ctrl-D to finish)

trait Test {
  val ord1: Ordering[String] = new Ordering[String] { def compare(l: String, r: String) = l compareTo r }
  val ord2: Ordering[String] = _ compareTo _
}
object Test extends Test

// Exiting paste mode, now interpreting.


scala> Test.ord1.getClass.getDeclaredFields
res0: Array[java.lang.reflect.Field] = Array()

scala> Test.ord2.getClass.getDeclaredFields
res1: Array[java.lang.reflect.Field] = Array(private static final long Test$$anonfun$ord2$2.serialVersionUID, private final Test Test$$anonfun$ord2$2.$outer)
```

## problem (among others)

```scala
scala> new java.io.ObjectOutputStream(new java.io.FileOutputStream(new java.io.File("/dev/null"))).writeObject(Test.ord1)

scala> new java.io.ObjectOutputStream(new java.io.FileOutputStream(new java.io.File("/dev/null"))).writeObject(Test.ord2)
java.io.NotSerializableException: Test$
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
  at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
  ... 28 elided

```

## expectation

No `$outer` in my lambda.

**Comment by dwijnand** [comment]
Is this #11356?  (Just found it b/c I was trying to understand wth "LMFable" means. 😄)

**Comment by SethTisue** [comment]
`LambdaMetaFactory` (it also wasn't obvious to me without looking it up).

Not fixed in Scala 3.3.1-RC6
