### ISSUE TITLE
Unsound cast on ident pattern is not always rejected

### ISSUE THREAD

**Issue by smarter** [scala/bug#11938]
Since https://github.com/scala/scala/pull/6502, the following is rejected:

```scala
object Test {
  def main(args: Array[String]): Unit = {
    val a : Nil.type = (Vector(): Any) match { case n @ Nil => n } // error
  }
}
```
... but the following isn't, and yet will crash in the same way:
```scala
object Test {
  def main(args: Array[String]): Unit = {
    val a : Nil.type = (Vector(): Any) match { case n @ (m @ Nil) => n } // error
  }
}
```
```scala
java.lang.ClassCastException: scala.collection.immutable.Vector cannot be cast to scala.collection.immutable.Nil$
        at Test$.main(i3200b.scala:3)
```

**Comment by smarter** [comment]
Also, it's suspicious that this compiles:
```scala
object Test {
  def main(args: Array[String]): Unit = {
    val d: Int = (1.0: Any) match { case x @ 1 => x } // error
  }
}
```
It doesn't crash because the compiler never actually casts `x` to an Int, it just uses `1` directly when needed, but it could (and maybe it would with a more complicated example).

**Comment by som-snytt** [comment]
Also unhelpful:
```
scala 2.13.1> (1.0: Any) match { case x @ (_: 1) => x }
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')
  at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
  ... 28 elided

scala 2.13.1> (1.0: Any) match { case x: 1 => x }
java.lang.ClassCastException: class java.lang.Double cannot be cast to class java.lang.Integer (java.lang.Double and java.lang.Integer are in module java.base of loader 'bootstrap')
  at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
  ... 28 elided
```

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/8874 was closed, but could be picked up again

**Comment by som-snytt** [comment]
I didn't want to clutter the queue with drafts. I'll get back to it, but I don't mind if someone else does first.

**Comment by SethTisue** [comment]
@dwijnand is something you might like to pick up? (just asking, no pressure)

**Comment by dwijnand** [comment]
Yep, I'll have a look - I'd lost track of this issue, thanks!
