### ISSUE TITLE
Trait value initialization causes runtime ClassCastException when specializing in more than one type 

### ISSUE THREAD

**Issue by Sciss** [scala/bug#11934]
## reproduction steps

```scala
trait T[@specialized(Int, Unit) S] {
  var value: S = _
}

final class C[@specialized(Int, Unit) S] extends T[S]

object Test extends App {
  new C[Int]
}
```

## problem

Tries to initialize the field `value` with a value taken from the right-most specialization variant, here `Unit`, instead of the correct variant, here `Int`:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at Test.main(SpecializedTest.scala)
Caused by: java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
	at C$mcI$sp.value_$eq(SpecializedTest.scala:16)
	at C.value$mcV$sp_$eq(SpecializedTest.scala:16)
	at T.$init$(SpecializedTest.scala:13)
	at C.<init>(SpecializedTest.scala:16)
	at C$mcI$sp.<init>(SpecializedTest.scala:16)
	at Test$.<clinit>(SpecializedTest.scala:19)
	... 1 more
```

Possibly related issues: #10094, #10141, #11707

**Comment by lrytz** [comment]
Seems to be a regression in 2.12, the example works in 2.11 (i.e., it doesn't crash in 2.11; I didn't look if specialization does the right thing).
