### ISSUE TITLE
Repl stack trace summary doesn't count suppressed frames correctly

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11945]
## reproduction steps

```scala
scala> val e = new AssertionError("oops")
e: AssertionError = java.lang.AssertionError: oops

scala> e.addSuppressed(new java.io.IOException("bad io"))

scala> e.printStackTrace
java.lang.AssertionError: oops
        at $line3.$read$$iw$$iw$.<clinit>(<console>:1)
        at $line3.$eval$.$print$lzycompute(<synthetic>:6)
        at $line3.$eval$.$print(<synthetic>:5)
        at $line3.$eval.$print(<synthetic>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:632)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:946)
        at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:474)
        at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:40)
        at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:40)
        at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:473)
        at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$3(IMain.scala:487)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:487)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:470)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:931)
        at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:788)
        at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:462)
        at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:485)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:1020)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
        Suppressed: java.io.IOException: bad io
                at $line5.$read$$iw$$iw$.<clinit>(<console>:1)
                at $line5.$eval$.$print$lzycompute(<synthetic>:6)
                at $line5.$eval$.$print(<synthetic>:5)
                at $line5.$eval.$print(<synthetic>)
                ... 24 more

scala> throw e
java.lang.AssertionError: oops
  ... 28 elided
  Suppressed: java.io.IOException: bad io
    ... 24 more

scala>
```

## problem

```scala
scala> e.getSuppressed.head.printStackTrace
java.io.IOException: bad io
        at $line5.$read$$iw$$iw$.<clinit>(<console>:1)
        at $line5.$eval$.$print$lzycompute(<synthetic>:6)
        at $line5.$eval$.$print(<synthetic>:5)
        at $line5.$eval.$print(<synthetic>)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[snip]
```

## expectation

Printing the suppressed exception doesn't seem to count frames correctly, as the depth is 28. Here, the top four differ in the two exceptions.

**Comment by som-snytt** [comment]
Probably it should report both `... 4 elided and 24 more`?

**Comment by NthPortal** [comment]
@som-snytt how do you feel about the following?

```
    ... 4 elided
    ... 24 more
```
