### ISSUE TITLE
$anon$1 class make compiler print java stack trace

### ISSUE THREAD

**Issue by zoogenic** [scala/bug#11949]
## reproduction steps

```scala

package lectures.part3oop

object AnonymousClasses extends App {
  abstract class Animal {
    def eat: Unit
  }

  class $anon$1 extends Animal {
    override def eat: Unit = println("brbrbrbrbrbrbrb")
  }

  val funnyAnimal: Animal = new Animal {
    override def eat: Unit = println("aggagagagagagaga")
  }

  val otherAnimal: Animal = new $anon$1

  println(funnyAnimal.getClass)
  funnyAnimal.eat

  println(otherAnimal.getClass)
  otherAnimal.eat
}
```

## problem

```scala
Error:scalac: Error: assertion failed: 
  (<$anon: lectures.part2oop.AnonymousClasses.Animal> in object AnonymousClasses,<$anon: lectures.part2oop.AnonymousClasses.Animal> in object AnonymousClasses)
     while compiling: /home/.../src/lectures/part2oop/AnonymousClasses.scala
        during phase: globalPhase=lambdalift, enteringPhase=constructors
     library version: version 2.13.1
    compiler version: version 2.13.1
  reconstructed args: -deprecation -classpath /usr/lib/jvm/jdk1.8.0_241/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/deploy.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/dnsns.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/jaccess.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/localedata.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/nashorn.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/sunec.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/zipfs.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/javaws.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/jce.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/jfxswt.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/management-agent.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/plugin.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/resources.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/rt.jar:/home/...:/usr/share/scala/lib/scala-reflect.jar:/usr/share/scala/lib/scala-library.jar
  last tree to typer: TypeTree(class String)
       tree position: line 36 of /home/.../src/lectures/part1basics/StringOps.scala
            tree tpe: String
              symbol: final class String in package lang
   symbol definition: final class String extends Serializable with Comparable with CharSequence (a ClassSymbol)
      symbol package: java.lang
       symbol owners: class String
           call site: method eat in package part2oop
== Source file context for tree position ==
    33 
    34   // F-interpolation
    35   val speed = 1.2f
    36   val myth = f"Davie can eat $speed%2.2f burgers per minute"
    37   println(myth)
    38 
    39   // raw-interpolation
java.lang.AssertionError: assertion failed: 
  (<$anon: lectures.part2oop.AnonymousClasses.Animal> in object AnonymousClasses,<$anon: lectures.part2oop.AnonymousClasses.Animal> in object AnonymousClasses)
     while compiling: /home/.../src/lectures/part2oop/AnonymousClasses.scala
        during phase: globalPhase=lambdalift, enteringPhase=constructors
     library version: version 2.13.1
    compiler version: version 2.13.1
  reconstructed args: -deprecation -classpath /usr/lib/jvm/jdk1.8.0_241/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/deploy.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/dnsns.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/jaccess.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/localedata.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/nashorn.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/sunec.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/ext/zipfs.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/javaws.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/jce.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/jfxswt.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/management-agent.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/plugin.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/resources.jar:/usr/lib/jvm/jdk1.8.0_241/jre/lib/rt.jar:/home/.../out/production/rock-the-jvm-scala-beginners-001:/usr/share/scala/lib/scala-reflect.jar:/usr/share/scala/lib/scala-library.jar
  last tree to typer: TypeTree(class String)
       tree position: line 36 of /home/.../src/lectures/part1basics/StringOps.scala
            tree tpe: String
              symbol: final class String in package lang
   symbol definition: final class String extends Serializable with Comparable with CharSequence (a ClassSymbol)
      symbol package: java.lang
       symbol owners: class String
           call site: method eat in package part2oop
== Source file context for tree position ==
    33 
    34   // F-interpolation
    35   val speed = 1.2f
    36   val myth = f"Davie can eat $speed%2.2f burgers per minute"
    37   println(myth)
    38 
    39   // raw-interpolation
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:170)
	at scala.reflect.internal.Scopes$Scope.enterUnique(Scopes.scala:151)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.liftDef(LambdaLift.scala:477)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.postTransform(LambdaLift.scala:487)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:557)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:59)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2614)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2612)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transformStats(LambdaLift.scala:575)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transformStats(LambdaLift.scala:59)
	at scala.reflect.internal.Trees$Block.transform(Trees.scala:529)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:307)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.preTransform(LambdaLift.scala:549)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:557)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:59)
	at scala.reflect.internal.Trees$ValDef.$anonfun$transform$4(Trees.scala:407)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:24)
	at scala.reflect.internal.Trees$ValDef.transform(Trees.scala:406)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:307)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.preTransform(LambdaLift.scala:549)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:557)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:59)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2614)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2612)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transformStats(LambdaLift.scala:575)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transformStats(LambdaLift.scala:59)
	at scala.reflect.internal.Trees$Template.transform(Trees.scala:517)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:47)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:32)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:307)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.preTransform(LambdaLift.scala:549)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:557)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:59)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:335)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:24)
	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:334)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:51)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:307)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.preTransform(LambdaLift.scala:549)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:557)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:59)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2614)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2612)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transformStats(LambdaLift.scala:575)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transformStats(LambdaLift.scala:59)
	at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:316)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:24)
	at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:316)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:49)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:37)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:32)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:307)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.preTransform(LambdaLift.scala:549)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transform(LambdaLift.scala:557)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:162)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.super$transformUnit(LambdaLift.scala:581)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.$anonfun$transformUnit$1(LambdaLift.scala:581)
	at scala.tools.nsc.transform.LambdaLift$LambdaLifter.transformUnit(LambdaLift.scala:581)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:36)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:452)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:397)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1614)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:41)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:42)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:133)
	at org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:123)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compilingNowCounterDecorated$1(Main.scala:112)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:120)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:96)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:55)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)```
```
## expectation
Compiler shouldn't output java stack trace. I would rather expect more informative error message

**Comment by SethTisue** [comment]
https://scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html says:

> The ‘$’ character is reserved for compiler-synthesized identifiers. User programs should not define identifiers which contain ‘$’ characters.

but you're of course right that a proper error message would be better.

**Comment by SethTisue** [comment]
even just compiling `class $anon$1` by itself crashes the compiler, though with a different error message:

```
error: Error while emitting S.scala
assertion failed:
  Cannot create ClassBType from NoSymbol
     while compiling: S.scala
        during phase: jvm
```

**Comment by zoogenic** [comment]
I guess the problem is `$anon$1` itself. It is a reserved anonymous class name. After replacing `$anon$1` with, say, `$bnon$1` the code works fine. And maybe it is another bug, if `$` is prohibited. The following code works:

```
package lectures.part2oop

object AnonymousClasses extends App {
  abstract class Animal {
    def eat: Unit
  }

  class $bnon$1 extends Animal {   // <----- 
    override def eat: Unit = println("brbrbrbrbrbrbrb")
  }

  val funnyAnimal: Animal = new Animal {
    override def eat: Unit = println("aggagagagagagaga")
  }

  val otherAnimal: Animal = new $bnon$1

  println(funnyAnimal.getClass)
  funnyAnimal.eat

  println(otherAnimal.getClass)
  otherAnimal.eat
}
```
**Output**
```
class lectures.part2oop.AnonymousClasses$$anon$1
aggagagagagagaga
class lectures.part2oop.AnonymousClasses$$bnon$1
brbrbrbrbrbrbrb
```

**Comment by SethTisue** [comment]
yeah basically if you use `$` in an identifier you're on your own, you might step on a landmine or you might not

**Comment by dwijnand** [comment]
> but you're of course right that a proper error message would be better.

Better, but "not a bug" or, put differently, an issue worth keeping open, IMO.

**Comment by som-snytt** [comment]
I'm not sure if dwijnand is voting to close or endorsing better behavior.

There are other issues that turn on weird encoding or implementation details.

spec:

The ‘$’ character is reserved for compiler-synthesized identifiers. User programs should not define identifiers which contain ‘$’ characters.

**Comment by SethTisue** [comment]
(earlier I said "a proper error message would be better", but I also agree with closing the ticket; we don't need to litter the bug tracker with opportunities to improve individual error messages, especially in unusual, out-of-bounds situations like this one)
