### ISSUE TITLE
ctl-C in REPL slays instead of some other behavior

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11956]
## reproduction steps

Under Ubuntu subsystem under Windows:

```scala
scala> class D extends C { override def f: Int = 42 } [ctl-C and enter at EOL]
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1367)
        at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
        at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:438)
        at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:458)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:960)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
```

## problem

The part where it slays.

## expectation

No expectation for ctl-C under REPL at this time, but I hit ctl-C by reflex.

I kind of thought it would just exit.

**Comment by SethTisue** [comment]
on MacOS, ctrl-C even on an empty line, but also with Som's sample line, just gives:

```
Exception in thread "main" com.sun.jna.LastErrorException: [5] Input/output error
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at com.sun.proxy.$Proxy0.tcsetattr(Unknown Source)
	at org.jline.terminal.impl.jna.osx.OsXNativePty.doSetAttr(OsXNativePty.java:76)
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
	at org.jline.terminal.impl.AbstractPosixTerminal.doClose(AbstractPosixTerminal.java:76)
	at org.jline.terminal.impl.PosixSysTerminal.doClose(PosixSysTerminal.java:95)
	at org.jline.terminal.impl.AbstractTerminal.close(AbstractTerminal.java:95)
	at scala.tools.nsc.interpreter.jline.Reader.close(Reader.scala:42)
	at scala.tools.nsc.interpreter.shell.ILoop.closeInterpreter(ILoop.scala:142)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:966)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

I guess let's tackle that first, and then see if the fix magically also makes the `InterruptedException` go away

**Comment by SethTisue** [comment]
ah actually I'm only able to reproduce the `com.sun.jna.LastErrorException` under Coursier, whether via https://github.com/dwijnand/scala-runners or with `cs launch --main-class scala.tools.nsc.MainGenericRunner org.scala-lang:scala-compiler:2.13.2 -- -usejavacp`

**Comment by SethTisue** [comment]
also no `LastErrorException` if you e.g. `"java" "-Dscala-compiler.version=2.13.2" "-cp" "/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.2/scala-compiler-2.13.2.jar:/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.2/scala-library-2.13.2.jar:/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.2/scala-reflect-2.13.2.jar:/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.14.1/jline-3.14.1.jar:/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar" "scala.tools.nsc.MainGenericRunner" "-usejavacp"`

so that shows that it isn't something special the `scala` script is doing that's preventing it

ah, and it isn't JLine 3 specific either, or at least something similar happens with JLine 2:

```
% cs launch --main-class scala.tools.nsc.MainGenericRunner org.scala-lang:scala-compiler:2.13.1 -- -usejavacp
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
Type in expressions for evaluation. Or try :help.

scala> 2 + 3
res0: Int = 5

scala> 
Exception in thread "main" java.io.IOException: Input/output error                                                                   
	at java.io.FileInputStream.read0(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:207)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2151)
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2141)
	at jline.console.ConsoleReader.readBinding(ConsoleReader.java:2226)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2467)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
	at scala.tools.nsc.interpreter.jline.JlineReader.readOneLine(JLineReader.scala:72)
	at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine(InteractiveReader.scala:40)
	at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine$(InteractiveReader.scala:38)
	at scala.tools.nsc.interpreter.jline.JlineReader.readLine(JLineReader.scala:37)
	at scala.tools.nsc.interpreter.shell.ILoop.readOneLine(ILoop.scala:473)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:485)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:1020)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

note that I evaluated an expression first, to be sure that everything is fully initialized

**Comment by SethTisue** [comment]
(a different control-C-in-the-REPL bug is https://github.com/scala/bug/issues/11999, which started its life in comments here, but it turned out to be Coursier-only and probably unrelated)
