### ISSUE TITLE
Initialization error in stdlib 

### ISSUE THREAD

**Issue by liufengyun** [scala/bug#11979]
I'm running Dotty initialization checker on stdlib, it reports an error.

I checked the source, it seems to be a true positive to me.

## problem

```scala
[error] -- Error: dotty/community-build/community-projects/stdLib213/src/library/scala/concurrent/impl/Promise.scala:367:26 
[error] 367 |  private[this] final val Noop = new Transformation[Nothing, Nothing](Xform_noop, null, ExecutionContext.parasitic)
[error]     |                          ^
[error]     |Access non-initialized field Noop. Calling trace:
[error]     | -> private[this] final val Noop = new Transformation[Nothing, Nothing](Xform_noop, null, ExecutionContext.parasitic)	[ Promise.scala:367 ]
[error]     |  -> final def this(xform: Int, f: _ => _, ec: ExecutionContext) = this(f.asInstanceOf[Any => Any], ec.prepare(), null, xform)	[ Promise.scala:381 ]
[error]     |   -> ) extends DefaultPromise[T]() with Callbacks[F] with Runnable with Batchable with OnCompleteRunnable {	[ Promise.scala:380 ]
[error]     |    -> final def this() = this(Noop: AnyRef)	[ Promise.scala:113 ]
```

**Comment by lrytz** [comment]
Very nice, congrats on your work! cc @viktorklang

**Comment by dwijnand** [comment]
I tried changing that to explicitly being `null`:

```
-    final def this() = this(Noop: AnyRef)
+    final def this() = this(null)
```

and that completely breaks them:

```
> partest test/files/jvm/future-spec test/files/jvm/scala-concurrent-tck.scala
...
?! 2 - jvm/future-spec                           [caught NoClassDefFoundError - Could not initialize class scala.concurrent.Future$][duration 5.14s]
?! 1 - jvm/scala-concurrent-tck.scala            [caught ExceptionInInitializerError - null][duration 5.14s]
```

which leads me to think it's not a true positive?  But I couldn't tell you why it works...

**Comment by liufengyun** [comment]
Thanks  @dwijnand , that is interesting. I'll look closer to see if I miss something here.

**Comment by dwijnand** [comment]
Just to add: I was just thinking, my diff might be too big a hammer, as it affects all constructions of `DefaultPromise` through that constructor...  But it fails because it can't initialise `Future$` so I think it's having the correct effect.

**Comment by liufengyun** [comment]
I added an assertion:

```Scala
   class DefaultPromise[T] private[this] (initial: AnyRef) extends AtomicReference[AnyRef](initial) with scala.concurrent.Promise[T] with scala.concurrent.Future[T] with (Try[T] => Unit) {
+    assert(initial != null)
```

And the test failed:

```Scala
> partest test/files/jvm/future-spec test/files/jvm/scala-concurrent-tck.scala
...
error: Could not initialize class scala.concurrent.Future$

error: assertion failed
```

**Comment by liufengyun** [comment]
The stack trace seems to confirm it's indeed a true positive:

```Scala
   // Left non-final to enable addition of extra fields by Java/Scala converters in scala-java8-compat.
   class DefaultPromise[T] private[this] (initial: AnyRef) extends AtomicReference[AnyRef](initial) with scala.concurrent.Promise[T] with scala.concurrent.Future[T] with (Try[T] => Unit) {
+    if (initial == null) throw new Exception("initial is null")
     /**
      * Constructs a new, completed, Promise.
      */
@@ -364,8 +365,7 @@ private[concurrent] object Promise {
     override final def toString: String = "ManyCallbacks"
   }

-  private[this] final val Noop = new Transformation[Nothing, Nothing](Xform_noop, null, ExecutionContext.parasitic)
-
+  private[this] final val Noop = try new Transformation[Nothing, Nothing](Xform_noop, null, ExecutionContext.parasitic) catch { case t: Throwable => t.printStackTrace; null  }
```

```
java.lang.Exception: initial is null
	at scala.concurrent.impl.Promise$DefaultPromise.<init>(Promise.scala:105)
	at scala.concurrent.impl.Promise$DefaultPromise.<init>(Promise.scala:114)
	at scala.concurrent.impl.Promise$Transformation.<init>(Promise.scala:380)
	at scala.concurrent.impl.Promise$Transformation.<init>(Promise.scala:381)
	at scala.concurrent.impl.Promise$.liftedTree1$1(Promise.scala:368)
	at scala.concurrent.impl.Promise$.<clinit>(Promise.scala:368)
	at scala.concurrent.impl.Promise$DefaultPromise.<init>(Promise.scala:109)
	at scala.concurrent.Promise$.fromTry(Promise.scala:147)
	at scala.concurrent.Future$.fromTry(Future.scala:651)
        at scala.concurrent.Future$.<clinit>(Future.scala:546)
``

**Comment by viktorklang** [comment]
Given that the code wouldn't pass tests if it didn't work—may I suggest some change in initialization logic which might affect this on Dotty?

**Comment by liufengyun** [comment]
The stack trace and assertion error come from Scala 2.13 compiler. It could be that the `null` value in `DefaultPromise` is never used, thus it is not an issue in practice.

**Comment by dwijnand** [comment]
Ah, I think I know what's happening.  It's only happening for Noop: Noop's initial value is null rather than Noop.  But that value never gets used.  My diff of making it always null for everything is too aggressive.

But I can't see an obvious way to fix that, particularly with Viktor's min/max'ing of bytecode/instructions.

**Comment by viktorklang** [comment]
@dwijnand @liufengyun AFAICS Noop is only used in methods (constructors are methods) and therefor it is alway initialized at the time when it is used. Can you link to a speicific line where it will be null at runtime?

**Comment by dwijnand** [comment]
https://github.com/scala/scala/blob/v2.13.2/src/library/scala/concurrent/impl/Promise.scala#L113

That line, when that's invoked from https://github.com/scala/scala/blob/v2.13.2/src/library/scala/concurrent/impl/Promise.scala#L367

I.e. it's recursive - an initialisation error.  One that doesn't seem to have any effect as Noop's "initial value" is never used.

**Comment by dwijnand** [comment]
@liufengyun I assume this equally reports as an error, right?

```diff
-    final def this() = this(Noop: AnyRef)
+    final def this(noop: Transformation[Nothing, Nothing] = Noop) = this(noop: AnyRef)
```

**Comment by viktorklang** [comment]
@dwijnand Ah, ok, yes—that's a benign side-effect then.

**Comment by liufengyun** [comment]
@dwijnand I just run the test on your diff, the checker reports the same error:

```Scala
[error] -- Error:dotty/community-build/community-projects/stdLib213/src/library/scala/concurrent/impl/Promise.scala:368:26
[error] 368 |  private[this] final val Noop = new Transformation[Nothing, Nothing](Xform_noop, null, ExecutionContext.parasitic)
[error]     |                          ^
[error]     |Access non-initialized field Noop. Calling trace:
[error]     | -> private[this] final val Noop = new Transformation[Nothing, Nothing](Xform_noop, null, ExecutionContext.parasitic)	[ Promise.scala:368 ]
[error]     |  -> final def this(xform: Int, f: _ => _, ec: ExecutionContext) = this(f.asInstanceOf[Any => Any], ec.prepare(), null, xform)	[ Promise.scala:382 ]
[error]     |   -> ) extends DefaultPromise[T]() with Callbacks[F] with Runnable with Batchable with OnCompleteRunnable {	[ Promise.scala:381 ]
[error]     |      -> final def this(noop: Transformation[Nothing, Nothing] = Noop) = this(noop: AnyRef)	[ Promise.scala:113 ]
```

This is not a blocker to us, we reported it with the worry that it might cause unintended effects in corner cases. It is good to know that it does not cause any issue in practice 👍

**Comment by viktorklang** [comment]
Thanks for reporting! 👍
-- 
Cheers,
√
