### ISSUE TITLE
Trying to ctl-c on input slays REPL

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11988]
## reproduction steps

```scala
$ scala
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 11.0.7).
Type in expressions for evaluation. Or try :help.

scala> class D extends C { override def f: Int = 42 }  // up arrow, change mind, hit ctl-C, enter
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1367)
        at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
        at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:438)
        at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:458)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:960)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
```

## problem

```scala
That entry seems to have slain the compiler.
```

## expectation

This is just a facet of control-C handling, for which there may already be a ticket?

A placeholder for "first line of input" usability issues.

This is WSL Ubuntu (YMMV).

**Comment by som-snytt** [comment]
Apparently I tried this already, because who wouldn't?

https://github.com/scala/bug/issues/11956
