### ISSUE TITLE
Missing immutable.Vector#updateAt with `2.13.2`

### ISSUE THREAD

**Issue by regadas** [scala/bug#11981]
## problem

After upgrading from `2.13.1` to `2.13.2` I got the following error:

```
java.lang.NoSuchMethodError: scala.collection.immutable.Vector.updateAt(ILjava/lang/Object;)Lscala/collection/immutable/Vector;
	at com.twitter.algebird.CMSInstance$CountsTable.$plus(CountMinSketch.scala:812)
	at com.twitter.algebird.CMSInstance.$anonfun$$plus$3(CountMinSketch.scala:768)
	at com.twitter.algebird.CMSInstance.$plus(CountMinSketch.scala:765)
	at com.twitter.algebird.CMSItem.$plus$plus(CountMinSketch.scala:612)
	at com.twitter.algebird.CMSItem.$plus$plus(CountMinSketch.scala:602)
	at com.twitter.algebird.CMSMonoid.plus(CountMinSketch.scala:121)
	at com.twitter.algebird.CMSMonoid.plus(CountMinSketch.scala:103)
	at com.spotify.scio.util.Functions$$anon$10$$anonfun$mergeAccumulators$5.apply(Functions.scala:331)
	at com.spotify.scio.util.Functions$Fns$.reduce(Functions.scala:54)
	at com.spotify.scio.util.Functions$Fns$.reduceOption(Functions.scala:62)
	at com.spotify.scio.util.Functions$$anon$10.mergeAccumulators(Functions.scala:331)
	at com.spotify.scio.util.Functions$$anon$10.mergeAccumulators(Functions.scala:321)
	at org.apache.beam.runners.direct.MultiStepCombine$MergeAccumulatorsAndExtractOutputEvaluator.processElement(MultiStepCombine.java:419)
	at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:160)
	at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:124)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

The library `algebird` is currently compiled with `2.13.1`

**Comment by smarter** [comment]
In 2.13.1, `updateAt` was `private[immutable]` so it should not be accessible from the outside: https://github.com/scala/scala/blob/3987e83b7cf0af7c8dcb17a08e8a040ccbe9a5e5/src/library/scala/collection/immutable/Vector.scala#L347
What does the corresponding source code look like? Perhaps algebird was published with inlining inside the standard library erroneously enabled?

**Comment by regadas** [comment]
Hi @smarter I checked `algebird` code and it's not being called directly ... https://github.com/twitter/algebird/blob/7292e8728d25949f1cd00662c9d3d8994795f4d9/algebird-core/src/main/scala/com/twitter/algebird/CountMinSketch.scala#L812

**Comment by smarter** [comment]
bingo: https://github.com/twitter/algebird/blob/515fa2bc0a86c7c5e70afa91571cb297d8df2271/build.sbt#L64 the check above is `scalaVersion.value.startsWith("2.12")` when it should also be using this branch for 2.13, because the default behavior of `-optimize` inlines through everything. So it's an algebird bug build.

**Comment by regadas** [comment]
Ahaha @smarter Thanks! ok I'll fix it right away! i was unaware of that flag! 🙏

**Comment by smarter** [comment]
Note that sbt provides a convenient API for matching against version numbers that should be easier and more robust than string comparisons: https://www.scala-sbt.org/1.x/docs/sbt-1.2-Release-Notes.html#Semantic+Version+selector+API

**Comment by regadas** [comment]
@smarter Gotcha! Thanks! 👍
