### ISSUE TITLE
under `cs launch`, ctrl-C in the repl gives "Input/output error"

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#11999]
on MacOS at least (not sure about other OSs), ctrl-C in the REPL prints an exception before exiting
```
Exception in thread "main" com.sun.jna.LastErrorException: [5] Input/output error
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at com.sun.proxy.$Proxy0.tcsetattr(Unknown Source)
	at org.jline.terminal.impl.jna.osx.OsXNativePty.doSetAttr(OsXNativePty.java:76)
	at org.jline.terminal.impl.AbstractPty.setAttr(AbstractPty.java:29)
	at org.jline.terminal.impl.AbstractPosixTerminal.doClose(AbstractPosixTerminal.java:76)
	at org.jline.terminal.impl.PosixSysTerminal.doClose(PosixSysTerminal.java:95)
	at org.jline.terminal.impl.AbstractTerminal.close(AbstractTerminal.java:95)
	at scala.tools.nsc.interpreter.jline.Reader.close(Reader.scala:42)
	at scala.tools.nsc.interpreter.shell.ILoop.closeInterpreter(ILoop.scala:142)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:966)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

I'm only able to reproduce this `com.sun.jna.LastErrorException` when launching via Coursier, whether through https://github.com/dwijnand/scala-runners or more directly with `cs launch --main-class scala.tools.nsc.MainGenericRunner org.scala-lang:scala-compiler:2.13.2 -- -usejavacp`

also no `LastErrorException` if you e.g. `"java" "-Dscala-compiler.version=2.13.2" "-cp" "/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.2/scala-compiler-2.13.2.jar:/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.2/scala-library-2.13.2.jar:/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.2/scala-reflect-2.13.2.jar:/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.14.1/jline-3.14.1.jar:/Users/tisue/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar" "scala.tools.nsc.MainGenericRunner" "-usejavacp"`

so that shows that it isn't something special the `scala` script is doing that's preventing it

it isn't JLine 3 specific or 213 specific either. something similar, though not exactly the same, happens with JLine 2:

```
% cs launch --main-class scala.tools.nsc.MainGenericRunner org.scala-lang:scala-compiler:2.13.1 -- -usejavacp
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
Type in expressions for evaluation. Or try :help.

scala> 2 + 3
res0: Int = 5

scala> 
Exception in thread "main" java.io.IOException: Input/output error                                                                   
	at java.io.FileInputStream.read0(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:207)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:257)
	at jline.internal.InputStreamReader.read(InputStreamReader.java:194)
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2151)
	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2141)
	at jline.console.ConsoleReader.readBinding(ConsoleReader.java:2226)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2467)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2378)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2366)
	at scala.tools.nsc.interpreter.jline.JlineReader.readOneLine(JLineReader.scala:72)
	at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine(InteractiveReader.scala:40)
	at scala.tools.nsc.interpreter.shell.InteractiveReader.readLine$(InteractiveReader.scala:38)
	at scala.tools.nsc.interpreter.jline.JlineReader.readLine(JLineReader.scala:37)
	at scala.tools.nsc.interpreter.shell.ILoop.readOneLine(ILoop.scala:473)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:485)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:1020)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

note that I evaluated an expression first, to be sure that everything is fully initialized — if you ctrl-C immediately, it quits without any exception

**Comment by SethTisue** [comment]
@alexarchambault do you have any guesses at what `cs launch` might be doing differently, somehow, that leads to this...? /cc @dwijnand

**Comment by dwijnand** [comment]
This is to do with the differences between `coursier` and `cs`.  I'd seen another instance of this, but forget the details...  `cs` is the graal native-image while `coursier` is an executable jar.  It's something to do with JVM forking or classpath or similar.

See how it's not broken with `coursier`:

```
$ coursier launch scala:2.13.2
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 11.0.6).
Type in expressions for evaluation. Or try :help.

scala> 2 + 3
val res0: Int = 5

scala>
:quit
$
```

---

Btw:

> also no `LastErrorException` if you e.g. `"java" "-Dscala-compiler.version=2.13.2" "-cp" "/Users/tisue/Library/Caches[...]

there's a handy intermediate, FYI:

```
$ java -Dscala-compiler.version=2.13.2 \
>   -cp $(cs fetch -p org.scala-lang:scala-compiler:2.13.2) \
>   scala.tools.nsc.MainGenericRunner -usejavacp
Welcome to Scala 2.13.2 (OpenJDK 64-Bit Server VM, Java 11.0.6).
Type in expressions for evaluation. Or try :help.

scala> 2 + 3
val res0: Int = 5

scala>
:quit
$```

**Comment by dwijnand** [comment]
OK, found the comment (https://github.com/coursier/coursier/issues/1519#issuecomment-578765724) but the details it gives don't seem relevant in this case: `cs launch --fork` errors just like before `coursier launch --fork` don't error just like before...

**Comment by alexarchambault** [comment]
I would say the problem originates from the coursier native launcher, rather than from scala. More precisely from the way `ProcessBuilder` works from the GraalVM native images.

The native launcher forks by default, that is starts apps in a separate process via a `java.lang.ProcessBuilder`. From the JVM, starting the app via a `ProcessBuilder` with `--fork`, works fine (as you found out, @dwijnand), so I would blame how it works from native images.

As a temporary workaround, one can pass `--jvm 8`, like
```bash
$ cs launch scala:2.13.2 --jvm 8
```
(this downloads, unpacks, and uses a AdoptOpenJDK 8 under `~/Library/Caches/Coursier/jvm`, if you don't already have one)

Because of some ~implementation details, `--jvm …` starts the app via the `execve` system call rather than via `java.lang.ProcessBuilder`. It seems this messes less with the started app input / output. Using execve should be the default, but it's not yet.

**Comment by alexarchambault** [comment]
@dwijnand `--fork` is ignored from the native launcher for now. Its equivalent from the native launcher would be `--execve`, which uses the `execve` system call to start the app in the current process rather than starting a new process, and watch it from the side. But it's interpreted as just a hint for now, and doesn't work if one doesn't pass `--jvm …`. I guess the native launcher should interpret `--fork` as "use ProcessBuilder rather than execve", that needs to be fixed.

**Comment by dwijnand** [comment]
Ah, I understand.  Thanks for all that, Alex.  Is there any benefit in using ProcessBuilder over execve?  I.e. why not just make `--fork` a deprecated alias of `--execve`?  Drops a variant, keeping things simpler/more uniform.

**Comment by alexarchambault** [comment]
I was more feeling like scrapping `--execve`. By default, `launch` would start apps in its own process, via class loading for the JVM launcher and via `execve` for the native launcher. If `--fork` is passed, both would use `ProcessBuilder` instead.

I'd be in favor of keeping `--fork`. Even though we ran into a limitation of `ProcessBuilder`, it feels less hacky than classloading things from the same JVM, or using `execve`, whose usage isn't very common from Java / Scala apps. `--fork` can be useful for debugging in particular.

Plus on Windows, `execve` isn't available, so we'll need to keep some `ProcessBuilder` logic around anyway.
