### ISSUE TITLE
Scala REPL is broken on rxvt

### ISSUE THREAD

**Issue by atk91** [scala/bug#12004]
## reproduction steps

using Scala 2.13.2, Linux, urxvt terminal emulator (or xterm with forced TERM variable, see below)

```
$ TERM=rxvt-unicode-256color scala
Welcome to Scala 2.13.2-20200423-084825-unknown (OpenJDK 64-Bit Server VM, Java 11.0.6).
Type in expressions for evaluation. Or try :help.
Exception in thread "main" java.io.IOError: java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at org.jline.utils.Curses.tputs(Curses.java:62)
	at org.jline.utils.Curses.tputs(Curses.java:45)
	at org.jline.keymap.KeyMap.key(KeyMap.java:243)
	at org.jline.reader.impl.LineReaderImpl.key(LineReaderImpl.java:6095)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.jline.reader.impl.LineReaderImpl.bindKeys(LineReaderImpl.java:6103)
	at org.jline.reader.impl.LineReaderImpl.emacs(LineReaderImpl.java:5813)
	at org.jline.reader.impl.LineReaderImpl.defaultKeyMaps(LineReaderImpl.java:5789)
	at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:293)
	at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:115)
	at scala.tools.nsc.interpreter.jline.Reader$.apply(Reader.scala:94)
	at scala.tools.nsc.interpreter.shell.ILoop.defaultIn$lzycompute(ILoop.scala:68)
	at scala.tools.nsc.interpreter.shell.ILoop.defaultIn(ILoop.scala:63)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:944)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.jline.utils.Curses.doTputs(Curses.java:359)
	at org.jline.utils.Curses.tputs(Curses.java:60)
	... 26 more

```

## problem

REPL does not start

It seems that problem is in JLine3, which cannot test itself under same circumstances https://github.com/jline/jline3/issues/533

After `git bisect`ing one can find that commit that introduced this is https://github.com/scala/scala/commit/77c7c477cc9ba6212bfd3ced3d034b70c6ea1b9f

Nevertheless, if and when it will be fixed, the JLine version still needs to be bumped in Scala.

**Comment by SethTisue** [comment]
tentatively milestoned 2.13.4 since it's unlikely there'll be a new JLine version in time for 2.13.3, but you never know. I've subscribed to the JLine ticket

workaround advice you offered on Gitter:

> you can set TERM=xterm-256color (but other things may break), or launch REPL inside tmux or screen

**Comment by SethTisue** [comment]
hmm maybe they will roll a release soon! https://github.com/jline/jline3/issues/532

**Comment by LeifW** [comment]
JLine 3.15.0 has been released: https://github.com/jline/jline3/issues/532

**Comment by SethTisue** [comment]
it seems from https://github.com/jline/jline3/issues/550 that moving to JLine 3.5.0 may only accomplished replacing the `StringIndexOutOfBoundsException` with a `NullPointerException`? @atk91 does it work for you with 2.13.3?

cc @konteal

**Comment by LeifW** [comment]
Yeah, I get the NPE now on Scala 2.13.3:
```
Welcome to Scala 2.13.3-20200701-163819-unknown (OpenJDK 64-Bit Server VM, Java 14.0.1).
Type in expressions for evaluation. Or try :help.
Jul 06, 2020 12:14:48 PM org.jline.utils.Log logr
WARNING: Unable to retrieve infocmp for type rxvt-unicode-256color
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at org.jline.utils.InputStreamReader.<init>(InputStreamReader.java:135)
	at org.jline.utils.InfoCmp.loadDefaultInfoCmp(InfoCmp.java:612)
	at org.jline.utils.InfoCmp.lambda$static$3(InfoCmp.java:623)
	at org.jline.utils.InfoCmp.getLoadedInfoCmp(InfoCmp.java:557)
	at org.jline.utils.InfoCmp.getInfoCmp(InfoCmp.java:545)
	at org.jline.terminal.impl.AbstractTerminal.parseInfoCmp(AbstractTerminal.java:202)
	at org.jline.terminal.impl.PosixSysTerminal.<init>(PosixSysTerminal.java:44)
	at org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:368)
	at org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:263)
	at scala.tools.nsc.interpreter.jline.Reader$.apply(Reader.scala:72)
	at scala.tools.nsc.interpreter.shell.ILoop.defaultIn$lzycompute(ILoop.scala:68)
	at scala.tools.nsc.interpreter.shell.ILoop.defaultIn(ILoop.scala:63)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:952)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by LeifW** [comment]
Well, it's not like it's *only* swapped `StringIndexOutOfBoundsException` for `NullPointerException` - the former would exit the repl, while the latter seems informational only - if I wait a second, the repl appears, and appears to work as normal, aside from the "The readline I get then fails to interpret control keys such as Home, End, Delete and Backspace, giving back control sequences like [~7 and so." mentioned on the linked issue.

I never knew those keys were options to use in the REPL to begin with - so this issue is basically "fixed" for me, other than it printing that stacktrace on startup...

**Comment by SethTisue** [comment]
that's good to hear. I'll leave the ticket open regardless since we'll want to get a newer JLine into 2.13.4 if one becomes available

**Comment by atk91** [comment]
@SethTisue I got NPE logged as well, but REPL works

**Comment by SethTisue** [comment]
2.13.4 will use JLine 3.16.0

**Comment by robstoll** [comment]
hitting the same problem again with sbt 1.6.2 in conjunction with `sbt -client`
`TERM=xterm-256color sbt -client` still works though
