### ISSUE TITLE
Migrating code to scala 2.13 : compiler crashes with "head of empty list" error

### ISSUE THREAD

**Issue by gaospina** [scala/bug#12041]
## reproduction steps

Clone this repository: https://github.com/gaospina/bac-a-sable.git

Compile the code with SBT or IntelliJ.

## problem

I want to migrate a project from Scala 2.12 to Scala 2.13. Of course, the code has several issues on deprecated code, and I solved the majority of those issues. But at the end I always get an error from the Scala compiler that is not directly related to the source code: 

```
Error:scalac: Error: head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:629)
	at scala.collection.immutable.Nil$.head(List.scala:628)
	at scala.reflect.internal.Types$TypeRef.customToString(Types.scala:2675)
	at scala.reflect.internal.Types$TypeRef.safeToString(Types.scala:2702)
	at scala.reflect.internal.tpe.TypeToStrings.typeToString(TypeToStrings.scala:55)
	at scala.reflect.internal.tpe.TypeToStrings.typeToString$(TypeToStrings.scala:34)
	at scala.reflect.internal.SymbolTable.typeToString(SymbolTable.scala:28)
	at scala.reflect.internal.Types$Type.toString(Types.scala:943)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1191)
	at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1186)
	at scala.collection.AbstractIterable.addString(Iterable.scala:920)
	at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1136)
	at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1134)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.NotWithinBoundsErrorMessage(ContextErrors.scala:1214)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.NotWithinBounds(ContextErrors.scala:1222)
	at scala.tools.nsc.typechecker.Infer$Inferencer.issueBoundsError$1(Infer.scala:982)
	at scala.tools.nsc.typechecker.Infer$Inferencer.check$1(Infer.scala:988)
	at scala.tools.nsc.typechecker.Infer$Inferencer.checkBounds(Infer.scala:992)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTypeApply(Typers.scala:4385)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:953)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit0(Implicits.scala:812)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.scala$tools$nsc$typechecker$Implicits$ImplicitSearch$$typedImplicit(Implicits.scala:631)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.rankImplicits(Implicits.scala:1222)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch$ImplicitComputation.findBest(Implicits.scala:1257)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.searchImplicit(Implicits.scala:1314)
	at scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1743)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
	at scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
	at scala.tools.nsc.Global$$anon$5.inferImplicit(Global.scala:482)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
	at scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
	at scala.tools.nsc.Global$$anon$5.inferImplicitFor(Global.scala:482)
	at scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:272)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:888)
	at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:492)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1305)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6035)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:6118)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5964)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6109)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1128)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1735)
	at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1909)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1873)
	at scala.tools.nsc.typechecker.Namers$Namer$MonoTypeCompleter.completeImpl(Namers.scala:875)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2057)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2055)
	at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2050)
	at scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1541)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1513)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1702)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5620)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6098)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2572)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5938)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5973)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:6297)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5928)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6098)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2082)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1912)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5929)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6098)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3452)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5629)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5932)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6020)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:117)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:105)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1505)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1489)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1616)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:42)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:43)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:117)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:109)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:95)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:53)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

## running environment

Scala 2.13.2
SBT 1.13.12

## expectation

The code should compile with several warnings (deprecation and migration warnings I didn't see yet because of this weird error). With some slight modifications the code compiles in Scala 2.12.11. A compile error related to the migration to Scala 2.13 may still be possible.

**Comment by som-snytt** [comment]
Same superficial symptom at https://github.com/scala/bug/issues/10700

I turned up some options and `sbt compile > file`:
```
[warn] 92 warnings found
[error] 5 errors found
[snip]
[error] java.lang.NullPointerException
[error]         at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:181)
[error]         at scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
[error]         at scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:93)
[error]         at scala.reflect.internal.Reporter.echo(Reporting.scala:112)
[error]         at scala.reflect.internal.Reporting.inform(Reporting.scala:73)
[error]         at scala.reflect.internal.Reporting.inform$(Reporting.scala:73)
[error]         at scala.reflect.internal.SymbolTable.inform(SymbolTable.scala:28)
[error]         at scala.reflect.internal.Reporting.inform(Reporting.scala:56)
[error]         at scala.reflect.internal.Reporting.inform$(Reporting.scala:56)
[error]         at scala.reflect.internal.SymbolTable.inform(SymbolTable.scala:28)
[error]         at scala.tools.nsc.Global.debuglog(Global.scala:311)
[error]         at scala.reflect.internal.SymbolTable$perRunCaches$.clearAll(SymbolTable.scala:450)
[error]         at scala.tools.nsc.Global.close(Global.scala:1735)
[error]         at xsbt.CachedCompiler0.close(CompilerInterface.scala:100)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:98)
```

**Comment by joroKr21** [comment]
`at scala.reflect.internal.Types$TypeRef.safeToString(Types.scala:2702)`
haha are you sure it's safe?

#10700 should be a compile error now, not a crash

**Comment by gaospina** [comment]
> 
> I turned up some options and `sbt compile > file`:
> 
What compiler options have you turned up ?

**Comment by joroKr21** [comment]
Reproduction: `def foo(xs: Int*) = new util.Random().shuffle(xs)`

**Comment by joroKr21** [comment]
```scala
scala> def dup[T](x: T)(y: x.type) = (x, y)
def dup[T](x: T)(y: x.type): (T, T)

scala> def foo(xs: Seq[Int]) = dup(xs)(xs)
def foo(xs: Seq[Int]): (Seq[Int], Seq[Int])

scala> def bar(xs: Int*) = dup(xs)(xs)
                                   ^
       error: type mismatch;
        found   : Seq[Int]
        required: Int
```

**Comment by SethTisue** [comment]
this regressed sometime between 2.13.0-M5 and 2.13.0-RC1. nothing at https://github.com/scala/scala/releases/tag/v2.13.0-RC1 jumps out at me. it might be worth bisecting to find the exact PR where it regressed.

**Comment by joroKr21** [comment]
It could be something related to singleton types

**Comment by dwijnand** [comment]
After adding this workaround in `safetoString`:

```scala
-      case RepeatedParamClass | JavaRepeatedParamClass => args.head.toString + "*"
+      case RepeatedParamClass | JavaRepeatedParamClass => args.headOption.fold("?*")(t => s"$t*")
```

The shuffle minimisation gives

```
scala> def foo(xs: Int*) = new util.Random().shuffle(xs)
                                                    ^
       error: Cannot construct a collection of type C with elements of type Int based on a collection of type xs.type.
```

**Comment by demming** [comment]
I've just experienced the same issue with Scala 2.13.8 (with and without using JetBrains' Scala compile server) compiling an endpoint description using tapir with the zio-http interpreter. I could reproduce it for the following [example](https://tapir.softwaremill.com/en/latest/server/ziohttp.html) from tapir's docs.

```scala
object ServerTapirZioBug {
  import sttp.tapir.ztapir.{endpoint, plainBody, stringBody, RichZEndpoint}
  import sttp.tapir.server.ziohttp.ZioHttpInterpreter
  import zio.ZIO

  def countCharacters(s: String) = ZIO.succeed(s.length)
  val countCharactersEndpoint = endpoint.in(stringBody).out(plainBody[Int])
  val countCharactersHttp = ZioHttpInterpreter().toHttp(countCharactersEndpoint.zServerLogic(countCharacters))
}
```

The issue is apparently caused by a transitive dependency unexpectedly pulling zio-2, while the tapir-zio module [depends on zio-1](https://github.com/softwaremill/tapir/blob/08b3116cd848212ed7cbd806ae9c3d69944d381f/build.sbt#L410-L414), cf. the [version list](https://github.com/softwaremill/tapir/blob/08b3116cd848212ed7cbd806ae9c3d69944d381f/project/Versions.scala#L23). That `ZIO` semantics is from zio-2 but `ZioHttpInterpreter` expects zio-1 semantics. I haven't had an opportunity to dig deeper, since the transitive dependency is undesired at this point.

<details>
<summary>
Here's the full stack trace:
</summary>

```
scalac: Error: head of empty list
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662)
	at scala.collection.immutable.Nil$.head(List.scala:661)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.NotWithinBoundsErrorMessage(ContextErrors.scala:1235)
	at scala.tools.nsc.typechecker.ContextErrors$InferencerContextErrors$InferErrorGen$.NotWithinBounds(ContextErrors.scala:1242)
	at scala.tools.nsc.typechecker.Infer$Inferencer.issueBoundsError$1(Infer.scala:981)
	at scala.tools.nsc.typechecker.Infer$Inferencer.check$1(Infer.scala:987)
	at scala.tools.nsc.typechecker.Infer$Inferencer.checkBounds(Infer.scala:991)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.scala$tools$nsc$typechecker$RefChecks$RefCheckTransformer$$checkBounds(RefChecks.scala:1248)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$RefCheckTypeMap$.checkTypeRef(RefChecks.scala:1465)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$RefCheckTypeMap$.apply(RefChecks.scala:1453)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$RefCheckTypeMap$.apply(RefChecks.scala:1410)
	at scala.reflect.internal.Types$TypeRef.mapOver(Types.scala:2366)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$RefCheckTypeMap$.apply(RefChecks.scala:1455)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$RefCheckTypeMap$.check(RefChecks.scala:1435)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1795)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:81)
	at scala.reflect.internal.Trees$ValDef.$anonfun$transform$4(Trees.scala:433)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.reflect.internal.Trees$ValDef.transform(Trees.scala:432)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1887)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1232)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1212)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:81)
	at scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1887)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:81)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
	at scala.reflect.internal.Trees$ModuleDef.$anonfun$transform$3(Trees.scala:396)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.reflect.internal.Trees$ModuleDef.transform(Trees.scala:395)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1887)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1243)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1212)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:81)
	at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:342)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:342)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1887)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:183)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:32)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:459)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:406)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1524)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1500)
	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1613)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
	at xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
	at xsbt.CompilerBridge.run(CompilerBridge.scala:39)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:57)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.doCompile(LocalServer.scala:52)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:30)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$4(ScalaBuilder.scala:65)
	at scala.util.Either.map(Either.scala:382)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$3(ScalaBuilder.scala:47)
	at scala.util.Either.flatMap(Either.scala:352)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.$anonfun$compile$2(ScalaBuilder.scala:46)
	at scala.util.Either.flatMap(Either.scala:352)
	at org.jetbrains.jps.incremental.scala.ScalaBuilder$.compile(ScalaBuilder.scala:44)
	at org.jetbrains.jps.incremental.scala.IdeaIncrementalBuilder.build(IdeaIncrementalBuilder.scala:83)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1529)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1163)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1310)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1128)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:877)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:459)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:197)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:131)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:334)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:162)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

**Comment by som-snytt** [comment]
The example repo, on the failing June commit, now says on 2.13.8:
```
bac-a-sable/src/main/scala/oscar/cbls/lib/search/neighborhoods/vlsn/MoveExplorer.scala:339:31: type mismatch;
[error]  found   : scala.collection.MapView[Int,Iterable[Int]]
[error]  required: Map[Int,Iterable[Int]]
[error]     exploreInsertionsNoRemove(vehicleToUnroutedNodeToInsert)
[error]                               ^
```
The linked ticket https://github.com/scala/bug/issues/10700 is still open, although it has a mitigation.
