### ISSUE TITLE
regression: Broken binary compatibility in scala-library-2.12.12 `ListMap.apply`

### ISSUE THREAD

**Issue by neko-kai** [scala/bug#12081]
## reproduction steps

using Scala 2.12.12, when running the following code compiled with an earlier Scala version

```scala
ListMap()
```

## problem

Getting an exception:

```scala
java.lang.NoSuchMethodError: 'scala.collection.GenMap scala.collection.immutable.ListMap$.apply(scala.collection.Seq)'
```

Full stack trace, happens when using `deriveEncoder` macro from `circe-derivation-0.13.0-M4`:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'scala.collection.GenMap scala.collection.immutable.ListMap$.apply(scala.collection.Seq)'
        at io.circe.derivation.DerivationMacros.caseClassFieldsDefaults(DerivationMacros.scala:720)
        at io.circe.derivation.DerivationMacros.membersFromPrimaryConstr(DerivationMacros.scala:187)
        at io.circe.derivation.DerivationMacros.$anonfun$productRepr$1(DerivationMacros.scala:200)
        at scala.Option.orElse(Option.scala:477)
        at io.circe.derivation.DerivationMacros.productRepr(DerivationMacros.scala:200)
        at io.circe.derivation.DerivationMacros.materializeEncoderCaseClassImpl(DerivationMacros.scala:548)
        at io.circe.derivation.DerivationMacros.materializeEncoderImpl(DerivationMacros.scala:681)
        at io.circe.derivation.DerivationMacros.materializeEncoder(DerivationMacros.scala:238)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$5(JavaReflectionRuntimes.scala:45)
        at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:758)
        at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:734)
        at scala.tools.nsc.Global$$anon$5.macroExpandWithRuntime(Global.scala:483)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:564)
        at scala.tools.nsc.Global.withInfoLevel(Global.scala:226)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:557)
        at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:544)
        at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:719)
        at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:717)
        at scala.tools.nsc.Global$$anon$5.standardMacroExpand(Global.scala:483)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:456)
        at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$10.default(AnalyzerPlugins.scala:453)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:410)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:453)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:453)
        at scala.tools.nsc.Global$$anon$5.pluginsMacroExpand(Global.scala:483)
        at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:708)
        at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:701)
        at scala.tools.nsc.Global$$anon$5.macroExpand(Global.scala:483)
        at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1212)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1277)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1250)
        at scala.tools.nsc.typechecker.Typers$Typer.adaptAfterOverloadResolution(Typers.scala:1284)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1245)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5900)
        at scala.tools.nsc.typechecker.Typers$Typer.typedValDefImpl(Typers.scala:6141)
        at scala.tools.nsc.typechecker.Typers$Typer.typedValDef(Typers.scala:2098)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5792)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2049)
        at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1879)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5794)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2049)
        at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1924)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5795)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5950)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3394)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3394)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5494)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5797)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5886)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:452)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:104)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1482)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:48)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:30)
        at scala.tools.nsc.Driver.process(Driver.scala:68)
        at scala.tools.nsc.Driver.main(Driver.scala:82)
```

**Comment by lrytz** [comment]
Hmm, I can't reproduce it with a simple example. Can you maybe share a sample project that shows the failure?

**Comment by neko-kai** [comment]
@lrytz I think that was a false positive I got from running Scala 2.13 compiler against scala-library-2.12, sorry for the misleading report.
