### ISSUE TITLE
2.12.12: Regression in 

### ISSUE THREAD

**Issue by dieu** [scala/bug#12084]
## reproduction steps

Using the latest 2.12.12 release with graal native-image is throw error in runtime.

## problem

The problem with the usage of MethodHandler in https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/immutable/VM.java#L24

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.LambdaForm$MH/1405562130.invoke_MT(Object, Object)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:86)
	at scala.collection.immutable.VM.releaseFence(VM.java:25)
	at scala.collection.immutable.HashSet$HashSetBuilder.result(HashSet.scala:1283)
	at scala.collection.immutable.Set$SetBuilderImpl.result(Set.scala:344)
	at scala.collection.immutable.Set$SetBuilderImpl.result(Set.scala:329)
	at scala.collection.generic.GenericCompanion.apply(GenericCompanion.scala:57)
```

**Comment by dieu** [comment]
similar substitution for `scala.collection.immutable.VM` as here: https://github.com/plokhotnyuk/jsoniter-scala/commit/e089f06c2d8b4bdb87a6874e17bf716e8608b117 -- works as well as a workaround for 2.12.12

**Comment by dwijnand** [comment]
Hi.  What version of GraalVM and for what Java 8 or Java 11?

**Comment by dieu** [comment]
Java 8 and 20.1.0

**Comment by SethTisue** [comment]
as with #12116, this may progress on the Graal side: https://github.com/scala/bug/issues/12116#issuecomment-712270196

**Comment by SethTisue** [comment]
and workarounds and knowhow are accumulating at https://github.com/scalameta/sbt-native-image
