### ISSUE TITLE
Replay fails in REPL

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12124]
## reproduction steps

using Scala 2.13.3,

```scala
scala> case class C(i: Int, j: Int)
class C

scala> { (i: Int, j) => C(i, j) }
java.lang.NullPointerException
	at scala.reflect.internal.Types$TypeRef.computeHashCode(Types.scala:2416)
[snip]

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]y
replay> case class C(i: Int, j: Int)
Exception in thread "main" java.lang.NullPointerException
	at scala.reflect.internal.Types$TypeRef.computeHashCode(Types.scala:2416)
```

## problem

It's supposed to re-run the first line successfully and stop. Instead it goes to replay it but sees the line 2 exception instead.

Weird, huh?

Noticed this at https://github.com/scala/bug/issues/12122 because how often does one slay the compiler these days?

**Comment by dwijnand** [comment]
Schrödinger's reproduction...

**Comment by SethTisue** [comment]
How broad is this problem? Does any compiler crash fail to replay, or only certain ones? If it's a pretty common problem then it's actually worth fixing, if it's super-specific maybe not.

**Comment by som-snytt** [comment]
I think it's an off-by-one, and possibly I logged a duplicate issue about it.

Alternative fix is to change the text from REPL:
```
I can re-run each line including the last one.
```
