### ISSUE TITLE
"Error while emitting" with bind to literal in match and literal type result

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12127]
## reproduction steps

```scala
scala 2.13.3> def f(x: Any): "hi" = x match { case s @ "hi" => s }
error: Error while emitting <console>
value s
```

## problem

Compiles normally when result type is `String` (as is inferred).

Trace under `-Vdebug`:
```
java.util.NoSuchElementException: value s
        at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:505)
        at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:504)
        at scala.collection.mutable.AnyRefMap.apply(AnyRefMap.scala:205)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$locals$.load(BCodeSkelBuilder.scala:428)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:361)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.$anonfun$genLoadLabelArguments$4(BCodeBodyBuilder.scala:912)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadLabelArguments(BCodeBodyBuilder.scala:912)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:640)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:303)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadIf(BCodeBodyBuilder.scala:205)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:286)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLabelDef(BCodeBodyBuilder.scala:483)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:266)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:87)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:803)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:373)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:641)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:673)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:546)
```

Noticed at https://github.com/scala/bug/issues/12119

**Comment by dwijnand** [comment]
This is `def h3` in neg/t1503.scala in scala/scala#8874.

**Comment by SethTisue** [comment]
Dotty 0.27.0-RC1:

```scala
scala> def f(x: Any): "hi" = x match { case s @ "hi" => s }                                                             
1 |def f(x: Any): "hi" = x match { case s @ "hi" => s }
  |                                                 ^
  |                                                 Found:    (s : Any)
  |                                                 Required: ("hi" : String)
```

which is what I’d expect — I would expect `s` to get the widened type (`String`), asking the expected singleton type to flow all the way down into the `case s @ ...` seems like a pretty big stretch

**Comment by som-snytt** [comment]
As dwijnand linked, this is the thing where the match is just equality, so `s` is `Any`.

The other expectation is
```
def f(x: Any): "hi" = x match { case s: "hi" => s }
```

**Comment by SethTisue** [comment]
(oh, I missed that `s` is `Any` and not `String`)
