### ISSUE TITLE
Running Scala script with -save crashes with NPE at GenBCode$BCodePhase.close(GenBCode.scala:106)

### ISSUE THREAD

**Issue by robby-phd** [scala/bug#12134]
## reproduction steps

Download [scala-save-bug.zip](https://github.com/scala/bug/files/5146253/scala-save-bug.zip); using Scala 2.13.3 (tested with OpenJDK Zulu14.29+23-CA (build 14.0.2+12)):

```
$ unzip scala-save-bug.zip
$ cd scala-save-bug
$ bash -ex test.sh
+ '[' '!' -f plugin.jar ']'
+ curl -s -JLo plugin.jar https://jitpack.io/org/sireum/scalac-plugin/4.20200829.945da6d/scalac-plugin-4.20200829.945da6d.jar
+ rm -fR test.jar
+ scala -Xplugin:plugin.jar -classpath lib.jar -howtorun:script test.sc
warning: 1 deprecation (since 2.13.0); re-run with -deprecation for details
Hello World!
+ scala -Xplugin:plugin.jar -classpath lib.jar -howtorun:script -save test.sc
Exception in thread "main" java.lang.NullPointerException
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.close(GenBCode.scala:106)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.$anonfun$run$1(GenBCode.scala:82)
	at scala.tools.nsc.backend.jvm.GenBCode$BCodePhase.run(GenBCode.scala:76)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1626)
	at scala.tools.nsc.DefaultScriptRunner.doCompile(ScriptRunner.scala:67)
	at scala.tools.nsc.AbstractScriptRunner.compile$1(ScriptRunner.scala:103)
	at scala.tools.nsc.AbstractScriptRunner.recompile$1(ScriptRunner.scala:125)
	at scala.tools.nsc.AbstractScriptRunner.$anonfun$withCompiledScript$9(ScriptRunner.scala:142)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:55)
	at scala.tools.nsc.AbstractScriptRunner.runScript(ScriptRunner.scala:151)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

## problem

As can be seen above, running the script (with the plugin) without `-save` works, but it crashes with `-save`.

**Comment by som-snytt** [comment]
This is due to https://github.com/scala/scala/pull/8564 which makes `-d` work when using `-save`, so that users can specify where the save happens. 

It looks like the plugin creates a dir `test.jar` which conflicts. The classfile writer assumes a `.jar` is a regular file, but the exception is superseded by the NPE (caused in some cleanup after incomplete initialization)

A workaround is to use `-d /tmp/out` where the destination is not a jar.

Note that the archive name is now `test.jar` and not `test.sc.jar` as per @lrytz 's ominous [comment](https://github.com/scala/scala/pull/8564#discussion_r352613609).

```
➜  scala-save-bug skala -J-XX:+ShowCodeDetailsInExceptionMessages -d /tmp/out -save -Xlint -Xplugin:plugin.jar -classpath lib.jar -howtorun:script test.sc 
with latest jar file test.jar with settings.out -d = /tmp/out
compile test.sc to /tmp/out
test.sc:1: warning: Passing an explicit array value to a Scala varargs method is deprecated (since 2.13.0) and will result in a defensive copy; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
// #Sireum
^
Hello World!
➜  scala-save-bug ls /tmp/out
Main$$anon$1.class Main$.class        Main.class         transformed
➜  scala-save-bug skala -J-XX:+ShowCodeDetailsInExceptionMessages -d /tmp/bad.jar -save -Xlint -Xplugin:plugin.jar -classpath lib.jar -howtorun:script test.sc
with latest jar file /tmp/bad.jar with settings.out -d = /tmp/bad.jar
compile test.sc to /tmp/bad.jar
test.sc:1: warning: Passing an explicit array value to a Scala varargs method is deprecated (since 2.13.0) and will result in a defensive copy; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
// #Sireum
^
error: /tmp/bad.jar (Is a directory)
```
The error is terse, but is no longer NPE after forthcoming PR.

**Comment by robby-phd** [comment]
@som-snytt Thanks for looking into this and describing the specific change and the actual underlying issue.  I have adapted the plugin so that it does not assume the output directory is not inside a jar file, thus avoiding creating the .jar parent directory.
