### ISSUE TITLE
Future hangs when used from an object that indirectly extends App

### ISSUE THREAD

**Issue by liff** [scala/bug#12135]
## reproduction steps

using Scala 2.13.x or 2.12.x, JVM 8 or 11.

Write file `Main.scala` with:

```scala
import scala.concurrent.ExecutionContext.Implicits.global
import scala.concurrent.{Await, Future}
import scala.concurrent.duration.Duration

trait MyApp extends App {
  def execute(): Unit

  execute()
}

object Main extends MyApp {
  def execute(): Unit = Await.result(Future(println("hi")), Duration.Inf)
}
```

Compile and run:

```bash
$ scalac Main.scala
$ scala Main
```

Running the program hangs and never prints “hi”.

## problem

On 2.11.12 and 2.10.7 it works as expected.

If I create a small sbt project with the above code, run it, terminate it with CTRL-C and then exit sbt, I get this error which looks like it’s likely related.

```
java.lang.NoClassDefFoundError: Could not initialize class Main$
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:671)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
        at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
	at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
	at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
	at scala.concurrent.BatchingExecutor$AsyncBatch.run(BatchingExecutor.scala:154)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)[error] (run-main-0) java.lang.ExceptionInInitializerError

	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

Changing the code to extend from `App` directly works as expected:

```scala
object Main extends App {
  def execute(): Unit = Await.result(Future(println("hi")), Duration.Inf)

  execute()
}
```

**Comment by som-snytt** [comment]
The scaladoc says:

> Classes and objects (but note, not traits) inheriting the DelayedInit marker trait will have their initialization code rewritten as follows: code becomes delayedInit(code).

Changing from trait to abstract class results in the expected behavior.

There are issues about the problem with DelayedInit, which is deprecated, and starting threads from an object's static initializer.

**Comment by SethTisue** [comment]
@liff a good place to ask about well-known gotchas like this is https://users.scala-lang.org
