### ISSUE TITLE
Map concat throwing NullPointerException

### ISSUE THREAD

**Issue by davidpadbury-da** [scala/bug#12140]
### 2.12.11

In Scala 2.12.11 the following program will throw a `NullPointerException`:

```scala
object MapConcatNpe {
  trait DataType              extends Product with Serializable
  case class Foo(arg: String) extends DataType
  case class Bar(arg: String) extends DataType

  def main(args: Array[String]): Unit = {
    val mapWithCollision = Map(Foo("toxic") -> 0, Bar("toxic") -> 0, Bar("2") -> 0, Bar("3") -> 0, Bar("4") -> 0)

    val other = Map(Foo("toxic") -> 0, Bar("5") -> 0, Bar("6") -> 0, Bar("7") -> 0, Bar("8") -> 0)

    mapWithCollision ++ other
  }
}
```

```
java.lang.NullPointerException
        at scala.collection.immutable.ListMap$Node.$plus(ListMap.scala:174)
        at scala.collection.immutable.HashMap$HashMapCollision1.updated0(HashMap.scala:425)
        at scala.collection.immutable.HashMap$HashMap1.merge0(HashMap.scala:387)
        at scala.collection.immutable.HashMap$HashTrieMap.mergeCommon$1(HashMap.scala:836)
        at scala.collection.immutable.HashMap$HashTrieMap.merge0(HashMap.scala:879)
        at scala.collection.immutable.HashMap.merged(HashMap.scala:137)
        at scala.collection.immutable.HashMap.$plus$plus(HashMap.scala:184)
        at scala.collection.immutable.HashMap.$plus$plus(HashMap.scala:173)
        at MapConcatNpe$.main(map-concat-npe.scala:11)
        at MapConcatNpe.main(map-concat-npe.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:106)
        at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
        at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:132)
        at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:106)
        at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:98)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:132)
        at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:28)
        at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:27)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
        at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:35)
        at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:34)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:73)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:92)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

Notably iterating the map first will prevent the exception from being thrown.

### 2.12.12

I tested with scala 2.12.12 and found that the example above is now successful. However the likely root cause of the above can still be reproduced issue when using a `HashMap` directly.

```scala
import scala.collection.immutable.HashMap

object HashMapConcatNpe {
  trait DataType              extends Product with Serializable
  case class Foo(arg: String) extends DataType
  case class Bar(arg: String) extends DataType

  def main(args: Array[String]): Unit = {
    // Create a HashMap consisting of a single HashMapCollision1.
    val collision = HashMap(Foo("toxic") -> 0, Bar("toxic") -> 0)
    val singleton = (new HashMap[DataType, Int]).updated(Foo("toxic"), 0)

    collision ++ singleton
  }
}
```

```
java.lang.NullPointerException
        at scala.collection.immutable.HashMap$$anon$3.apply(HashMap.scala:287)
        at scala.collection.immutable.HashMap$HashMapCollision1.updated0(HashMap.scala:451)
        at scala.collection.immutable.HashMap$HashMapCollision1.merge0(HashMap.scala:507)
        at scala.collection.immutable.HashMap.$plus$plus(HashMap.scala:187)
        at scala.collection.immutable.HashMap.$plus$plus(HashMap.scala:177)
        at HashMapConcatNpe$.main(hashmap-concat-npe.scala:13)
        at HashMapConcatNpe.main(hashmap-concat-npe.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:106)
        at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
        at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:132)
        at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:106)
        at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:98)
        at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:132)
        at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:28)
        at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:27)
        at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
        at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:35)
        at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:34)
        at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:73)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:92)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by SethTisue** [comment]
@retronym ring a bell?

**Comment by retronym** [comment]
Yep. Ouch. I've submitted a fix.

**Comment by kubukoz** [comment]
Hi, what's the status of 2.12.13? I just hit this and it's pretty annoying 😅

**Comment by SethTisue** [comment]
https://contributors.scala-lang.org/t/coming-soon-scala-2-12-13/4546/14

**Comment by ian-bertolacci** [comment]
@davidpadbury-da you mentioned:
> iterating the map first will prevent the exception from being thrown.
What specifically did you do to "iterate" the map?
I know this issue is resolved in later patches of 2.12, but I'm having the same issue but am not immediately able to upgrade our scala version, so I'm hoping this can be a stop-gap until we are able to do so.

**Comment by kubukoz** [comment]
I think a .toList may do, or a foreach with a no-op.

**Comment by som-snytt** [comment]
```
    //mapWithCollision.foreach(_ => ())
    other.foreach(_ => ())
    mapWithCollision ++ other
```
Iterate the `other`.
