### ISSUE TITLE
Crash with `List(null: _*)`

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12198]
## reproduction steps

using Scala 2.13.3,

```scala
➜  snips cat nully.scala

class C {
  def f = List(null: _*)
}
object Test extends App {
  println(new C().f)
}

➜  snips scala nully.scala
Exception in thread "main" scala.MatchError: <error> (of class scala.reflect.internal.Types$ErrorType$)
        at scala.reflect.internal.pickling.Translations.picklerTag(Translations.scala:73)
        at scala.reflect.internal.pickling.Translations.picklerTag$(Translations.scala:73)
        at scala.reflect.internal.SymbolTable.picklerTag(SymbolTable.scala:28)
        at scala.reflect.internal.pickling.Translations.picklerTag(Translations.scala:42)
        at scala.reflect.internal.pickling.Translations.picklerTag$(Translations.scala:41)
        at scala.tools.nsc.symtab.classfile.Pickler$Pickle.writeEntry(Pickler.scala:621)
        at scala.tools.nsc.symtab.classfile.Pickler$Pickle.$anonfun$writeArray$3(Pickler.scala:639)
        at scala.tools.nsc.symtab.classfile.Pickler$Pickle.writeArray(Pickler.scala:639)
        at scala.tools.nsc.symtab.classfile.Pickler$Pickle.close(Pickler.scala:174)
        at scala.tools.nsc.symtab.classfile.Pickler.pickle(Pickler.scala:162)
        at scala.tools.nsc.symtab.classfile.Pickler$PicklePhase.pickle$3(Pickler.scala:81)
        at scala.tools.nsc.symtab.classfile.Pickler$PicklePhase.pickle$2(Pickler.scala:94)
        at scala.tools.nsc.symtab.classfile.Pickler$PicklePhase.$anonfun$apply$1(Pickler.scala:74)
        at scala.tools.nsc.symtab.classfile.Pickler$PicklePhase.pickle$2(Pickler.scala:74)
        at scala.tools.nsc.symtab.classfile.Pickler$PicklePhase.apply(Pickler.scala:102)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:401)
        at scala.tools.nsc.symtab.classfile.Pickler$PicklePhase.run(Pickler.scala:123)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1626)
```

## problem

I would expect compile-time help with my null, or dotty does the same as `List((null: Seq[String]): _*)`:

```
scala> List((null: Seq[String]): _*)
java.lang.NullPointerException: Cannot invoke "scala.collection.IterableOnce.knownSize()" because "prefix" is null
        at scala.collection.immutable.List.prependedAll(List.scala:148)
        at scala.collection.immutable.List$.from(List.scala:651)
        at scala.collection.immutable.List$.from(List.scala:648)
        at scala.collection.IterableFactory.apply(Factory.scala:103)
        at scala.collection.IterableFactory.apply$(Factory.scala:103)
        at scala.collection.immutable.List$.apply(List.scala:648)
```

**Comment by som-snytt** [comment]
Since 2.13.4, it doesn't crash but
```
error: erroneous or inaccessible type
```
which appears to be a thing.

```
package <empty> {
  class C extends scala.AnyRef {
    def <init>(): C = {
      C.super.<init>();
      ()
    };
    def <f: error>: <error> = scala.`package`.List.apply[A]((null: _*))
  };
  object Test extends AnyRef with App {
    def <init>(): Test.type = {
      Test.super.<init>();
      ()
    };
    scala.Predef.println(new C().<f: error>)
  }
}
```
~`List.apply` is special-cased.~ ~Who is supposed to report the error.~ 

Apparently I did the same for `Nothing` seven years ago.

That was when I worked for `Nothing`.
