### ISSUE TITLE
Investigate test failures under J9

### ISSUE THREAD

**Issue by retronym** [scala/bug#12214]
I have given our [test suite a spin](https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/5402/consoleText) using IBM's J9 JDK.

A few issues cropped up, and I will catalog and diagnose them here.

# Worrying

## "conflicting default methods"

`t4297.scala` et al.

```scala
// test.scala
object Test {
  def main(args: Array[String]): Unit = {
    def f = List(1,2,3).view
    assert(f.mkString == "123")
  }
}
```

```
java.lang.IncompatibleClassChangeError: conflicting default methods for 'mkString()Ljava/lang/String;' in scala/collection/SeqView from classes [scala/collection/TraversableOnce, scala/collection/ViewMkString]
```

Different in behaviour between HotSpot and J9. Who is right?

## Java Generic Signature

```scala
class Wrapper[X](x: X)

class C {
  def a(w: Wrapper[Array[Int]]) = 0
}

object Test {
  def main(args: Array[String]): Unit = {
    val methods = classOf[C].getDeclaredMethods.sortBy(_.getName)
    println("= Java Erased Signatures =")
    println(methods.mkString("\n"))
    println("\n= Java Generic Signatures =")
    println(methods.map(_.toGenericString).mkString("\n"))
  }
}
```

J9 prints `public int C.a(Wrapper<[I>)` rather than `public int C.a(Wrapper<int[]>)`.

## `methodName != apply$mcV$sp`

[Test case](https://github.com/scala/scala/blob/824103644337758f2a6a70ea69a33a9671e1e69c/test/files/run/t9814.scala#L9) exercising Scala compiler time specialization and strictfp. Needs more diagnostics to see what's happening on J9.

## Reflection / `getSimpleName` / `isAnonymous`

Test Case: [jvm/javaReflection](https://github.com/scala/scala/tree/824103644337758f2a6a70ea69a33a9671e1e69c/test/files/jvm/javaReflection)

Instructions to run without our test harness
```
% scalac -version && scalac -d . test/files/jvm/javaReflection/{Classes_1,Test}.scala && scala -Dpartest.output=. Test > /tmp/output.txt; diff /tmp/output.txt test/files/jvm/javaReflection.check
Scala compiler version 2.12.3 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
...
```

```
!! 11 - jvm/javaReflection                        [non-zero exit code]
##### Log file '/home/jenkins/workspace/scala-2.12.x-validate-test/test/files/jvm/javaReflection-jvm.log' from failed test #####

A / A (canon) / A (simple)
- declared cls: List(class A$B, interface A$C, class A$D$)
- enclosing   : null (declaring cls) / null (cls) / null (constr) / null (meth)
- properties  : false (local) / false (member)
A$$anon$2 / null (canon) /  (simple)
- declared cls: List()
- enclosing   : null (declaring cls) / class A (cls) / null (constr) / null (meth)
- properties  : false (local) / false (member)
java.lang.AssertionError: assertion failed: class A$$anon$2
	at Test$.assertNotAnonymous(Test.scala:68)
	at Test$.showClass(Test.scala:110)
	at Test$.$anonfun$main$3(Test.scala:135)
	at Test$.main(Test.scala:135)
	at Test.main(Test.scala)
```

## Scala Reflection under OSGi

Kill me now.

```
[info] Test tools.test.osgi.reflection.toolbox.ReflectionToolBoxTest.basicMirrorThroughOsgi started
..
[error] Test tools.test.osgi.reflection.toolbox.ReflectionToolBoxTest.basicMirrorThroughOsgi failed: java.lang.AssertionError: assertion failed: no symbol could be loaded from class com.ibm.jit.JITHelpers in package jit with name JITHelpers and classloader scala.reflect.internal.util.AbstractFileClassLoader@ff8c0bc6, took 1.821 sec
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala1(JavaMirrors.scala:1028)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$classToScala$1(JavaMirrors.scala:986)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror$$Lambda$110.00000000A4FB94C0.apply(Unknown Source)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:98)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror$$Lambda$109.00000000A4FB8590.apply(Unknown Source)
[error]     at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:38)
[error]     at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:96)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:986)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScala(JavaMirrors.scala:1091)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.jfieldAsScala1(JavaMirrors.scala:1137)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$jfieldAsScala$1(JavaMirrors.scala:1132)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror$$Lambda$144.00000000A4FEB110.apply(Unknown Source)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:98)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror$$Lambda$109.00000000A4FB8590.apply(Unknown Source)
[error]     at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:38)
[error]     at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
[error]     at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:96)
```

# Benign

## Use of JOL

`OpenHashMapTest.freesDeletedKey` used JOL features tha only work on OpenJDK. Use `Assuume.assumeTrue` to gracefully degrade.

## Exception message differently worded differently

 `run/t6411a.scala`, `run/t6827.scala`  et al

`ClassCastException`:  "incompatible with" vs "cannot be cast to"
`ArrayIndexOutOfBoundsException`: "Array index out of range -1" vs "-1"

## Extra console output on OOME

[run/t6969.scala](https://github.com/scala/scala/blob/99b4d95fe6c908ce3170ff4d090420f8e47efa1d/test/files/run/t6969.scala#L29)

J9 appears to default to dumping JVM state on OOME, and printing the location of dump files to console. We have a few tests that seem to intentionally provoke an OOME.

**Comment by dwijnand** [comment]
There are many parts to this ticket.  I presume it's all still valid, but there hasn't been any interest in it over the last 3 years.  So I'm going to close and invite anyone interested in fixing any specific part of this to spin it out into its own ticket (or pull request!)
