### ISSUE TITLE
Scala compiler generates inconsistent inner classes

### ISSUE THREAD

**Issue by farquet** [scala/bug#12235]
## Reproduction steps

Create a file named `Test.scala` with the following code:

```scala
import dotty.tools.dotc.printing.SyntaxHighlighting

object Test extends App {
  val foo = Class.forName("dotty.tools.dotc.printing.SyntaxHighlighting$TreeHighlighter$1$")
  println(foo)
  println(foo.getEnclosingClass())
}
```
Using the latest Scala 2.13.4 or earlier, run it by adding the jars linked below[1][2] to the classpath:
```bash
scala -cp dotty-compiler_0.27-0.27.0.jar:dotty-library_0.27-0.27.0.jar -Ytasty-reader Test.scala
```

The output will be:
```
class dotty.tools.dotc.printing.SyntaxHighlighting$TreeHighlighter$1$
Exception in thread "main" java.lang.IncompatibleClassChangeError: dotty.tools.dotc.printing.SyntaxHighlighting and dotty.tools.dotc.printing.SyntaxHighlighting$TreeHighlighter$1$ disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1235)
	at java.lang.Class.getEnclosingClass(Class.java:1277)
...
```

I faced the issue while working with dotty, but it's independent of the problem here which affects scala 2.13. I was just unable to create a smaller reproducer.

[1] https://mvnrepository.com/artifact/ch.epfl.lamp/dotty-library_0.26/0.26.0
[2] https://mvnrepository.com/artifact/ch.epfl.lamp/dotty-compiler_0.26/0.26.0

## Problem

The problem resides in the classfiles available on maven (which I assume they were compiled with 2.13.3 based on what the compile dependency states).

Looking at the InnerClasses attribute in the bytecode of those class files, we see:

For `SyntaxHighlighting$.class`:
```
InnerClasses:
     public static #12= #9 of #11; //Setting=class dotty/tools/dotc/config/Settings$Setting of class dotty/tools/dotc/config/Settings
     public static final #15= #14 of #11; //Setting$=class dotty/tools/dotc/config/Settings$Setting$ of class dotty/tools/dotc/config/Settings
     public static abstract #20= #17 of #19; //Context=class dotty/tools/dotc/core/Contexts$Context of class dotty/tools/dotc/core/Contexts
     public static #23= #22 of #19; //FreshContext=class dotty/tools/dotc/core/Contexts$FreshContext of class dotty/tools/dotc/core/Contexts
     public static abstract #28= #25 of #27; //Name=class dotty/tools/dotc/core/Names$Name of class dotty/tools/dotc/core/Names
     public static final #31= #30 of #27; //SimpleName=class dotty/tools/dotc/core/Names$SimpleName of class dotty/tools/dotc/core/Names
     public static #36= #33 of #35; //ScalaTermNames=class dotty/tools/dotc/core/StdNames$ScalaTermNames of class dotty/tools/dotc/core/StdNames
     public static #41= #38 of #40; //Parser=class dotty/tools/dotc/parsing/Parsers$Parser of class dotty/tools/dotc/parsing/Parsers
     public static #46= #43 of #45; //Scanner=class dotty/tools/dotc/parsing/Scanners$Scanner of class dotty/tools/dotc/parsing/Scanners
     public static final #49= #48 of #45; //Scanner$=class dotty/tools/dotc/parsing/Scanners$Scanner$ of class dotty/tools/dotc/parsing/Scanners
     private static final #54= #51 of #53; //TreeHighlighter$=class dotty/tools/dotc/printing/SyntaxHighlighting$TreeHighlighter$1$ of class dotty/tools/dotc/printing/SyntaxHighlighting
     public static final #59= #56 of #58; //NoReporter$=class dotty/tools/dotc/reporting/Reporter$NoReporter$ of class dotty/tools/dotc/reporting/Reporter
     public static final #64= #61 of #63; //Span=class dotty/tools/dotc/util/Spans$Span of class dotty/tools/dotc/util/Spans
     public static final #67= #66 of #63; //Span$=class dotty/tools/dotc/util/Spans$Span$ of class dotty/tools/dotc/util/Spans
```

For `SyntaxHighlighting$TreeHighlighter$1$.class`:
```
InnerClasses:
     public static #10= #7 of #9; //Ident=class dotty/tools/dotc/ast/Trees$Ident of class dotty/tools/dotc/ast/Trees
     public static abstract #13= #12 of #9; //MemberDef=class dotty/tools/dotc/ast/Trees$MemberDef of class dotty/tools/dotc/ast/Trees
     public static abstract #16= #15 of #9; //NameTree=class dotty/tools/dotc/ast/Trees$NameTree of class dotty/tools/dotc/ast/Trees
     public static abstract #19= #18 of #9; //Tree=class dotty/tools/dotc/ast/Trees$Tree of class dotty/tools/dotc/ast/Trees
     public static #22= #21 of #9; //TypTree=class dotty/tools/dotc/ast/Trees$TypTree of class dotty/tools/dotc/ast/Trees
     public static abstract #25= #24 of #9; //ValOrDefDef=class dotty/tools/dotc/ast/Trees$ValOrDefDef of class dotty/tools/dotc/ast/Trees
     public static #30= #27 of #29; //Modifiers=class dotty/tools/dotc/ast/untpd$Modifiers of class dotty/tools/dotc/ast/untpd
     public static abstract #31= #4 of #29; //UntypedTreeTraverser=class dotty/tools/dotc/ast/untpd$UntypedTreeTraverser of class dotty/tools/dotc/ast/untpd
     public static abstract #36= #33 of #35; //Context=class dotty/tools/dotc/core/Contexts$Context of class dotty/tools/dotc/core/Contexts
     public static abstract #41= #38 of #40; //Name=class dotty/tools/dotc/core/Names$Name of class dotty/tools/dotc/core/Names
     public static abstract #44= #43 of #40; //TermName=class dotty/tools/dotc/core/Names$TermName of class dotty/tools/dotc/core/Names
     public static #49= #46 of #48; //ScalaTermNames=class dotty/tools/dotc/core/StdNames$ScalaTermNames of class dotty/tools/dotc/core/StdNames
     private static final #52= #2 of #51; //TreeHighlighter$=class dotty/tools/dotc/printing/SyntaxHighlighting$TreeHighlighter$1$ of class dotty/tools/dotc/printing/SyntaxHighlighting
```

For `SyntaxHighlighting.class`
```
InnerClasses:
     public static abstract #10= #7 of #9; //Context=class dotty/tools/dotc/core/Contexts$Context of class dotty/tools/dotc/core/Contexts
```

The disagreement is due to the fact that in `SyntaxHighlighting.class`, there is no information about `SyntaxHighlighting$TreeHighlighter$1$.class` while this must be the case.

## Consequence

GraalVM native image (the points-to analysis) relies heavily on those inner classes references to be correct and this prevents creating native images of large scala applications (in this case dotty compiled with Scala 2).

This issue seems to be a more generic case of #10487 fixed by @lrytz in 2.12.

**Comment by dwijnand** [comment]
Hey.  Does the same thing happen with 3.0.0-M1?  Note the coordinates have changed: https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3.0.0-M1/3.0.0-M1/

I'm fairly certain this is a Scala 3 bug (https://github.com/lampepfl/dotty/issues) and you could probably prove that by porting that little Scala into Java and compiling and running it to get the same failure.

**Comment by smarter** [comment]
Yep, this is a Scala 3 bug, many of the backend bugfixes from Scala 2 haven't been ported to Scala 3 so far, because @lrytz is the only person who understands how this stuff works: https://github.com/lampepfl/dotty/issues/4192

**Comment by farquet** [comment]
Ok, thanks for the answers! I confirm that the issue still occurs with dotty 3.0.0-M1 and 3.0.0-M2.

lampepfl/dotty#4192 seems indeed to be the issue to follow.
