### ISSUE TITLE
NullPointerException: Cannot invoke "scala.reflect.internal.Types$Type.typeSymbol()" because the return value of "scala.reflect.internal.Trees$Tree.tpe()" is null

### ISSUE THREAD

**Issue by lukaseder** [scala/bug#12380]
## reproduction steps

I can't seem to reduce the problem to a fully self-contained example (I tried for 1 hour without success), but it can be easily reproduced using a third party dependency, starting from this commit here:
https://github.com/jOOQ/jOOQ/commit/1ab673fa9a1f8fb38877883f3d44b8e08ff0d7d0

But it still also works with this one:
https://github.com/jOOQ/jOOQ/commit/5e69809283c7804373c32ae3bac2f4ff82eab599

Reproduction steps using openjdk version "17-ea" 2021-09-14 available from here https://jdk.java.net/17:

```
$ git clone https://github.com/jOOQ/jOOQ
$ cd jOOQ
$ git checkout 5e69809283c7804373c32ae3bac2f4ff82eab599
$ mkdir jOOQ-scala_2.13/src/main/scala/p
$ cat > jOOQ-scala_2.13/src/main/scala/p/S.scala
package p

import org.jooq.{Field, Record2}
import org.jooq.impl.UDTRecordImpl

abstract class S extends UDTRecordImpl[S](null) with Record2[Integer, String] {
}
$ mvn clean install -pl jooq,jooq-scala_2.13
```

## problem

The following error is produced:

```
[ERROR] ## Exception when compiling 2 sources to C:\Users\lukas\jOOQ\3.15\workspace\jOOQ-pro\jOOQ-test-codegen-scala\target\classes
java.lang.NullPointerException: Cannot invoke "scala.reflect.internal.Types$Type.typeSymbol()" because the return value of "scala.reflect.internal.Trees$Tree.tpe()" is null
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.preErase(Erasure.scala:1276)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1331)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
scala.reflect.internal.Trees$DefDef.$anonfun$transform$5(Trees.scala:453)
scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
scala.reflect.internal.Trees$DefDef.transform(Trees.scala:451)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1357)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:342)
scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:342)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:55)
scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
scala.tools.nsc.transform.Erasure$ErasureTransformer.transform(Erasure.scala:1377)
scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:183)
scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:32)
scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
scala.tools.nsc.Global$GlobalPhase.run(Global.scala:401)
scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1524)
scala.tools.nsc.Global$Run.compileUnits(Global.scala:1508)
scala.tools.nsc.Global$Run.compileSources(Global.scala:1500)
scala.tools.nsc.Global$Run.compileFiles(Global.scala:1614)
xsbt.CachedCompiler0.run(CompilerBridge.scala:163)
xsbt.CachedCompiler0.run(CompilerBridge.scala:134)
xsbt.CompilerBridge.run(CompilerBridge.scala:39)
sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
sbt_inc.SbtIncrementalCompiler.compile(SbtIncrementalCompiler.java:218)
scala_maven.ScalaCompilerSupport.incrementalCompile(ScalaCompilerSupport.java:322)
scala_maven.ScalaCompilerSupport.compile(ScalaCompilerSupport.java:121)
scala_maven.ScalaCompilerSupport.doExecute(ScalaCompilerSupport.java:96)
scala_maven.ScalaMojoSupport.execute(ScalaMojoSupport.java:471)
org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.base/java.lang.reflect.Method.invoke(Method.java:568)
org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

Revert jOOQ to commit `fcc258bfe82ff4e81e4148f2d9cf1bbd12c28425` and the error goes away:

```
$ git checkout fcc258bfe82ff4e81e4148f2d9cf1bbd12c28425
$ mvn clean install -pl jooq,jooq-scala_2.13
```

**Comment by lrytz** [comment]
👋 hey!

Before I have to go figure out `mvn` and how it calls into scalac, is there an easy way for me or you to prepare a bunch of jar(s) and source(s) that would let me reproduce it as `scalac -cp jars/*.jar src/*.scala`?

**Comment by lukaseder** [comment]
Hey, @lrytz ! :)

Sure thing. Copy https://www.jooq.org/scalac-12380/jooq-3.15.0-SNAPSHOT.jar (I'll leave it there for a while - can't attach jar files to github issues) to some local dir and then run:

```
$ mkdir p
$ cat > p/S.scala
package p

import org.jooq.{Field, Record2}
import org.jooq.impl.UDTRecordImpl

abstract class S extends UDTRecordImpl[S](null) with Record2[Integer, String] {
}
$ scalac -cp jooq-3.15.0-SNAPSHOT.jar p/S.scala
```

The stack trace is now:

```
error: java.lang.NullPointerException: Cannot invoke "scala.reflect.internal.Types$Type.typeSymbol()" because the return value of "scala.reflect.internal.Trees$Tree.tpe()" is null
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.preErase(Erasure.scala:1276)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1331)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.internal.Trees$DefDef.$anonfun$transform$5(Trees.scala:453)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
        at scala.reflect.internal.Trees$DefDef.transform(Trees.scala:451)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1357)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
        at scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
        at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
        at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
        at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:342)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
        at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:342)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:55)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer.transform(Erasure.scala:1377)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:183)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:32)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:401)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1524)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1508)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1500)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1635)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:48)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:30)
        at scala.tools.nsc.Driver.process(Driver.scala:68)
        at scala.tools.nsc.Driver.main(Driver.scala:82)
        at scala.tools.nsc.Main.main(Main.scala)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "scala.reflect.internal.Types$Type.typeSymbol()" because the return value of "scala.reflect.internal.Trees$Tree.tpe()" is null
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.preErase(Erasure.scala:1276)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1331)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.internal.Trees$DefDef.$anonfun$transform$5(Trees.scala:453)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
        at scala.reflect.internal.Trees$DefDef.transform(Trees.scala:451)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1357)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
        at scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
        at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
        at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:991)
        at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
        at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
        at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:342)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
        at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:342)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:55)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
        at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$4.transform(Erasure.scala:1367)
        at scala.tools.nsc.transform.Erasure$ErasureTransformer.transform(Erasure.scala:1377)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:183)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:32)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:401)
        at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1524)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1508)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1500)
        at scala.tools.nsc.Global$Run.compile(Global.scala:1635)
        at scala.tools.nsc.Driver.doCompile(Driver.scala:48)
        at scala.tools.nsc.MainClass.doCompile(Main.scala:30)
        at scala.tools.nsc.Driver.process(Driver.scala:68)
        at scala.tools.nsc.Driver.main(Driver.scala:82)
        at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by lrytz** [comment]
So... 😃  There are a bunch of things coming together here it seems.

First a minimization:

```java
package p;

public class A {

  public static class C extends B {
    // The bridge below is added because `B` is package-private. I assume this
    // makes it easier to emit bytecode for `(new C()).m()` outside the package,
    // the bytecode `invokevirtual B.m()Object` would be invalid.
    // Using `invokevirtual C.m()Object` would be valid even without the bridge
    // I think, but 🤷‍♂️.
    // public synthetic bridge m() { return super[B].m()Object }
  }

  /* package-private */ static class B implements I {
    @Override public Object m() { return new Object(); }
  }
  
  public static interface I {
    public Object m();
  }

  public static interface J extends I {
    @Override public String m();

    // public synthetic bridge default Object m() { return this.m()String; }
  }

  // the below doesn't compile:
  //   m() in B cannot implement m() in J
  //   return type Object is not compatible with String
  // abstract static class Test extends C implements J { }
}
```

```scala
// This should be rejected in override checking, but isn't.
// Corresponding Scala-only is rejected:
//   scala> trait I { def m: Object }; trait J { def m: String }; class B extends I { def m = new Object }; class C extends B
//   
//   scala> class Test extends C with J
//                ^
//          error: incompatible type in overriding
//          def m: String (defined in trait J)
//            with def m: Object (defined in class B);
//           found   : Object
//           required: String
object Test extends p.A.C with p.A.J {
  def main(args: Array[String]): Unit = {
    println(m)
  }
}
```

This causes the same NPE in the compiler. Even if it shouldn't compile (as explained in the comment), the NPE is a bug, here's a possible fix: https://github.com/scala/scala/compare/2.13.x...lrytz:t12380?expand=1

When compiling the Scala code with that fix, the generated bridge methods call each other in a loop. Not sure if that's also a bug, or if the compiler is just doing the wrong thing because it gets an invalid program that should have been rejected.

```
	at Test$.m(Test.scala:12)
	at Test$.m(Test.scala:12)
	at p.A$J.m(A.java:22)
	at Test$.m(Test.scala:12)
	at Test$.m(Test.scala:12)
	at p.A$J.m(A.java:22)
```

So, @lukaseder I think the Scala compiler should reject the class `abstract class S extends UDTRecordImpl[S](null) with Record2[Integer, String]`, because the class `UDTRecordImpl` has a concrete `public Row valuesRow()`, and the interface  `Record2` has an abstract `public Row2<T1, T2> valuesRow()`. Does that make sense..?

**Comment by lukaseder** [comment]
Hah, excellent. I was chasing the wrong set of changes I made, thinking this had anything to do with the recursive generics I introduced, when it was about package private types and methods, and bridges... Thanks for the minimisation - I don't think I would have found it.

Yes, the compiler should reject the class `S` as I suggested it to be, which has also been minimised for this bug's purpose as it still reproduces the NPE. The actual class `S` will have  a covariant override: `override def valuesRow: Row2[Integer, String]` (which I hope will not be rejected, given that `Row2 <: Row`?)

**Comment by lrytz** [comment]
Yes, with that override (which the compiler should require) it compiles correctly.

So this bug doesn't actually affect you in any way currently, is that right? I will still dig around to figure out what fixes need to be done.

**Comment by lukaseder** [comment]
> So this bug doesn't actually affect you in any way currently, is that right?

It still affects me. I'm still getting the NPE even with all the necessary covariant overrides in place. Here's a slightly more complete example (still simplified):

```scala
package p

import org.jooq.{Field, Record2, Row2}
import org.jooq.impl.UDTRecordImpl

class S extends UDTRecordImpl[S](null) with Record2[Integer, String] {
  override def fieldsRow: Row2[Integer, String] = null
  override def valuesRow: Row2[Integer, String] = null
  override def field1: Field[Integer] = null
  override def field2: Field[String] = null
  override def component1: Integer = null
  override def component2: String = null
  override def value1: Integer = null
  override def value2: String = null
  override def value1(value: Integer): S = this
  override def value2(value: String): S = this
  override def values(value1 : Integer, value2 : String): S = this
}
```

This used to compile before the I introduced the change to the type hierarchy that I mentioned before (https://github.com/jOOQ/jOOQ/commit/1ab673fa9a1f8fb38877883f3d44b8e08ff0d7d0)

> I will still dig around to figure out what fixes need to be done.

Thanks a lot, I really appreciate it!

**Comment by lrytz** [comment]
OK, with the new version of `S` it's the method `with` causing the crash.

However, I cannot add an override of `with` to `S` because `with` is `final` in `AbstractQualifiedRecord`. I think that makes `UDTRecordImpl[S](null) with Record2[Integer, String]` invalid -- you'd need to override `with` for correctness, but can't because it's final. No?

**Comment by lukaseder** [comment]
Thanks to those recursive generics on `UpdatableRecord<R extends UpdatableRecord<R>>`, I don't have to override those `with` methods in the corresponding generated Java or kotlin classes, and they can be `final` in `AbstractQualifiedRecord`. In `S`, there should be a bridge method for `with` that already returns `S`, which satisfies all of the overridden method return types. 

Here's an equivalent `S.java` class:

```java
package p;

import org.jooq.*;
import org.jooq.impl.UDTRecordImpl;

public class S extends UDTRecordImpl<S> implements Record2<Integer, String> {
    S() { super(null); }
    @Override public Row2<Integer, String> fieldsRow() {return null; }
    @Override public Row2<Integer, String> valuesRow() { return null; }
    @Override public Field<Integer> field1() { return null; }
    @Override public Field<String> field2() { return null; }
    @Override public Integer component1() { return null; }
    @Override public String component2() { return null; }
    @Override public Integer value1() { return null; }
    @Override public String value2() { return null; }
    @Override public S value1(Integer value) { return this; }
    @Override public S value2(String value) { return this; }
    @Override public S values(Integer value1, String value2) { return this; }
}
```

And here's the bytecode of `S.class`, showing the generated synthetic bridges:

```
  // Method descriptor #48 (Lorg/jooq/Field;Ljava/lang/Object;Lorg/jooq/Converter;)Lorg/jooq/Record2;
  // Stack: 4, Locals: 4
  public bridge synthetic org.jooq.Record2 with(org.jooq.Field arg0, java.lang.Object arg1, org.jooq.Converter arg2);
     0  aload_0 [this]
     1  aload_1 [arg0]
     2  checkcast org.jooq.Field [49]
     5  aload_2 [arg1]
     6  checkcast java.lang.Object [51]
     9  aload_3 [arg2]
    10  checkcast org.jooq.Converter [53]
    13  invokevirtual p.S.with(org.jooq.Field, java.lang.Object, org.jooq.Converter) : org.jooq.QualifiedRecord [55]
    16  checkcast org.jooq.Record2 [5]
    19  areturn
      Line numbers:
        [pc: 0, line: 1]
  
  // Method descriptor #58 (Lorg/jooq/Field;Ljava/lang/Object;)Lorg/jooq/Record2;
  // Stack: 3, Locals: 3
  public bridge synthetic org.jooq.Record2 with(org.jooq.Field arg0, java.lang.Object arg1);
     0  aload_0 [this]
     1  aload_1 [arg0]
     2  checkcast org.jooq.Field [49]
     5  aload_2 [arg1]
     6  checkcast java.lang.Object [51]
     9  invokevirtual p.S.with(org.jooq.Field, java.lang.Object) : org.jooq.QualifiedRecord [59]
    12  checkcast org.jooq.Record2 [5]
    15  areturn
      Line numbers:
        [pc: 0, line: 1]
```

**Comment by lrytz** [comment]
Right, thanks for pointing it out. Here's the reproducer for that:

```java
package p;

public class A {
  public static interface I1 {
    public I1 w();
  }

  public static interface J1<R extends J1<R>> extends I1 {
    @Override public R w();
  }

  public static interface R1 extends I1 {
    @Override public R1 w();
  }

  /* package-private */ static class B1<R extends J1<R>> implements J1<R> {
    @Override public R w() { return null; }
  }

  public static class C1<R extends J1<R>> extends B1<R> implements J1<R> { }

  // OK in Java, crashes scalac
  public static class Test1 extends C1<Test1> implements R1 { }
}
```

```scala
class Test1 extends p.A.C1[Test1] with p.A.R1
```
