### ISSUE TITLE
REPL doesn't start with -Dscala.repl.power

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12395]
## reproduction steps

using Scala 2.13.5,

```scala
$ scala -Dscala.repl.power
Welcome to Scala 2.13.5 (OpenJDK 64-Bit Server VM, Java 16.0.1).
Type in expressions for evaluation. Or try :help.
Exception in thread "main" scala.NotImplementedError: an implementation is missing
        at scala.tools.nsc.interpreter.jline.Reader.redrawLine(Reader.scala:42)
        at scala.tools.nsc.interpreter.shell.ILoop.echoAndRefresh(ILoop.scala:79)
        at scala.tools.nsc.interpreter.shell.ILoop.asyncMessage(ILoop.scala:97)
        at scala.tools.nsc.interpreter.shell.ILoop.asyncEcho(ILoop.scala:753)
        at scala.tools.nsc.interpreter.shell.ILoop.enablePowerMode(ILoop.scala:729)
        at scala.tools.nsc.interpreter.shell.ILoop.interpretPreamble(ILoop.scala:933)
        at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$run$3(ILoop.scala:963)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.tools.nsc.interpreter.shell.ILoop.echoOff(ILoop.scala:90)
        at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$run$2(ILoop.scala:963)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.tools.nsc.interpreter.IMain.withSuppressedSettings(IMain.scala:1406)
        at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$run$1(ILoop.scala:954)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.tools.nsc.interpreter.shell.ReplReporterImpl.withoutPrintingResults(Reporter.scala:64)
        at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:954)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
        at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

## problem

`:power` works but not when jumpstarted.

**Comment by jxnu-liguobin** [comment]
I try to avoid this problem with minimal coding, but I don't know if I understand it correctly.
