### ISSUE TITLE
Intermittent local failure of scala.reflect.internal.util.FileUtilsTest.showPerformance

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12417]
## reproduction steps

2.13.6/7 build on WSL 2 Ubuntu.

```scala
sbt:root> junit/testOnly scala.reflect.internal.util.FileUtilsTest
[info] Test run started
[info] Test scala.reflect.internal.util.FileUtilsTest.showPerformance started
```

## problem

It hung and didn't complete. I reproduced it a few times (using a local starr under test), but could not reproduce with clean local starr, or after switching back to local starr under test.

Apparently, `showPerformance` calls `writeIsSame` in a "warmup" loop. It writes two files repeatedly.

Here are the files left by terminated runs. `t1` correctly has 2000 lines, `t2` has 1657 lines and no terminal newline.

Since `BufferedWriter` has an 8K buffer, and 49152 is exactly 6 buffers, it looks like an intermittent issue writing newline after a full buffer.

```
-rw-r--r-- 1 amarki amarki   49152 Jun 20 14:09  FileUtilsTest9580764986601946010t2
-rw-r--r-- 1 amarki amarki   59786 Jun 20 14:09  FileUtilsTest15738232695896285195t1
-rw-r--r-- 1 amarki amarki   49152 Jun 20 14:36  FileUtilsTest249596159509880420t2
-rw-r--r-- 1 amarki amarki   59786 Jun 20 14:36  FileUtilsTest17787878896657929316t1
-rw-r--r-- 1 amarki amarki   59786 Jun 20 14:39  FileUtilsTest5312455609194729641t1
-rw-r--r-- 1 amarki amarki   49152 Jun 20 14:39  FileUtilsTest11530457115345509427t2
```

I see `fork := true` in build.sbt, so I see `sys.process` in sbt thread dump but on WSL `ps ef` did not show a child process. Maybe the child exited; the test asserts that the 2 file lengths are equal, so something else might have thrown that is not caught as a test failure?

Thread dump snip
```
[info] Test scala.reflect.internal.util.FileUtilsTest.showPerformance started
2021-06-20 14:22:02
Full thread dump OpenJDK 64-Bit Server VM (16.0.1+9 mixed mode, sharing):
```
I was watching the Giants beat the Phillies, so sbt was stuck for 13 mins before I took a look. I also did a jstack, but then accidentally git cleaned and lost the output file.

**Comment by som-snytt** [comment]
Was about to close this because couldn't reproduce. I also verified that sbt notices if child test exits or throws Error. I haven't checked IOE or interrupted.

Went back to my local branch and it hung.
```
-rw-r--r-- 1 amarki amarki   49152 Jun 20 18:23  FileUtilsTest13764424094786395314t2
-rw-r--r-- 1 amarki amarki   59786 Jun 20 18:23  FileUtilsTest11941640762094943590t1
```
So jstack of child test says the runner thread is actually at AsynchThing.close. So last flush at close of the regular BufferedWriter was never called. PrintWriter has the flag to say autoflush on each print call. Probably there's supposed to be another thread. I haven't looked at the source yet.
```
"pool-1-thread-1" #15 prio=5 os_prio=0 cpu=55323.44ms elapsed=202.26s allocated=12998M defined_classes=13788 tid=0x00007f499424ae30 nid=0x2451 waiting on condition  [0x00007f49608b7000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@16.0.1/Native Method)
        - parking to wait for  <0x00000006e8b8f5a0> (a scala.concurrent.impl.CompletionLatch)
        at java.util.concurrent.locks.LockSupport.park(java.base@16.0.1/LockSupport.java:211)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@16.0.1/AbstractQueuedSynchronizer.java:714)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(java.base@16.0.1/AbstractQueuedSynchronizer.java:1046)
        at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:245)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:263)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
        at scala.concurrent.Await$$$Lambda$6967/0x00000008019a3988.apply(Unknown Source)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
        at scala.concurrent.package$.blocking(package.scala:124)
        at scala.concurrent.Await$.result(package.scala:201)
        at scala.reflect.internal.util.FileUtils$AsyncBufferedWriter.close(FileUtils.scala:138)
        at scala.reflect.internal.util.FileUtilsTest.writeIsSame(FileUtilsTest.scala:33)
        at scala.reflect.internal.util.FileUtilsTest.$anonfun$showPerformance$1(FileUtilsTest.scala:56)
        at scala.reflect.internal.util.FileUtilsTest$$Lambda$6965/0x00000008019a2328.apply$mcVI$sp(Unknown Source)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:190)
        at scala.reflect.internal.util.FileUtilsTest.showPerformance(FileUtilsTest.scala:55)
[snip]
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at com.novocode.junit.JUnitRunner$1.execute(JUnitRunner.java:132)
        at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
        at sbt.ForkMain$Run$$Lambda$16/0x0000000800c08d20.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(java.base@16.0.1/FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@16.0.1/ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@16.0.1/ThreadPoolExecutor.java:630)
        at java.lang.Thread.run(java.base@16.0.1/Thread.java:831)
```
main is presumably normal
```
"main" #1 prio=5 os_prio=0 cpu=138.17ms elapsed=202.43s allocated=2577K defined_classes=262 tid=0x00007f4994024eb0 nid=0x243e waiting on condition  [0x00007f499c5d6000]
   java.lang.Thread.State: WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@16.0.1/Native Method)
        - parking to wait for  <0x00000006d5100cf0> (a java.util.concurrent.FutureTask)
        at java.util.concurrent.locks.LockSupport.park(java.base@16.0.1/LockSupport.java:211)
        at java.util.concurrent.FutureTask.awaitDone(java.base@16.0.1/FutureTask.java:447)
        at java.util.concurrent.FutureTask.get(java.base@16.0.1/FutureTask.java:190)
        at sbt.ForkMain$Run.runTestTasks(ForkMain.java:385)
        at sbt.ForkMain$Run.runTests(ForkMain.java:358)
        at sbt.ForkMain$Run.run(ForkMain.java:191)
        at sbt.ForkMain$Run.access$100(ForkMain.java:186)
        at sbt.ForkMain.main(ForkMain.java:177)
        at sbt.ForkMain.main(ForkMain.java:163)
```

**Comment by som-snytt** [comment]
This was just a merge bug one midnight.

**Comment by som-snytt** [comment]
This was just a merge bug one midnight.
