### ISSUE TITLE
Getting error in scala code "Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.charArrayOps([C)Lscala/collection/mutable/ArrayOps;"

### ISSUE THREAD

**Issue by Shital2408** [scala/bug#12427]
I am using Scala version using 2.12.3 in my project. When i am trying to run code i am getting below error (with same version it works for others).  Running code from sbt as well using eclipse IDE but still same issue. Crosscheck libraries version used in buildpath and installed version as well as check version sbt as well.

Version output from sbt prompt 

> sbtVersion
[info] basecamp/*:sbtVersion
[info] 	0.13.15
> scalaVersion
[info] basecamp/*:scalaVersion
[info] 	2.12.3
> 

**Error Log:**

Exception in thread "main" java.lang.NoSuchMethodError: scala.Predef$.charArrayOps([C)Lscala/collection/mutable/ArrayOps;
	at scala.util.parsing.json.Lexer.<init>(Lexer.scala:81)
	at scala.util.parsing.json.Parser.<init>(Parser.scala:121)
	at scala.util.parsing.json.JSON$.<init>(JSON.scala:32)
	at scala.util.parsing.json.JSON$.<clinit>(JSON.scala)
	at com.oed.scheduler.servlet.ReportSchedularListner.contextInitialized(ReportSchedularListner.scala:31)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at basecamp.lib.servlet.ServletServer.start(ServletServer.scala:99)
	at basecamp.dashboard.DashboardService.$anonfun$start$1(DashboardService.scala:134)
	at basecamp.dashboard.DashboardService.$anonfun$start$1$adapted(DashboardService.scala:69)
	at basecamp.lib.io.File.$anonfun$lock$3(File.scala:52)
	at basecamp.lib.io.File.$anonfun$lock$3$adapted(File.scala:52)
	at basecamp.lib.io.FileLockImpl.lock(File.scala:93)
	at basecamp.lib.io.File.lock(File.scala:52)
	at basecamp.dashboard.DashboardService.start(DashboardService.scala:136)
	at basecamp.dashboard.DashboardService$.start(DashboardService.scala:244)
	at basecamp.dashboard.DashboardService$.main(DashboardService.scala:240)
	at basecamp.dashboard.DashboardService.main(DashboardService.scala)

I need urgent help on this issue. I did lots of troubleshooting on this issue, but no luck.

**Comment by dwijnand** [comment]
Please use https://users.scala-lang.org/ (or maybe StackOverflow) for such troubleshooting questions.

**Comment by SethTisue** [comment]
see https://users.scala-lang.org/t/getting-error-in-scala-code-exception-in-thread-main-java-lang-nosuchmethoderror-scala-predef-chararrayops-c-lscala-collection-mutable-arrayops/7580
