### ISSUE TITLE
FatalError: bad qualifier received when trying to instantiate a trait with an existential variable prefix if the trait defines any methods

### ISSUE THREAD

**Issue by neko-kai** [scala/bug#12514]
## reproduction steps

using Scala 2.13.7,

```scala
import scala.language.existentials

trait T {
  trait Y {
    def x = 0
  }
}

object App extends App {
  println(new (t.type forSome { val t: T })#Y {}.x)
}
```

Scastie: https://scastie.scala-lang.org/7J0TZHVVQdaBcGHo3oB8pg

## problem

<details>
  <summary>Stack trace:</summary>

```
scala.reflect.internal.FatalError: 
  bad qualifier received: mkAttributedQualifier(App.t.type forSome { val t: (): T }, <none>)
     while compiling: /tmp/scastie14865556416669802642/src/main/scala/main.scala
        during phase: globalPhase=explicitouter, enteringPhase=erasure
     library version: version 2.13.7
    compiler version: version 2.13.7
  reconstructed args: -bootclasspath /home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.7/scala-library-2.13.7.jar -deprecation -feature -unchecked -Wconf:cat=unchecked:w -Wconf:cat=feature:w -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws -classpath /tmp/scastie14865556416669802642/target/scala-2.13/classes:/home/sbtRunnerContainer/.ivy2/local/org.scastie/runtime-scala_2.13/1.0.0-SNAPSHOT/jars/runtime-scala_2.13.jar:/home/sbtRunnerContainer/.ivy2/local/org.scastie/api_2.13/0.30.0+af8db5616740ad08e1579eb54bc8576d775b09a2/jars/api_2.13.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-json_2.13/2.10.0-RC5/play-json_2.13-2.10.0-RC5.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-functional_2.13/2.10.0-RC5/play-functional_2.13-2.10.0-RC5.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.7/scala-reflect-2.13.7.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.11.4/jackson-annotations-2.11.4.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.11.4/jackson-datatype-jdk8-2.11.4.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.11.4/jackson-datatype-jsr310-2.11.4.jar:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.jar -language:higherKinds -Xplugin:/home/sbtRunnerContainer/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/kind-projector_2.13.7/0.13.2/kind-projector_2.13.7-0.13.2.jar -Ydelambdafy:inline

  last tree to typer: EmptyTree
       tree position: <unknown>
            tree tpe: <notype>
              symbol: null
           call site: <$anon: App.t.Y> in package <empty>

== Source file context for tree position ==


	at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:121)
	at scala.reflect.internal.TreeGen.mkAttributedQualifier(TreeGen.scala:74)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.mixinOuterAccessorDef(ExplicitOuter.scala:381)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.$anonfun$transform$3(ExplicitOuter.scala:407)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.$anonfun$transform$2(ExplicitOuter.scala:405)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:398)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:350)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:309)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:517)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:350)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
	at scala.reflect.internal.Trees$Block.transform(Trees.scala:556)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:309)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:517)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:350)
	at scala.reflect.internal.Trees$Select.transform(Trees.scala:852)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:309)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:452)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:350)
	at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:309)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:517)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:350)
	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2591)
	at scala.reflect.internal.Trees$Apply.transform(Trees.scala:786)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:309)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:517)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:350)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$2(Trees.scala:2621)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2621)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
	at scala.reflect.internal.Trees$Template.transform(Trees.scala:544)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$1(TypingTransformers.scala:53)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:309)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:411)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:350)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2595)
	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:361)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:360)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:57)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:309)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:517)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:350)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2622)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2620)
	at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:342)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:32)
	at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:342)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.$anonfun$transform$2(TypingTransformers.scala:55)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2633)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:43)
	at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:38)
	at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:309)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:517)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:183)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.super$transformUnit(ExplicitOuter.scala:525)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.$anonfun$transformUnit$1(ExplicitOuter.scala:525)
	at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transformUnit(ExplicitOuter.scala:525)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:32)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:459)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:406)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1524)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1508)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1500)
	at scala.tools.nsc.Global$Run.compileFiles(Global.scala:1613)
```

</details>

Note, if trait Y defines no methods, as in `trait Y {}`, the above compiles and runs.

In practice I don't think anyone ever writes something like that  - that's no longer expressible in Scala 3 either - however I add this report because there was no previous report for this case when searching for 'bad qualifier received'. As well, I expected a rejection for existential `new` when the target class uses variables defined in outer class - because that's impossible to instantiate - but `def x = 0` does not refer to outer class, so it seemed odd to me that the error is the same as when there's usage of outer as in `trait T { val x = 0; trait Y { val y = x } }`.

**Comment by joroKr21** [comment]
You can see that the problem is in `ExplicitOuter` which means `Y` is retaining an outer reference regardless of whether you use it for something or not. Apropos you can also see in the stack trace that `Y` is unnecessarily treated as a mixin. It could be just an interface with a default method but that opportunity was missed in 2.13. If you make the method abstract, the error goes away. A crash is always bad but what you're trying to write is equivalent to `T#Y` so not sure if worth fixing.

**Comment by joroKr21** [comment]
I think this is the issue:
```scala
scala> typeOf[t.type forSome { val t: T }].isStable
val res1: Boolean = true
```

I don't think that's true. `t.type` is stable inside the existential but not outside of it.

**Comment by neko-kai** [comment]
> is equivalent to T#Y so not sure if worth fixing

I know it shouldn't work, just didn't expect a crash

**Comment by joroKr21** [comment]
It's complicated because qualifying terms is a hack:
https://github.com/scala/scala/blob/2.13.x/src/reflect/scala/reflect/internal/ExistentialsAndSkolems.scala#L79-L94
