### ISSUE TITLE
String Interpolation in annotation parameter causes NullPointerException

### ISSUE THREAD

**Issue by kamenitxan** [scala/bug#12538]
## reproduction steps

using Scala 2.13.8 (OpenJDK 64-Bit Server VM, Java 11.0.13),

```scala
scala> @java.lang.Deprecated(since = s"test") var i = 4
```

## problem
When I try to use string interpolation for annotation parameter it causes following compiler exception.

`java.lang.NullPointerException
	at scala.tools.nsc.typechecker.Typers$Typer.isDefaultArg$1(Typers.scala:3963)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedAnnotation$11(Typers.scala:3969)
	at scala.tools.nsc.typechecker.Typers$Typer.typedAnnotation(Typers.scala:4055)
	at scala.tools.nsc.typechecker.Namers$Namer.computeInfo$1(Namers.scala:1898)
	at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$annotSig$6(Namers.scala:1912)
	at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.forcedInfo$lzycompute(AnnotationInfos.scala:162)
	at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.forcedInfo(AnnotationInfos.scala:162)
	at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.completeInfo(AnnotationInfos.scala:175)
	at scala.tools.nsc.typechecker.Typers$Typer.typedValDefImpl(Typers.scala:2127)
	at scala.tools.nsc.typechecker.Typers$Typer.typedValDef(Typers.scala:2111)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5949)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6119)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3410)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3410)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2064)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1895)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5951)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6119)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3410)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3410)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2064)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1895)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5951)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6119)
	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3410)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3410)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5634)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5954)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:6041)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:117)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:459)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:106)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1524)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1508)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:744)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:967)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:533)
	at scala.tools.nsc.interpreter.IMain.doInterpret(IMain.scala:519)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:503)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:501)
	at scala.tools.nsc.interpreter.shell.ILoop.loop$1(ILoop.scala:878)
	at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:906)
	at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:433)
	at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:440)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:458)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:968)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
`

**Comment by som-snytt** [comment]
Not specific to REPL. With JDK17,
```
error: java.lang.NullPointerException: Cannot invoke "scala.reflect.internal.Symbols$Symbol.isDefaultGetter()" because the return value of "scala.reflect.internal.Trees$Tree.symbol()" is null
        at scala.tools.nsc.typechecker.Typers$Typer.isDefaultArg$1(Typers.scala:3963)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedAnnotation$11(Typers.scala:3969)
        at scala.tools.nsc.typechecker.Typers$Typer.typedAnnotation(Typers.scala:4055)
        at scala.tools.nsc.typechecker.Namers$Namer.computeInfo$1(Namers.scala:1898)
        at scala.tools.nsc.typechecker.Namers$Namer.$anonfun$annotSig$6(Namers.scala:1912)
        at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.forcedInfo$lzycompute(AnnotationInfos.scala:162)
        at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.forcedInfo(AnnotationInfos.scala:162)
        at scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.completeInfo(AnnotationInfos.scala:175)
        at scala.tools.nsc.typechecker.Typers$Typer.typedValDefImpl(Typers.scala:2127)

Exception in thread "main" java.lang.NullPointerException: Cannot invoke "scala.reflect.internal.Symbols$Symbol.isDefaultGetter()" because the return value of "scala.reflect.internal.Trees$Tree.symbol()" is null
        at scala.tools.nsc.typechecker.Typers$Typer.isDefaultArg$1(Typers.scala:3963)
```

**Comment by som-snytt** [comment]
oh, was
```
error: annotation argument needs to be a constant; found: ("test": String)
```
