### ISSUE TITLE
Failed to use default method parameter value in macro generated code

### ISSUE THREAD

**Issue by mbore** [scala/bug#12576]
## Reproduction steps

Scala version: 2.13.8
Macro definition: 
* package object
```scala
package object test {
    def wrapper(expr: Any): List[Any] = macro wrapper_impl
}
```
* body
```scala
  def wrapper_impl(c: blackbox.Context)(expr: c.Expr[Any]): c.Expr[List[Any]] = {
    import c.universe._
    
    val code = q"List.empty[Any].flatMap(x => List($expr))"

    c.Expr[List[Any]](code)
  }
```

Macro usage:
```scala
object TestMain extends App {

  case class A()
  case class B(i: Int, s: String)

  object B {
//the order matters in this case - if we swap params it works
    def default(s: String = "defaultString", i: Int): B = new B(i, s)
  }

// `a` param is necessary to reproduce the issue, but order, in this case, doesn't matter 
  case class C(b: B, a: A)

  object Test {
    val theC = wrapper(
      B.default(i = 1)
    )
  }

}
```

## Problem
In this example, compilation fails with 
```
[error] Error while emitting TestMain.scala
[error] value x$2
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

The issue was originally reported in MacWire - https://github.com/softwaremill/macwire/issues/197

**Comment by som-snytt** [comment]
macro.scala
```
import language.experimental.macros

import reflect.macros._

package object test {
  def wrapper(expr: Any): List[Any] = macro TestMacros.wrapper_impl
}

package test {

  object TestMacros {

    def wrapper_impl(c: blackbox.Context)(expr: c.Expr[Any]): c.Expr[List[Any]] = {
      import c.universe._

      val code = q"List.empty[Any].flatMap(x => List($expr))"

      c.Expr[List[Any]](code)
    }
  }
}
```
usage.scala
```
package usage

import test._

case class A()
case class B(i: Int, s: String)
object B {
  //the order matters in this case - if we swap params it works
  def default(s: String = "defaultString", i: Int): B = new B(i, s)
}

// `a` param is necessary to reproduce the issue, but order, in this case, doesn't matter
case class C(b: B, a: A)

object Wrapped {
  val theC = wrapper(B.default(i = 1))
  val expected = List.empty[Any].flatMap[B]((z: Any) => List({val y = "hi"; val x = 42; B(x,y)}))
}

object Test extends App {
  println {
    Wrapped.theC
  }
}
```
and
```
➜  t12576 scalac -d out macro.scala
➜  t12576 scalac -Vdebug -Vmacro-lite -Vprint:typer -d out -cp out usage.scala
```
shows
```
java.util.NoSuchElementException: value x$2
        at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:508)
        at scala.collection.mutable.AnyRefMap$ExceptionDefault.apply(AnyRefMap.scala:507)
        at scala.collection.mutable.AnyRefMap.apply(AnyRefMap.scala:207)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder$locals$.load(BCodeSkelBuilder.scala:428)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:375)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.$anonfun$genLoadArguments$1(BCodeBodyBuilder.scala:940)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:940)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:632)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:317)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlock(BCodeBodyBuilder.scala:819)
```

**Comment by som-snytt** [comment]
The hygienic form:
```
import language.experimental.macros

import reflect.macros._

package object test {
  def wrapper(expr: Any): List[Any] = macro TestMacros.wrapper_impl
}

package test {

  object TestMacros {

    def wrapper_impl(c: blackbox.Context)(expr: c.Expr[Any]): c.Expr[List[Any]] = {
      import c.universe._

      val f = q"(x: Any) => List($expr)"
      val g = c.typecheck(f)
      c.universe.internal.changeOwner(expr.tree, c.internal.enclosingOwner, g.symbol)
      val code = q"List.empty[Any].flatMap($g)"
      //val code = q"List.empty[Any].flatMap(x => List($expr))"

      c.Expr[List[Any]](code)
    }
  }
}
```
The difference is visible under `-Vsymbols`. Other helpful options are `-Vdebug`, `-Vmacro-lite`, `-Vmacro`.

See https://github.com/scala/scala/blob/v2.13.8/src/reflect/scala/reflect/macros/Universe.scala#L62

It was pretty painful to figure out the API. Is there documentation online?

https://www.scala-lang.org/api/2.13.8/scala-reflect/scala/reflect/?search=chang

It was 10 years ago that one of my first contributions had to do with broken ownership chain and default args failing in lambalift.

https://github.com/scala/scala/pull/468

May the chain never be broken!
