### ISSUE TITLE
Crash in macro expansion with untypecheck

### ISSUE THREAD

**Issue by lrytz** [scala/bug#12577]
Same in 2.12.15 and 2.13.8.

A.scala

```scala
import scala.language.experimental.macros
import scala.reflect.macros.blackbox.Context

object A {
  def foo[A, B](pf: PartialFunction[A, B]): PartialFunction[A, B] = macro impl
  def impl(c: Context)(pf: c.Tree): c.Tree = c.untypecheck(pf)
}
```

B.scala

```scala
trait X
class B[T](val i: Int)
object B {
  def unapply[T](b: B[T]): Option[Int] = Some(b.i)
}
object Test {
  def main(args: Array[String]): Unit = {
    A.foo[B[X], Int] { case B(x) => x }
  }
}
```

Compiling B gives

```
error: scala.reflect.internal.FatalError:
  unexpected UnApply B.unapply[X](<unapply-selector>) <unapply> ((x @ _))
     while compiling: B.scala
        during phase: typer
     library version: version 2.13.8
    compiler version: version 2.13.8
  reconstructed args:

  last tree to typer: UnApply
       tree position: line 8 of B.scala
              symbol: null
           call site: method applyOrElse in package <empty>

== Source file context for tree position ==

     5 }
     6 object Test {
     7   def main(args: Array[String]): Unit = {
     8     A.foo[B[X], Int] { case B(x) => x }
     9   }
    10 }
    11
	at scala.reflect.internal.Reporting.abort(Reporting.scala:69)
	at scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5990)
```

**Comment by joroKr21** [comment]
The issue with `untypecheck` is that it doesn't work for all trees because type checking is not idempotent: #5464
Extractors are mentioned as one of the problematic cases.

**Comment by som-snytt** [comment]
I see 8500 is the other umbrella ticket. I won't link to it.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/6356 seems relevant — it fixed something similar by rewriting `Unapply` to `Apply` in `ResetAttrs` ; do we need to do the same thing in one more place?
