### ISSUE TITLE
Flaky ProcessTest

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12652]
## Reproduction steps

Scala version: 2.13.10

```scala
sbt.ForkMain$ForkError: org.junit.ComparisonFailure: expected:<[hello, world]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at test.scala.sys.process.ProcessTest.$anonfun$t10823$7(ProcessTest.scala:97)
	at test.scala.sys.process.ProcessTest.$anonfun$t10823$7$adapted(ProcessTest.scala:97)
	at test.scala.sys.process.ProcessTest.$anonfun$t10823$4(ProcessTest.scala:97)
	at test.scala.sys.process.ProcessTest.$anonfun$t10823$4$adapted(ProcessTest.scala:92)
	at test.scala.sys.process.ProcessTest.$anonfun$t10823$1(ProcessTest.scala:92)
	at test.scala.sys.process.ProcessTest.testily(ProcessTest.scala:24)
	at test.scala.sys.process.ProcessTest.t10823(ProcessTest.scala:92)
```

## Problem

Flaky unit test fails once in a blue moon.

**Comment by som-snytt** [comment]
Not seen in recent memory. It's a good thing they are going to split `sys.process` into a separate project.
