### ISSUE TITLE
NullPointerException in scalac when compiling a case class with both -Ydebug and -Ylog:0-100

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12676]
## Reproduction steps

Scala version: 2.13.10

```scala
case class CaseClass(field :Int)
```

## Problem
Compiling with `-Ydebug -Ylog:0-100` *or* `-Xdev -Xprint:0-100` (in both cases, both flags must be present).
```
scalac: Error: Cannot invoke "xsbti.Reporter.log(xsbti.Problem)" because "this.delegate" is null
java.lang.NullPointerException: Cannot invoke "xsbti.Reporter.log(xsbti.Problem)" because "this.delegate" is null
	at xsbt.DelegatingReporter.info0(DelegatingReporter.scala:185)
	at scala.tools.nsc.reporters.MakeFilteringForwardingReporter.doReport(ForwardingReporter.scala:59)
	at scala.tools.nsc.reporters.FilteringReporter.info0(Reporter.scala:104)
	at scala.reflect.internal.Reporter.echo(Reporting.scala:109)
	at scala.reflect.internal.Reporting.inform(Reporting.scala:73)
	at scala.reflect.internal.Reporting.inform$(Reporting.scala:73)
	at scala.reflect.internal.SymbolTable.inform(SymbolTable.scala:28)
	at scala.reflect.internal.Reporting.inform(Reporting.scala:56)
	at scala.reflect.internal.Reporting.inform$(Reporting.scala:56)
	at scala.reflect.internal.SymbolTable.inform(SymbolTable.scala:28)
	at scala.tools.nsc.Global.debuglog(Global.scala:325)
	at scala.reflect.internal.SymbolTable$perRunCaches$.clearAll(SymbolTable.scala:452)
	at scala.tools.nsc.Global.close(Global.scala:1758)
	at xsbt.CachedCompiler0.close(CompilerBridge.scala:109)
	at xsbt.CompilerBridge.run(CompilerBridge.scala:41)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:57)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.doCompile(LocalServer.scala:52)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:30)
	at org.jetbrains.jps.incremental.scala.remote.Main$.compileLogic(Main.scala:209)
	at org.jetbrains.jps.incremental.scala.remote.Main$.$anonfun$handleCommand$1(Main.scala:192)
	at org.jetbrains.jps.incremental.scala.remote.Main$.decorated$1(Main.scala:182)
	at org.jetbrains.jps.incremental.scala.remote.Main$.handleCommand(Main.scala:189)
	at org.jetbrains.jps.incremental.scala.remote.Main$.serverLogic(Main.scala:165)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:105)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at com.facebook.nailgun.NGSession.runImpl(NGSession.java:312)
	at com.facebook.nailgun.NGSession.run(NGSession.java:198)
```
Almost certainly related to #12675 

I know these are all 'internal' flags, but I am trying to debug where another StackOverflowException in the compiler is coming from, so I need all the help I can get.

**Comment by som-snytt** [comment]
Not sure about the association, but this looks like it's at the sbt reporting level. (I haven't looked at the sbt code.)

**Comment by noresttherein** [comment]
I reported it here because the code was called from `scala` package. From what you say I assume SBT implements some sort of callback interface in the compiler, right? Should I report it to SBT project then?

**Comment by som-snytt** [comment]
Actually I see I have a branch of zinc that addresses the existing duplicate, which I reported once upon a time.

https://github.com/sbt/zinc/issues/806
