### ISSUE TITLE
scala-2.13.10 fails scala.tools.tastytest.TastyTestJUnit.negFullCircle due to incorrect formatting

### ISSUE THREAD

**Issue by telans** [scala/bug#12694]
The test scala.tools.tastytest.TastyTestJUnit.negFullCircle fails due to incorrect formatting within test output.

## Reproduction steps

Scala version: 2.13.10

${WORKDIR} is simply a temporary directory used for building.

1. `sbt -Djavac.args="-encoding UTF-8" -Duser.home="${WORKDIR}" compile`
2. `sbt -Djavac.args="-encoding UTF-8" -Duser.home="${WORKDIR}" publishLocal`
3. `sbt -Djavac.args="-encoding UTF-8" -Duser.home="${WORKDIR}" test`

There is no change with or without `-Djavac.args="-encoding UTF-8"`

```
[info] Test scala.tools.tastytest.TastyTestJUnit.negFullCircle started
ERROR: /var/tmp/portage/dev-lang/scala-2.13.10/work/scala-2.13.10/test/tasty/neg-full-circle/src-3-app/TestExperimentalDefsPre_fail.scala failed, unexpected output.
--- check
+++ output
@@ -1,17 +1,17 @@
--- Error: TestExperimentalDefsPre_fail.scala:4:10
+-- Error: TestExperimentalDefsPre_fail.scala:4:10 ------------------------------------------------------------------------------------------
 4 |  def test = new SubExperimentalNotExperimental
   |          ^
-  |object ExperimentalDefsPre is marked @experimental and therefore may only be used in an experimental scope.
--- Error: TestExperimentalDefsPre_fail.scala:4:17
+  |          object ExperimentalDefsPre is marked @experimental and therefore may only be used in an experimental scope.
+-- Error: TestExperimentalDefsPre_fail.scala:4:17 ------------------------------------------------------------------------------------------
 4 |  def test = new SubExperimentalNotExperimental
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-  |object ExperimentalDefsPre is marked @experimental and therefore may only be used in an experimental scope.
--- Error: TestExperimentalDefsPre_fail.scala:6:35
+  |                 object ExperimentalDefsPre is marked @experimental and therefore may only be used in an experimental scope.
+-- Error: TestExperimentalDefsPre_fail.scala:6:35 ------------------------------------------------------------------------------------------
 6 |  class SubSubExperimental extends SubExperimentalNotExperimental
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-  |object ExperimentalDefsPre is marked @experimental and therefore may only be used in an experimental scope.
--- Error: TestExperimentalDefsPre_fail.scala:6:8
+  |                                   object ExperimentalDefsPre is marked @experimental and therefore may only be used in an experimental scope.
+-- Error: TestExperimentalDefsPre_fail.scala:6:8 -------------------------------------------------------------------------------------------
 6 |  class SubSubExperimental extends SubExperimentalNotExperimental
   |        ^
-  |extension of experimental class SubExperimentalNotExperimental must have @experimental annotation
+  |        extension of experimental class SubExperimentalNotExperimental must have @experimental annotation
 4 errors found
[error] Test scala.tools.tastytest.TastyTestJUnit.negFullCircle failed: java.lang.AssertionError: scala.tools.tastytest.TestFailure: 1 error. These sources either compiled or had an incorrect or missing check file: /var/tmp/portage/dev-lang/scala-2.13.10/work/scala-2.13.10/test/tasty/neg-full-circle/src-3-app/TestExperimentalDefsPre_fail.scala., took 4.649 sec
[error]     at scala.tools.tastytest.TastyTestJUnit$TryOps$.eval$extension(TastyTestJUnit.scala:104)
[error]     at scala.tools.tastytest.TastyTestJUnit.negFullCircle(TastyTestJUnit.scala:67)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
```

## Problem

It appears that the test is failing due to indented output despite the error being expected. No other tests appear to fail. I have attached the build log below.

[build.log](https://github.com/scala/bug/files/10101600/build.log)

**Comment by SethTisue** [comment]
@bishabosha ?

**Comment by bishabosha** [comment]
Thanks for spotting this, I'll take a look

**Comment by bishabosha** [comment]
not really sure what to say about this, I can't reproduce it :) unless there is a dotty compiler setting that affects whitespace on your OS?

**Comment by som-snytt** [comment]
The lack of a horizontal dashed line says `pageWidth` is not set. If `-pagewidth` is not provided, it defaults to `COLUMNS` or on windows `ANSICON`.
