### ISSUE TITLE
StackOverflowError in scalac (reg. NoArgsTypeRef.typeParams)

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12741]
## Reproduction steps

Scala version: 2.13.10

```scala
	trait Base[L, R] {
		type U
		val swap :Base[R, L] { type U = Base.this.U }
	}
	trait Sub[L, R] extends Base[L, R] {
		type U
		override val swap :Sub[R, L] { type U = Sub.this. U }
	}
```

## Problem

```
	at scala.reflect.internal.Types$NoArgsTypeRef.typeParams(Types.scala:2160)
	at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1809)
	at scala.reflect.internal.Types$NoArgsTypeRef.typeParams(Types.scala:2160)
	at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1809)
	at scala.reflect.internal.Types$NoArgsTypeRef.typeParams(Types.scala:2160)
	at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1809)
        ...
```

**Comment by SethTisue** [comment]
a bit more minimal:

```scala
trait Base {
   type U
   def swap: Base { type U = Base.this.U }
}
trait Sub extends Base {
  override val swap: Sub { type U = Sub.this.U }
}
```

**Comment by som-snytt** [comment]
@noresttherein never rests. Nor does @SethTisue when minimizing.

I observe that no one begins by saying, "I don't wish to appear to be minimizing your problem, but..."

**Comment by noresttherein** [comment]
Sorry for not minimizing it. I mean, I was so surprised by it being already so simple, because I was so sure I did it already countless times, and I kind of assumed it's already minimized.

**Comment by joroKr21** [comment]
The most confusing part is that in the minimal version there are no `typeParams` involved 🤔
