### ISSUE TITLE
REPL won't tell me the parameters with multiple completion candidates

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12843]
## Reproduction steps

Scala version: 2.13.11

```scala
scala> b.update()
               ^
       error: not enough arguments for method update: (index: Int, elem: String): Unit.
       Unspecified value parameters index, elem.

scala> b.update
         ^
       error: missing argument list for method update in class ArrayBuffer
       Unapplied methods are only converted to functions when a function type is expected.
       You can make this conversion explicit by writing `update _` or `update(_,_)` instead of `update`.
```

## Problem

I'd like to see the signature without attempting an invocation. (Because who knows what may happen.)

It would be nice if `missing argument list` just told me the signature if unique, or that there are overloads.

Completion no longer tells me parameters when there are multiple completion candidates. (This used to be offered on subsequent tab.)

In this case, `update` and `updated` are candidates.

It does report signatures of a single completion candidate with overloads:
```
def remove(index: Int, count: Int): Unit
def remove(index: Int): String

scala> b.remove
```

**Comment by SethTisue** [comment]
Yeah, this has long bugged me.

**Comment by som-snytt** [comment]
First tab

![Image](https://github.com/user-attachments/assets/4265bd20-2692-47c7-8e9c-95bc9620afc6)

Second tab to select with enter

![Image](https://github.com/user-attachments/assets/41324349-4845-4351-8729-02dac1a61b55)

Third tab to show it above the prompt (instead of below?)

![Image](https://github.com/user-attachments/assets/0396267c-67fd-4a4a-83d4-cfe2dea5b664)

Fourth tab to select updated instead then fifth tab for sig (actually I've lost track of the tabs while pasting screen shots)

![Image](https://github.com/user-attachments/assets/e92d7c6b-6e67-4dbe-85e8-56bb30fd5c7b)

The carefully curated IOOBE is different for `updated`:

```
scala> b.updated(0, 42)
java.lang.IndexOutOfBoundsException: 0
  at scala.collection.SeqOps.updated(Seq.scala:956)
  at scala.collection.SeqOps.updated$(Seq.scala:953)
  at scala.collection.AbstractSeq.updated(Seq.scala:1190)
  ... 30 elided

scala> b.update(0, 42)
java.lang.IndexOutOfBoundsException: 0 is out of bounds (min 0, max -1)
  at scala.collection.generic.CommonErrors$.indexOutOfBounds(CommonErrors.scala:23)
  at scala.collection.mutable.ListBuffer.update(ListBuffer.scala:207)
  ... 30 elided
```

The behavior is similar but the signature is different on 3.6.4:
```
scala> val b = collection.mutable.ListBuffer.empty[Int]
val b: scala.collection.mutable.ListBuffer[Int] = ListBuffer()

def update(idx: Int, elem: A): Unit

def updated[B >: A](index: Int, elem: B): CC[B]

scala> b.updated
```

Less convenient 2.12 does not tab through alternatives, so you must finish typing it yourself and then tab for sig:
```
Welcome to Scala 2.12.20 (OpenJDK 64-Bit Server VM, Java 23.0.2).
Type in expressions for evaluation. Or try :help.

scala> val b = collection.mutable.ListBuffer.empty[Int]
b: scala.collection.mutable.ListBuffer[Int] = ListBuffer()

scala> b.update
update   updated

scala> b.update
   def update(n: Int,x: Int): Unit

scala> b.update
   def update(n: Int,x: Int): Unit

scala> b.updated

def updated[B >: Int, That](index: Int,elem: B)(implicit bf: scala.collection.generic.CanBuildFrom[scala.collection.mutable.ListBuffer[Int],B,That]): That

scala> b.updated
```
I don't know that I was right that the behavior used to be different: for a single completion candidate, tab shows sigs of all overloads. If more than one completion candidate, you must complete before viewing sigs. (Edit: it works that way in 2.13.11, so I don't know what my problem was.)

My other observation was that it doesn't show the sig of a missing arg list, but will show sigs of ambiguous overload, which is somehow ironic:
```
scala> b.remove
         ^
       error: ambiguous reference to overloaded definition,
       both method remove in class ListBuffer of type (idx: Int, count: Int): Unit
       and  method remove in class ListBuffer of type (idx: Int): Int
       match expected type ?

scala> b.update
         ^
       error: missing argument list for method update in class ListBuffer
       Unapplied methods are only converted to functions when a function type is expected.
       You can make this conversion explicit by writing `update _` or `update(_,_)` instead of `update`.
```
Maybe I will keep this open just for that part; maybe that's what bugged Seth and not the tab behavior.

**Comment by som-snytt** [comment]
The foulest check file:
```
test/files/run/t12720.check:newSource1.scala:14: error: missing argument list for method f*** in class D***
```

**Comment by som-snytt** [comment]
The other point is that the method may be overloaded even if an alternative has been selected.
```
t13055.scala:15: error: missing argument list for method forAll in object Main of type [T1, P](g: Main.Gen[T1])(f: T1 => P)(implicit p: P => Main.Prop): Main.Prop
```
because the source looks like
```
  def forAll[T1, P](g: Gen[T1])(f: T1 => P)(implicit p: P => Prop): Prop = ???
  def forAll[A1, P](f: A1 => P)(implicit p: P => Prop): Prop = ???
```
where the current message is unhelpful (or at least unhintful).
