### ISSUE TITLE
IllegalAccessError when accessing a Java protected member via a self-type

### ISSUE THREAD

**Issue by scabug** [scala/bug#3564]
This is with Scala 2.8.0.RC3

Steps to reproduce:

in p/Base.java

```scala
package p;
public class Base {
  protected void test() { }
}
```

in test.scala 

```scala
trait Ext {
  this: p.Base =>
  def run = test // Access Java protected member here
}

object Test {
  def main(args: Array[String]) {
    val s = new p.Base with Ext
    s.run
  }
}
```

compile & run
```scala
$$ javac p/Base.java
$$ scalac test.scala
$$ scala Test
java.lang.IllegalAccessError: tried to access method p.Base.test()V from class Ext$$class
	at Ext$$class.run(test.scala:3)
	at Test$$$$anon$$1.run(test.scala:8)
	at Test$$.main(test.scala:9)
	at Test.main(test.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at scala.tools.nsc.util.ScalaClassLoader$$$$anonfun$$run$$1.apply(ScalaClassLoader.scala:81)
	at scala.tools.nsc.util.ScalaClassLoader$$class.asContext(ScalaClassLoader.scala:24)
	at scala.tools.nsc.util.ScalaClassLoader$$URLClassLoader.asContext(ScalaClassLoader.scala:86)
	at scala.tools.nsc.util.ScalaClassLoader$$class.run(ScalaClassLoader.scala:81)
	at scala.tools.nsc.util.ScalaClassLoader$$URLClassLoader.run(ScalaClassLoader.scala:86)
	at scala.tools.nsc.MainGenericRunner$$.main(MainGenericRunner.scala:78)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

If the base class is written in Scala, this doesn't happen (because the protected method is compiled as public).

**Comment by SethTisue** [comment]
this is broken in 2.11.11 and 2.12.2 (thx @RomanIakovlev for calling attention to it)

**Comment by unkarjedy** [comment]
caught the error at runtime in `2.12.7`

**Comment by unkarjedy** [comment]
Ok, I managed to prepare a minimal reproducible example even with scala **2.13.3** 
(example project: [illegal_access_to_protected_member.zip](https://github.com/scala/bug/files/4936852/illegal_access_to_protected_member.zip))

It looks like there is no any error when both scala class and base java classes are in the same scope `main` (run `Main.scala`).
But the error arises if you place scala classes in `test` scope and.

![image](https://user-images.githubusercontent.com/3989292/87771442-03221100-c829-11ea-8f9a-a07a3abe4494.png)

![image](https://user-images.githubusercontent.com/3989292/87771889-a541f900-c829-11ea-8006-bf0f1a9250f4.png)

![image](https://user-images.githubusercontent.com/3989292/87772019-d1f61080-c829-11ea-8853-df172a25feb4.png)

```
Exception in thread "main" java.lang.IllegalAccessError: class test_package.MyTrait tried to access protected field main_package.BaseJavaClass.baseField (test_package.MyTrait and main_package.BaseJavaClass are in unnamed module of loader 'app')
	at test_package.MyTrait.bar(MainFromTests.scala:18)
	at test_package.MyTrait.bar$(MainFromTests.scala:18)
	at test_package.MyClass.bar(MainFromTests.scala:8)
	at test_package.MyClass.foo(MainFromTests.scala:12)
	at test_package.MainFromTests$.main(MainFromTests.scala:5)
	at test_package.MainFromTests.main(MainFromTests.scala)
```

**Comment by unkarjedy** [comment]
Encountered it once again, this time base class was from a library jar

**Comment by som-snytt** [comment]
Possibly related to https://github.com/scala/bug/issues/12249

**Comment by som-snytt** [comment]
Scala 3.now says
```
➜  t3564 ~/projects/dotty/bin/scalac -d out3 -cp out3 illegal_access_to_protected_member/src/test/scala/test_package/MainFromTests.scala
-- Error: illegal_access_to_protected_member/src/test/scala/test_package/MainFromTests.scala:13:20 ---------------------
13 |  def bar: String = baseField
   |                    ^^^^^^^^^
   |                    illegal access to protected variable baseField in class BaseJavaClass from trait MyTrait
1 error found
```
versus (to confirm)
```
➜  t3564 scala -cp out test_package.MainFromTests
Exception in thread "main" java.lang.IllegalAccessError: class test_package.MyTrait tried to access protected field main_package.BaseJavaClass.baseField (test_package.MyTrait and main_package.BaseJavaClass are in unnamed module of loader java.net.URLClassLoader @6537cf78)
        at test_package.MyTrait.bar(MainFromTests.scala:13)
        at test_package.MyTrait.bar$(MainFromTests.scala:13)
        at test_package.MyClass.bar(MainFromTests.scala:9)
        at test_package.MyClass.foo(MainFromTests.scala:10)
        at test_package.MainFromTests$.main(MainFromTests.scala:7)
        at test_package.MainFromTests.main(MainFromTests.scala)
```

**Comment by som-snytt** [comment]
Or I guess fixed isn't the right word.
