### ISSUE TITLE
getClass raises Stackoverflow In Script Mode

### ISSUE THREAD

**Issue by scabug** [scala/bug#4033]
In Script mode

```scala
>cat testCode.scala
object ok {
  def klass = ok.getClass
}

object ng {
  val klass = ng.getClass
}

println("ok:" + ok.klass)
println("ng:" + ng.klass)

>scala testCode.scala
```

I expect the following behavior.

```scala
ok:class Main$$$$anon$$1$$ok$$
ng:class Main$$$$anon$$1$$ng$$
```

but...

```scala
ok:class Main$$$$anon$$1$$ok$$
java.lang.StackOverflowError
	at Main$$$$anon$$1.Main$$$$anon$$$$ng(testCode.scala:5)
	at Main$$$$anon$$1$$ng$$.<init>(testCode.scala:6)
	at Main$$$$anon$$1.Main$$$$anon$$$$ng(testCode.scala:5)
	at Main$$$$anon$$1$$ng$$.<init>(testCode.scala:6)
	at Main$$$$anon$$1.Main$$$$anon$$$$ng(testCode.scala:5)
	at Main$$$$anon$$1$$ng$$.<init>(testCode.scala:6)
                    :
```

Scala:2.8.1.final

Java:1.6.0_22

Operating system:MacOS 10.6.5

**Comment by som-snytt** [comment]
This is a consequence of wrapping the code local to main.

A quick workaround would be moving top-level to a second file: https://github.com/scala/bug/issues/5161

Other future workarounds: top-level defs and alt ways to invoke main.
