### ISSUE TITLE
specialized references specialized: IllegalAccessError

### ISSUE THREAD

**Issue by scabug** [scala/bug#4511]
```scala
/** Test case from Lukas Pustina (pustina@cs.uni-bonn.de)
 */

class Interval[@specialized T](val high: T)
class Node[@specialized T](val interval: Interval[T]) {
  val x1 = Some(interval.high)
}

object Test {
  def main(args: Array[String]): Unit = {
    new Node(new Interval(5)).x1
  }
}
```
Output:
```scala
java.lang.IllegalAccessError
	at Node$$mcI$$sp.<init>(0424.scala:6)
	at Test$$.main(0424.scala:11)
	at Test.main(0424.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
```
Same with 2.8.1 or r24819.

**Comment by som-snytt** [comment]
From https://github.com/scala/bug/issues/10967
```
class A[@specialized(Int) T]

class B[@specialized(Int) T] {
  val a = new A[T]
  val b = new Object // requires a second field for the bug to occur
}

object BugDemo extends App {
  new B[Int]
}
```

**Comment by pityka** [comment]
Hi, I think I am seeing a bug similar to this (or the same). I found the following minimized example:
```
// removing the annotation makes it work
class A[@specialized T] 

// inserting the @specialized annotation makes it work
class B[T] 

// removing the annotation makes it work
class O[@specialized T] {
  println("a")
  val a = new A[T]
  println("b")
  val c = new B[T]
  println("c")
}

object App  {
  def main(args:Array[String]) {
    println(new O[Int])
  }
}
```

Running it in sbt produces:
```
[info] Running App
a
b
[error] (run-main-6) java.lang.IllegalAccessError
[error] java.lang.IllegalAccessError
[error] 	at O$mcI$sp.<init>(bug.scala:13)
[error] 	at App$.main(bug.scala:19)
[error] 	at App.main(bug.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
```

I tried with sbt 1.3.0 and 1.2.8 with scala version 2.11.9 2.12.0 2.12.9 2.13.0.

Thanks for all of your work on the scala project

**Comment by joroKr21** [comment]
```scala
class B[@specialized(Int) T](t: T) {
  val a = t
  val b = "?"
}

new B(42)
```
