### ISSUE TITLE
scalap unable to parse signatures with a constant type over a java enum

### ISSUE THREAD

**Issue by scabug** [scala/bug#5194]
Just started to work on some scalap related issues and found following problem:
Example:

Java:
```scala
package com;

public enum K {
    K
}
```

Scala:
```scala
package com

object KK {
  val k = com.K.K
}

object ZZ {
  final val z = com.K.K
}
```

After compilation scalap can open class KK, however for class ZZ it's failed with exception.
Problem with value getter type. It has different byte code presentation:
28 7 -62 -128 -124 0 29 in first case
28 7 -62 -128 -124 2 29 in second case (this is failed for type parser => exception)
It's almost the same, however it should be exactly the same, because only difference is final modifier (I think second case shouldn't compile at all, because value z is already final, however it's not related issue).
I'm not sure if it's compiler related bug, so if you can explain me this difference, feel free to assign this issue to me, I'll fix it in scalap.

Original class with this problem (compiled with 2.8.1): play-scala.jar!\play\db\jpa\FetchTypeWrapper.class
I checked with 2.9.1, still the same.

**Comment by retronym** [comment]
```
$ cat sandbox/test.scala && scalac sandbox/test.scala && scalap C
class C {
  final val Constant = java.util.concurrent.TimeUnit.DAYS
}

Exception in thread "main" scala.tools.scalap.scalax.rules.ScalaSigParserError: Unexpected failure
	at scala.tools.scalap.scalax.rules.Rules.$anonfun$expect$1(Rules.scala:75)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigSymbol.applyRule(Symbol.scala:36)
	at scala.tools.scalap.scalax.rules.scalasig.SymbolInfoSymbol.infoType$lzycompute(Symbol.scala:71)
	at scala.tools.scalap.scalax.rules.scalasig.SymbolInfoSymbol.infoType(Symbol.scala:71)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.printMethod(ScalaSigPrinter.scala:258)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.printSymbol(ScalaSigPrinter.scala:64)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.$anonfun$printChildren$1(ScalaSigPrinter.scala:91)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.$anonfun$printChildren$1$adapted(ScalaSigPrinter.scala:91)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.printChildren(ScalaSigPrinter.scala:91)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.printClass(ScalaSigPrinter.scala:147)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.printSymbol(ScalaSigPrinter.scala:62)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.printSymbol(ScalaSigPrinter.scala:31)
	at scala.tools.scalap.Main.$anonfun$parseScalaSignature$1(Main.scala:87)
	at scala.tools.scalap.Main.parseScalaSignature(Main.scala:87)
	at scala.tools.scalap.Main.decompileScala(Main.scala:96)
	at scala.tools.scalap.Main.process(Main.scala:122)
	at scala.tools.scalap.Main$.$anonfun$main$4(Main.scala:195)
	at scala.tools.scalap.Main$.main(Main.scala:195)
	at scala.tools.scalap.Main.main(Main.scala)
```

**Comment by retronym** [comment]
Similar problem with `ClazzTag` constants:

```
$ cat sandbox/test.scala && qscalac sandbox/test.scala && scalap C
class C {
  final val Constant = classOf[String]
}

Exception in thread "main" scala.MatchError: TypeRefType(SingleType(TypeRefType(ThisType(<no symbol>.<root>),scala,List()),scala.Predef),scala.Predef.String,List()) (of class scala.tools.scalap.scalax.rules.scalasig.TypeRefType)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.toString(ScalaSigPrinter.scala:332)
	at scala.tools.scalap.scalax.rules.scalasig.ScalaSigPrinter.toString(ScalaSigPrinter.scala:325)
```

**Comment by retronym** [comment]
Other constants parse correctly, but fail to print the constant type correctly:

```
$ cat sandbox/test.scala && qscalac sandbox/test.scala && scalap C
class C {
  final val Constant = ""
}

class C extends scala.AnyRef {
  def this() = { /* compiled code */ }
  final val Constant: java.lang.String = { /* compiled code */ }
}

```
