### ISSUE TITLE
-optimise crash: Record Record(anonymous class JavaToScala$$anonfun$makeScalaPackage$1,Map()) does not contain a field value owner$1

### ISSUE THREAD

**Issue by scabug** [scala/bug#5391]
Not the world's tightest reproduction but all I have at the moment.
```
% scalac3 -optimise -d /tmp $(find src/compiler/scala/reflect src/library/scala/reflect/api src/library/scala/runtime -name '*.scala')

error: java.lang.AssertionError: assertion failed: Record Record(anonymous class JavaToScala$$anonfun$makeScalaPackage$1,Map()) does not contain a field value owner$1
	at scala.Predef$.assert(Predef.scala:160)
	at scala.tools.nsc.backend.icode.analysis.CopyPropagation$copyLattice$State.getFieldNonRecordValue(CopyPropagation.scala:119)
	at scala.tools.nsc.backend.icode.analysis.CopyPropagation$copyLattice$State.getFieldNonRecordValue(CopyPropagation.scala:128)
	at scala.tools.nsc.backend.opt.ClosureElimination$ClosureElim$$anonfun$analyzeMethod$2$$anonfun$apply$2.replaceFieldAccess$1(ClosureElimination.scala:124)
	at scala.tools.nsc.backend.opt.ClosureElimination$ClosureElim$$anonfun$analyzeMethod$2$$anonfun$apply$2.apply(ClosureElimination.scala:140)
	at scala.tools.nsc.backend.opt.ClosureElimination$ClosureElim$$anonfun$analyzeMethod$2$$anonfun$apply$2.apply(ClosureElimination.scala:106)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
	at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
	at scala.tools.nsc.backend.icode.BasicBlocks$BasicBlock.foreach(BasicBlocks.scala:184)
	at scala.tools.nsc.backend.opt.ClosureElimination$ClosureElim$$anonfun$analyzeMethod$2.apply(ClosureElimination.scala:106)
	at scala.tools.nsc.backend.opt.ClosureElimination$ClosureElim$$anonfun$analyzeMethod$2.apply(ClosureElimination.scala:102)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
```

**Comment by SethTisue** [comment]
closing old back end tickets that are likely no longer applicable
