### ISSUE TITLE
Compiler barfs on source referring to class which refers to an annotation class not on the classpath

### ISSUE THREAD

**Issue by scabug** [scala/bug#5420]
Given a simple java class with an annotation:

```java
@Foo
public class FooBean {
    ...
}
```

FooBean is already compiled and available on the compiler classpath.

when attempting to compile some scala code that instantiates/uses the FooBean class when the Foo annotation class is not accessible on the compiler's classpath but FooBean is, the scala compiler gives me a "Missing dependency" error:

```scala
scala> new FooBean
error: error while loading FooBean, Missing dependency 'class package.to.Foo', required by /home/raman/test/jars/foobean.jar(FooBean.class)
<console>:8: error: FooBean does not have a constructor
              new FooBean
```

This seems very similar to #1135, the fix for which should be in 2.9.1. This also seems similar to #5343, which is marked as Fixed and will be in 2.10.x. However, [as per Jason Zaugg on the users mailing list](https://groups.google.com/d/msg/scala-user/IRtPohkz0dw/gKMzAkDmcHIJ), this issue will still occur even with the fix for #5343.

I have verified this by checking this on Scala 2.10.0.M1, and get the following error:

```scala
scala> new FooBean
warning: Class package.to.Foo not found - continuing with a stub.
java.lang.AssertionError: assertion failed: package.to.Foo
        at scala.Predef$.assert(Predef.scala:160)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:946)
        at scala.reflect.internal.Symbols$TypeSymbol.isNonBottomSubClass(Symbols.scala:2324)
        at scala.reflect.internal.AnnotationInfos$AnnotationInfo.matches(AnnotationInfos.scala:220)
        at scala.reflect.internal.AnnotationInfos$Annotatable$$anonfun$hasAnnotation$1.apply(AnnotationInfos.scala:37)
        at scala.reflect.internal.AnnotationInfos$Annotatable$$anonfun$hasAnnotation$1.apply(AnnotationInfos.scala:37)
        at scala.collection.LinearSeqOptimized$class.exists(LinearSeqOptimized.scala:79)
        at scala.collection.immutable.List.exists(List.scala:76)
        at scala.reflect.internal.AnnotationInfos$Annotatable$class.hasAnnotation(AnnotationInfos.scala:37)
        at scala.reflect.internal.Symbols$Symbol.hasAnnotation(Symbols.scala:71)
        at scala.reflect.internal.Symbols$Symbol.isDeprecated(Symbols.scala:533)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.checkDeprecated(RefChecks.scala:1275)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.scala$tools$nsc$typechecker$RefChecks$RefCheckTransformer$$checkTypeRef(RefChecks.scala:1379)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$24.apply(RefChecks.scala:1581)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$24.apply(RefChecks.scala:1577)
        at scala.reflect.internal.Types$ForEachTypeTraverser.traverse(Types.scala:4331)
        at scala.reflect.internal.Types$Type.foreach(Types.scala:708)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.doTypeTraversal(RefChecks.scala:1388)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1577)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$4.apply(Trees.scala:1156)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$4.apply(Trees.scala:1155)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:1271)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:1154)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1632)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1226)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1139)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:243)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:243)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:76)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:243)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:112)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:107)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:1174)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1632)
        at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:1248)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$2.apply(Trees.scala:1146)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$2.apply(Trees.scala:1145)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:1271)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:1144)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1632)
        at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:1246)
        at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:1246)
        at scala.collection.immutable.List.loop$1(List.scala:150)
        at scala.collection.immutable.List.mapConserve(List.scala:166)
        at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:1246)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.eliminateModuleDefs(RefChecks.scala:1185)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1224)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1139)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:243)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:243)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:76)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:243)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:112)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:107)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:1174)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1632)
        at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:1248)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$2.apply(Trees.scala:1146)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$2.apply(Trees.scala:1145)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:1271)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:1144)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1632)
        at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:1246)
        at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:1246)
        at scala.collection.immutable.List.loop$1(List.scala:150)
        at scala.collection.immutable.List.mapConserve(List.scala:166)
        at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:1246)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.eliminateModuleDefs(RefChecks.scala:1185)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1224)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1139)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:243)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:243)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:76)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:243)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:112)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:107)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:1174)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1632)
        at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:1248)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$2.apply(Trees.scala:1146)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$2.apply(Trees.scala:1145)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:1271)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:1144)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1632)
        at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:1246)
        at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:1246)
        at scala.collection.immutable.List.loop$1(List.scala:150)
        at scala.collection.immutable.List.mapConserve(List.scala:166)
        at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:1246)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.eliminateModuleDefs(RefChecks.scala:1185)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1224)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$$anonfun$transformStats$1.apply(RefChecks.scala:1139)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:243)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:243)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
        at scala.collection.immutable.List.foreach(List.scala:76)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:243)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:112)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:107)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$1.apply(Trees.scala:1140)
        at scala.reflect.api.Trees$Transformer$$anonfun$transform$1.apply(Trees.scala:1140)
        at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:1271)
        at scala.reflect.api.Trees$Transformer.transform(Trees.scala:1139)
        at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1632)
        at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:225)
        at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:386)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:355)
        at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:349)
        at scala.collection.Iterator$class.foreach(Iterator.scala:687)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1112)
        at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:349)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1130)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1105)
        at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:445)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:835)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:789)
        at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:953)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:616)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:583)
        at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:777)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:828)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:734)
        at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:598)
        at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:605)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:608)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:905)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:870)
        at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:870)
        at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:155)
        at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:870)
        at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:79)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:92)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
```

**Comment by SethTisue** [comment]
it's possible this got fixed along the way somewhere — someone could check. some work occurred in this general area around [SCP-009](https://github.com/scalacenter/advisoryboard/blob/main/proposals/009-improve-direct-dependency-experience.md)

**Comment by som-snytt** [comment]
The last nail in the coffin was https://github.com/scala/scala/pull/3655

I tweaked the test in 10999 so now the only question is which PR will make the odometer roll over.
