### ISSUE TITLE
cannot reify implicit classes

### ISSUE THREAD

**Issue by scabug** [scala/bug#5758]
```scala
import scala.reflect.mirror._

class Foo

object Test extends App {
  reify {
    implicit class FooPimped(foo: Foo) {
      def bar = println("hello")
    }

    new Foo().bar
  }.eval
}
```

```scala
reifying = 
{
  implicit class FooPimped extends scala.AnyRef {
    <paramaccessor> private[this] val foo: Foo = _;
    def <init>(foo: Foo): FooPimped = {
      FooPimped.super.<init>();
      ()
    };
    def bar: Unit = scala.this.Predef.println("hello")
  };
  implicit <synthetic> def FooPimped(foo: Foo): FooPimped = new FooPimped(foo);
  FooPimped(new Foo()).bar
}
Block(List(ClassDef(Modifiers(Set(`implicit`)), newTypeName("FooPimped"), List(), Template(List(Select(Ident(newTermName("scala")), newTypeName("AnyRef"))), emptyValDef, List(ValDef(Modifiers(Set(paramAccessor, `private`, local)), newTermName("foo"), TypeTree().setType(Foo), EmptyTree), DefDef(Modifiers(), newTermName("<init>"), List(), List(List(ValDef(Modifiers(Set(parameter, paramAccessor)), newTermName("foo"), TypeTree().setType(Foo), EmptyTree))), TypeTree().setType(FooPimped), Block(List(Apply(Select(Super(This(newTypeName("")), newTypeName("")), newTermName("<init>")), List())), Literal(Constant(())))), DefDef(Modifiers(), newTermName("bar"), List(), List(), TypeTree().setType(Unit), Apply(Select(Select(This(newTypeName("scala")), newTermName("Predef")), newTermName("println")), List(Literal(Constant("hello")))))))), DefDef(Modifiers(Set(`implicit`)), newTermName("FooPimped"), List(), List(List(ValDef(Modifiers(Set(parameter, paramAccessor)), newTermName("foo"), TypeTree().setType(Foo), EmptyTree))), TypeTree().setType(FooPimped), ApplyConstructor(Select(New(Ident(newTypeName("FooPimped"))), newTermName("<init>")), List(Ident(newTermName("foo")))))), Select(Apply(Ident(newTermName("FooPimped")), List(ApplyConstructor(Select(New(Ident(newTypeName("Foo"))), newTermName("<init>")), List()))), newTermName("bar")))
reifee is located at: source-C:\Projects\Kepler\sandbox\Test.scala,line-6,offset=76
prefix = scala.reflect.`package`.mirror
[calculate phase]
boundSym: class FooPimped of type <notype>
boundSym: value foo of type Foo
boundSym: constructor FooPimped of type FooPimped
boundSym: value foo of type Foo
boundSym: method bar of type Unit
boundSym: method FooPimped of type FooPimped
boundSym: value foo of type Foo
[reshape phase]
resetting visibility of field: <paramaccessor> private[this] val foo: Foo = _ => <paramaccessor> private[this] val foo: Foo = _
TypeTree, essential: Foo (TypeRef)
verdict: rolled back to original Foo
TypeTree, essential: Foo (TypeRef)
verdict: rolled back to original Foo
TypeTree, non-essential: FooPimped (TypeRef)
verdict: discarded
TypeTree, non-essential: Unit (TypeRef)
verdict: discarded
TypeTree, essential: Foo (TypeRef)
verdict: rolled back to original Foo
TypeTree, essential: FooPimped (TypeRef)
verdict: rolled back to original FooPimped
[metalevels phase]
[interlude]
symbol table = <empty>
reifee = 
{
  implicit class FooPimped extends scala.AnyRef {
    <paramaccessor> private[this] val foo: Foo = _;
    def <init>(foo: Foo): FooPimped = {
      FooPimped.super.<init>();
      ()
    };
    def bar: Unit = scala.this.Predef.println("hello")
  };
  implicit <synthetic> def FooPimped(foo: Foo): FooPimped = new FooPimped(foo);
  FooPimped(new Foo()).bar
}
Block(List(ClassDef(Modifiers(Set(`implicit`)), newTypeName("FooPimped"), List(), Template(List(Select(Ident(newTermName("scala")), newTypeName("AnyRef"))), emptyValDef, List(ValDef(Modifiers(Set(paramAccessor, `private`, local)), newTermName("foo"), Ident(newTypeName("Foo")), EmptyTree), DefDef(Modifiers(), newTermName("<init>"), List(), List(List(ValDef(Modifiers(Set(parameter, paramAccessor)), newTermName("foo"), Ident(newTypeName("Foo")), EmptyTree))), TypeTree(), Block(List(Apply(Select(Super(This(newTypeName("")), newTypeName("")), newTermName("<init>")), List())), Literal(Constant(())))), DefDef(Modifiers(), newTermName("bar"), List(), List(), TypeTree(), Apply(Select(Select(This(newTypeName("scala")), newTermName("Predef")), newTermName("println")), List(Literal(Constant("hello")))))))), DefDef(Modifiers(Set(`implicit`)), newTermName("FooPimped"), List(), List(List(ValDef(Modifiers(Set(parameter, paramAccessor)), newTermName("foo"), Ident(newTypeName("Foo")), EmptyTree))), Ident(newTypeName("FooPimped")), ApplyConstructor(Select(New(Ident(newTypeName("FooPimped"))), newTermName("<init>")), List(Ident(newTermName("foo")))))), Select(Apply(Ident(newTermName("FooPimped")), List(ApplyConstructor(Select(New(Ident(newTypeName("Foo"))), newTermName("<init>")), List()))), newTermName("bar")))
[reify phase]
reifying bound type type AnyRef (underlying type is Object, dealiased is Object)
tpe is locatable: reify as Ident(class Object)
reifying bound type class Foo (underlying type is Foo, dealiased is Foo)
tpe is locatable: reify as Ident(class Foo)
reifying bound type class Foo (underlying type is Foo, dealiased is Foo)
tpe is locatable: reify as Ident(class Foo)
This for package scala, reified as This
reifying bound type class Foo (underlying type is Foo, dealiased is Foo)
tpe is locatable: reify as Ident(class Foo)
reifying bound type class Foo (underlying type is Foo, dealiased is Foo)
tpe is locatable: reify as Ident(class Foo)
reified = {
  val $mr: scala.reflect.`package`.mirror.type = scala.reflect.`package`.mirror;
  $mr.Expr[Unit]($mr.Block(scala.collection.immutable.List.apply($mr.ClassDef($mr.modifiersFromInternalFlags(512L, $mr.newTypeName(""), scala.collection.immutable.List.apply()), $mr.newTypeName("FooPimped"), scala.collection.immutable.List.apply(), $mr.Template(scala.collection.immutable.List.apply($mr.Ident($mr.staticClass("java.lang.Object"))), $mr.emptyValDef, scala.collection.immutable.List.apply($mr.ValDef($mr.modifiersFromInternalFlags(537395204L, $mr.newTypeName(""), scala.collection.immutable.List.apply()), $mr.newTermName("foo"), $mr.Ident($mr.staticClass("Foo")), $mr.EmptyTree), $mr.DefDef($mr.modifiersFromInternalFlags(0L, $mr.newTypeName(""), scala.collection.immutable.List.apply()), $mr.newTermName("<init>"), scala.collection.immutable.List.apply(), scala.collection.immutable.List.apply(scala.collection.immutable.List.apply($mr.ValDef($mr.modifiersFromInternalFlags(536879104L, $mr.newTypeName(""), scala.collection.immutable.List.apply()), $mr.newTermName("foo"), $mr.Ident($mr.staticClass("Foo")), $mr.EmptyTree))), $mr.TypeTree(), $mr.Block(scala.collection.immutable.List.apply($mr.Apply($mr.Select($mr.Super($mr.This($mr.newTypeName("")), $mr.newTypeName("")), $mr.newTermName("<init>")), scala.collection.immutable.List.apply())), $mr.Literal($mr.Constant(())))), $mr.DefDef($mr.modifiersFromInternalFlags(0L, $mr.newTypeName(""), scala.collection.immutable.List.apply()), $mr.newTermName("bar"), scala.collection.immutable.List.apply(), scala.collection.immutable.List.apply(), $mr.TypeTree(), $mr.Apply($mr.Select($mr.Select($mr.This($mr.staticModule("scala").moduleClass), $mr.newTermName("Predef")), $mr.newTermName("println")), scala.collection.immutable.List.apply($mr.Literal($mr.Constant("hello")))))))), $mr.DefDef($mr.modifiersFromInternalFlags(2097728L, $mr.newTypeName(""), scala.collection.immutable.List.apply()), $mr.newTermName("FooPimped"), scala.collection.immutable.List.apply(), scala.collection.immutable.List.apply(scala.collection.immutable.List.apply($mr.ValDef($mr.modifiersFromInternalFlags(536879104L, $mr.newTypeName(""), scala.collection.immutable.List.apply()), $mr.newTermName("foo"), $mr.Ident($mr.staticClass("Foo")), $mr.EmptyTree))), $mr.Ident($mr.newTypeName("FooPimped")), $mr.Apply($mr.Select($mr.New($mr.Ident($mr.newTypeName("FooPimped"))), $mr.newTermName("<init>")), scala.collection.immutable.List.apply($mr.Ident($mr.newTermName("foo")))))), $mr.Select($mr.Apply($mr.Ident($mr.newTermName("FooPimped")), scala.collection.immutable.List.apply($mr.Apply($mr.Select($mr.New($mr.Ident($mr.staticClass("Foo"))), $mr.newTermName("<init>")), scala.collection.immutable.List.apply()))), $mr.newTermName("bar"))))($mr.ConcreteTypeTag[Unit]($mr.staticClass("scala.Unit").asTypeConstructor, Predef.this.classOf[scala.runtime.BoxedUnit]))
}
scala.reflect.runtime.ToolBoxes$ToolBox$ToolBoxError: reflective compilation has failed: 

method FooPimped is defined twice in <no source file>
  at scala.reflect.runtime.ToolBoxes$ToolBox$ToolBoxGlobal.throwIfErrors(ToolBoxes.scala:252)
  at scala.reflect.runtime.ToolBoxes$ToolBox$ToolBoxGlobal.compileExpr(ToolBoxes.scala:200)
  at scala.reflect.runtime.ToolBoxes$ToolBox$ToolBoxGlobal.runExpr(ToolBoxes.scala:227)
  at scala.reflect.runtime.ToolBoxes$ToolBox.runExpr(ToolBoxes.scala:344)
  at scala.reflect.api.Exprs$Expr.eval(Exprs.scala:15)
  at Test$delayedInit$body.apply(Test.scala:12)
  at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
  at scala.collection.immutable.List.foreach(List.scala:77)
  at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:31)
  at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
  at scala.App$class.main(App.scala:61)
  at Test$.main(Test.scala:5)
  at Test.main(Test.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:92)
  at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:40)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:161)
  at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:92)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:161)
  at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
  at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
  at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
  at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:70)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:92)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by SethTisue** [comment]
closing this along with the other "cannot reify" bugs as unlikely to progress
