### ISSUE TITLE
ToolBox.typeCheck doesn't like naked imports

### ISSUE THREAD

**Issue by scabug** [scala/bug#5864]
```scala
import scala.reflect.runtime.universe._
import scala.reflect.runtime.{currentMirror => cm}
import scala.tools.reflect.ToolBox

object Test extends App {
  val toolbox = cm.mkToolBox()
  val tree1 = Import(Select(Ident(newTermName("scala")), newTermName("Predef")), List(ImportSelector(nme.WILDCARD, -1, null, -1)))
  val ttree1 = toolbox.typeCheck(tree1, withImplicitViewsDisabled = false)
  println(ttree1)
}
```

```scala
java.lang.AssertionError: assertion failed: 
     while compiling:  <no file>
       current phase:  typer
     library version:  version 2.10.0-20120601-213054-49a8bcc4de
    compiler version:  version 2.10.0-20120601-223315-77696b69bd
  reconstructed args:  

!forInteractive
  at scala.Predef$.assert(Predef.scala:162)
  at scala.tools.nsc.Global.assert(Global.scala:207)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4993)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5037)
  at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2149)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$4.apply(Typers.scala:4716)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$4.apply(Typers.scala:4716)
  at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:501)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4715)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5037)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typeCheckExpr$1$$anonfun$16.apply(ToolBoxFactory.scala:126)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typeCheckExpr$1$$anonfun$16.apply(ToolBoxFactory.scala:126)
  at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:717)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typeCheckExpr$1.apply(ToolBoxFactory.scala:126)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typeCheckExpr$1.apply(ToolBoxFactory.scala:126)
  at scala.tools.nsc.typechecker.Contexts$Context.withMacrosEnabled(Contexts.scala:221)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$14.apply(ToolBoxFactory.scala:118)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$14.apply(ToolBoxFactory.scala:118)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$wrapper$1$1.apply(ToolBoxFactory.scala:119)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$wrapper$1$1.apply(ToolBoxFactory.scala:119)
  at scala.tools.nsc.typechecker.Contexts$Context.withImplicitsEnabled(Contexts.scala:190)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$12.apply(ToolBoxFactory.scala:117)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$12.apply(ToolBoxFactory.scala:117)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapper$1(ToolBoxFactory.scala:119)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.typeCheckExpr(ToolBoxFactory.scala:126)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typeCheck(ToolBoxFactory.scala:324)
  at Test$delayedInit$body.apply(toolbox_typecheck_implicitsdisabled.scala:8)
  at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
  at scala.collection.immutable.List.foreach(List.scala:77)
  at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
  at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
  at scala.App$class.main(App.scala:61)
  at Test$.main(toolbox_typecheck_implicitsdisabled.scala:5)
  at Test.main(toolbox_typecheck_implicitsdisabled.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:93)
  at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:41)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:162)
  at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:93)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:162)
  at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
  at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
  at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
  at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:70)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:92)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by SethTisue** [comment]
not reproducible even as far back as 2.10.2 (the oldest version I can easily test)
