### ISSUE TITLE
Cannot reify the GADTs example

### ISSUE THREAD

**Issue by scabug** [scala/bug#5871]
```scala
import scala.reflect.runtime.universe._
import scala.tools.reflect.Eval

object Test extends App {
  reify {
    /* The syntax tree of a toy language */
    abstract class Term[T]

    /* An integer literal */
    case class Lit(x: Int) extends Term[Int]

    /* Successor of a number */
    case class Succ(t: Term[Int]) extends Term[Int]

    /* Is 't' equal to zero? */
    case class IsZero(t: Term[Int]) extends Term[Boolean]

    /* An 'if' expression. */
    case class If[T](c: Term[Boolean],
                     t1: Term[T],
                     t2: Term[T]) extends Term[T]

    /** A type-safe eval function. The right-hand sides can
     *  make use of the fact that 'T' is a more precise type,
     *  constraint by the pattern type.
     */
    def eval[T](t: Term[T]): T = t match {
      case Lit(n)        => n

      // the right hand side makes use of the fact
      // that T = Int and so it can use '+'
      case Succ(u)       => eval(u) + 1
      case IsZero(u)     => eval(u) == 0
      case If(c, u1, u2) => eval(if (eval(c)) u1 else u2)
    }
    println(
      eval(If(IsZero(Lit(1)), Lit(41), Succ(Lit(41)))))
  }.eval
}
```

```scala
java.lang.ClassCastException: java.lang.Integer cannot be cast to scala.runtime.Nothing$
  at __wrapper$1$000eb7bd2a484c469826015e17c35b41$.eval$1(<no source file>)
  at __wrapper$1$000eb7bd2a484c469826015e17c35b41$.eval$1(<no source file>)
  at __wrapper$1$000eb7bd2a484c469826015e17c35b41$.eval$1(<no source file>)
  at __wrapper$1$000eb7bd2a484c469826015e17c35b41$.wrapper(<no source file>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.runExpr(ToolBoxFactory.scala:234)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.runExpr(ToolBoxFactory.scala:370)
  at scala.tools.reflect.Eval.eval(package.scala:65)
  at Test$delayedInit$body.apply(reify_gadts.scala:38)
  at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
  at scala.collection.immutable.List.foreach(List.scala:77)
  at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
  at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
  at scala.App$class.main(App.scala:61)
  at Test$.main(reify_gadts.scala:4)
  at Test.main(reify_gadts.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:93)
  at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:41)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:162)
  at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:93)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:162)
  at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
  at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
  at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
  at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:70)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:92)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by SethTisue** [comment]
seems unlikely to progress, scala.reflect isn't changing much these days
