### ISSUE TITLE
Cannot reify into a field of a class when referring the parameter of that class

### ISSUE THREAD

**Issue by scabug** [scala/bug#5873]
```scala
import scala.reflect.runtime.universe._
import scala.tools.reflect.Eval

object Test extends App {
  {
    class C(val y: Int) {
      val code = reify {
        reify{y}.splice
      }
    }

    println(new C(2).code.eval)
  }
}
```

```scala
java.lang.NullPointerException
  at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1350)
  at scala.reflect.internal.Importers$StandardImporter.doImport$1(Importers.scala:106)
  at scala.reflect.internal.Importers$StandardImporter.importOrRelink$1(Importers.scala:172)
  at scala.reflect.internal.Importers$StandardImporter$$anonfun$importSymbol$1.apply(Importers.scala:195)
  at scala.reflect.internal.Importers$StandardImporter$$anonfun$importSymbol$1.apply(Importers.scala:195)
  at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:167)
  at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
  at scala.reflect.internal.Importers$StandardImporter.importSymbol(Importers.scala:195)
  at scala.reflect.internal.Importers$StandardImporter$$anonfun$doImport$2$4.apply(Importers.scala:230)
  at scala.reflect.internal.Importers$StandardImporter$$anonfun$doImport$2$4.apply(Importers.scala:230)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
  at scala.collection.immutable.List.foreach(List.scala:77)
  at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:308)
  at scala.reflect.internal.Importers$StandardImporter.doImport$2(Importers.scala:230)
  at scala.reflect.internal.Importers$StandardImporter.importOrRelink$2(Importers.scala:259)
  at scala.reflect.internal.Importers$StandardImporter$$anonfun$importType$1.apply(Importers.scala:267)
  at scala.reflect.internal.Importers$StandardImporter$$anonfun$importType$1.apply(Importers.scala:267)
  at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:167)
  at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
  at scala.reflect.internal.Importers$StandardImporter.importType(Importers.scala:267)
  at scala.reflect.internal.Importers$StandardImporter$$anon$1.complete(Importers.scala:113)
  at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1143)
  at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1275)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4648)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5024)
  at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5104)
  at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5110)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4892)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5024)
  at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5229)
  at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:1985)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4674)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5024)
  at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:2576)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62$$anonfun$63.apply(Typers.scala:2672)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62$$anonfun$63.apply(Typers.scala:2672)
  at scala.collection.immutable.List.loop$1(List.scala:163)
  at scala.collection.immutable.List.mapConserve(List.scala:179)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:2672)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:2671)
  at scala.tools.nsc.typechecker.Typers$Typer.withSavedContext(Typers.scala:517)
  at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2671)
  at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1729)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$42.apply(Typers.scala:1637)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$42.apply(Typers.scala:1637)
  at scala.tools.nsc.typechecker.Typers$Typer.typerReportAnyContextErrors(Typers.scala:508)
  at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1636)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4664)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5024)
  at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:2576)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62$$anonfun$63.apply(Typers.scala:2672)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62$$anonfun$63.apply(Typers.scala:2672)
  at scala.collection.immutable.List.loop$1(List.scala:163)
  at scala.collection.immutable.List.mapConserve(List.scala:179)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:2672)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:2671)
  at scala.tools.nsc.typechecker.Typers$Typer.withSavedContext(Typers.scala:517)
  at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2671)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:4657)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5024)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5082)
  at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:97)
  at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:453)
  at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:89)
  at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:89)
  at scala.collection.Iterator$class.foreach(Iterator.scala:724)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1151)
  at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:89)
  at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1372)
  at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1340)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compileExpr(ToolBoxFactory.scala:204)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.runExpr(ToolBoxFactory.scala:233)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.runExpr(ToolBoxFactory.scala:370)
  at scala.tools.reflect.Eval.eval(package.scala:65)
  at Test$delayedInit$body.apply(reify_newimpl_07.scala:12)
  at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
  at scala.collection.immutable.List.foreach(List.scala:77)
  at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
  at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
  at scala.App$class.main(App.scala:61)
  at Test$.main(reify_newimpl_07.scala:4)
  at Test.main(reify_newimpl_07.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:93)
  at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:41)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:162)
  at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:93)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:162)
  at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
  at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
  at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
  at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:70)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:92)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by SethTisue** [comment]
seems unlikely to progress. scala.reflect isn't changing much these days
