### ISSUE TITLE
Mixed reifies and evals crash during runtime compilation

### ISSUE THREAD

**Issue by scabug** [scala/bug#5874]
```scala
import scala.reflect.runtime.universe._
import scala.tools.reflect.Eval

object Test extends App {
  val code = reify {
    class C(val y: Int) {
      val code = reify {
        reify{y}.eval
      }
    }

    new C(2).code.eval
  }

  println(code.eval)
}
```

```scala
scala.reflect.internal.MissingRequirementError: object __wrapper$1$4883a8059d7b4da59522440957a75896 in JavaMirror with Cl#278604369 of type class scala.tools.nsc.interpreter.AbstractFileClassLoader with classpath [(memory)] and [file:/c:/PROGRA~1/Java/JDK16~1.0_2/jre/lib/resources.jar,file:/c:/PROGRA~1/Java/JDK16~1.0_2/jre/lib/rt.jar,file:/c:/PROGRA~1/Java/JDK16~1.0_2/jre/lib/jsse.jar,file:/c:/PROGRA~1/Java/JDK16~1.0_2/jre/lib/jce.jar,file:/c:/PROGRA~1/Java/JDK16~1.0_2/jre/lib/charsets.jar,file:/c:/PROGRA~1/Java/JDK16~1.0_2/jre/lib/ext/dnsns.jar,file:/c:/PROGRA~1/Java/JDK16~1.0_2/jre/lib/ext/localedata.jar,file:/c:/PROGRA~1/Java/JDK16~1.0_2/jre/lib/ext/sunjce_provider.jar,file:/C:/Projects/KeplerUnderRefactoring/test/files/codelib/code.jar,file:/C:/Projects/KeplerUnderRefactoring/lib/jline.jar,file:/C:/Projects/KeplerUnderRefactoring/lib/fjbg.jar,file:/C:/Projects/KeplerUnderRefactoring/build/locker/classes/compiler/,file:/C:/Projects/KeplerUnderRefactoring/build/locker/classes/library/,file:/C:/Projects/ScalaQuery/bin/scalaquery_2.9.1-0.10.0-SNAPSHOT.jar,file:/C:/Projects/KeplerUnderRefactoring/sandbox/./,file:/C:/PROGRA~2/QUICKT~1/QTSystem/QTJava.zip,file:/c:/PROGRA~1/Java/JDK16~1.0_2/lib/tools.jar,file:/C:/Program%20Files%20(x86)/QuickTime/QTSystem/QTJava.zip,file:/C:/Program%20Files%20(x86)/Java/jre6/lib/ext/QTJava.zip] not found.
  at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
  at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
  at scala.reflect.internal.Mirrors$RootsBase$$anonfun$getModuleOrClass$4.apply(Mirrors.scala:45)
  at scala.reflect.internal.Mirrors$RootsBase$$anonfun$getModuleOrClass$4.apply(Mirrors.scala:45)
  at scala.reflect.internal.Symbols$Symbol.orElse(Symbols.scala:2055)
  at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:44)
  at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:57)
  at scala.reflect.internal.Mirrors$RootsBase.getModule(Mirrors.scala:76)
  at scala.reflect.internal.Mirrors$RootsBase.getRequiredModule(Mirrors.scala:96)
  at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:72)
  at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:17)
  at __wrapper$1$4883a8059d7b4da59522440957a75896$C$1$$treecreator4$1.applyImpl(<no source file>)
  at __wrapper$1$4883a8059d7b4da59522440957a75896$C$1$$treecreator4$1.apply(<no source file>)
  at scala.reflect.api.Exprs$ExprImpl.tree(Exprs.scala:44)
  at scala.tools.reflect.Eval.eval(package.scala:65)
  at __wrapper$1$4883a8059d7b4da59522440957a75896$.wrapper(<no source file>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.runExpr(ToolBoxFactory.scala:234)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.runExpr(ToolBoxFactory.scala:370)
  at scala.tools.reflect.Eval.eval(package.scala:65)
  at Test$delayedInit$body.apply(reify_newimpl_08.scala:15)
  at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
  at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.App$$anonfun$main$1.apply(App.scala:61)
  at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
  at scala.collection.immutable.List.foreach(List.scala:77)
  at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
  at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
  at scala.App$class.main(App.scala:61)
  at Test$.main(reify_newimpl_08.scala:4)
  at Test.main(reify_newimpl_08.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
  at java.lang.reflect.Method.invoke(Method.java:597)
  at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:93)
  at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:41)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:162)
  at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:93)
  at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:162)
  at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
  at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
  at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
  at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:70)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:92)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:101)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by SethTisue** [comment]
seems unlikely to progress. scala.reflect isn't changing much these days
