### ISSUE TITLE
scala.util.Properties freeze application at startup

### ISSUE THREAD

**Issue by scabug** [scala/bug#6151]
Please, alter hard coded useless call of `pickJarBasedOn getResourceAsStream propFilename` at scala/util/Properties.scala:30. It would be nice to have some trigger that prevent it.

```
21:17:43.537 P1826 T1826 D StrictMode:             StrictMode policy violation; ~duration=10525 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=23 violation=2
21:17:43.537 P1826 T1826 D StrictMode:             at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:745)
21:17:43.537 P1826 T1826 D StrictMode:             at dalvik.system.BlockGuard$WrappedFileSystem.open(BlockGuard.java:228)
21:17:43.537 P1826 T1826 D StrictMode:             at java.io.RandomAccessFile.<init>(RandomAccessFile.java:132)
21:17:43.537 P1826 T1826 D StrictMode:             at java.io.RandomAccessFile.<init>(RandomAccessFile.java:173)
21:17:43.537 P1826 T1826 D StrictMode:             at java.util.zip.ZipFile.<init>(ZipFile.java:133)
21:17:43.537 P1826 T1826 D StrictMode:             at java.util.jar.JarFile.<init>(JarFile.java:199)
21:17:43.537 P1826 T1826 D StrictMode:             at org.apache.harmony.luni.internal.net.www.protocol.jar.JarURLConnectionImpl.openJarFile(JarURLConnectionImpl.java:143)
21:17:43.537 P1826 T1826 D StrictMode:             at org.apache.harmony.luni.internal.net.www.protocol.jar.JarURLConnectionImpl.findJarFile(JarURLConnectionImpl.java:119)
21:17:43.537 P1826 T1826 D StrictMode:             at org.apache.harmony.luni.internal.net.www.protocol.jar.JarURLConnectionImpl.connect(JarURLConnectionImpl.java:85)
21:17:43.537 P1826 T1826 D StrictMode:             at org.apache.harmony.luni.internal.net.www.protocol.jar.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:232)
21:17:43.537 P1826 T1826 D StrictMode:             at java.net.URL.openStream(URL.java:645)
21:17:43.537 P1826 T1826 D StrictMode:             at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:486)
21:17:43.537 P1826 T1826 D StrictMode:             at java.lang.Class.getResourceAsStream(Class.java:1207)
21:17:43.537 P1826 T1826 D StrictMode:             at scala.util.PropertiesTrait$class.scalaProps(Properties.scala:31)
21:17:43.537 P1826 T1826 D StrictMode:             at scala.util.Properties$.scalaProps(Properties.scala:15)
21:17:43.537 P1826 T1826 D StrictMode:             at scala.util.PropertiesTrait$class.scalaPropOrElse(Properties.scala:59)
21:17:43.537 P1826 T1826 D StrictMode:             at scala.util.Properties$.scalaPropOrElse(Properties.scala:15)
21:17:43.537 P1826 T1826 D StrictMode:             at scala.util.PropertiesTrait$class.$init$(Properties.scala:65)
21:17:43.537 P1826 T1826 D StrictMode:             at scala.util.Properties$.<init>(Properties.scala:15)
21:17:43.537 P1826 T1826 D StrictMode:             at scala.util.Properties$.<clinit>(Properties.scala)
```

**Comment by SethTisue** [comment]
can someone verify if this is even still an issue?

**Comment by NthPortal** [comment]
the mentioned line of code [still exists](https://github.com/scala/scala/blob/9ba5196fe652967ec1c3bdc643bc8472b772ef55/src/library/scala/util/Properties.scala#L36); more than that I can't say, as I don't know the context in which this came up on Android

**Comment by SethTisue** [comment]
probably reproducible using `SecurityManager`?

**Comment by NthPortal** [comment]
Sorry I never got around to looking into this. I don't think I will have time in the near future either. If someone else wants to pick this up, cheers!

**Comment by SethTisue** [comment]
we can reopen if someone finds it still to be a problem
