### ISSUE TITLE
Super accessors and specialization interplay

### ISSUE THREAD

**Issue by scabug** [scala/bug#6265]
```scala

trait B[@specialized(Int) T] {
  def foo(x: T) = println("B.foo " + x)
}


trait M[@specialized(Int) T] extends B[T] {
  abstract override def foo(x: T) {
    super.foo(x)
    println("M.foo " + x)
  }
}


object C extends B[Int] with M[Int]


object Test {

  def main(args: Array[String]) {
    println(C.foo(1))
  }

}
```

causes:

```scala
aleksandar@lampmac14:~/workspaces/scala/scala/test/files/run [issue/4996●●]‡ scalac-version 2.9.2 t4996b.scala                                                        
error: java.lang.UnsupportedOperationException: tail of empty list
	at scala.collection.immutable.Nil$.tail(List.scala:404)
	at scala.collection.immutable.Nil$.tail(List.scala:399)
	at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$rebindSuper$1.apply(Mixin.scala:96)
	at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$rebindSuper$1.apply(Mixin.scala:95)
	at scala.tools.nsc.symtab.SymbolTable.atPhase(SymbolTable.scala:95)
	at scala.tools.nsc.transform.Mixin.scala$tools$nsc$transform$Mixin$$rebindSuper(Mixin.scala:95)
	at scala.tools.nsc.transform.Mixin$$anonfun$mixinTraitMembers$1$1.apply(Mixin.scala:332)
	at scala.tools.nsc.transform.Mixin$$anonfun$mixinTraitMembers$1$1.apply(Mixin.scala:285)
```

**Comment by SethTisue** [comment]
leaving un-milestoned for now since we're not actually sure when it started working
