### ISSUE TITLE
overriding objects leads to CCE

### ISSUE THREAD

**Issue by scabug** [scala/bug#6525]
```scala
class Phase

abstract class SyntaxAnalyzer {
  
  def newPhase(): Phase = new ParserPhase()
  class ParserPhase() extends Phase {
    def apply(x: Any): Unit = {
      println("running parser....")
    }
  }
}

class Global {
  object sAnalyzer extends SyntaxAnalyzer 

  class Run {
     val firstPhase: Phase = sAnalyzer.newPhase()
  }
}

class DebuggerGlobal extends Global {
  override object sAnalyzer extends SyntaxAnalyzer

  def initRun() {
    new Run()
  }

}

object Test {
  def main(args: Array[String]) {
    val g = new DebuggerGlobal()
    println("will crash...")
    g.initRun()
  }
}
```
```scala
scalac -Yoverride-objects Override.scala -d /tmp
scala -cp /tmp Test
```
Leads to ClassCastException:
```scala
will crash...
java.lang.ClassCastException: DebuggerGlobal$sAnalyzer$ cannot be cast to Global$sAnalyzer$
	at DebuggerGlobal.sAnalyzer(Override.scala:21)
	at Global$Run.<init>(Override.scala:17)
	at DebuggerGlobal.initRun(Override.scala:25)
	at Test$.main(Override.scala:34)
	at Test.main(Override.scala)
```

**Comment by xuwei-k** [comment]
https://github.com/scala/scala/commit/a82a56ea5ba1ff0fb3b69c0963d4aec620ab68ad

`-Yoverride-objects` dropped since Scala 2.13.0-M4
