### ISSUE TITLE
return of filterKeys is not serializable

### ISSUE THREAD

**Issue by scabug** [scala/bug#6654]
Return of filterKeys is not serializable. I'm not sure this is intended behaviour or a bug, but it's possible to confuse users. Attached file throws following exception:

java.io.NotSerializableException: scala.collection.immutable.MapLike$$anon$1
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1180)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1528)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1493)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1416)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1174)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at Test$delayedInit$body.apply(Test.scala:13)

**Comment by Blaisorblade** [comment]
Copying tags from #7005 since collections are being worked upon @szeiger @julienrf.

**Comment by Blaisorblade** [comment]
Feel free to reassign but these issues belong together.
