### ISSUE TITLE
compiler crash in custom virtualized pattern __match in monad other than Option

### ISSUE THREAD

**Issue by scabug** [scala/bug#7076]
```scala
trait ListMatcher {                                                                
  object __match {                                                                 
    def one[T](x: T): List[T] = List(x)                                            
    def zero = Nil                                                                 
    def guard[T](cond: Boolean, result: => T): List[T] =                           
      if (cond) one(result) else zero                                              
    def runOrElse[T, U](in: T)(matcher: T => List[U]): List[U] =                   
      matcher(in)                                                                  
  }                                                                                
                                                                                   
  def infix_orElse[A](lst: List[A], alternative: => List[A]): List[A] =            
    lst ++ alternative                                                             
                                                                                   
  object CharsOf {                                                                 
    def unapply(s: String): List[Char] = s.toList                                  
  }                                                                                
}                                                                                  
                                                                                   
object Test extends App with ListMatcher {                                         
  def f(s: String) = s match {                                                     
    case CharsOf(c) => c                                                           
  }                                                                                
  println(f("hello"))                                                              
}
```

When compiling this snippet with flags -Xexperimental, we get a compiler crash:
```
error: java.lang.NullPointerException
	at scala.tools.nsc.typechecker.PatternMatching$MatchTranslation$ExtractorCallProd.rawSubPatTypes(PatternMatching.scala:732)
	at scala.tools.nsc.typechecker.PatternMatching$MatchTranslation$ExtractorCallProd.isSeq(PatternMatching.scala:731)
	at scala.tools.nsc.typechecker.PatternMatching$MatchTranslation$ExtractorCall.subPatTypes(PatternMatching.scala:641)
...
```

The problem is that Infer.extractorFormalTypes is hard-coded for the Option monad. A quick fix is simply changing
```scala
lazy val optionArgs = resTp.baseType(OptionClass).typeArgs
```
to
```scala
lazy val optionArgs = resTp.typeArgs
```
in https://github.com/scala/scala/blob/2.10.x/src/compiler/scala/tools/nsc/typechecker/Infer.scala#L98

Then the snippet runs, with the expected result: List(h, e, l, l, o).

**Comment by dwijnand** [comment]
How do you reproduce this?  Is there a flag that enables "virtualized pattern __match"?

**Comment by SethTisue** [comment]
the virtualized pattern matcher has been on by default since Scala 2.10.0; see https://stackoverflow.com/questions/8533826/what-is-scalas-experimental-virtual-pattern-matcher

**Comment by NthPortal** [comment]
I think this is moot since pattern matching is now name-based.

Compiling the code now results in the following error:

```
error: The result type of an unapply method must contain a member `get` to be used as an extractor pattern, no such member exists in List[Char]
```

**Comment by Jasper-M** [comment]
By the way, I think virtually the same thing as in the report can now be achieved with

```
scala> class MatchResult[A](val get: A) extends AnyVal { def isEmpty = false }
defined class MatchResult

scala> object CharsOf { def unapply(s: String) = new MatchResult(s.toList) }
defined object CharsOf

scala> def f(s: String) = s match {                                                     
     |   case CharsOf(c) => c                                                           
     | } 
f: (s: String)List[Char]

scala> f("hello")
res1: List[Char] = List(h, e, l, l, o)
```
