### ISSUE TITLE
reify {} fails with "unexpected: bound type that doesn't have a tpe"

### ISSUE THREAD

**Issue by scabug** [scala/bug#7078]
Steps to reproduce:

scala> import reflect.runtime.universe._
scala> reify { val s = "1"; val (x,y) = s match { case "1" => (1,2); case _ => throw new Exception }}
error: exception during macro expansion:
java.lang.Error: unexpected: bound type that doesn't have a tpe: Ident(newTypeName("Exception"))
        at scala.reflect.reify.codegen.GenTrees$class.reifyBoundType$1(GenTrees.scala:154)
        at scala.reflect.reify.codegen.GenTrees$class.reifyBoundType(GenTrees.scala:201)
        at scala.reflect.reify.codegen.GenTrees$class.reifyTree(GenTrees.scala:56)
        ...

**Comment by SethTisue** [comment]
(not sure of exact fix-by version; I only have 2.10.7 on my computer)
