### ISSUE TITLE
Specialized trait + specialized method = java.lang.RuntimeException: Fatal error in code generation: this should never be called. (at scala.sys.package$.error(package.scala:27))

### ISSUE THREAD

**Issue by scabug** [scala/bug#7117]
program fails at runtime when invoking specialized method on specialized trait (see code: https://ideone.com/phKz2D) with the following message in stderr:

Exception in thread "main" java.lang.RuntimeException: Fatal error in code generation: this should never be called.
	at scala.sys.package$.error(package.scala:27)
	at FastView$class.foldLeft$mJc$sp(Main.scala)
	at FastView$$anon$3.foldLeft$mJc$sp(Main.scala:10)
	at FastView$class.foldLeft$mJcJ$sp(Main.scala:27)
	at FastView$$anon$3.foldLeft$mJcJ$sp(Main.scala:10)
	at Main$.main(Main.scala:4)
	at Main.main(Main.scala)

There is no compilation warning and messages about what caused error, so this is a bug anyway.

UPD: Same error happens if I change trait to abstract class

**Comment by SethTisue** [comment]
the code link is no longer available

**Comment by SethTisue** [comment]
the code, unless the link should ever go away:

```scala
object Main {
  def main(args: Array[String]) {
    val test = Array.range(0, 100000).map(_.toLong)
    val fail = FastView(test).foldLeft(0L)(_ + _)
  }
}

object FastView {
  @inline def apply[@specialized(Int, Long) A](s: Array[A]) = {
    new FastView[A] {
      val src = s
      final def foldLeft[@specialized(Int, Long) B](init: B)(fun: (B, A) => B): B = {
        var res = init
        var i = 0
        var len = src.length
        while (i < len) {
          res = fun(res, src(i))
          i += 1
        }
        res
      }
    }
  }
}

trait FastView[@specialized(Int, Long) A] {
  def foldLeft[@specialized(Int, Long) B](init: B)(fun: (B, A) => B): B
}
```

**Comment by SethTisue** [comment]
currently (2.13.10) it does not crash, but gives

```
On line 12: error: Type parameter has to be specialized at least for the same types as in the overridden method. Missing types: Int, Long
```

**Comment by som-snytt** [comment]
I don't know what I'm doing, obviously, but this version crashes the compiler.

```
object Main {
  def main(args: Array[String]) {
    val test = Array.range(0, 100000).map(_.toLong)
    val fail = FastView(test).foldLeft(0L)(_ + _)
  }
}

object FastView {
  def apply[@specialized(Int, Long) C](s: Array[C]): FastView[C] = {
    class impl[@specialized(Int, Long) A](src: Array[A]) extends FastView[A] {
      final def foldLeft[@specialized(Int, Long) B](init: B)(fun: (B, A) => B): B = {
        var res = init
        var i = 0
        var len = src.length
        while (i < len) {
          res = fun(res, src(i))
          i += 1
        }
        res
      }
    }
    new impl(s)
  }
}

trait FastView[@specialized(Int, Long) A] {
  def foldLeft[@specialized(Int, Long) B](init: B)(fun: (B, A) => B): B
}
```

**Comment by SethTisue** [comment]
which minimizes to:

```scala
object Test {                                                                                       
  def foo: Unit = {
    class Local[@specialized(Int) A]
  }
}
```

**Comment by SethTisue** [comment]
at which point it seems like a different bug entirely, so I'm going to re-close this one

**Comment by SethTisue** [comment]
yeah, this version is just a duplicate of #8287
