### ISSUE TITLE
macro impl jit doesn't work with code in templates

### ISSUE THREAD

**Issue by scabug** [scala/bug#7191]
```scala
import scala.reflect.macros.Context
import language.experimental.macros

object Test extends App {
  def impl(c: Context) = c.universe.reify(println("hello world!"))
  def hello = macro impl
  hello
}
```

```scala
Last login: Wed Feb 27 16:11:40 on ttys000
16:12 ~$ sbparadise 
16:12 ~/Projects/Paradise/sandbox (paradise/macros)$ scalac -Xmacro-jit Test.scala
error: no-symbol does not have an owner
error: 
     while compiling: Test.scala
        during phase: typer
     library version: version 2.11.0-20130225-121611-b4be0886d1
    compiler version: version 2.11.0-20130227-070337-e50a3719d8
  reconstructed args: -language:experimental.macros -Xmacro-jit

  last tree to typer: Ident(hello)
              symbol: <none> (flags: )
   symbol definition: <none>
       symbol owners: 
      context owners: value <local Test> -> object Test -> package <empty>

== Enclosing template or block ==

Template( // val <local Test>: <notype> in object Test
  "App" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  // 4 statements
  DefDef( // def <init>(): Test.type in object Test
    <method>
    "<init>"
    []
    List(Nil)
    <tpt> // tree.tpe=Test.type
    Block(
      Apply(
        super."<init>"
        Nil
      )
      ()
    )
  )
  DefDef( // def impl(c: scala.reflect.macros.Context): c.universe.Expr[Unit] in object Test
    <method> <triedcooking>
    "impl"
    []
    // 1 parameter list
    ValDef( // c: scala.reflect.macros.Context
      <param> <triedcooking>
      "c"
      "Context"
      <empty>
    )
    <tpt> // tree.tpe=c.universe.Expr[Unit]
    Apply( // def reify[T](expr: T): Universe.this.Expr[T] in class Universe
      "c"."universe"."reify" // def reify[T](expr: T): Universe.this.Expr[T] in class Universe, tree.tpe=[T](expr: T)c.universe.Expr[T]
      Apply(
        "println"
        "hello world!"
      )
    )
  )
  DefDef( // def hello: Unit in object Test
    <method> <macro> <triedcooking> @{ scala.reflect.macros.internal.macroImpl(`macro`("versionFormat" = 2, "isBundle" = false, "className" = "Test$", "methodName" = "impl", "signature" = List(List(-1)))) }
    "hello"
    []
    Nil
    <tpt> // tree.tpe=Unit
    "impl"
  )
  "hello"
)

uncaught exception during compilation: FatalError("
     while compiling: <no file>
        during phase: global=typer, enteringPhase=parser
     library version: version 2.11.0-20130225-121611-b4be0886d1
    compiler version: version 2.11.0-20130227-070337-e50a3719d8
  reconstructed args: -language:experimental.macros -Xmacro-jit

  last tree to typer: TypeTree(trait App)
              symbol: trait App in package scala (flags: abstract <trait>)
   symbol definition: abstract trait App extends DelayedInit
                 tpe: App
       symbol owners: trait App -> package scala
      context owners: object Test -> package <empty>

== Enclosing template or block ==

Template( // val <local Test>: <?> in object Test
  "App" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  // 4 statements
  DefDef( // def <init>: <?> in object Test
    <method>
    "<init>"
    []
    List(Nil)
    <tpt> // tree.tpe=Test.type
    Block(
      Apply(
        super."<init>"
        Nil
      )
      ()
    )
  )
  DefDef( // def impl(c: scala.reflect.macros.Context): c.universe.Expr[Unit] in object Test
    <method> <triedcooking>
    "impl"
    []
    // 1 parameter list
    ValDef( // c: scala.reflect.macros.Context
      <param> <triedcooking>
      "c"
      "Context"
      <empty>
    )
    <tpt> // tree.tpe=c.universe.Expr[Unit]
    Apply( // def reify[T](expr: T): Universe.this.Expr[T] in class Universe
      "c"."universe"."reify" // def reify[T](expr: T): Universe.this.Expr[T] in class Universe, tree.tpe=[T](expr: T)c.universe.Expr[T]
      Apply(
        "println"
        "hello world!"
      )
    )
  )
  DefDef( // def hello: <?> in object Test
    <method> <macro> <triedcooking>
    "hello"
    []
    Nil
    <tpt> // tree.tpe=Unit
    "impl"
  )
  "hello"
)

== Expanded type of tree ==

TypeRef(TypeSymbol(abstract trait App extends DelayedInit))

no-symbol does not have an owner") @ scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:52)
error: scala.reflect.internal.FatalError: 
     while compiling: <no file>
        during phase: global=typer, enteringPhase=parser
     library version: version 2.11.0-20130225-121611-b4be0886d1
    compiler version: version 2.11.0-20130227-070337-e50a3719d8
  reconstructed args: -language:experimental.macros -Xmacro-jit

  last tree to typer: TypeTree(trait App)
              symbol: trait App in package scala (flags: abstract <trait>)
   symbol definition: abstract trait App extends DelayedInit
                 tpe: App
       symbol owners: trait App -> package scala
      context owners: object Test -> package <empty>

== Enclosing template or block ==

Template( // val <local Test>: <?> in object Test
  "App" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  // 4 statements
  DefDef( // def <init>: <?> in object Test
    <method>
    "<init>"
    []
    List(Nil)
    <tpt> // tree.tpe=Test.type
    Block(
      Apply(
        super."<init>"
        Nil
      )
      ()
    )
  )
  DefDef( // def impl(c: scala.reflect.macros.Context): c.universe.Expr[Unit] in object Test
    <method> <triedcooking>
    "impl"
    []
    // 1 parameter list
    ValDef( // c: scala.reflect.macros.Context
      <param> <triedcooking>
      "c"
      "Context"
      <empty>
    )
    <tpt> // tree.tpe=c.universe.Expr[Unit]
    Apply( // def reify[T](expr: T): Universe.this.Expr[T] in class Universe
      "c"."universe"."reify" // def reify[T](expr: T): Universe.this.Expr[T] in class Universe, tree.tpe=[T](expr: T)c.universe.Expr[T]
      Apply(
        "println"
        "hello world!"
      )
    )
  )
  DefDef( // def hello: <?> in object Test
    <method> <macro> <triedcooking>
    "hello"
    []
    Nil
    <tpt> // tree.tpe=Unit
    "impl"
  )
  "hello"
)

== Expanded type of tree ==

TypeRef(TypeSymbol(abstract trait App extends DelayedInit))

no-symbol does not have an owner
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:52)
	at scala.tools.nsc.Global.abort(Global.scala:251)
	at scala.reflect.internal.Symbols$NoSymbol.owner(Symbols.scala:3310)
	at scala.reflect.internal.Symbols$Symbol.isOverridingSymbol(Symbols.scala:2150)
	at scala.reflect.macros.runtime.JitCompiler$ClosureAnalyzer$$anonfun$scala$reflect$macros$runtime$JitCompiler$ClosureAnalyzer$$getLinkedIds$4.apply(JitCompiler.scala:523)
	at scala.reflect.macros.runtime.JitCompiler$ClosureAnalyzer$$anonfun$scala$reflect$macros$runtime$JitCompiler$ClosureAnalyzer$$getLinkedIds$4.apply(JitCompiler.scala:523)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:775)
	at scala.collection.immutable.List.foreach(List.scala:300)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:774)
	at scala.reflect.macros.runtime.JitCompiler$ClosureAnalyzer.scala$reflect$macros$runtime$JitCompiler$ClosureAnalyzer$$getLinkedIds(JitCompiler.scala:523)
	at scala.reflect.macros.runtime.JitCompiler$ClosureAnalyzer.calculateClosure(JitCompiler.scala:619)
	at scala.reflect.macros.runtime.JitCompiler$.tryCompile(JitCompiler.scala:21)
	at scala.reflect.macros.runtime.JitRuntimes$JitResolvers$class.resolveJitRuntime(JitRuntimes.scala:17)
	at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveJitRuntime(MacroRuntimes.scala:72)
	at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:90)
	at scala.reflect.macros.runtime.MacroRuntimes$$anonfun$macroRuntime$3.apply(MacroRuntimes.scala:34)
	at scala.reflect.macros.runtime.MacroRuntimes$$anonfun$macroRuntime$3.apply(MacroRuntimes.scala:34)
	at scala.collection.mutable.MapLike$class.getOrElseUpdate(MapLike.scala:187)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:91)
	at scala.reflect.macros.runtime.MacroRuntimes$class.macroRuntime(MacroRuntimes.scala:34)
	at scala.tools.nsc.Global$$anon$1.macroRuntime(Global.scala:440)
	at scala.tools.nsc.typechecker.Macros$$anonfun$scala$tools$nsc$typechecker$Macros$$macroExpand1$1.apply(Macros.scala:804)
	at scala.tools.nsc.typechecker.Macros$$anonfun$scala$tools$nsc$typechecker$Macros$$macroExpand1$1.apply(Macros.scala:795)
	at scala.tools.nsc.Global.withInfoLevel(Global.scala:183)
	at scala.tools.nsc.typechecker.Macros$class.scala$tools$nsc$typechecker$Macros$$macroExpand1(Macros.scala:794)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:531)
	at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:518)
	at scala.tools.nsc.typechecker.Macros$class.macroExpandApply(Macros.scala:592)
	at scala.tools.nsc.Global$$anon$1.macroExpandApply(Global.scala:440)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1228)
	at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1052)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5368)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2872)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:2976)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:2976)
	at scala.collection.immutable.List.loop$1(List.scala:170)
	at scala.collection.immutable.List.mapConserve(List.scala:186)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2976)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1973)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$28.apply(Typers.scala:1843)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$28.apply(Typers.scala:1843)
	at scala.tools.nsc.typechecker.Typers$Typer.typerReportAnyContextErrors(Typers.scala:483)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1842)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5298)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5350)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2872)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:2976)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:2976)
	at scala.collection.immutable.List.loop$1(List.scala:170)
	at scala.collection.immutable.List.mapConserve(List.scala:186)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:2976)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5034)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5301)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5350)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5409)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:99)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:411)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:91)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3$$anonfun$run$1.apply(Analyzer.scala:90)
	at scala.collection.Iterator$class.foreach(Iterator.scala:725)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.run(Analyzer.scala:90)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1477)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1584)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
	at scala.tools.nsc.Main$.doCompile(Main.scala:53)
	at scala.tools.nsc.Driver.process(Driver.scala:54)
	at scala.tools.nsc.Driver.main(Driver.scala:67)
	at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by SethTisue** [comment]
`-Xmacro-jit` doesn't even exist anymore
