### ISSUE TITLE
Stackoverflow in IDE while compiling spray-http

### ISSUE THREAD

**Issue by scabug** [scala/bug#7277]
I tried compiling the spray distribution in eclipse. It compiles properly using sbt. I then added the sbt eclipse plugin and imported all spry projects into Eclipse. Even with only the spray-http project open (all others closed) the compiler crashes with a Stackoverflow exception, apparently having to do with an infinite loop in the general vicinity of "scala.reflect.api.Printers".

These are the steps to reproduce:

1) clone spray:
  git clone git://github.com/spray/spray.git
  
I got this commit:

commit 54e4235afd44a0c3dbacb1eaea4c10d24c7190af
Merge: 8de6ca7 f966250
Author: Mathias <mathias@decodified.com>
Date:   Wed Feb 6 05:02:10 2013 -0800

2) Edit project/plugins.sbt to add this line at the end:

addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "2.0.0")

3) Create eclipse projects

sbt eclipse

4) Open eclipse and try to compile the spray-http project

eclipse.buildId=M20120208-0800
java.version=1.6.0_27
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86

java.lang.StackOverflowError
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:189)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.api.Printers$class.render(Printers.scala:174)
	at scala.reflect.api.Universe.render(Universe.scala:59)
	at scala.reflect.api.Printers$class.show(Printers.scala:190)
	at scala.reflect.api.Universe.show(Universe.scala:59)
	at scala.reflect.api.Printers$class.treeToString(Printers.scala:182)
	at scala.reflect.api.Universe.treeToString(Universe.scala:59)
	at scala.reflect.api.Trees$TreeApi$class.toString(Trees.scala:192)
	at scala.reflect.internal.Trees$TreeContextApiImpl.toString(Trees.scala:76)
	at scala.reflect.internal.Printers$class.backquotedPath(Printers.scala:57)
	at scala.reflect.internal.SymbolTable.backquotedPath(SymbolTable.scala:13)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:382)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printSeq(Printers.scala:88)
	at scala.reflect.internal.Printers$TreePrinter.printRow(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.api.Printers$class.render(Printers.scala:174)
	at scala.reflect.api.Universe.render(Universe.scala:59)
	at scala.reflect.api.Printers$class.show(Printers.scala:190)
	at scala.reflect.api.Universe.show(Universe.scala:59)
	at scala.reflect.api.Printers$class.treeToString(Printers.scala:182)
	at scala.reflect.api.Universe.treeToString(Universe.scala:59)
	at scala.reflect.api.Trees$TreeApi$class.toString(Trees.scala:192)
	at scala.reflect.internal.Trees$TreeContextApiImpl.toString(Trees.scala:76)
	at scala.reflect.internal.Printers$class.backquotedPath(Printers.scala:57)
	at scala.reflect.internal.SymbolTable.backquotedPath(SymbolTable.scala:13)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:382)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printSeq(Printers.scala:88)
	at scala.reflect.internal.Printers$TreePrinter.printRow(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.api.Printers$class.render(Printers.scala:174)
	at scala.reflect.api.Universe.render(Universe.scala:59)
	at scala.reflect.api.Printers$class.show(Printers.scala:190)
	at scala.reflect.api.Universe.show(Universe.scala:59)
	at scala.reflect.api.Printers$class.treeToString(Printers.scala:182)
	at scala.reflect.api.Universe.treeToString(Universe.scala:59)
	at scala.reflect.api.Trees$TreeApi$class.toString(Trees.scala:192)
	at scala.reflect.internal.Trees$TreeContextApiImpl.toString(Trees.scala:76)
	at scala.reflect.internal.Printers$class.backquotedPath(Printers.scala:57)
	at scala.reflect.internal.SymbolTable.backquotedPath(SymbolTable.scala:13)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:382)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printSeq(Printers.scala:88)
	at scala.reflect.internal.Printers$TreePrinter.printRow(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.api.Printers$class.render(Printers.scala:174)
	at scala.reflect.api.Universe.render(Universe.scala:59)
	at scala.reflect.api.Printers$class.show(Printers.scala:190)
	at scala.reflect.api.Universe.show(Universe.scala:59)
	at scala.reflect.api.Printers$class.treeToString(Printers.scala:182)
	at scala.reflect.api.Universe.treeToString(Universe.scala:59)
	at scala.reflect.api.Trees$TreeApi$class.toString(Trees.scala:192)
	at scala.reflect.internal.Trees$TreeContextApiImpl.toString(Trees.scala:76)
	at scala.reflect.internal.Printers$class.backquotedPath(Printers.scala:57)
	at scala.reflect.internal.SymbolTable.backquotedPath(SymbolTable.scala:13)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:382)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printSeq(Printers.scala:88)
	at scala.reflect.internal.Printers$TreePrinter.printRow(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.api.Printers$class.render(Printers.scala:174)
	at scala.reflect.api.Universe.render(Universe.scala:59)
	at scala.reflect.api.Printers$class.show(Printers.scala:190)
	at scala.reflect.api.Universe.show(Universe.scala:59)
	at scala.reflect.api.Printers$class.treeToString(Printers.scala:182)
	at scala.reflect.api.Universe.treeToString(Universe.scala:59)
	at scala.reflect.api.Trees$TreeApi$class.toString(Trees.scala:192)
	at scala.reflect.internal.Trees$TreeContextApiImpl.toString(Trees.scala:76)
	at scala.reflect.internal.Printers$class.backquotedPath(Printers.scala:57)
	at scala.reflect.internal.SymbolTable.backquotedPath(SymbolTable.scala:13)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:382)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter$$anonfun$printRow$2.apply(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printSeq(Printers.scala:88)
	at scala.reflect.internal.Printers$TreePrinter.printRow(Printers.scala:99)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:357)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:34)
	at scala.tools.nsc.ast.Printers$TreePrinter.print(Printers.scala:19)
	at scala.reflect.api.Printers$class.render(Printers.scala:174)
	at scala.reflect.api.Universe.render(Universe.scala:59)
	at scala.reflect.api.Printers$class.show(Printers.scala:190)
	at scala.reflect.api.Universe.show(Universe.scala:59)
	at scala.reflect.api.Printers$class.treeToString(Printers.scala:182)
	at scala.reflect.api.Universe.treeToString(Universe.scala:59)
	at scala.reflect.api.Trees$TreeApi$class.toString(Trees.scala:192)
	at scala.reflect.internal.Trees$TreeContextApiImpl.toString(Trees.scala:76)
	at scala.reflect.internal.Printers$class.backquotedPath(Printers.scala:57)
	at scala.reflect.internal.SymbolTable.backquotedPath(SymbolTable.scala:13)
	at scala.reflect.internal.Printers$TreePrinter.printTree(Printers.scala:382)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:22)
	at scala.tools.nsc.ast.Printers$TreePrinter$$anonfun$print$1.apply(Printers.scala:19)
...
(many more lines of the same cycle)

**Comment by SethTisue** [comment]
unlikely to progress without minimization.
