### ISSUE TITLE
Very large string literals generate class files with errors

### ISSUE THREAD

**Issue by scabug** [scala/bug#7527]
When attempting to run the attached file with a large (>65535 character) String literal, I get the following error:

```scala
Exception in thread "main" java.lang.ClassFormatError: Unknown constant tag 32 in class file LongStringLiteral$delayedInit$body
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at LongStringLiteral$.<init>(LongStringLiteral.scala:1)
	at LongStringLiteral$.<clinit>(LongStringLiteral.scala)
	at LongStringLiteral.main(LongStringLiteral.scala)
```

**Comment by wang7x** [comment]
meet same error when call length() on a very large string [scastie example](https://scastie.scala-lang.org/PmnOAiZuSGOINdwe1Y7nlg)

**Comment by som-snytt** [comment]
```
➜  snips scala-cli compile --server=false -S 2.13.18 LongStringLiteral.scala
error: Error while emitting LongStringLiteral$
UTF8 string too large
error: Method delayedEndpoint$LongStringLiteral$1 in class LongStringLiteral$ has a bad String constant of length 52705
2 errors
Compilation failed
➜  snips scala-cli compile --server=false -S 3.8.2 LongStringLiteral.scala
Error while emitting LongStringLiteral$
UTF8 string too large
there was 1 deprecation warning; re-run with -deprecation for details
1 warning found
1 error found
Compilation failed
```
