### ISSUE TITLE
runtime reflection crash when loading inner classes

### ISSUE THREAD

**Issue by scabug** [scala/bug#7553]
Clone the project from https://github.com/xeno-by/livefx, launch sbt, switch to "project livefx_jfx", run "test:run-main test.livefx.DemoReflectionAssertion".

```scala
14:10 ~/Projects/livefx (master)$ java7
Switching to Java 1.7
Java home is detected at /Library/Java/JavaVirtualMachines/jdk1.7.0_12.jdk/Contents/Home
Symlinked /usr/local/java -> /Library/Java/JavaVirtualMachines/jdk1.7.0_12.jdk/Contents/Home/bin
Updated .bashrc with export JAVA_HOME = "/Library/Java/JavaVirtualMachines/jdk1.7.0_12.jdk/Contents/Home"
14:10 ~/Projects/livefx (master)$ sbt
Detected sbt version 0.12.2
Starting sbt: invoke with -help for other options
Using /Users/xeno_by/.sbt/0.12.2 as sbt dir, -sbt-dir to override.
[info] Loading project definition from /Users/xeno_by/Projects/livefx/project/project
[info] Loading project definition from /Users/xeno_by/Projects/livefx/project
[info] Set current project to livefx (in build file:/Users/xeno_by/Projects/livefx/)
[info] Defining */*:console-project::trace-level, */*:console::trace-level and 2 others.
[info] The new values will be used by no settings or tasks.
[info] 	Run `last` for details.
[info] Reapplying settings...
[info] Set current project to livefx (in build file:/Users/xeno_by/Projects/livefx/)
> project livefx_jfx
[info] Set current project to livefx_jfx (in build file:/Users/xeno_by/Projects/livefx/)
> test:run-main test.livefx.DemoReflectionAssertion
[info] Running test.livefx.DemoReflectionAssertion
[info] class CubicCurve
[info] class ProgressBar
[info] class HTMLEditor
[info] class TableCell
[info] class ButtonBase
[info] class TreeCell
[info] class BubbleChart
[info] class ScrollPane
[info] class Slider
[info] class Region
[info] class PieChart
[info] class CategoryAxis
[info] class TitledPane
[info] class ImageView
[info] class $1
[info] class SplitPane
[info] class Arc
[info] class Pagination
[info] class ColorPicker
[info] class ProgressIndicator
[info] class TextInputControl
[info] class HBox
[info] class TextFieldListCell
[info] class FlowPane
[info] class AnchorPane
[info] class BarChart
[info] class TextArea
[info] class Ellipse
[info] class MenuButton
[info] class CheckBoxListCell
[info] class $1
[info] class TableView
[info] class Button
[info] class CheckBoxTableCell
[info] class Chart
[info] class Parent
[info] class CheckBoxTreeCell
[info] class SplitMenuButton
[info] class QuadCurve
[info] class ToolBar
[info] class LineChart
[info] class ScrollBar
[info] class TreeView
[info] class ListCell
[info] class RadioButton
[info] class VBox
[info] class TextField
[info] class AreaChart
[info] class ScatterChart
[info] class Line
[info] class ComboBox
[info] class Labeled
[info] class TilePane
[info] class ComboBoxTableCell
[info] class Canvas
[info] class ChoiceBoxListCell
[info] class ListView
[info] class IndexedCell
[info] class Group
[info] class Rectangle
[info] class ComboBoxListCell
[info] class Accordion
[info] class Hyperlink
[info] class TableRow
[error] java.lang.AssertionError: assertion failed: no symbol could be
[error]  loaded from class javafx.scene.control.PopupControl$CSSBridge in class PopupControl with name $CSSBridge and classloader scala.tools.nsc.util.ScalaClassLoader$URLClassLoader@656e1fa
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$classToScala1(JavaMirrors.scala:966)
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:925)
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:925)
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$toScala$1.apply(JavaMirrors.scala:104)
[error] 	at scala.reflect.runtime.TwoWayCache.toScala(TwoWayCache.scala:38)
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:102)
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:925)
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:205)
[error] 	at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:65)
[error] 	at test.livefx.DemoReflectionAssertion$$anonfun$main$1.apply(DemoReflectionAssertion.scala:20)
[error] 	at test.livefx.DemoReflectionAssertion$$anonfun$main$1.apply(DemoReflectionAssertion.scala:19)
[error] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
[error] 	at test.livefx.DemoReflectionAssertion$.main(DemoReflectionAssertion.scala:19)
[error] 	at test.livefx.DemoReflectionAssertion.main(DemoReflectionAssertion.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:601)
[error] 	at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
[error] 	at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
[error] 	at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
[error] 	at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
[error] 	at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
[error] 	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
[error] 	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
[error] 	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
[error] 	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
[error] 	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
[error] 	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
[error] 	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
[error] 	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
[success] Total time: 2 s, completed Jun 4, 2013 2:10:17 PM
>
```

**Comment by SethTisue** [comment]
needs minimization and confirmation that the issue still even exists
