### ISSUE TITLE
Illegal field modifiers in class: 0x11 when referencing value from surrounding scope from inner trait/class of a trait.

### ISSUE THREAD

**Issue by scabug** [scala/bug#7970]
This only happens if Outer is a trait. If it is a class it runs fine. Also session has to be a value of a block of lambda function for it to happen.

**Reproduce code:**
```scala
object IllegalFieldModifiers extends App {
  {
    val session = null
    trait Outer{
      trait Inner{
        session
      }          
    }
    new Outer{}
  }
}
```

**Expected result:**
(Compiles and runs fine) or fails statically.

**Actual result:**
Compiles fine, but leads to runtime exception:
```
java.lang.ClassFormatError: Illegal field modifiers in class IllegalFieldModifiers$Outer$1: 0x11
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at IllegalFieldModifiers$.<init>(NyScala2013.scala:9)
	at IllegalFieldModifiers$.<clinit>(NyScala2013.scala)
	at IllegalFieldModifiers.main(NyScala2013.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
```

**Comment by som-snytt** [comment]
Verified broken on 2.11, works on 2.12. But did not look at why. 2.12 has the lambda change?

**Comment by joroKr21** [comment]
2.12 had trait encoding changes for Java 8
