### ISSUE TITLE
Future.mapTo errors very difficult to debug due to lack of error message

### ISSUE THREAD

**Issue by scabug** [scala/bug#7977]
A typical Future.mapTo exception when the cast fails:

```
Caused by: java.lang.ClassCastException: null
    at java.lang.Class.cast(Class.java:3047) ~[na:1.6.0_65]
    at scala.concurrent.Future$$anonfun$mapTo$1.liftedTree1$1(Future.scala:483) ~[scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$mapTo$1.apply(Future.scala:482) ~[scala-library.jar:na]
    at scala.concurrent.Future$$anonfun$mapTo$1.apply(Future.scala:479) ~[scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:29) [scala-library.jar:na]
    at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.processBatch$1(Future.scala:731) [scala-library.jar:na]
    at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply$mcV$sp(Future.scala:746) [scala-library.jar:na]
    at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply(Future.scala:723) [scala-library.jar:na]
    at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply(Future.scala:723) [scala-library.jar:na]
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) [scala-library.jar:na]
    at scala.concurrent.Future$InternalCallbackExecutor$Batch.run(Future.scala:722) [scala-library.jar:na]
    at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:782) [scala-library.jar:na]
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:773) [scala-library.jar:na]
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:37) [scala-library.jar:na]
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:133) [scala-library.jar:na]
    at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:269) ~[akka-actor_2.10-2.2.0.jar:2.2.0]
    at actors.FileLoader$$anonfun$receive$1.applyOrElse(FileLoader.scala:24) ~[classes/:na]
```

The last element in the stack trace there is my code, but it's not the code where mapTo was called, it's the code that causes the future to be redeemed.  Now, there's probably nothing Scala can do about that, but since the ClassCastException error message is null, all I know is that something tried to map a message sent by my actor to some type.  Scala really should be trying to provide a meaningful error message, for example:

```
Future.mapTo mapping failed, can't cast type X to Y.
```

**Comment by SethTisue** [comment]
closing since we no longer target Java 6

**Comment by som-snytt** [comment]
also they no longer target 2.11.

That was a lot of words for a one-liner that was never PR'd. OTOH, it is not necessary now to remove the workaround, so that's something.
