### ISSUE TITLE
Partest should fail nice on empty dir

### ISSUE THREAD

**Issue by scabug** [scala/bug#8000]
On an empty dir, instead of a nice error or ignoring it,

```
java.lang.RuntimeException: Error running /home/apm/clones/scala/test/files/pos/AAAA
	at scala.tools.partest.nest.SuiteRunner.liftedTree1$1(Runner.scala:773)
	at scala.tools.partest.nest.SuiteRunner.runTest(Runner.scala:771)
	at scala.tools.partest.nest.SuiteRunner$$anonfun$19$$anonfun$apply$6.apply(Runner.scala:786)
	at scala.tools.partest.nest.SuiteRunner$$anonfun$19$$anonfun$apply$6.apply(Runner.scala:786)
	at scala.tools.partest.package$$anon$2.call(package.scala:133)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.UnsupportedOperationException: tail of empty list
```

**Comment by som-snytt** [comment]
```
[error] Uncaught exception when running partest: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error running /home/amarki/projects/scala/test/files/pos/aaa
sbt.ForkMain$ForkError: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error running /home/amarki/projects/scala/test/files/pos/aaa
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at scala.tools.partest.nest.SuiteRunner.$anonfun$runTestsForFiles$5(Runner.scala:795)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:230)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:188)
	at scala.collection.TraversableLike.map(TraversableLike.scala:230)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:223)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:188)
	at scala.tools.partest.nest.SuiteRunner.runTestsForFiles(Runner.scala:795)
	at scala.tools.partest.nest.AbstractRunner.$anonfun$run$16(AbstractRunner.scala:176)
	at scala.tools.partest.nest.AbstractRunner.$anonfun$run$16$adapted(AbstractRunner.scala:172)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:785)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:188)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:784)
	at scala.tools.partest.nest.AbstractRunner.$anonfun$run$14(AbstractRunner.scala:172)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.tools.partest.package$.timed(package.scala:129)
	at scala.tools.partest.nest.AbstractRunner.run(AbstractRunner.scala:172)
	at scala.tools.partest.sbt.PartestTask.execute(Framework.scala:43)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sbt.ForkMain$ForkError: java.lang.RuntimeException: Error running /home/amarki/projects/scala/test/files/pos/aaa
	at scala.tools.partest.nest.SuiteRunner.liftedTree1$1(Runner.scala:776)
	at scala.tools.partest.nest.SuiteRunner.runTest(Runner.scala:774)
	at scala.tools.partest.nest.SuiteRunner.$anonfun$runTestsForFiles$2(Runner.scala:789)
	at scala.tools.partest.package$$anon$2.call(package.scala:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: sbt.ForkMain$ForkError: java.lang.UnsupportedOperationException: tail of empty list
	at scala.collection.immutable.Nil$.tail(List.scala:430)
	at scala.collection.immutable.Nil$.tail(List.scala:425)
	at scala.tools.partest.nest.Runner.groupedFiles(Runner.scala:421)
	at scala.tools.partest.nest.Runner.compilationRounds(Runner.scala:502)
	at scala.tools.partest.nest.Runner.$anonfun$runTestCommon$1(Runner.scala:529)
	at scala.tools.partest.nest.Runner.runInContext(Runner.scala:415)
	at scala.tools.partest.nest.Runner.runTestCommon(Runner.scala:529)
	at scala.tools.partest.nest.Runner.run(Runner.scala:650)
	at scala.tools.partest.nest.SuiteRunner.$anonfun$runTest$1(Runner.scala:774)
	at scala.tools.partest.package$.timed(package.scala:129)
	at scala.tools.partest.nest.SuiteRunner.liftedTree1$1(Runner.scala:774)
	at scala.tools.partest.nest.SuiteRunner.runTest(Runner.scala:774)
	at scala.tools.partest.nest.SuiteRunner.$anonfun$runTestsForFiles$2(Runner.scala:789)
	at scala.tools.partest.package$$anon$2.call(package.scala:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[debug] Summary for partest not available.
```
