### ISSUE TITLE
"no progress in completing object Xxx" during typechecking in presentation compiler

### ISSUE THREAD

**Issue by scabug** [scala/bug#8106]
While working on the last assignment of the Coursera reactive course, I got the following exception:

```
2013-12-29 13:58:57,285 ERROR [main] - org.scala-ide.sdt.core - org.scala-ide.sdt.core - org.scala-ide.sdt.core - 0 - AT: RangePosition(/media/win/Users/schaefer/data/dev/Scala/reactive-kvstore/src/main/scala/kvstore/Replica.scala, 1222, 1222, 1233)
scala.reflect.internal.FatalError: no progress in completing object Persistence: <?>
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:56)
	at scala.tools.nsc.Global.abort(Global.scala:263)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1334)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1473)
	at scala.tools.nsc.typechecker.Namers$class.companionSymbolOf(Namers.scala:1690)
	at scala.tools.nsc.interactive.Global$$anon$5.companionSymbolOf(Global.scala:219)
	at scala.tools.nsc.typechecker.Namers$Namer.ensureCompanionObject(Namers.scala:470)
	at scala.tools.nsc.typechecker.Namers$Namer.enterClassDef(Namers.scala:665)
	at scala.tools.nsc.typechecker.Namers$Namer.dispatch$1(Namers.scala:251)
	at scala.tools.nsc.typechecker.Namers$Namer.enterSym(Namers.scala:265)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$enterSyms$1.apply(Namers.scala:455)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$enterSyms$1.apply(Namers.scala:454)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
	at scala.collection.immutable.List.foldLeft(List.scala:83)
	at scala.tools.nsc.typechecker.Namers$Namer.enterSyms(Namers.scala:454)
	at scala.tools.nsc.typechecker.Namers$Namer.templateSig(Namers.scala:878)
	at scala.tools.nsc.typechecker.Namers$Namer.moduleSig(Namers.scala:942)
	at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1442)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1457)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:735)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1484)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:726)
	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1599)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1607)
	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1597)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1326)
	at scala.reflect.internal.Symbols$Symbol.cookJavaRawInfo(Symbols.scala:1540)
	at scala.tools.nsc.typechecker.Infer$Inferencer.checkAccessible(Infer.scala:271)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$makeAccessible(Typers.scala:582)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:4830)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIdentOrWildcard$1(Typers.scala:4845)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5279)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5299)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5335)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5362)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5309)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5313)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5411)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5419)
	at scala.tools.nsc.typechecker.Namers$Namer.importSig(Namers.scala:1347)
	at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1454)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1457)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:735)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1484)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:726)
	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1599)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1607)
	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1597)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1326)
	at scala.tools.nsc.typechecker.Contexts$ImportInfo.qual(Contexts.scala:1279)
	at scala.tools.nsc.typechecker.Contexts$ImportInfo.importedSymbol(Contexts.scala:1313)
	at scala.tools.nsc.typechecker.Contexts$Context.importedAccessibleSymbol(Contexts.scala:948)
	at scala.tools.nsc.typechecker.Contexts$Context.lookupImport$1(Contexts.scala:1094)
	at scala.tools.nsc.typechecker.Contexts$Context.lookupSymbol(Contexts.scala:1115)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIdent$2(Typers.scala:4807)
	at scala.tools.nsc.typechecker.Typers$Typer.typedIdentOrWildcard$1(Typers.scala:4845)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5279)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5299)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5335)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5362)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5309)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5313)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5411)
	at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5417)
	at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:4750)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5283)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5299)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5335)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5362)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5309)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5313)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5405)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTypeApply$1(Typers.scala:5071)
	at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5259)
	at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5292)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5299)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5335)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5362)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5309)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5313)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5402)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5493)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:833)
	at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1302)
	at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1448)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1457)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:735)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1484)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:734)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:726)
	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1599)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1607)
	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1597)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1326)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1473)
	at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$class.addDerivedTrees(MethodSynthesis.scala:181)
	at scala.tools.nsc.typechecker.Namers$Namer.addDerivedTrees(Namers.scala:53)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$28.apply(Typers.scala:1916)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$28.apply(Typers.scala:1916)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1857)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1854)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.List.foreach(List.scala:302)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1916)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1753)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5248)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5298)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5335)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5362)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5309)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5313)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5391)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3021)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$64.apply(Typers.scala:3125)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$64.apply(Typers.scala:3125)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3125)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4958)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5251)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5298)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5335)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5362)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5309)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5313)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5387)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:424)
	at scala.tools.nsc.interactive.Global$TyperRun$$anonfun$applyPhase$1.apply(Global.scala:1215)
	at scala.tools.nsc.interactive.Global$TyperRun$$anonfun$applyPhase$1.apply(Global.scala:1215)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:243)
	at scala.tools.nsc.interactive.Global$TyperRun.applyPhase(Global.scala:1215)
	at scala.tools.nsc.interactive.Global$TyperRun.typeCheck(Global.scala:1208)
	at scala.tools.nsc.interactive.Global.scala$tools$nsc$interactive$Global$$typeCheck(Global.scala:657)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5$$anonfun$apply$8.apply(Global.scala:573)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5.apply(Global.scala:569)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5.apply(Global.scala:569)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.immutable.List.foreach(List.scala:302)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:569)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:25)
```

The corresponding source file contains (the error position in the error message points to `import Persistence._` of class `Replica`):

```scala
package kvstore

import akka.actor.{ OneForOneStrategy, Props, ActorRef, Actor }
import kvstore.Arbiter._
import scala.collection.immutable.Queue
import akka.actor.SupervisorStrategy.Restart
import scala.annotation.tailrec
import akka.pattern.{ ask, pipe }
import akka.actor.Terminated
import scala.concurrent.duration._
import akka.actor.PoisonPill
import akka.actor.OneForOneStrategy
import akka.actor.SupervisorStrategy
import akka.util.Timeout

object Replica {
  sealed trait Operation {
    def key: String
    def id: Long
  }
  case class Insert(key: String, value: String, id: Long) extends Operation
  case class Remove(key: String, id: Long) extends Operation
  case class Get(key: String, id: Long) extends Operation

  sealed trait OperationReply
  case class OperationAck(id: Long) extends OperationReply
  case class OperationFailed(id: Long) extends OperationReply
  case class GetResult(key: String, valueOption: Option[String], id: Long) extends OperationReply

  def props(arbiter: ActorRef, persistenceProps: Props): Props = Props(new Replica(arbiter, persistenceProps))
}

class Replica(val arbiter: ActorRef, persistenceProps: Props) extends Actor {
  import Replica._
  import Replicator._
  import Persistence._
  import context.dispatcher

  /*
   * The contents of this actor is just a suggestion, you can implement it in any way you like.
   */
  
  var kv = Map.empty[String, String]
  // a map from secondary replicas to replicators
  var secondaries = Map.empty[ActorRef, ActorRef]
  // the current set of replicators
  var replicators = Set.empty[ActorRef]

  def receive = {
    case JoinedPrimary   => context.become(leader)
    case JoinedSecondary => context.become(replica)
  }

  /* TODO Behavior for  the leader role. */
  val leader: Receive = {
    case _ =>
  }

  /* TODO Behavior for the replica role. */
  val replica: Receive = {
    case _ =>
  }

}
```

Persistence.scala contains:

```scala
import akka.actor.Props

object Persistence {
  case class Persist(key: String, valueOption: Option[String], id: Long)
  case class Persisted(key: String, id: Long)

  class PersistenceException extends Exception("Persistence failure")

  def props(flaky: Boolean): Props = Props(classOf[Persistence], flaky)
}
```

**Comment by hihhuli** [comment]
The problem still persists. With Ensime and Emacs, Scala 2.11.8:

`[Exceptions.scala]: exception during background compile: scala.reflect.internal.FatalError: no progress in completing object Exceptions: <?>
scala.reflect.internal.FatalError: no progress in completing object Exceptions: <?>
	at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1522)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1889)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1808)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5310)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5452)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:3047)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3151)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$65.apply(Typers.scala:3151)
	at scala.collection.immutable.List.loop$1(List.scala:173)
	at scala.collection.immutable.List.mapConserve(List.scala:189)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3151)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5015)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5312)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5359)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5396)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5448)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
	at scala.tools.nsc.interactive.Global$TyperRun$$anonfun$applyPhase$1.apply(Global.scala:1338)
	at scala.tools.nsc.interactive.Global$TyperRun$$anonfun$applyPhase$1.apply(Global.scala:1338)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
	at scala.tools.nsc.interactive.Global$TyperRun.applyPhase(Global.scala:1338)
	at scala.tools.nsc.interactive.Global$TyperRun.typeCheck(Global.scala:1331)
	at scala.tools.nsc.interactive.Global.typeCheck(Global.scala:670)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5$$anonfun$apply$8.apply(Global.scala:585)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5.apply(Global.scala:581)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5.apply(Global.scala:581)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:581)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:25)`

Exceptions is an object containing case classes. This happens in multiple files with multiple projects. Compiler args: "-unchecked" "-deprecation" "-encoding" "utf8" "-feature" "-Xlint" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture" "-Ymacro-expand:discard"
