### ISSUE TITLE
Compiler assertion error in case of local lazy val of type Unit

### ISSUE THREAD

**Issue by scabug** [scala/bug#8277]
```scala
class A{
  def p()  = {
    lazy val s = 1;
    lazy val d = ();
    s
  }
}
```

```scala
scalac 1.scala 
error: java.lang.AssertionError: assertion failed: lazy value d$1
	at scala.reflect.internal.Symbols$Symbol.accessed(Symbols.scala:1924)
	at scala.reflect.internal.Symbols$Symbol.accessed(Symbols.scala:1920)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.bitmapCategory(Mixin.scala:618)
	at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$buildBitmapOffsets$1$1.apply(Mixin.scala:994)
	at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$buildBitmapOffsets$1$1.apply(Mixin.scala:994)
	at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:332)
	at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:331)
	at scala.collection.immutable.List.foreach(List.scala:302)
	at scala.collection.TraversableLike$class.groupBy(TraversableLike.scala:331)
	at scala.collection.AbstractTraversable.groupBy(Traversable.scala:104)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.buildBitmapOffsets$1(Mixin.scala:994)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.addNewDefs(Mixin.scala:999)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.scala$tools$nsc$transform$Mixin$MixinTransformer$$postTransform(Mixin.scala:1137)
	at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$transform$1.apply(Mixin.scala:1248)
	at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$transform$1.apply(Mixin.scala:1248)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:241)
	at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:250)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1248)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:463)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2642)
	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1394)
	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1393)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2677)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1392)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:14)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:14)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2634)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1245)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:463)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2666)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2664)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2664)
	at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1412)
	at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1412)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2677)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1411)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:14)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:14)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2634)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1245)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:463)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:145)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:424)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:391)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:391)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:391)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1603)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1588)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1583)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1681)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
	at scala.tools.nsc.Driver.process(Driver.scala:55)
	at scala.tools.nsc.Driver.main(Driver.scala:68)
	at scala.tools.nsc.Main.main(Main.scala)
Exception in thread "main" java.lang.AssertionError: assertion failed: lazy value d$1
	at scala.reflect.internal.Symbols$Symbol.accessed(Symbols.scala:1924)
	at scala.reflect.internal.Symbols$Symbol.accessed(Symbols.scala:1920)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.bitmapCategory(Mixin.scala:618)
	at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$buildBitmapOffsets$1$1.apply(Mixin.scala:994)
	at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$buildBitmapOffsets$1$1.apply(Mixin.scala:994)
	at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:332)
	at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:331)
	at scala.collection.immutable.List.foreach(List.scala:302)
	at scala.collection.TraversableLike$class.groupBy(TraversableLike.scala:331)
	at scala.collection.AbstractTraversable.groupBy(Traversable.scala:104)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.buildBitmapOffsets$1(Mixin.scala:994)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.addNewDefs(Mixin.scala:999)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.scala$tools$nsc$transform$Mixin$MixinTransformer$$postTransform(Mixin.scala:1137)
	at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$transform$1.apply(Mixin.scala:1248)
	at scala.tools.nsc.transform.Mixin$MixinTransformer$$anonfun$transform$1.apply(Mixin.scala:1248)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:241)
	at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:250)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1248)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:463)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2642)
	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1394)
	at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1393)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2677)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1392)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:14)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:14)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2634)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1245)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:463)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2666)
	at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2664)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2664)
	at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1412)
	at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1412)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2677)
	at scala.reflect.internal.Trees$class.itransform(Trees.scala:1411)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:14)
	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:14)
	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2634)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1245)
	at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:463)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:145)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:424)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:391)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:391)
	at scala.collection.Iterator$class.foreach(Iterator.scala:743)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:391)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1603)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1588)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1583)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1681)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
	at scala.tools.nsc.Driver.process(Driver.scala:55)
	at scala.tools.nsc.Driver.main(Driver.scala:68)
	at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by SethTisue** [comment]
closing stale backend tickets; comment/reopen if you have evidence this is still applicable

**Comment by lrytz** [comment]
Let's add a regression test.
