### ISSUE TITLE
Scala interpreter fails on named pipes

### ISSUE THREAD

**Issue by scabug** [scala/bug#8294]
Since `scala` doesn't seem to have a means to pass in a Scala string to be executed (unlike Python, Ruby, Perl, etc), I was hoping named pipes would do the job, but apparently the script runner is expecting a real file. I don't however think it should be necessary because this is the interpreter not compiler so it doesn't need to emit `.class` files side by side with the source file.

Or maybe this is because the `.scala` extension is missing—not sure.

    $ scala <(echo 'println("Hello")')
    java.io.IOException: no such file: /dev/fd/63
            at scala.tools.nsc.ScriptRunner.runScript(ScriptRunner.scala:190)
            at scala.tools.nsc.ScriptRunner.runScriptAndCatch(ScriptRunner.scala:201)
            at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:76)
            at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
            at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
            at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala

**Comment by som-snytt** [comment]
I've wanted to do retronym-like things for a long time.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6365
