### ISSUE TITLE
Toolbox compilation fails due to lack of position on trees

### ISSUE THREAD

**Issue by scabug** [scala/bug#8465]
```scala
scala> toolbox.typecheck(q"class C extends Dynamic { def selectDynamic(s: String) = ??? }; val c = new C; c.foo")
java.lang.UnsupportedOperationException: Position.point on NoPosition
  at scala.reflect.internal.util.Position.fail(Position.scala:17)
  at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:95)
  at scala.reflect.internal.util.UndefinedPosition.point(Position.scala:90)
  at scala.tools.nsc.typechecker.Typers$Typer$dyna$$anonfun$mkInvoke$2.apply(Typers.scala:3989)
  at scala.tools.nsc.typechecker.Typers$Typer$dyna$$anonfun$mkInvoke$2.apply(Typers.scala:3960)
  at scala.Option.map(Option.scala:145)
  at scala.tools.nsc.typechecker.Typers$Typer$dyna$.mkInvoke(Typers.scala:3960)
  at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$asDynamicCall$1(Typers.scala:4612)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$handleMissing$1$2.apply(Typers.scala:4657)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$handleMissing$1$2.apply(Typers.scala:4657)
  at scala.Option.orElse(Option.scala:266)
  at scala.tools.nsc.typechecker.Typers$Typer.handleMissing$1(Typers.scala:4657)
  at scala.tools.nsc.typechecker.Typers$Typer.typedSelectInternal$1(Typers.scala:4662)
  at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedSelect$1(Typers.scala:4594)
  at scala.tools.nsc.typechecker.Typers$Typer.typedSelectOrSuperCall$1(Typers.scala:4733)
  at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5251)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5267)
  at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5303)
  at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5330)
  at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5277)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5281)
  at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2361)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5225)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5225)
  at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:479)
  at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5225)
  at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5260)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5267)
  at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5303)
  at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5330)
  at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5277)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5281)
  at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2361)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5225)
  at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typedOutsidePatternMode$1$1.apply(Typers.scala:5225)
  at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:479)
  at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5225)
  at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5260)
  at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5267)
  at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5303)
  at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5330)
  at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5277)
  at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5281)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typecheck$1$$anonfun$13.apply(ToolBoxFactory.scala:171)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typecheck$1$$anonfun$13.apply(ToolBoxFactory.scala:171)
  at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:693)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typecheck$1.apply(ToolBoxFactory.scala:171)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$typecheck$1.apply(ToolBoxFactory.scala:169)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$11.apply(ToolBoxFactory.scala:147)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$11.apply(ToolBoxFactory.scala:147)
  at scala.tools.nsc.typechecker.Contexts$Context.withMode(Contexts.scala:374)
  at scala.tools.nsc.typechecker.Contexts$Context.withMacrosEnabled(Contexts.scala:381)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$9.apply(ToolBoxFactory.scala:138)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$9.apply(ToolBoxFactory.scala:138)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$withContext$1$1.apply(ToolBoxFactory.scala:139)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$withContext$1$1.apply(ToolBoxFactory.scala:139)
  at scala.tools.nsc.typechecker.Contexts$Context.withMode(Contexts.scala:374)
  at scala.tools.nsc.typechecker.Contexts$Context.withImplicitsEnabled(Contexts.scala:378)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$7.apply(ToolBoxFactory.scala:137)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1$$anonfun$7.apply(ToolBoxFactory.scala:137)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1.withContext$1(ToolBoxFactory.scala:139)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1.apply(ToolBoxFactory.scala:147)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$transformDuringTyper$1.apply(ToolBoxFactory.scala:121)
  at scala.reflect.internal.Trees$class.wrappingIntoTerm(Trees.scala:1691)
  at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:16)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.withWrapping$1(ToolBoxFactory.scala:120)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.transformDuringTyper(ToolBoxFactory.scala:121)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.typecheck(ToolBoxFactory.scala:168)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$typecheck$2.apply(ToolBoxFactory.scala:374)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$$anonfun$typecheck$2.apply(ToolBoxFactory.scala:366)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:354)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:354)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typecheck(ToolBoxFactory.scala:366)
  at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.typecheck(ToolBoxFactory.scala:27)
  ... 32 elided
```

**Comment by SethTisue** [comment]
full repro including required imports:

```scala
import scala.tools.reflect.ToolBox
import scala.reflect.runtime.currentMirror
val toolbox = currentMirror.mkToolBox()
import scala.reflect.runtime.universe._
toolbox.typecheck(q"class C extends Dynamic { def selectDynamic(s: String) = ??? }; val c = new C; c.foo") 
```

the problem remains reproducible in Scala 2.13.10
