### ISSUE TITLE
missing synthetics while typechecking reflect.api.Internals

### ISSUE THREAD

**Issue by scabug** [scala/bug#8725]
```scala
!ENTRY org.scala-ide.sdt.core 4 0 2014-07-15 12:31:46.285
!MESSAGE AT: RangePosition(/home/antoras/dev/scala/scala/src/reflect/scala/reflect/api/Internals.scala, 14892, 14898, 18859)
!STACK 0
scala.reflect.internal.FatalError: No synthetics for method TypeDecoratorApi: synthetics contains 
	at scala.reflect.internal.Reporting$class.abort(Reporting.scala:59)
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:16)
	at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth$class.addDerivedTrees(MethodSynthesis.scala:215)
	at scala.tools.nsc.typechecker.Namers$Namer.addDerivedTrees(Namers.scala:53)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$25.apply(Typers.scala:1879)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$25.apply(Typers.scala:1879)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1816)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$rewrappingWrapperTrees$1.apply(Typers.scala:1813)
	at scala.collection.immutable.List.flatMap(List.scala:327)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1879)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1738)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5206)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1892)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1738)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5206)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1892)
	at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1738)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5206)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4916)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5209)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4916)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5209)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
	at scala.collection.immutable.List.loop$1(List.scala:172)
	at scala.collection.immutable.List.mapConserve(List.scala:188)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4916)
	at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5209)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
	at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
	at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:102)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:410)
	at scala.tools.nsc.interactive.Global$TyperRun$$anonfun$applyPhase$1.apply(Global.scala:1217)
	at scala.tools.nsc.interactive.Global$TyperRun$$anonfun$applyPhase$1.apply(Global.scala:1217)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
	at scala.tools.nsc.interactive.Global$TyperRun.applyPhase(Global.scala:1217)
	at scala.tools.nsc.interactive.Global$TyperRun.typeCheck(Global.scala:1210)
	at scala.tools.nsc.interactive.Global.scala$tools$nsc$interactive$Global$$typeCheck(Global.scala:659)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5$$anonfun$apply$8.apply(Global.scala:574)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5.apply(Global.scala:570)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5.apply(Global.scala:570)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
	at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:570)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:25)
```

**Comment by SethTisue** [comment]
Although Scala IDE is dead it's conceivable the root cause here is something that's still relevant. Provisionally closing regardless, as we don't have a reproducer or a confirmation that it still happens in Scala 2.13.
