### ISSUE TITLE
Specialized default parameters has no definition

### ISSUE THREAD

**Issue by scabug** [scala/bug#9014]
```scala
def spec[@specialized T : Integral](t: T) = {
  def inner(default: T = t): T = t
  inner()
}

```

error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$3: Object
error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$5: Object
error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$7: Object
error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$9: Object
error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$11: Object
error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$13: Object
error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$15: Object
error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$17: Object
error: Concrete method has no definition: final <synthetic> private[this] def inner$default$1$19: Object

**Comment by hrhino** [comment]
Now (2.12.8) the error is:
```
java.lang.ClassFormatError: Method inner$default$1$3 in class  has illegal modifiers: 0x41A
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:74)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  at .$print$lzycompute(<console>:7)
  at .$print(<console>:6)
  at $print(<console>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:746)
```

**Comment by som-snytt** [comment]
Now (2.13.6) the error is: the same.

**Comment by joroKr21** [comment]
This looks wrong:
```scala
[[syntax trees at end of                specialize]] // <console>
package $line3 {
  sealed class $read extends Object with java.io.Serializable {
    def <init>(): $line3.$read = {
      $read.super.<init>();
      ()
    };
    sealed class $iw extends Object with java.io.Serializable {
      def <init>(): $iw = {
        $iw.super.<init>();
        ()
      };
      def spec[@specialized T](t: T, evidence$1: scala.math.Integral[T]): T = {
        def inner(default: T): T = t;
        <synthetic> def inner$default$1(): T @scala.annotation.unchecked.uncheckedVariance = t;
        inner(inner$default$1())
      };
      <specialized> def spec$mZc$sp(t: Boolean, evidence$1: scala.math.Integral[Boolean]): Boolean = {
        def inner(default: Boolean): Boolean = t;
        <synthetic> def inner$default$1(): Boolean @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      };
      <specialized> def spec$mBc$sp(t: Byte, evidence$1: scala.math.Integral[Byte]): Byte = {
        def inner(default: Byte): Byte = t;
        <synthetic> def inner$default$1(): Byte @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      };
      <specialized> def spec$mCc$sp(t: Char, evidence$1: scala.math.Integral[Char]): Char = {
        def inner(default: Char): Char = t;
        <synthetic> def inner$default$1(): Char @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      };
      <specialized> def spec$mDc$sp(t: Double, evidence$1: scala.math.Integral[Double]): Double = {
        def inner(default: Double): Double = t;
        <synthetic> def inner$default$1(): Double @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      };
      <specialized> def spec$mFc$sp(t: Float, evidence$1: scala.math.Integral[Float]): Float = {
        def inner(default: Float): Float = t;
        <synthetic> def inner$default$1(): Float @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      };
      <specialized> def spec$mIc$sp(t: Int, evidence$1: scala.math.Integral[Int]): Int = {
        def inner(default: Int): Int = t;
        <synthetic> def inner$default$1(): Int @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      };
      <specialized> def spec$mJc$sp(t: Long, evidence$1: scala.math.Integral[Long]): Long = {
        def inner(default: Long): Long = t;
        <synthetic> def inner$default$1(): Long @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      };
      <specialized> def spec$mSc$sp(t: Short, evidence$1: scala.math.Integral[Short]): Short = {
        def inner(default: Short): Short = t;
        <synthetic> def inner$default$1(): Short @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      };
      <specialized> def spec$mVc$sp(t: Unit, evidence$1: scala.math.Integral[Unit]): Unit = {
        def inner(default: Unit): Unit = t;
        <synthetic> def inner$default$1(): Unit @scala.annotation.unchecked.uncheckedVariance = t;
        <synthetic> def inner$default$1: T @scala.annotation.unchecked.uncheckedVariance;
        inner(inner$default$1())
      }
    };
    private[this] val $iw: $iw = new $iw();
    <stable> <accessor> def $iw(): $iw = $read.this.$iw
  };
  object $read extends Object with java.io.Serializable {
    def <init>(): type = {
      $read.super.<init>();
      ()
    };
    private[this] val INSTANCE: $line3.$read = new $line3.$read();
    <stable> <accessor> def INSTANCE(): $line3.$read = $read.this.INSTANCE;
    <synthetic> private def writeReplace(): Object = new scala.runtime.ModuleSerializationProxy(classOf[$line3.$read$])
  }
}
```

**Comment by hrhino** [comment]
@som-snytt I barely recognize you with that face on.

**Comment by som-snytt** [comment]
@hrhino it wasn't easy being green.

**Comment by joroKr21** [comment]
If someone wants to fix it -> look into `SpecializationDuplicator` which retypes specialized bodies and enters the default getter a second time (during `Namer`)

**Comment by joroKr21** [comment]
And this leads me to thing that there may be similar problems with other synthetics in specialized bodies.
