### ISSUE TITLE
Inlining can prolong object lifetimes leading to OutOfMemoryError

### ISSUE THREAD

**Issue by scabug** [scala/bug#9137]
```scala
object Test {
  def main(args: Array[String]): Unit = {
    test()
  }
  def test() {
    new Stream().withFilter.next.next.next.next.next.next.next.next
  }
  class Stream() {
    println("new Stream()")
    val data = Array.ofDim[Byte](64 * 1024 * 1024)
    lazy val next = new Stream
    @inline
    final def withFilter = new StreamWithFilter(this)
  }

  final class StreamWithFilter(var s: Stream) {
    lazy val filtered = { val result = s.next; s = null; result}  
    def next: Stream = filtered.next
  }
}
```

```
% qscalac sandbox/test.scala && echo ':javap -c Test$#test' | qscala && qscala -nc Test
Welcome to Scala version 2.12.0-20150204-161502-f894c55ef3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_25).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :javap -c Test$#test
  public void test();
    Code:
       0: new           #22                 // class Test$Stream
       3: dup
       4: invokespecial #23                 // Method Test$Stream."<init>":()V
       7: invokevirtual #27                 // Method Test$Stream.withFilter:()LTest$StreamWithFilter;
      10: invokevirtual #33                 // Method Test$StreamWithFilter.next:()LTest$Stream;
      13: invokevirtual #34                 // Method Test$Stream.next:()LTest$Stream;
      16: invokevirtual #34                 // Method Test$Stream.next:()LTest$Stream;
      19: invokevirtual #34                 // Method Test$Stream.next:()LTest$Stream;
      22: invokevirtual #34                 // Method Test$Stream.next:()LTest$Stream;
      25: invokevirtual #34                 // Method Test$Stream.next:()LTest$Stream;
      28: invokevirtual #34                 // Method Test$Stream.next:()LTest$Stream;
      31: invokevirtual #34                 // Method Test$Stream.next:()LTest$Stream;
      34: pop
      35: return
}

scala> :quit
new Stream()
new Stream()
new Stream()
new Stream()
new Stream()
new Stream()
new Stream()
new Stream()
new Stream()
new Stream()

% qscalac -optimize -Yinline-warnings -Xfatal-warnings sandbox/test.scala && echo ':javap -c Test$#test' | qscala && qscala -nc Test
Welcome to Scala version 2.12.0-20150204-161502-f894c55ef3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_25).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :javap -c Test$#test
  public void test();
    Code:
       0: new           #22                 // class Test$Stream
       3: dup
       4: invokespecial #23                 // Method Test$Stream."<init>":()V
       7: astore_1
       8: new           #25                 // class Test$StreamWithFilter
      11: dup
      12: aload_1
      13: invokespecial #28                 // Method Test$StreamWithFilter."<init>":(LTest$Stream;)V
      16: invokevirtual #32                 // Method Test$StreamWithFilter.filtered:()LTest$Stream;
      19: invokevirtual #35                 // Method Test$Stream.next:()LTest$Stream;
      22: invokevirtual #35                 // Method Test$Stream.next:()LTest$Stream;
      25: invokevirtual #35                 // Method Test$Stream.next:()LTest$Stream;
      28: invokevirtual #35                 // Method Test$Stream.next:()LTest$Stream;
      31: invokevirtual #35                 // Method Test$Stream.next:()LTest$Stream;
      34: invokevirtual #35                 // Method Test$Stream.next:()LTest$Stream;
      37: invokevirtual #35                 // Method Test$Stream.next:()LTest$Stream;
      40: invokevirtual #35                 // Method Test$Stream.next:()LTest$Stream;
      43: pop
      44: return
}

scala> :quit
new Stream()
new Stream()
new Stream()
java.lang.OutOfMemoryError: Java heap space
    at scala.reflect.ManifestFactory$$anon$6.newArray(Manifest.scala:93)
    at scala.reflect.ManifestFactory$$anon$6.newArray(Manifest.scala:91)
```

**Comment by SethTisue** [comment]
@lrytz should this stay open and assigned to you?

**Comment by lrytz** [comment]
yes, keep it open

**Comment by lrytz** [comment]
There are two variants of this bug.

In the first one, the inliner creates a new local variable (in the example below for the receiver):

```scala
object Test {
  def main(args: Array[String]): Unit =
    new Stream().ident.next.next.next.next.next.next.next.next

  class Stream() {
    println("new Stream")

    val data = Array.ofDim[Byte](256 * 1024 * 1024)
    lazy val next = new Stream

    @noinline def id(s: Stream) = s
    @inline final def ident: Stream = id(this)
  }
}
```

This can be fixed by setting all local vars created by the inliner to `null` after the inlined code. However, the same problem exists for local variables copied into the callsite method:

```scala
object Test {
  def main(args: Array[String]): Unit =
    new Stream().ident.next.next.next.next.next.next.next.next

  class Stream() {
    println("new Stream")

    val data = Array.ofDim[Byte](256 * 1024 * 1024)
    lazy val next = new Stream

    @inline final def ident: Stream = {
      var alias: Stream = null
      if (data != null) alias = this
      alias
    }
  }
}
```

To avoid a full combined liveness&nullness analysis, we can just set all those local vars to null after inlining a method (part of https://github.com/scala/scala/pull/7133).

**Comment by Jasper-M** [comment]
> liveness analysis for nulling out locals

Not really related to inlining anymore, but something like this, either at bytecode or at Scala-language level, could also make the runtime semantics of block expressions more intuitive.

```scala
val x = {
  val tmp = getBigObject()
  tmp.mutate(42)
  processBigObject(tmp)
}
// tmp out of scope for Scala, but GC doesn't know it
```

**Comment by lrytz** [comment]
Yes, I'm not saying it's a useless optimization. But at least the user can manually make `tmp` a `var` and `null` it out. If the issue is due to inlining, you're out of luck (except for `@noinline`). We'd also need to study if nulling out locals is universally a good idea (for performance), or if it can cause issues on its own.

So I think it makes sense to be eager about nulling out locals in the inliner for now.
