### ISSUE TITLE
sam type inference avoids cycles

### ISSUE THREAD

**Issue by scabug** [scala/bug#9244]
```scala
object Test {
  trait F1[T1, R]  { def apply(a1: T1): R }

  def cycle[T](function: F1[_ >: T, _ <: T]): Unit = ???

  cycle((_: String) => "")
}
```

shouldn't crash the compiler

```scala
error: java.lang.AssertionError: assertion failed: TVar<_$1=null>
	at scala.reflect.internal.Types$TypeVar.addLoBound(Types.scala:2972)
	at scala.reflect.internal.tpe.TypeConstraints$class.solveOne$1(TypeConstraints.scala:228)
	at scala.reflect.internal.tpe.TypeConstraints$$anonfun$solve$1.apply(TypeConstraints.scala:260)
	at scala.reflect.internal.tpe.TypeConstraints$$anonfun$solve$1.apply(TypeConstraints.scala:260)
	at scala.reflect.internal.util.Collections$class.foreach3(Collections.scala:228)
	at scala.reflect.internal.SymbolTable.foreach3(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeConstraints$class.solve(TypeConstraints.scala:260)
	at scala.reflect.internal.SymbolTable.solve(SymbolTable.scala:16)
	at scala.reflect.internal.Types$ExistentialType.withTypeVars(Types.scala:2696)
	at scala.reflect.internal.tpe.TypeComparers$class.thirdTry$1(TypeComparers.scala:483)
	at scala.reflect.internal.tpe.TypeComparers$class.secondTry$1(TypeComparers.scala:450)
	at scala.reflect.internal.tpe.TypeComparers$class.firstTry$1(TypeComparers.scala:426)
	at scala.reflect.internal.tpe.TypeComparers$class.isSubType2(TypeComparers.scala:552)
	at scala.reflect.internal.tpe.TypeComparers$class.isSubType1(TypeComparers.scala:320)
	at scala.reflect.internal.tpe.TypeComparers$class.isSubType(TypeComparers.scala:278)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:16)
	at scala.reflect.internal.tpe.TypeComparers$class.isWeakSubType(TypeComparers.scala:575)
	at scala.reflect.internal.SymbolTable.isWeakSubType(SymbolTable.scala:16)
	at scala.reflect.internal.Types$Type.weak_$less$colon$less(Types.scala:825)
	at scala.tools.nsc.typechecker.Infer$Inferencer.scala$tools$nsc$typechecker$Infer$Inferencer$$isCompatible(Infer.scala:305)
	at scala.tools.nsc.typechecker.Infer$Inferencer$$anonfun$methTypeArgs$2.apply(Infer.scala:545)
	at scala.tools.nsc.typechecker.Infer$Inferencer$$anonfun$methTypeArgs$2.apply(Infer.scala:539)
	at scala.reflect.internal.util.Collections$class.map2(Collections.scala:79)
	at scala.reflect.internal.SymbolTable.map2(SymbolTable.scala:16)
	at scala.tools.nsc.typechecker.Infer$Inferencer.methTypeArgs(Infer.scala:539)
	at scala.tools.nsc.typechecker.Infer$Inferencer.inferMethodInstance(Infer.scala:993)
	at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3510)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3515)
```

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/11558
