### ISSUE TITLE
Getting a private field using reflection fails when referenced from an anonymous function

### ISSUE THREAD

**Issue by scabug** [scala/bug#9306]
Test case below. Uncommenting the line makes the test throw:

```
scala.ScalaReflectionException: Scala field x  isn't represented as a Java field, neither it has a Java accessor method
note that private parameters of class constructors don't get mapped onto fields and/or accessors,
unless they are used outside of their declaring constructors.
```

Test case:

```scala
class FieldAccessTest {

  class TestClass {
    private val x = 123
    // Uncomment the following line to make the test fail
    // () => x
  }

  @Test
  def testFieldAccess(): Unit = {
    import scala.reflect.runtime.{universe => ru}
    val mirror = ru.runtimeMirror(getClass.getClassLoader)

    val obj = new TestClass
    val objType = mirror.reflect(obj).symbol.toType
    val objFields = objType.members.collect { case ms: ru.MethodSymbol if ms.isGetter => ms }

    Assert.assertEquals(123, mirror.reflect(obj).reflectField(objFields.head).get)
  }
}
```

The problem appears to be caused by name mangling, which is triggered by the presence of the anonymous function. The field is then named "FieldAccessTest$TestClass$$x" instead of "x" in the resulting bytecode, which causes reflection to fail.

**Comment by xuwei-k** [comment]
Could not reproduce Scala 2.12.0 or later

**Comment by hrhino** [comment]
fixed by fields phase, maybe?

**Comment by som-snytt** [comment]
The example progressed because lambdas became static methods, so mangling the private accessor was no longer necessary.

However, as the bumper sticker says, "mangling happens":

```
class C {
  private val c = 42
}
object C {
  def f(c: C) = c.c
}
```
so
```
scala 2.13.1> import reflect.runtime._
import reflect.runtime._

scala 2.13.1> val c = new C
c: C = C@9f1ca74

scala 2.13.1> currentMirror.reflect(c).symbol.toType
res0: reflect.runtime.universe.Type = C

scala 2.13.1> .members
res1: reflect.runtime.universe.MemberScope =
Scope{
  private[this] val c: <?>;
  private val c: <?>;
  def <init>: <?>;
  final def $asInstanceOf[T0](): T0;
  final def $isInstanceOf[T0](): Boolean;
  final def synchronized[T0](x$1: T0): T0;
  final def ##(): Int;
  final def !=(x$1: Any): Boolean;
  final def ==(x$1: Any): Boolean;
  final def ne(x$1: AnyRef): Boolean;
  final def eq(x$1: AnyRef): Boolean;
  final def notifyAll(): Unit;
  final def notify(): Unit;
  protected[package lang] def clone(): Object;
  final def getClass(): Class[_];
  def hashCode(): Int;
  def toString(): String;
  def equals(x$1: Object): Boolean;
  final def wait(): Unit;
  final def wait(x$1: Long, x$2: Int): Unit;
  final def wait(x$1: Long): Unit;
  protected[package lang] def finalize(): Unit;
  fina...

scala 2.13.1> .collect { case m: universe.MethodSymbol if m.isGetter => m }
                                              ^
              warning: abstract type pattern reflect.runtime.universe.MethodSymbol is unchecked since it is eliminated by erasure
res2: Iterable[reflect.runtime.universe.MethodSymbol] = List(value c)

scala 2.13.1> currentMirror.reflect(c).reflectField(res2.head).get
scala.ScalaReflectionException: Scala field c  of class C isn't represented as a Java field, nor does it have a
Java accessor method. One common reason for this is that it may be a private class parameter
not used outside the primary constructor.
  at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$ErrorNonExistentField(JavaMirrors.scala:149)
  at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.reflectField(JavaMirrors.scala:278)
  at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.reflectField(JavaMirrors.scala:269)
  ... 28 elided

scala 2.13.1> :javap -pc C
[snip]
Compiled from "<pastie>"
public class C {
  private final int C$$c;

  public static int f(C);
    Code:
       0: getstatic     #19                 // Field C$.MODULE$:LC$;
       3: aload_0
       4: invokevirtual #21                 // Method C$.f:(LC;)I
       7: ireturn

  public int C$$c();
    Code:
       0: aload_0
       1: getfield      #24                 // Field C$$c:I
       4: ireturn

  public C();
    Code:
       0: aload_0
       1: invokespecial #30                 // Method java/lang/Object."<init>":()V
       4: aload_0
       5: bipush        42
       7: putfield      #24                 // Field C$$c:I
      10: return
}
```
