### ISSUE TITLE
Typer stack-overflow when Dynamic with implicit conversions are used

### ISSUE THREAD

**Issue by scabug** [scala/bug#9310]
When compiling the `so.scala` file, scalac stack-overflows in the typer:

```
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPos(Typers.scala:5454)
        at scala.tools.nsc.typechecker.Typers$Typer.insertApply$1(Typers.scala:949)
        at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1115)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1166)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5410)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
        at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5370)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5374)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPos(Typers.scala:5454)
        at scala.tools.nsc.typechecker.Typers$Typer.insertApply$1(Typers.scala:949)
        at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1115)
        at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1166)
        at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5410)
        at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5423)
...
```

**Comment by som-snytt** [comment]
Less is more:
```
  class C extends Dynamic {
    def applyDynamic(arg: Any): C = ???
  }
  new C().m(42)
```

**Comment by som-snytt** [comment]
Similar to https://github.com/scala/bug/issues/8006, with a similar fix.
