### ISSUE TITLE
Bad class file due to value with constant type that overrides a specialized trait method

### ISSUE THREAD

**Issue by scabug** [scala/bug#9486]
```scala
trait A[@specialized(Int) T] {
  def f: T = ???
}

object B extends A[Int] {
  override final val f = 0
}
```

will cause the following error when B is loaded:
```scala
Exception in thread "main" java.lang.ClassFormatError: Duplicate method name&signature in class file test/B$
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:125)
```

Interestingly, if we removed the "final" marker in object B, the code will run properly.

**Comment by som-snytt** [comment]
duplicated by https://github.com/scala/bug/issues/12301
