### ISSUE TITLE
AssertionError with -Xfatal-warnings when warnings are issued (only from sbt)

### ISSUE THREAD

**Issue by scabug** [scala/bug#9592]
When using `-Xfatal-warnings` and some warnings are issued, and when compiling from sbt, after issuing the error message, the compiler crashes with an AssertionError. This only happens when compiling from SBT, not with the command-line compiler. Same in 2.11.7 and 2.12.0-M3.

```
$ cat build.sbt
scalaVersion := "2.11.7"

scalacOptions ++= List(
  "-Xfatal-warnings"
)

$ cat project/build.properties
sbt.version=0.13.9

$ cat src/main/scala/Main.scala
class C {
  @deprecated def d = 0
  def t = d
}
object outer {
  trait Inner {
    def filter = "hai"
  }
  object Inner
}
```

```
> compile
[info] Compiling 1 Scala source to /Users/luc/tmp/sbtproj/target/scala-2.11/classes...
[error] there were two deprecation warnings; re-run with -deprecation for details
[trace] Stack trace suppressed: run last compile:compileIncremental for the full output.
[error] (compile:compileIncremental) java.lang.AssertionError: assertion failed: <no phase>
[error] Total time: 2 s, completed Dec 16, 2015 11:05:34 AM
> last compile:compileIncremental
[debug]
[debug] Initial source changes:
[debug] 	removed:Set()
[debug] 	added: Set(/Users/luc/tmp/sbtproj/src/main/scala/Main.scala)
[debug] 	modified: Set()
[debug] Invalidated products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set(/Users/luc/tmp/sbtproj/src/main/scala/Main.scala)
[debug]
[debug] Sources indirectly invalidated by:
[debug] 	product: Set()
[debug] 	binary dep: Set()
[debug] 	external source: Set()
[debug] All initially invalidated sources: Set(/Users/luc/tmp/sbtproj/src/main/scala/Main.scala)
[debug] Recompiling all 1 sources: invalidated sources (1) exceeded 50.0% of all sources
[info] Compiling 1 Scala source to /Users/luc/tmp/sbtproj/target/scala-2.11/classes...
[debug] Getting compiler-interface from component compiler for Scala 2.11.7
[debug] Getting compiler-interface from component compiler for Scala 2.11.7
[debug] Running cached compiler 29e06731, interfacing (CompilerInterface) with Scala compiler version 2.11.7
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug] 	-Xfatal-warnings
[debug] 	-bootclasspath
[debug] 	/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/classes:/Users/luc/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar
[debug] 	-classpath
[debug] 	/Users/luc/tmp/sbtproj/target/scala-2.11/classes
[error] there were two deprecation warnings; re-run with -deprecation for details
java.lang.AssertionError: assertion failed: <no phase>
	at scala.reflect.internal.SymbolTable.phase_$eq(SymbolTable.scala:192)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1488)
	at scala.tools.nsc.Global$Run$$anonfun$scala$tools$nsc$Global$Run$$resetPackageClass$1$$anonfun$apply$4.apply(Global.scala:1618)
	at scala.tools.nsc.Global$Run$$anonfun$scala$tools$nsc$Global$Run$$resetPackageClass$1$$anonfun$apply$4.apply(Global.scala:1618)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
	at scala.tools.nsc.Global$Run$$anonfun$scala$tools$nsc$Global$Run$$resetPackageClass$1.apply(Global.scala:1618)
	at scala.tools.nsc.Global$Run$$anonfun$scala$tools$nsc$Global$Run$$resetPackageClass$1.apply(Global.scala:1618)
	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
	at scala.tools.nsc.Global$Run.scala$tools$nsc$Global$Run$$resetPackageClass(Global.scala:1617)
	at scala.tools.nsc.Global$Run$$anonfun$compileUnitsInternal$6.apply(Global.scala:1561)
	at scala.tools.nsc.Global$Run$$anonfun$compileUnitsInternal$6.apply(Global.scala:1561)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
	at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:103)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:103)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1561)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
```

The problem is in this section: https://github.com/scala/scala/blob/v2.11.7/src/compiler/scala/tools/nsc/Global.scala#L1553-L1561
The module class symbol of `outer` is reset. The subsequent call to `resetPackageClass` for `outer` (which is the `Inner` class' outer) invokes `.info`. That calls `phase = phaseOf(infos.validFrom)`, which is now `NoPhase` (https://github.com/scala/scala/blob/v2.11.7/src/reflect/scala/reflect/internal/Symbols.scala#L1488).

**Comment by som-snytt** [comment]
Confirmed that it errors correctly with 2.13, sbt 1.2.8. All that resetting was excised. It's like Bugatti's famous retort, "I make my cars to go, not to stop."
