### ISSUE TITLE
IllegalArgumentException during compile

### ISSUE THREAD

**Issue by scabug** [scala/bug#9679]
compiling the below code results in
```scala
Error:scalac: Error: org.jetbrains.jps.incremental.scala.remote.ServerException
java.lang.IllegalArgumentException
	at scala.tools.asm.ByteVector.putUTF8(ByteVector.java:213)
	at scala.tools.asm.ClassWriter.newUTF8(ClassWriter.java:1092)
	at scala.tools.asm.MethodWriter.getSize(MethodWriter.java:2098)
	at scala.tools.asm.ClassWriter.toByteArray(ClassWriter.java:827)
	at scala.tools.nsc.backend.jvm.GenASM$JBuilder.writeIfNotTooBig(GenASM.scala:526)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1341)
	at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:198)
	at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:204)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:115)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:94)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at org.jetbrains.jps.incremental.scala.local.IdeaIncrementalCompiler.compile(IdeaIncrementalCompiler.scala:29)
	at org.jetbrains.jps.incremental.scala.local.LocalServer.compile(LocalServer.scala:26)
	at org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:67)
	at org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:24)
	at org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
```

```scala
package org.uwes.bleeding

import scala.util.parsing.combinator.RegexParsers

trait CParser extends RegexParsers  {
  def number:Parser[Int] = "[0-9]+".r ^^ {_.toInt}

  def ident:Parser[String]   = """[a-z]+""".r       ^^ { _.toString }

  def sexpr = repsep(",",expr0)
  def hier_ = "."  ~atom
  def scope_ = "::"~atom
  def array_ =  "["~expr0~"]"

  def function_ = rep("(" ~ sexpr ~ ")")
  def atom = number | ident | "(" ~ expr0 ~ ")"
  def l15 = atom ~ rep(function_ | array_ | hier_ | scope_)
  def l14 = rep("+"|"-"|"!"|"~"|"&"|"~&"|"|"|"~|"|"^"|"~^"|"^~") ~ l15
  def l13 = l14 ~ rep("**" ~ l14)
  def l12 = l13 ~ rep(("*"|"/"|"%") ~ l13)
  def l11 = l12 ~ rep(("+"|"-") ~ l12)
  def l10 = l11 ~ rep(("<<"|">>"|"<<<"|">>>") ~ l11)
  def l9 = l10 ~ rep(("<"|"<="|">"|">="|"inside"|"dist") ~ l10)
  def l8 = l9 ~ rep(("=="|"!="|"==="|"!=="|"==?"|"!=?") ~ l9)
  def l7 = l8 ~ rep("&" ~ l8)
  def l6 = l7 ~ rep(("^"|"~^"|"^~") ~ l7)
  def l5 = l6 ~ rep("|" ~ l6)
  def l4 = l5 ~ rep("&&" ~ l5)
  def l3 = l4 ~ rep("||" ~ l4)
  def l2 = l3 ~ rep("?:" ~ l3)
  def l1 = l2 ~ rep(("->"|"<->") ~ l2)
  def l0 = l1 ~ opt((":="|":/") ~ l1)
  def expr0:Parser[Any] = l0 | "{" ~ sexpr ~ "}" | "{{" ~ sexpr ~ "}}"
}
```

**Comment by xuwei-k** [comment]
> the error message could be improved 

https://github.com/scala/scala-asm/commit/d2f33ce3154e34484f6304ec5923d4ebde8ec72c

**Comment by SethTisue** [comment]
```scala
//> using dep org.scala-lang.modules::scala-parser-combinators:2.4.0
```

```
% scala compile -S 2.12 S.scala
Downloading 2 dependencies
Compiling project (Scala 2.12.20, JVM (17))
Error: Error while emitting CParser
UTF8 string too large
Error compiling project (Scala 2.12.20, JVM (17))
Compilation failed
```

```
% scala compile -S 2 S.scala
Compiling project (Scala 2.13.16, JVM (17))
Error: Error while emitting CParser
UTF8 string too large
Error: Method l6 in class CParser has a bad signature of length 94365
Error: Method l5 in class CParser has a bad signature of length 188829
Error: Method l4 in class CParser has a bad signature of length 377757
Error: Method l3 in class CParser has a bad signature of length 755613
Error: Method l2 in class CParser has a bad signature of length 1511325
Error: Method l1 in class CParser has a bad signature of length 3022749
Error: Method l0 in class CParser has a bad signature of length 6045578
Error compiling project (Scala 2.13.16, JVM (17))
Compilation failed
```

```
% scala compile -S 3 S.scala
Downloading 2 dependencies
Compiling project (Scala 3.6.3, JVM (17))
Error: Error while emitting CParser
UTF8 string too large
Error compiling project (Scala 3.6.3, JVM (17))
Compilation failed
```

maybe the error message could be even better, but I'm closing since the original `IllegalArgumentException` no longer occurs

**Comment by som-snytt** [comment]
That rang a bell.

https://github.com/scala/scala/pull/10791

It even says, `This is just a start.`

Github claims that was last year, but it was actually a million years ago.
