### ISSUE TITLE
Scalac does not seem to support JSR 308

### ISSUE THREAD

**Issue by scabug** [scala/bug#9883]
JSR 308 brought annotations on type parameters such as

```java
class SomeBean {
     Optional<@Base64 String> bs;
}
```

After a quick byte-code analysis (`javap -v ... | grep Base64`) the following scala code does not seem to compile properly:
```scala
case class SomeScalaBean(bs: Optional[String @Base64]) 
```

This was asked on SO: http://stackoverflow.com/questions/38833827/how-to-annotate-a-type-parameter-in-scala

**Comment by tmoschou** [comment]
This looks to still be an issue with annotation on type parameters being ignored by scalac. An example use case is implementing a custom Hibernate Validator ValueExtractor, which requires it. 

See https://docs.jboss.org/hibernate/stable/validator/reference/en-US/html_single/#_implementing_a_code_valueextractor_code

```scala
import javax.validation.valueextraction.{ExtractedValue, ValueExtractor}
import javax.validation.{Validation, Validator}

object SeqValueExtractor extends ValueExtractor[Seq[_ @ExtractedValue]] {
  override def extractValues(
    originalValue: Seq[_],
    receiver: ValueExtractor.ValueReceiver
  ): Unit = {
    for ((x, i) <- originalValue.zipWithIndex) {
      receiver.indexedValue(null, i, x)
    }
  }
}

Validation
  .byDefaultProvider
  .configure
  .addValueExtractor(SeqValueExtractor)
```

```
Caused by: javax.validation.valueextraction.ValueExtractorDefinitionException: HV000203: Value extractor type io.stellargraph.storage.web.config.SeqValueExtractor$ fails to declare the extracted type parameter using @ExtractedValue.
	at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorDescriptor.getExtractedTypeParameter(ValueExtractorDescriptor.java:95)
	at org.hibernate.validator.internal.engine.valueextraction.ValueExtractorDescriptor.<init>(ValueExtractorDescriptor.java:49)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.addValueExtractor(ConfigurationImpl.java:219)
	at org.hibernate.validator.internal.engine.ConfigurationImpl.addValueExtractor(ConfigurationImpl.java:68)
```
