### ISSUE TITLE
NoSuchMethodError at runtime for equals on AnyVal

### ISSUE THREAD

**Issue by scabug** [scala/bug#9922]
To reproduce, compile and run the attached file. I include it inline for convenience:

```scala
// This package object is empty, but must be present to reproduce the problem.
// Also, if it is moved after the `package foo { ... }` block below,
// the problem disappears.
package object foo {}

package foo {
  final case class Foo[A](value: A) extends AnyVal
}

object Bar extends App {
  import foo._

  List(Foo(5)) == List(Foo(5))
}
```

```scala
$ ~/scala-2.12.0-M5/bin/scalac main.scala 
$ ~/scala-2.12.0-M5/bin/scala Bar
java.lang.NoSuchMethodError: foo.Foo$.equals$extension(Ljava/lang/Object;Ljava/lang/Object;)Z
	at foo.Foo.equals(main.scala:7)
	at scala.runtime.BoxesRunTime.equals2(BoxesRunTime.java:135)
	at scala.runtime.BoxesRunTime.equals(BoxesRunTime.java:121)
	at scala.collection.LinearSeqOptimized.sameElements$(LinearSeqOptimized.scala:254)
	at scala.collection.LinearSeqOptimized.sameElements(LinearSeqOptimized.scala:248)
	at scala.collection.GenSeqLike.equals$(GenSeqLike.scala:477)
	at scala.collection.AbstractSeq.equals(Seq.scala:41)
	at Bar$.delayedEndpoint$Bar$1(main.scala:13)
	at Bar$delayedInit$body.apply(main.scala:10)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:376)
	at scala.App.main$(App.scala:76)
	at scala.App.main(App.scala:74)
	at Bar.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:98)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:32)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:30)
	at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:98)
	at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:90)
	at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:22)
	at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:21)
	at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:29)
	at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:28)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by dwijnand** [comment]
No longer present in Scala 2.12.2, with either snippets:

```
12:10:27 $ rm -r *
12:10:29 $ pbpaste > main.scala
12:10:37 $ scalac main.scala
12:10:49 $ scala Bar
12:10:52 $ rm -r *
12:10:55 $ pbpaste > test.scala
12:11:06 $ scalac test.scala
12:11:14 $ scala Test
12:11:17 $
```
